### ISSUE TITLE
Autodiscover error while binding on IPv6 addresses

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1002]
#### Description

While testing the https://github.com/nicolargo/glances/issues/1001 issue.

```
$ glances -s -B '::'
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.8', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 232, in main
    start_server(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 168, in start_server
    args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/server.py", line 215, in __init__
    self.autodiscover_client = GlancesAutoDiscoverClient(socket.gethostname().split('.', 1)[0], args)
  File "/usr/local/lib/python2.7/dist-packages/glances/autodiscover.py", line 210, in __init__
    address=socket.inet_aton(zeroconf_bind_address), port=args.port,
socket.error: illegal IP address string passed to inet_aton
```

Note: Glances works fine if i add the --disable-autodiscovery option

#### Versions

* Glances (glances -V): 2.8
* PSutil (glances -V): 6.0.1
* Operating System (lsb_release -a): Ubuntu 16.04

**Comment by nicolargo** [comment]
Done in the HEAD version of the DEVELOP branch.
