### ISSUE TITLE
Docker - Error

### ISSUE THREAD

**Issue by onedr0p** [nicolargo/glances#1003]
Hi,

I am trying to run glances with docker-compose. I am using your docker container.

Docker version: 1.12.6

docker-compose.yaml
```yaml
version: "2"
services:
  glances:
    image: docker.io/nicolargo/glances
    container_name: glances
    ports:
      - "61208-61209:61208-61209"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    pid: "host"
```

I get this errors in the console:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/glances/glances/__main__.py", line 29, in <module>
    glances.main()
  File "glances/__init__.py", line 238, in main
    start_webserver(config=config, args=args)
  File "glances/__init__.py", line 193, in start_webserver
    webserver = GlancesWebServer(config=config, args=args)
  File "glances/webserver.py", line 41, in __init__
    self.stats.update()
  File "glances/stats.py", line 164, in update
    self._plugins[p].update()
  File "glances/plugins/glances_plugin.py", line 805, in wrapper
    ret = fct(self, *args, **kw)
  File "glances/plugins/glances_plugin.py", line 814, in wrapper
    ret = fct(*args, **kw)
  File "/glances/glances/plugins/glances_wifi.py", line 102, in update
    wifi_cells = Cell.all(net)
  File "/usr/local/lib/python2.7/dist-packages/wifi/scan.py", line 39, in all
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I get the same error when running:
`docker run -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host -it docker.io/nicolargo/glances`

Thanks for all your help!

**Comment by EwyynTomato** [comment]
I also have this issue. This is caused by [wifi](https://pypi.python.org/pypi/wifi) library, see [this issue](https://github.com/rockymeza/wifi/issues/93).

My own fix is to create a Dockerfile and install ```wireless-tools``` package:

```
FROM nicolargo/glances

RUN apt-get update
RUN apt-get install -y wireless-tools
```

and edit docker-compose.yml to build using the Dockerfile:

```
version: "2"
services:
  glances:
    image: test-glances
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glances
    ports:
      - "61208-61209:61208-61209"
    environment:
      - GLANCES_OPT=-w
```

**Comment by thebwt** [comment]
For those using this from a headless server, add `--disable-wifi` to the GLANCES_OPT section

**Comment by onedr0p** [comment]
`--disable-wifi` did the trick thanks!

**Comment by nicolargo** [comment]
I just add the wireless-tools package inside the top level Dockerfile.

It should work out-of-the-box now... 

Just wait on or two hours before testing (the Docker build process is long...).
