### ISSUE TITLE
Error running glances (no such file or directory)

### ISSUE THREAD

**Issue by jaxxstorm** [nicolargo/glances#1004]
#### Description

Clean install on CentOS 7:

#### Versions

* Glances (glances -V): v2.8
* PSutil (glances -V): v5.0.1
* Operating System (lsb_release -a):  lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core)
Release:	7.2.1511
Codename:	Core

#### Logs

```
[root@virt3 ~]# glances -s
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.8', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 232, in main
    start_server(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 168, in start_server
    args=args)
  File "/usr/lib/python2.7/site-packages/glances/server.py", line 210, in __init__
    self.server.register_instance(GlancesInstance(cached_time, config, args))
  File "/usr/lib/python2.7/site-packages/glances/server.py", line 127, in __init__
    self.stats.update()
  File "/usr/lib/python2.7/site-packages/glances/stats_server.py", line 46, in update
    super(GlancesStatsServer, self).update()
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 164, in update
    self._plugins[p].update()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 805, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 814, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_wifi.py", line 102, in update
    wifi_cells = Cell.all(net)
  File "/usr/lib/python2.7/site-packages/wifi/scan.py", line 39, in all
    stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by karibuTW** [comment]
Same issue here, on Debian Stretch using the Curl installation process.

**Comment by nicolargo** [comment]
Should be solved in the latest version of the glancesautoinstall script.

Please test and report.

**Comment by karibuTW** [comment]
Good for me now.

Thanks !
