### ISSUE TITLE
How to: Run Glances in subshell?

### ISSUE THREAD

**Issue by clounie** [nicolargo/glances#1015]
#### Description

Goal: Run a glances client (exporting data) via a shell script, then kill the process after an interval of time.

Problem: Glances won't export data when run from another script.

If I use:
```bash
bash ./test.sh
```
it spits out the errors below...but if I pass the environment when running it, like so:
```bash
. ./test.sh
```
...it runs, but doesn't flush any output to the csv file.

#### Versions

* Glances (glances -V): v2.7
* PSutil (glances -V): v5.0.1
* Operating System (lsb_release -a): macOS Sierra - 10.12.2

**Script**:
```bash
#!/bin/bash

## Start a test ##

function runGlances () {
  glances -t=0.5 -c=<ip-address> --quiet --export-csv=./tmp/raw_data/results.csv
}
runGlances &

## End test, analyze data from glances ##

```
**Command**: `bash ./test.sh`

**Error**:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.7', 'console_scripts', 'glances')()
  File "/Library/Python/2.7/site-packages/Glances-2.7-py2.7.egg/glances/__init__.py", line 154, in main
    if not client.login():
  File "/Library/Python/2.7/site-packages/Glances-2.7-py2.7.egg/glances/client.py", line 170, in login
    self.screen = GlancesCursesClient(config=self.config, args=self.args)
  File "/Library/Python/2.7/site-packages/Glances-2.7-py2.7.egg/glances/outputs/glances_curses.py", line 79, in __init__
    self._init_cursor()
  File "/Library/Python/2.7/site-packages/Glances-2.7-py2.7.egg/glances/outputs/glances_curses.py", line 136, in _init_cursor
    curses.cbreak()
_curses.error: cbreak() returned ERR
```

Same error on Ubuntu 16.04.1:
```bash
Traceback (most recent call last):
  File "/home/nwuser1016d/.local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/home/nwuser1016d/.local/lib/python2.7/site-packages/glances/__init__.py", line 230, in main
    start_client(config=config, args=args)
  File "/home/nwuser1016d/.local/lib/python2.7/site-packages/glances/__init__.py", line 145, in start_client
    if not client.login():
  File "/home/nwuser1016d/.local/lib/python2.7/site-packages/glances/client.py", line 170, in login
    self.screen = GlancesCursesClient(config=self.config, args=self.args)
  File "/home/nwuser1016d/.local/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 114, in __init__
    self._init_cursor()
  File "/home/nwuser1016d/.local/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 171, in _init_cursor
    curses.cbreak()
_curses.error: cbreak() returned ERR```

**Comment by nicolargo** [comment]
Just have a test with the latest Glances release (2.8).

It works with both:

    bash ./test.sh

or 

    . ./test.sh

Be aware that Glances may not work if t < 1...

**Comment by clounie** [comment]
I upgraded glances on both machines:
```bash
± glances -V
Glances v2.8 with psutil v5.0.1
```
And also changed the time (on server and both clients) to `-t=1` to rule that out. Did not get any results.

**Comment by nicolargo** [comment]
Just a (stupid) question. Does the following command line works as expected ?

    glances -t 1 -c <ip-address> --quiet --export-csv ./tmp/raw_data/results.csv

**Comment by clounie** [comment]
Nope. Odd, the command no longer works at all...
