### ISSUE TITLE
glances crashes on Raspberry Pi3/Pi2 on archlinuxarm.

### ISSUE THREAD

**Issue by Crazybob2** [nicolargo/glances#1020]
#### Description

glances crashes on Raspberry Pi3/Pi2 on archlinuxarm.

Step to reproduce:
Up to date archlinux on RaspberryPi Version 3 or Raspberry Pi Version2. 
Start glances without Arguments, just 'glances'.

Expected:
glances will start wirh the general overwiew.

What happend:
After a few seconds glances produces a traceback withot coming up.

Additional information:
glances on Archlinux with x86_64 Architecture and same versions works as expected

#### Versions

* Glances (glances -V): Glances v2.8 with psutil v5.1.0
* PSutil (glances -V): psutil v5.1.0
* Operating System (lsb_release -a): Linux 4.4.45-1-ARCH #1 SMP Fri Jan 27 18:52:49 MST 2017 armv7l GNU/Linux

#### Logs

Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.8', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 225, in main
    start_standalone(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 105, in start_standalone
    standalone = GlancesStandalone(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 164, in update
    self._plugins[p].update()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 805, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 814, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_irq.py", line 70, in update
    self.stats = self.irq.get()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_irq.py", line 141, in get
    return self.__update()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_irq.py", line 202, in __update
    current_irqs = self.__sum(line)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_irq.py", line 181, in __sum
    return sum(map(int, splitted_line[1:(self.cpu_number + 1)]))
ValueError: invalid literal for int() with base 10: 'usb_fiq'

**Comment by nicolargo** [comment]
Rejected: cause duplicated https://github.com/nicolargo/glances/issues/1007
