### ISSUE TITLE
Unable to launch Glances on Windows

### ISSUE THREAD

**Issue by WarriusBird** [nicolargo/glances#1021]
#### Description

After successfully installing Glances via pip, the program errors out when attempting to launch.

#### Versions

* Glances (glances -V): v2.8
* PSutil (glances -V): v5.1.1
* Operating System (lsb_release -a): Windows 7
* Python: 2.7.9

#### Logs

In CMD post install:
```
C:\windows\system32>glances
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\glances.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\glances\__init__.py", line 238, in main
    start_webserver(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\__init__.py", line 193, in start_w
ebserver
    webserver = GlancesWebServer(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\webserver.py", line 41, in __init_
_
    self.stats.update()
  File "c:\python27\lib\site-packages\glances\stats.py", line 164, in update
    self._plugins[p].update()
  File "c:\python27\lib\site-packages\glances\plugins\glances_processcount.py",
line 57, in update
    glances_processes.update()
  File "c:\python27\lib\site-packages\glances\processes.py", line 427, in update

    standard_stats=self.max_processes is None)
  File "c:\python27\lib\site-packages\glances\processes.py", line 386, in __get_
process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "c:\python27\lib\site-packages\glances\processes.py", line 271, in __get_
mandatory_stats
    self.cmdline_cache[procstat['pid']] = proc.cmdline()
  File "c:\python27\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 611, in wrappe
r
    return fun(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 681, in cmdlin
e
    ret = cext.proc_cmdline(self.pid)
WindowsError: [Error 18] There are no more files
```

I've attempted getting glances to work on my other Windows desktops to similar issues. I wouldn't be surprised if this is user error, but I'd love to know how to approach resolving this if anyone has some insight.

**Comment by nicolargo** [comment]
Look like a PsUtil issue...

cc: @giampaolo

**Comment by nicolargo** [comment]
Add the WindowsError exception to the catched list.

Available into the DEVELOP branch.

**Comment by WarriusBird** [comment]
Quick update:

After upgrading to glances 2.8.2 and reinstalling psutil from the biniary on python.org I'm getting the following:

```
C:\windows\system32>glances
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\glances.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\glances\__init__.py", line 238, in main
    start_webserver(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\__init__.py", line 193, in start_w
ebserver
    webserver = GlancesWebServer(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\webserver.py", line 41, in __init_
_
    self.stats.update()
  File "c:\python27\lib\site-packages\glances\stats.py", line 164, in update
    self._plugins[p].update()
  File "c:\python27\lib\site-packages\glances\plugins\glances_processcount.py",
line 57, in update
    glances_processes.update()
  File "c:\python27\lib\site-packages\glances\processes.py", line 427, in update

    standard_stats=self.max_processes is None)
  File "c:\python27\lib\site-packages\glances\processes.py", line 386, in __get_
process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "c:\python27\lib\site-packages\glances\processes.py", line 271, in __get_
mandatory_stats
    self.cmdline_cache[procstat['pid']] = proc.cmdline()
  File "c:\python27\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 618, in wrappe
r
    return fun(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 688, in cmdlin
e
    ret = cext.proc_cmdline(self.pid)
WindowsError: [Error 2] The system cannot find the file specified
```

This doesn't include the commits towards 2.8.3, but it might be of some interest.
