### ISSUE TITLE
Glances won't run after updating PIP Packages (The system cannot find the file specified)

### ISSUE THREAD

**Issue by seanvree** [nicolargo/glances#1022]
#### Description

After updating all my python packages via PIP, glances will no longer run.  I've tried it on both python2.7 and 3.6

#### Versions

* Glances (glances -V): 2.8 
* PSutil (glances -V): 5.1.2
* Operating System (lsb_release -a): Windows 10E

#### Logs

C:\WINDOWS\system32>glances
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\glances.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\glances\__init__.py", line 238, in main
    start_webserver(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\__init__.py", line 193, in start_webserver
    webserver = GlancesWebServer(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\webserver.py", line 41, in __init__
    self.stats.update()
  File "c:\python27\lib\site-packages\glances\stats.py", line 164, in update
    self._plugins[p].update()
  File "c:\python27\lib\site-packages\glances\plugins\glances_plugin.py", line 805, in wrapper
    ret = fct(self, *args, **kw)
  File "c:\python27\lib\site-packages\glances\plugins\glances_plugin.py", line 814, in wrapper
    ret = fct(*args, **kw)
  File "c:\python27\lib\site-packages\glances\plugins\glances_wifi.py", line 102, in update
    wifi_cells = Cell.all(net)
  File "c:\python27\lib\site-packages\wifi\scan.py", line 39, in all
    stderr=subprocess.STDOUT)
  File "c:\python27\lib\subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "c:\python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

C:\WINDOWS\system32>

**Comment by nicolargo** [comment]
It should be solved in the next 2.8.1 release.

As a workaround: glances --disable-wifi

**Comment by seanvree** [comment]
@nicolargo - I've disabled wifi, doesn't work.

**Comment by seanvree** [comment]
@nicolargo: hey this works if I run from a prompt, but I'm trying to make it work as I did before as a windows server, but when I call python.exe, I get this error:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\Python36\

C:\Python36>python.exe -m glances --disable-wifi
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\lib\site-packages\glances\__main__.py", line 29, in <module>
    glances.main()
  File "C:\Python36\lib\site-packages\glances\__init__.py", line 238, in main
    start_webserver(config=config, args=args)
  File "C:\Python36\lib\site-packages\glances\__init__.py", line 193, in start_webserver
    webserver = GlancesWebServer(config=config, args=args)
  File "C:\Python36\lib\site-packages\glances\webserver.py", line 34, in __init__
    self.stats = GlancesStats(config, args)
  File "C:\Python36\lib\site-packages\glances\stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "C:\Python36\lib\site-packages\glances\stats.py", line 77, in load_modules
    self.load_plugins(args=args)
  File "C:\Python36\lib\site-packages\glances\stats.py", line 96, in load_plugins
    plugin = __import__(os.path.basename(item)[:-3])
  File "C:\Python36\lib\site-packages\glances\plugins\glances_gpu.py", line 26, in <module>
    import pynvml
  File "C:\Python36\lib\site-packages\pynvml.py", line 1671
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'

C:\Python36>

**Comment by nicolargo** [comment]
@seanvree It is a PyNVML error. The lib is not compliant with Python 3. Please uninstall it (pip uninstall nvidia-ml-py).

**Comment by seanvree** [comment]
Perfect!

@nicolargo - do you recommend running glances with py3 or py2?

**Comment by asergi** [comment]
@seanvree it was a known [issue](https://github.com/nicolargo/glances/issues/170#issuecomment-269232405) now fixed in f468367522c567ea6badac91cce80092244bb7a5.

It's 2017, use Python 3. My two cents.
