### ISSUE TITLE
Global name standalone not defined

### ISSUE THREAD

**Issue by WarriusBird** [nicolargo/glances#1030]
To be clear, this is a different machine and install from #1021 

#### Description

When launched, glances appears to start a webserver and launches a webpage that does not load to anything. When Ctrl + C is invoked, an error is called. This persists when launching with the -d flag. API is nonresponsive (going off of recommendations in #745 ) as well.

#### Versions

* Glances (glances -V): 2.8.2
* PSutil (glances -V): 5.1.3
* Operating System (lsb_release -a): Windows 10

#### Logs

```
C:\Windows\system32>glances
Glances web server started on http://0.0.0.0:61209/
Traceback (most recent call last):
  File "C:\Python27\Scripts\glances-script.py", line 11, in <module>
    load_entry_point('Glances==2.8.2', 'console_scripts', 'glances')()
  File "c:\python27\lib\site-packages\glances\__init__.py", line 238, in main
    start_webserver(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\__init__.py", line 196, in start_webserver
    webserver.serve_forever()
  File "c:\python27\lib\site-packages\glances\webserver.py", line 48, in serve_forever
    self.web.start(self.stats)
  File "c:\python27\lib\site-packages\glances\outputs\glances_bottle.py", line 148, in start
    self._app.run(host=self.args.bind_address, port=self.args.port, quiet=not self.args.debug)
  File "C:\Python27\Scripts\bottle.py", line 755, in run
    run(self, **kwargs)
  File "C:\Python27\Scripts\bottle.py", line 3127, in run
    server.run(app)
  File "C:\Python27\Scripts\bottle.py", line 2782, in run
    srv.serve_forever()
  File "c:\python27\lib\SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "c:\python27\lib\SocketServer.py", line 150, in _eintr_retry
    return func(*args)
  File "c:\python27\lib\site-packages\glances\__init__.py", line 68, in __signal_handler
    end()
  File "c:\python27\lib\site-packages\glances\__init__.py", line 75, in end
    standalone.end()
NameError: global name 'standalone' is not defined
```

**Comment by nicolargo** [comment]
Just push a patch on the DEVELOP branch to resolve the error message when Glances is ended. Nevertheless, the main cause of the current issue (webpage that does not load to anything) is not take into account.

**Comment by nicolargo** [comment]
@WarriusBird Can you paste/bin us the Glances logs file (debug mode). Thanks !

**Comment by WarriusBird** [comment]
Here you go:
http://pastebin.com/hfH81qyR

**Comment by nicolargo** [comment]
Nothing wrong on the Glances logs file. Can you show us a screenshot of your browser web console (raccourci clavier Ctrl-Maj-K) ?

**Comment by WarriusBird** [comment]
![glances](https://cloud.githubusercontent.com/assets/10179709/22866255/3c7a7e5a-f141-11e6-9097-3196ac77cfb6.PNG)

Not a whole lot to see I'm afraid.

**Comment by nicolargo** [comment]
@WarriusBird Can you try with the latest 2.8.5 version ?

**Comment by WarriusBird** [comment]
From a fresh install of Python:
```

C:\Windows\system32>glances
Traceback (most recent call last):
  File "C:\Python27\Scripts\glances-script.py", line 11, in <module>
    load_entry_point('Glances==2.8.5', 'console_scripts', 'glances')()
  File "c:\python27\lib\site-packages\glances\__init__.py", line 238, in main
    start_webserver(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\__init__.py", line 193, in start_webserver
    webserver = GlancesWebServer(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\webserver.py", line 41, in __init__
    self.stats.update()
  File "c:\python27\lib\site-packages\glances\stats.py", line 164, in update
    self._plugins[p].update()
  File "c:\python27\lib\site-packages\glances\plugins\glances_processcount.py", line 57, in update
    glances_processes.update()
  File "c:\python27\lib\site-packages\glances\processes.py", line 427, in update
    standard_stats=self.max_processes is None)
  File "c:\python27\lib\site-packages\glances\processes.py", line 386, in __get_process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "c:\python27\lib\site-packages\glances\processes.py", line 272, in __get_mandatory_stats
    except (AttributeError, UnicodeDecodeError, psutil.AccessDenied, psutil.NoSuchProcess, psutil.WindowsError):
AttributeError: 'module' object has no attribute 'WindowsError'
```

Debug log: http://pastebin.com/NvMfxvTf

**Comment by nicolargo** [comment]
@WarriusBird Please also upgrade your PSUtil version to 5.2.0 or higher:

    pip install --upgrade psutil

**Comment by WarriusBird** [comment]
5.2.0 was already installed at the time of last running. That or pip thinks it was.

```
C:\Windows\system32>glances -V
Glances v2.8.5 with psutil v5.2.0
```

**Comment by nicolargo** [comment]
Ok, should be corrected in Glances 2.8.6 , available in Pypi. Can you test it ?

**Comment by WarriusBird** [comment]
```
C:\Windows\system32>glances
Glances web server started on http://0.0.0.0:61209/
Traceback (most recent call last):
  File "C:\Python27\Scripts\glances-script.py", line 11, in <module>
    load_entry_point('Glances==2.8.6', 'console_scripts', 'glances')()
  File "c:\python27\lib\site-packages\glances\__init__.py", line 235, in main
    start_webserver(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\__init__.py", line 196, in start_webserver
    webserver.serve_forever()
  File "c:\python27\lib\site-packages\glances\webserver.py", line 48, in serve_forever
    self.web.start(self.stats)
  File "c:\python27\lib\site-packages\glances\outputs\glances_bottle.py", line 142, in start
    if self.args.open_web_browser:
AttributeError: 'Namespace' object has no attribute 'open_web_browser'
```

Debug log: http://pastebin.com/nFjz0nST

**Comment by nicolargo** [comment]
@WarriusBird  Dam... Validation on Windows is a mess for me...

The version 2.8.7 should (i hope) solve yours issues...

Please check.

**Comment by WarriusBird** [comment]
It appears to be working now! Minor complaint that it doesn't auto open the web browser/tab, but that's minor at worst. It also appears to be working on my other machine, but I haven't had a chance to poke around with it in depth.

One last debug log should you need it: http://pastebin.com/cmHvqcDw

**Comment by nicolargo** [comment]
@WarriusBird Use the --open-web-browser option to automatically open the Web browser.

Thanks for your time !

**Comment by ladislavsulc** [comment]
Hi. Similar problem here with Windows 10 and:

Glances v2.11.1 with psutil v5.4.3

```
127.0.0.1 - - [07/Jan/2018 23:13:32] "GET /favicon.ico HTTP/1.1" 200 4286
Traceback (most recent call last):
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 333, in send_headers
    self._write(bytes(self.headers))
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\headers.py", line 142, in __bytes__
    return str(self).encode('iso-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0159' in position 74: ordinal not in range(256)
127.0.0.1 - - [07/Jan/2018 23:13:33] "GET /favicon.ico HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 22510)
Traceback (most recent call last):
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 333, in send_headers
    self._write(bytes(self.headers))
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\headers.py", line 142, in __bytes__
    return str(self).encode('iso-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0159' in position 74: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 348, in process_request

    self.finish_request(request, client_address)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\simple_server.py", line 133, in handle

    handler.run(self.server.get_app())
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [07/Jan/2018 23:13:41] "GET / HTTP/1.1" 200 917
Traceback (most recent call last):
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 258, in send_preamble
    self._write(('Server: %s\r\n' % self.server_software).encode('iso-8859-1'))
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] Software v hostitelském počítači ukončil vytvořené připojení
127.0.0.1 - - [07/Jan/2018 23:13:41] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 22519)
Traceback (most recent call last):
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 258, in send_preamble
    self._write(('Server: %s\r\n' % self.server_software).encode('iso-8859-1'))
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] Software v hostitelském počítači ukončil vytvořené připojení

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 348, in process_request

    self.finish_request(request, client_address)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\lada\appdata\local\programs\python\python36\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\simple_server.py", line 133, in handle

    handler.run(self.server.get_app())
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "c:\users\lada\appdata\local\programs\python\python36\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```
