### ISSUE TITLE
error in Glances setup command: Invalid environment marker: python_version<"3.5"

### ISSUE THREAD

**Issue by SalvorinFex** [nicolargo/glances#1033]
This is similar to issue #1028 

#### Description

After updating the PIP install I am receiving this message:
```
Collecting glances
  Using cached Glances-2.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in Glances setup command: Invalid environment marker: python_version<"3.5"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/k9/z1d7ds617mxf8q8grrjb_jjc0000gn/T/pip-build-VPrzMh/glances/
```

#### Versions

* Glances (glances -V): 2.6.2
* PSutil (glances -V): 4.2.0
* Operating System (lsb_release -a): OSX 10.9.5

Might have something to where it was installed in my OSX, but not sure how to change that to re-test.

**Comment by asergi** [comment]
`pip install -U pip setuptools`

**Comment by Leafney** [comment]
Thanks!

**Comment by kehao95** [comment]
Will 'update requirements' solve this I came across the same problem today.

**Comment by AShabana** [comment]
Working thank you asergi

**Comment by liud** [comment]
when run: 'pip install -U pip setuptools',below is error details


Requirement already up-to-date: pip in /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg
Collecting setuptools
  Using cached setuptools-35.0.0-py2.py3-none-any.whl
Requirement already up-to-date: appdirs>=1.4.0 in /Library/Python/2.7/site-packages (from setuptools)
Collecting packaging>=16.8 (from setuptools)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting six>=1.6.0 (from setuptools)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Installing collected packages: pyparsing, six, packaging, setuptools
  Found existing installation: pyparsing 2.0.1
    DEPRECATION: Uninstalling a distutils installed project (pyparsing) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pyparsing-2.0.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/4y/ylxr5wkx1v9br7qwxkx9pyyw0000gn/T/pip-gJ2ezz-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pyparsing-2.0.1-py2.7.egg-info'

**Comment by senorsmile** [comment]
This exact same bug is happening to me on any newly updated ubuntu 14.04.5 install.  Installing 2.8.0 works fine.  Shall I open a new bug with the same name?
