### ISSUE TITLE
OSError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by PaulReiber** [nicolargo/glances#1035]
#### Description

When I run glances as a regular user in a terminal, it works great for a while but eventually crashes. When I run this with sudo it doesn't seem to crash.

```
Pauls-MBP:~ Paul$ glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 225, in main
    start_standalone(config=config, args=args)
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 108, in start_standalone
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/usr/local/lib/python2.7/site-packages/glances/standalone.py", line 100, in __serve_forever
    self.stats.update()
  File "/usr/local/lib/python2.7/site-packages/glances/stats.py", line 164, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/site-packages/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "/usr/local/lib/python2.7/site-packages/glances/processes.py", line 427, in update
    standard_stats=self.max_processes is None)
  File "/usr/local/lib/python2.7/site-packages/glances/processes.py", line 386, in __get_process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "/usr/local/lib/python2.7/site-packages/glances/processes.py", line 252, in __get_mandatory_stats
    ad_value=''))
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 563, in as_dict
    ret = meth()
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 1148, in memory_percent
    metrics = fun()
  File "/usr/local/lib/python2.7/site-packages/psutil/_common.py", line 316, in wrapper
    ret = cache[fun] = fun(self)
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 1108, in memory_info
    return self._proc.memory_info()
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 285, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 392, in memory_info
    rawtuple = self._get_pidtaskinfo()
  File "/usr/local/lib/python2.7/site-packages/psutil/_common.py", line 316, in wrapper
    ret = cache[fun] = fun(self)
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 323, in _get_pidtaskinfo
    ret = cext.proc_pidtaskinfo_oneshot(self.pid)
OSError: [Errno 1] Operation not permitted
Pauls-MBP:~ Paul$

```
#### Versions

```
Pauls-MBP:~ Paul$ glances -V
Glances v2.8.2 with psutil v5.1.3

* Operating System (lsb_release -a):  
Pauls-MBP:~ Paul$ uname -a
Darwin Pauls-MBP.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

**Comment by giampaolo** [comment]
This looks like a psutil bug as that exception should have been `AccessDenied`, not `OSError`. `AccessDenied` wouldn't have bubbled up.

**Comment by giampaolo** [comment]
I tried to replicate this bug by modifying the C code and make it raise `EACCES` and the `wrap_exceptions` decorator correctly translates `OSError(EACCES)` to `AccessDenied` as dictated here:
https://github.com/giampaolo/psutil/blob/8113eadf7861becfd52dffb634695e93970fdaee/psutil/_psosx.py#L297
...so I'm really not sure why this happens.

**Comment by PaulReiber** [comment]
It takes quite some time for the error to happen.

I'll switch away from the tab in iterm and be working elsewhere, then come back to the shell session some time in the future, expecting to see a lovely display, only to find the traceback I shared. In the interim the mac might also get suspended, resumed, or have its networking change out from under it (wifi, vpn). 

If there are any special commandline options or env vars I should set to help debug this better, just let me know.

**Comment by giampaolo** [comment]
Maybe it's not related but... do you know if the PID being inspected was PID 0?

**Comment by pokey** [comment]
I'm seeing this too.  @giampaolo how do I tell if the PID being inspected was PID 0?  I just ran glances with no arguments, waited a while, and came back to see this

**Comment by nicolargo** [comment]
@giampaolo I let the issue open but perhaps it will be better to clone it to PsUtil ?

**Comment by darvelo** [comment]
I'm seeing this error too after a few seconds of running glances. Is there anything I can do to help troubleshooting this?
