### ISSUE TITLE
no module named glances_cloud

### ISSUE THREAD

**Issue by Eraac** [nicolargo/glances#1043]
#### Description

I have two servers with glances installed (server mode) running into docker. One with image of glances build 4 month ago (nicolargo/glances:latest - image_id: 77a5e135b375), and another server with the newest image of glances, build 2 days ago (image_id: 61744eb5326a).

When I use glances (client mode) from my computer to the servers, the one with the oldest image works but the other server with the newest image it crashes (error into logs section).

The configuration is exactly the same between the both servers (same docker-compose.yml). Glances into my computer has been recently installed (today), with `pip install glances`

#### Versions

* Glances (glances -V): 2.8.2
* PSutil (glances -V): 5.1.1
* Operating System (lsb_release -a): MacOS Sierra 10.12.3
* Python (python --version): 2.7.12

#### Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 228, in main
    start_clientbrowser(config=config, args=args)
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 125, in start_clientbrowser
    client.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/client_browser.py", line 246, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/client_browser.py", line 237, in __serve_forever
    self.__serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/client_browser.py", line 237, in __serve_forever
    self.__serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/client_browser.py", line 234, in __serve_forever
    self.__display_server(self.get_servers_list()[self.screen.active_server])
  File "/usr/local/lib/python2.7/site-packages/glances/client_browser.py", line 189, in __display_server
    if not client.login():
  File "/usr/local/lib/python2.7/site-packages/glances/client.py", line 156, in login
    if not self._login_glances():
  File "/usr/local/lib/python2.7/site-packages/glances/client.py", line 124, in _login_glances
    self.stats.set_plugins(json.loads(self.client.getAllPlugins()))
  File "/usr/local/lib/python2.7/site-packages/glances/stats_client.py", line 48, in set_plugins
    plugin = __import__(header + item)
ImportError: No module named glances_cloud
```

**Comment by nicolargo** [comment]
Your client is not compatible with the latest version of the Glances container. 

Two solutions:

1) Upgrade the client to the DEVELOP branch
2) Re-install your bugged container with the 'stable' tag (https://hub.docker.com/r/nicolargo/glances/tags/)

My advise: solution 2)
