### ISSUE TITLE
Glances cannot load "Powersupply"

### ISSUE THREAD

**Issue by seanvree** [nicolargo/glances#1051]
#### Description

Glances crashes when running in any mode.

#### Versions

Glances v2.8.7 
psutil v5.2.0
Python 2.7 & 3.6
Windows 10E

#### Logs

C:\WINDOWS\system32>python3.6 -m glances

Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\lib\site-packages\glances\__main__.py", line 29, in <module>
    glances.main()
  File "C:\Python36\lib\site-packages\glances\__init__.py", line 235, in main
    start_webserver(config=config, args=args)
  File "C:\Python36\lib\site-packages\glances\__init__.py", line 193, in start_webserver
    webserver = GlancesWebServer(config=config, args=args)
  File "C:\Python36\lib\site-packages\glances\webserver.py", line 34, in __init__
    self.stats = GlancesStats(config, args)
  File "C:\Python36\lib\site-packages\glances\stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "C:\Python36\lib\site-packages\glances\stats.py", line 77, in load_modules
    self.load_plugins(args=args)
  File "C:\Python36\lib\site-packages\glances\stats.py", line 105, in load_plugins
    self._plugins[plugin_name] = plugin.Plugin(args=args)
  File "C:\Python36\lib\site-packages\glances\plugins\glances_batpercent.py", line 56, in __init__
    self.glancesgrabbat = GlancesGrabBat()
  File "C:\Python36\lib\site-packages\glances\plugins\glances_batpercent.py", line 98, in __init__
    self.bat = batinfo.batteries()
  File "C:\Python36\lib\site-packages\batinfo\battery.py", line 104, in __init__
    self.update()
  File "C:\Python36\lib\site-packages\batinfo\battery.py", line 113, in update
    for dirname in os.listdir(self.bat_root_path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/sys/class/power_supply'

**Comment by nicolargo** [comment]
The batinfo lib is not compatible with Windows... Please uninstall it:

    pip uninstall batinfo

**Comment by seanvree** [comment]
@nicolargo  - THanks, and this one:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python36\lib\site-packages\glances\__main__.py", line 29, in <module>
    glances.main()
  File "c:\Python36\lib\site-packages\glances\__init__.py", line 235, in main
    start_webserver(config=config, args=args)
  File "c:\Python36\lib\site-packages\glances\__init__.py", line 193, in start_webserver
    webserver = GlancesWebServer(config=config, args=args)
  File "c:\Python36\lib\site-packages\glances\webserver.py", line 41, in __init__
    self.stats.update()
  File "c:\Python36\lib\site-packages\glances\stats.py", line 164, in update
    self._plugins[p].update()
  File "c:\Python36\lib\site-packages\glances\plugins\glances_processcount.py", line 57, in update
    glances_processes.update()
  File "c:\Python36\lib\site-packages\glances\processes.py", line 433, in update
    standard_stats=self.max_processes is None)
  File "c:\Python36\lib\site-packages\glances\processes.py", line 392, in __get_process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "c:\Python36\lib\site-packages\glances\processes.py", line 278, in __get_mandatory_stats
    except (AttributeError, UnicodeDecodeError, psutil.AccessDenied, psutil.NoSuchProcess, PsUtilWindowsError):
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by asergi** [comment]
Fixed in 7ecafebdc70e01a41a68d6e4d8c8ac12ac507432.
