### ISSUE TITLE
FreeBSD: If oid 'hw.acpi.battery' not present, Glances wont start

### ISSUE THREAD

**Issue by IchSchreiGleich** [nicolargo/glances#1055]
#### Description

On FreeBSD, if oids for battery stats (hw.acpi.battery.*) not present, Glances wont start. This is because PSutil throws an OSError exception (see output below). - Editing line 411 in _psbsd.py solves this issue.

In my view, Glances should catch this kind of errors instead of dying. :)

#### Versions

* Glances (glances -V): 2.8.8
* PSutil (glances -V): 5.2.0
* Operating System (lsb_release -a): FreeBSD 11.0-RELEASE-p8

#### Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.8.8', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 225, in main
    start_standalone(config=config, args=args)
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 105, in start_standalone
    standalone = GlancesStandalone(config=config, args=args)
  File "/usr/local/lib/python2.7/site-packages/glances/standalone.py", line 43, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/local/lib/python2.7/site-packages/glances/stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "/usr/local/lib/python2.7/site-packages/glances/stats.py", line 77, in load_modules
    self.load_plugins(args=args)
  File "/usr/local/lib/python2.7/site-packages/glances/stats.py", line 96, in load_plugins
    plugin = __import__(os.path.basename(item)[:-3])
  File "/usr/local/lib/python2.7/site-packages/glances/plugins/glances_batpercent.py", line 38, in <module>
    psutil.sensors_battery()
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 2263, in sensors_battery
    return _psplatform.sensors_battery()
  File "/usr/local/lib/python2.7/site-packages/psutil/_psbsd.py", line 411, in sensors_battery
    percent, minsleft, power_plugged = cext.sensors_battery()
OSError: [Errno 2] No such file or directory

```

**Comment by nicolargo** [comment]
It's a PSUtil issue. Perhaps related to https://github.com/giampaolo/psutil/issues/955 ? cc: @giampaolo
