### ISSUE TITLE
Potential memory leak in Windows WebUI

### ISSUE THREAD

**Issue by WarriusBird** [nicolargo/glances#1056]
#### Description

After running for some time, a tab pointed at the glances WebUI will crash due to lack of memory.

#### Versions

* Glances (glances -V): 2.8.8
* PSutil (glances -V): 5.2.0
* Operating System (lsb_release -a): Win 7 SP1

#### Logs
Unknown if this error message is related, but here you go: 

Glances web server started on http://0.0.0.0:61209/
Traceback (most recent call last):
  File "c:\python27\lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "c:\python27\lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "c:\python27\lib\wsgiref\handlers.py", line 212, in write
    self.send_headers()
  File "c:\python27\lib\wsgiref\handlers.py", line 270, in send_headers
    self.send_preamble()
  File "c:\python27\lib\wsgiref\handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "c:\python27\lib\socket.py", line 324, in write
    self.flush()
  File "c:\python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53675)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "c:\python27\lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "c:\python27\lib\socket.py", line 279, in close
    self.flush()
  File "c:\python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine
----------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "c:\python27\lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "c:\python27\lib\wsgiref\handlers.py", line 212, in write
    self.send_headers()
  File "c:\python27\lib\wsgiref\handlers.py", line 270, in send_headers
    self.send_preamble()
  File "c:\python27\lib\wsgiref\handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "c:\python27\lib\socket.py", line 324, in write
    self.flush()
  File "c:\python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53676)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "c:\python27\lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "c:\python27\lib\socket.py", line 279, in close
    self.flush()
  File "c:\python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine
----------------------------------------

**Comment by nicolargo** [comment]
The error message is a consequence, not the cause.

_WSAECONNABORTED 10053
Software caused connection abort.
An established connection was aborted by the software in your host computer, possibly due to a data transmission time-out or protocol error._

@notFloran Can you run a memory leak software to check the Glances UI ?
