### ISSUE TITLE
Fails to start, OSError in sensors_temperatures

### ISSUE THREAD

**Issue by blakcap** [nicolargo/glances#1057]
#### Description
Glances fails to start (as of a few weeks ago). It might not be directly related to glances, since it used to work, and I think an unrelated Arch Linux upgrade might've broken it.

#### Versions

* Glances (glances -V): v2.8.8
* PSutil (glances -V): v5.2.0
* Operating System (lsb_release -a): Arch Linux (kernel 4.10.3)

#### Logs
```
2017-03-20 11:13:13,138 -- INFO -- Start Glances 2.8.8
2017-03-20 11:13:13,138 -- INFO -- CPython 3.6.0 and PSutil 5.2.0 detected
2017-03-20 11:13:13,140 -- INFO -- Start standalone mode
2017-03-20 11:15:45,817 -- INFO -- Start Glances 2.8.8
2017-03-20 11:15:45,817 -- INFO -- CPython 3.6.0 and PSutil 5.2.0 detected
2017-03-20 11:15:45,819 -- INFO -- Start standalone mode
2017-03-20 11:17:01,483 -- INFO -- Start Glances 2.8.8
2017-03-20 11:17:01,483 -- INFO -- CPython 3.6.0 and PSutil 5.2.0 detected
2017-03-20 11:18:36,997 -- INFO -- Start Glances 2.8.8
2017-03-20 11:18:36,997 -- INFO -- CPython 3.6.0 and PSutil 5.2.0 detected
2017-03-20 11:18:37,000 -- INFO -- Start standalone mode
```
#### Trace
```
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.8.8', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 225, in main
    start_standalone(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 105, in start_standalone
    standalone = GlancesStandalone(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/standalone.py", line 43, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 77, in load_modules
    self.load_plugins(args=args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 105, in load_plugins
    self._plugins[plugin_name] = plugin.Plugin(args=args)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_sensors.py", line 53, in __init__
    self.glancesgrabsensors = GlancesGrabSensors()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_sensors.py", line 229, in __init__
    self.stemps = psutil.sensors_temperatures()
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 2212, in sensors_temperatures
    rawdict = _psplatform.sensors_temperatures()
  File "/usr/lib/python3.6/site-packages/psutil/_pslinux.py", line 1110, in sensors_temperatures
    current = float(cat(base + '_input')) / 1000.0
  File "/usr/lib/python3.6/site-packages/psutil/_pslinux.py", line 299, in cat
    return f.read().strip()
OSError: [Errno 5] Input/output error
```

**Comment by nicolargo** [comment]
Corrected in the DEVELOP branch.

Workaround: Disable sensors module (--disable-sensors)

**Comment by blakcap** [comment]
Wow, thanks for the quick turnaround!

**Comment by blakcap** [comment]
Actually, I still get this error with `glances --disable-sensors`. Traceback:
```
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.8.8', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 225, in main
    start_standalone(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 105, in start_standalone
    standalone = GlancesStandalone(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/standalone.py", line 43, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 77, in load_modules
    self.load_plugins(args=args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 105, in load_plugins
    self._plugins[plugin_name] = plugin.Plugin(args=args)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_sensors.py", line 53, in __init__
    self.glancesgrabsensors = GlancesGrabSensors()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_sensors.py", line 229, in __init__
    self.stemps = psutil.sensors_temperatures()
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 2212, in sensors_temperatures
    rawdict = _psplatform.sensors_temperatures()
  File "/usr/lib/python3.6/site-packages/psutil/_pslinux.py", line 1110, in sensors_temperatures
    current = float(cat(base + '_input')) / 1000.0
  File "/usr/lib/python3.6/site-packages/psutil/_pslinux.py", line 299, in cat
    return f.read().strip()
OSError: [Errno 5] Input/output error
```
