### ISSUE TITLE
required sudo to run

### ISSUE THREAD

**Issue by AnthonyWC** [nicolargo/glances#1058]
#### Description
Need sudo to run; without sudo gets errors (see below):

#### Versions

* Glances (glances -V): Glances v2.3 
* PSutil (glances -V): with psutil v3.4.2
* Operating System (lsb_release -a):
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

```
antho@alto  ~  glances                                                                                                                                                                                            
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.3', 'console_scripts', 'glances')()
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 119, in main
    args=core.get_args())
  File "/usr/lib/python3/dist-packages/glances/core/glances_standalone.py", line 36, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3/dist-packages/glances/core/glances_stats.py", line 55, in __init__
    self.load_plugins(args=args)
  File "/usr/lib/python3/dist-packages/glances/core/glances_stats.py", line 95, in load_plugins
    plugin = __import__(os.path.basename(item)[:-3])
  File "/usr/lib/python3/dist-packages/glances/plugins/glances_docker.py", line 29, in <module>
    import docker
  File "/usr/lib/python3/dist-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/lib/python3/dist-packages/docker/client.py", line 19, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'
```

**Comment by nicolargo** [comment]
Try to upgrade you Docker Python lib.

**Comment by hjgarron** [comment]
My glances docker instances stopped showing the containers info. Upgrading the docker-py lib as stated above fixed it. I am running on Ubuntu 16.04 with all updates and the latest ubuntu package of docker.io (ubuntu version, not the docker-engine from Docker)

This is how I did it:

```
docker exec -i -t glances pip install docker-py --upgrade
docker stop glances
docker start glances
```
