### ISSUE TITLE
KeyError: <function Process.cpu_times at 0x103fccea0> when not running using sudo

### ISSUE THREAD

**Issue by GabLeRoux** [nicolargo/glances#1062]
#### Description
App runs for a small amount of time and then crashes with the following error:

**Python3.6 PermissionError: [Errno 1] Operation not permitted**
```
Traceback (most recent call last):
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/_common.py", line 316, in wrapper
    ret = cache[fun]
KeyError: <function Process.cpu_times at 0x103fccea0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/_common.py", line 316, in wrapper
    ret = cache[fun]
KeyError: <function Process._get_pidtaskinfo at 0x103ff1840>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gableroux/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/__init__.py", line225, in main
    start_standalone(config=config, args=args)
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/__init__.py", line108, in start_standalone
    standalone.serve_forever()
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/standalone.py", line 100, in __serve_forever
    self.stats.update()
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/stats.py", line 164, in update
    self._plugins[p].update()
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/processes.py", line 428, in update
    standard_stats=self.max_processes is None)
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/processes.py", line 387, in __get_process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/glances/processes.py", line 242, in __get_mandatory_stats
    ad_value=''))
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/__init__.py", line 563, in as_dict
    ret = meth()
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/_common.py", line 318, in wrapper
    ret = cache[fun] = fun(self)
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/__init__.py", line 1097, in cpu_times
    return self._proc.cpu_times()
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/_psosx.py", line 293, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/_psosx.py", line 416, in cpu_times
    rawtuple = self._get_pidtaskinfo()
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/_common.py", line 318, in wrapper
    ret = cache[fun] = fun(self)
  File "/Users/gableroux/.virtualenvs/glances/lib/python3.6/site-packages/psutil/_psosx.py", line 331, in _get_pidtaskinfo
    ret = cext.proc_pidtaskinfo_oneshot(self.pid)
PermissionError: [Errno 1] Operation not permitted
```

Everything seems fine when running with sudo.

#### Versions

```bash
glances --version
Glances v2.8.8 with psutil v5.2.
```

I run glances in its own python virtualenv using **Python 3.6.0**.

```bash
pip freeze | grep psutil
psutil==5.2.0
```

```bash
uname -a
Darwin warbookpro.localhost 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```
```bash
                 -/+:.          gableroux@localhost
                :++++.          OS: 64bit Mac OS X 10.12.3 16D32
               /+++/.           Kernel: x86_64 Darwin 16.4.0
       .:-::- .+/:-``.::-       Uptime: 5h 5m
    .:/++++++/::::/++++++/:`    Packages: 174
  .:///////////////////////:`   Shell: zsh 5.2
  ////////////////////////`     Resolution: 2880x1800 1920x1080 1080x1920
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     CPU: Intel Core i7-4770HQ @ 2.20GHz
  osssssssssssssssssssssssso/`  GPU: Intel Iris Pro
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  RAM: 8250MiB / 16384MiB
   `ossssssssssssssssssssss/
     :ooooooooooooooooooo+.
      `:+oo+/:-..-:/+o+/-
```

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Looks like a PsUtil error...

cc: @giampaolo

**Comment by giampaolo** [comment]
Now this is weird, and I seem to remember another similar issue posted not long ago.
It appears the `wrap_exceptions` decorator which is supposed to turn `PermissionError` into `psutil.AccesssDenied` doesn't do its job.
`cpu_times` is decorated: https://github.com/giampaolo/psutil/blob/7ff84c208af10e618e23aacb3691c668eb25a12d/psutil/_psosx.py#L414
...and the trick of translating `PermissionError` to `AccessDenied` is supposed to occur here:
https://github.com/giampaolo/psutil/blob/7ff84c208af10e618e23aacb3691c668eb25a12d/psutil/_psosx.py#L305-L306
...but it doesn't.

**Comment by giampaolo** [comment]
So, I've tried to emulate a `PermissionError` like this:

```
    @wrap_exceptions
    def cpu_times(self):
        os.remove('/etc/xtab')
```

...then I run Glances. As expected, the exception is handled and Glances does not crash. Instead the list of processes is empty, which may indicate a bug with Glances, which is yet another (and separate) issue (I would expect the CPU / TIME+ column to be empty but the rest should be rendered).

**Comment by giampaolo** [comment]
Screenshot: 

![screenshot from 2017-03-26 07-49-32](https://cloud.githubusercontent.com/assets/681260/24328987/e13f44de-11f8-11e7-910f-f255deca2da3.png)

**Comment by giampaolo** [comment]
@GabLeRoux what happens if you use Python 2.7 instead?

**Comment by nicolargo** [comment]
@asergi some stats are mandatories because Glances automatically sorts processes. For example, on high CPU consumption, Glances sorts processes list by cpu_time. Mandatories stats list is define here: https://github.com/nicolargo/glances/blob/develop/glances/processes.py#L226-L234
If one of the mandatories stats is not available, the process is not displayed in the list.

**Comment by GabLeRoux** [comment]
I managed to reproduce this today, still hard to tell what's causing this tho.

I first tried to stress test my mac while running glances and it kept running smoothly even with 4cpus at 100% and ran smoothly for a few minutes so unrelated to actual performance I suppose.

Friday I was playing with some docker images so I was monitoring my computer a little at the same time just in case. Turns out it happened when I issued `docker-compose` commands while running glances in an other shell. 

I just tried that again today and I had the error while running this command:
```bash
docker-compose stop && docker-compose rm && docker-compose up
```

I tried to reproduce again this way but only happened once with the above so could be unrelated.

---

I just tried with python2.7 and I do have some stacktrace while its running, but glances keep running. Gives something a bit ugly like this:

![image](https://cloud.githubusercontent.com/assets/1264761/24335367/7cf3a7d0-1249-11e7-9090-f0c0822861d8.png)

Here's in plain text (I cleaned output a little):

    Exception in thread Thread-7:
    Traceback (most recent call last):
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self, **self.__kwargs)
    File "/Users/gableroux/.virtualenvs/glances27/lib/python2.7/site-packages/glances/outdated.py", line 163, in _update_pypi_version
    self._save_cache()
    File "/Users/gableroux/.virtualenvs/glances27/lib/python2.7/site-packages/glances/outdated.py", line 143, in _save_cache
    with open(self.cache_file, 'wb') as f:
    IOError: [Errno 13] Permission denied: '/Users/gableroux/Library/Caches/glances/glances-version.db'

in case it's useful:
```bash
ls -la /Users/gableroux/Library/Caches/glances/glances-version.db
-rw-r--r--  1 root  staff  137 24 Mar 15:59 /Users/gableroux/Library/Caches/glances/glances-version.db
```

Let's call this second error _"glances-version.db Permission denied"_ so we don't mix things up, not sure it's the same error.

I don't think its related to docker itself as I killed it and I still do have the above 2.7 _"glances-version.db Permission denied"_ error. And right now, I can't reproduce the first error in python3.6.

Let me know if you need some more details.

**Comment by nicolargo** [comment]
@GabLeRoux / @giampaolo : concerning the initial issue i can not reproduce it on my Linux system. A Docker-compose command line:

    docker-compose stop && docker-compose rm && docker-compose up

do not make Glances crash...

===

The second issue happens because you have started Glances with sudo the first time. The glances-version.db file has been created with root rights. When you start Glances with a non root user, it can not update it... I just open a new issue to track it => https://github.com/nicolargo/glances/issues/1066
