### ISSUE TITLE
Arch package problem with some library

### ISSUE THREAD

**Issue by mostafaasadi** [nicolargo/glances#1072]
Hi
the glances package in [Arch repo](https://www.archlinux.org/packages/community/any/glances/) runs with this error : 
`➜  ~ glances
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.8.8', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 225, in main
    start_standalone(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 105, in start_standalone
    standalone = GlancesStandalone(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/standalone.py", line 43, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 77, in load_modules
    self.load_plugins(args=args)
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 105, in load_plugins
    self._plugins[plugin_name] = plugin.Plugin(args=args)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_sensors.py", line 53, in __init__
    self.glancesgrabsensors = GlancesGrabSensors()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_sensors.py", line 229, in __init__
    self.stemps = psutil.sensors_temperatures()
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 2212, in sensors_temperatures
    rawdict = _psplatform.sensors_temperatures()
  File "/usr/lib/python3.6/site-packages/psutil/_pslinux.py", line 1116, in sensors_temperatures
    current = float(cat(base + '_input')) / 1000.0
  File "/usr/lib/python3.6/site-packages/psutil/_pslinux.py", line 299, in cat
    return f.read().strip()
OSError: [Errno 19] No such device
`
so I installed glances with curl script  and it run perfectlly successful .
do you access this package ? can you fix it ?
best regards

**Comment by nicolargo** [comment]
Please open an issue on the Arch issue tracker.

My two cents, it look like a PsUtil issue...
