### ISSUE TITLE
glances --browser on Windows (produces a curses error). Also cannot run --browser -w

### ISSUE THREAD

**Issue by nrapopor** [nicolargo/glances#1076]
##### Issue 1
browser option not working on windows ...

 1.    install on windows according to the instructions 
 2.    run glances --browser

 ````bash
 Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\glances-script.py", line 11, in <module>
    load_entry_point('Glances==2.9.1', 'console_scripts', 'glances')()
  File "c:\program files\python36\lib\site-packages\glances\__init__.py", line 134, in main
    start(config=config, args=args)
  File "c:\program files\python36\lib\site-packages\glances\__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "c:\program files\python36\lib\site-packages\glances\client_browser.py", line 56, in __init__
    self.screen = GlancesCursesBrowser(args=self.args)
  File "c:\program files\python36\lib\site-packages\glances\outputs\glances_curses_browser.py", line 36, in __init__
    super(GlancesCursesBrowser, self).__init__(args=args)
  File "c:\program files\python36\lib\site-packages\glances\outputs\glances_curses.py", line 102, in __init__
    self.screen = curses.initscr()
NameError: name 'curses' is not defined
 ````

##### Solution 
 1.    download latest curses from http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses
 2.    pip install curses‑2.2‑cp36‑cp36m‑win_amd64.whl 
 3.    modify `glances_curses.py` comment out the `if not WINDOWS` and adjust indent
 4.    run: glances --browser .. it works

##### Issue 2 
if I run **glances --browser -w** the **-w** is ignored  ... I was hoping to monitor all my machines from an easy chair in my living room on my iPad ... just saying

#### Versions

* Glances (glances -V): Glances v2.9.1
* PSutil (glances -V): psutil v5.2.1
* Operating System (lsb_release -a):  Windows 10

#### Logs
N/A

**Comment by nrapopor** [comment]
Sorry -- which part the curses support,  or running --browser as web. 

Thanks,

Nick

**Comment by mrmcox** [comment]
running browser as a web server would be awesome. then Glances could be accessed from an office windows PC and provide an over view of many other boxes.

**Comment by RazCrimson** [comment]
The Web UI feature with `--browser` is tracked here: #1121
