### ISSUE TITLE
No module named glances_monitor

### ISSUE THREAD

**Issue by halfpastfouram** [nicolargo/glances#1078]
#### Description

Trying to run `glances -c x.x.x.x` on my MacBook Pro results in an error saying "No module named glances_monitor".

I have a bunch of Linux servers running `glances -s`. I can use `glances -c x.x.x.x` from any one of those servers to check on the other servers, but when trying the same from my macOS machine i'm getting the error described above.

#### Versions

* Glances (glances -V): Glances v2.9.1
* PSutil (glances -V): psutil v5.2.0
* Operating System (lsb_release -a): macOS Sierra 10.12.3

#### Logs
    Traceback (most recent call last):
      File "/usr/local/bin/glances", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 134, in main
        start(config=config, args=args)
      File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 103, in start
        mode.serve_forever()
      File "/usr/local/lib/python2.7/site-packages/glances/client.py", line 228, in serve_forever
        if not self.login():
      File "/usr/local/lib/python2.7/site-packages/glances/client.py", line 156, in login
        if not self._login_glances():
      File "/usr/local/lib/python2.7/site-packages/glances/client.py", line 124, in _login_glances
        self.stats.set_plugins(json.loads(self.client.getAllPlugins()))
      File "/usr/local/lib/python2.7/site-packages/glances/stats_client.py", line 48, in set_plugins
        plugin = __import__(header + item)
    ImportError: No module named glances_monitor

**Comment by nicolargo** [comment]
What is your Glances server version ?

**Comment by halfpastfouram** [comment]
V2.1.1 with psutil v2.1.1

**Comment by nicolargo** [comment]
Can you try to upgrade it ?

**Comment by halfpastfouram** [comment]
After upgrading on one of the servers (now version v2.1.1 with psutil v2.1.1) the problem persists:
```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/client.py", line 228, in serve_forever
    if not self.login():
  File "/usr/local/lib/python2.7/site-packages/glances/client.py", line 156, in login
    if not self._login_glances():
  File "/usr/local/lib/python2.7/site-packages/glances/client.py", line 124, in _login_glances
    self.stats.set_plugins(json.loads(self.client.getAllPlugins()))
  File "/usr/local/lib/python2.7/site-packages/glances/stats_client.py", line 48, in set_plugins
    plugin = __import__(header + item)
ImportError: No module named glances_monitor
```

**Comment by halfpastfouram** [comment]
That actually worked. Upgrading was a bit of a hassle, though.

**Comment by halfpastfouram** [comment]
It would be great if a more user-friendly error message showed up on the client side.

**Comment by piozylka** [comment]
problem still exists
i can run glances on localhost but when i try to connect to remote server with glances
`No module named glances_monitor` pops out.
`Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.9.1', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/lib/python3.6/site-packages/glances/client.py", line 228, in serve_forever
    if not self.login():
  File "/usr/lib/python3.6/site-packages/glances/client.py", line 156, in login
    if not self._login_glances():
  File "/usr/lib/python3.6/site-packages/glances/client.py", line 124, in _login_glances
    self.stats.set_plugins(json.loads(self.client.getAllPlugins()))
  File "/usr/lib/python3.6/site-packages/glances/stats_client.py", line 48, in set_plugins
    plugin = __import__(header + item)
ModuleNotFoundError: No module named 'glances_monitor'
`
Glances v2.9.1 with psutil v5.2.2
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.0.1
Codename:	Gellivara

this problem exists on Arch Linux distribution.
tried to upgrade via pip with no success

**Comment by nicolargo** [comment]
@piozylka What is your remote Glances version ? (the server)

**Comment by piozylka** [comment]
I see what's ur point....
the server is `Glances v2.1.1 with psutil v2.1.1`
and the client `Glances v2.9.1 with psutil v5.2.2`
unfortunetly i cant upgrade glances on all 70 servers (Debian 8 Jessie) because the latest Glances needs python 3.5 or higher 
for now latest version of python for jessie is 3.4
so i'll wait for upgrade from  repos
thx for ur help
