### ISSUE TITLE
Easy bash install script fails on Debian 8

### ISSUE THREAD

**Issue by COLABORATI** [nicolargo/glances#1090]
The auto install script ```curl -L http://bit.ly/glances | /bin/bash``` fails on debian 8 - yes, I know one does not use auto-install bash scripts from the internetz - this is just a test system and usually I NEVER use auto install bash scripts because they might not work and leave the system in a f*d state without giving any hint about how to roll back the action, I just needed a quick glance on system temperatures and glances came to mind.... Uhmmm...

```
Install dependancies
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages
Downloading/unpacking glances[action,batinfo,browser,cpuinfo,chart,docker,export,folders,gpu,ip,raid,snmp,web,wifi]
  Downloading Glances-2.9.1.tar.gz (5.6MB): 5.6MB downloaded
  Running setup.py (path:/tmp/pip-build-pAuAwz/glances/setup.py) egg_info for package glances
    error in Glances setup command: Invalid environment marker: python_version<"3.5"
    Complete output from command python setup.py egg_info:
    error in Glances setup command: Invalid environment marker: python_version<"3.5"

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-pAuAwz/glances
Storing debug log for failure in /root/.pip/pip.log

root@testserver:~# cat /root/.pip/pip.log
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages
  skipping extra certs
  skipping extra ssl:sys_platform=='win32'
Downloading/unpacking glances[action,batinfo,browser,cpuinfo,chart,docker,export,folders,gpu,ip,raid,snmp,web,wifi]
  Getting page https://pypi.python.org/simple/glances/
  URLs to search for versions for glances[action,batinfo,browser,cpuinfo,chart,docker,export,folders,gpu,ip,raid,snmp,web,wifi]:
  * https://pypi.python.org/simple/glances/
  Analyzing links from page https://pypi.python.org/simple/glances/
    Skipping link https://pypi.python.org/packages/01/02/49e06fae0806fe82dc12c5652abd45da48d1243c855ceac91437e2caeebf/Glances-2.8.7-py3.4.egg#md5=a4c37b72366f42df1ba99ca6bf422ea1 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/09/5b/aacf4fd9215b5840d17df311da3089684bd055dd7ea96c36ff0383c7d3d1/Glances-2.8.2-py3.3.egg#md5=afce2b7fea3f62e4f80e4a62b646b67c (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/0e/1b/c9e36d47e09a0766c91a1ee7f1a4478e88d739302826f0ac224a3242884a/Glances-2.8.5-py3.3.egg#md5=8917b0e51b04729adf545a972379df20 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/11/57/3c741e46a1dfe48da16f349f9b861093a46dd72ba3dcfba9c55afe052c74/Glances-1.7.4.tar.gz#md5=522cf14906b407e877771e7c632c5409 (from https://pypi.python.org/simple/glances/), version: 1.7.4
    Skipping link https://pypi.python.org/packages/14/43/084d80a8562596d2bb7372eba7701b8aec0b418e76faa3c2f028a3eed7ff/Glances-2.8.5-py3.6.egg#md5=9b1f8af2c3d5c5b4633a936e74e9fd8d (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/17/2b/c1ae63b4b07441d13ac426dbaaa02bc099a38d4071becc6d03b777118da8/Glances-2.8.2-py2.7.egg#md5=cd0c063725d6933cd95b57bc4032d9b8 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/1a/07/e0767a579c2845bf2de575b4f98a811535244e7b5ea006262d6497ffbdd3/Glances-2.9.0-py3.3.egg#md5=7fe201c7b19303308f3d95910f064f79 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/1b/df/a11d7aafa9c4ab94e1fbfdef35a2eaec710f32310cc9dd569461e126a4ed/Glances-2.8.7-py3.5.egg#md5=7ce838f6eb91b80a9a1ecd6ef21ed3e7 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/1d/13/bfe748fc7bcd84cd21159fec86dad113cabc243fd40667651d74e0edb123/Glances-2.5.tar.gz#md5=70a7825a7b32048885f18ad3f8500294 (from https://pypi.python.org/simple/glances/), version: 2.5
    Found link https://pypi.python.org/packages/1f/10/ba2025883d595499a7bba5392a548a8fddd934af630a981d7bf8cbd1ec6e/Glances-2.7.1.tar.gz#md5=77a036e9cf988c543b5b216d37244871 (from https://pypi.python.org/simple/glances/), version: 2.7.1
    Skipping link https://pypi.python.org/packages/1f/27/29abe6d5befbfc1af286d6f757617243f6e913ecc3f92fd0791f3f2b0157/Glances-2.8.2-py3.6.egg#md5=179f3dba13c61ecc30bf7d8e149c09af (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/22/f6/ae8deefccf18e35d8fcac7ae5dc147c3d0349a399e4ec1f39c5ff7b126f4/Glances-2.8.6-py3.5.egg#md5=23af5ea6a9e2727306c0bd9a3e0dc0a6 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/28/53/c60eaa80467178e9805798e64fdafd200e1bb5ce4a2918cbbc907e13654d/Glances-2.8.7-py2.7.egg#md5=3bf11428538faff4c5fe522d41a70675 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/29/40/8ed28617649e1b538c1a4c40c7d24ea373758d1949424c4080e36d255287/Glances-2.6.tar.gz#md5=217cdfdec8b9f1db005e5f9cc9c9d5af (from https://pypi.python.org/simple/glances/), version: 2.6
    Skipping link https://pypi.python.org/packages/2f/c7/9d645dcdd53c8f49d5a266b4414a27427cef2d9db1c30fd324ff665d9807/Glances-2.9.1-py3.6.egg#md5=33330b05f53d11549df2e154851eeec5 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2f/e2/b42694c92354a4ba1e4a7546e79b21d39c245b64731b2adc8a4a0f1e7c96/Glances-2.8.6-py3.4.egg#md5=999fff782d9eb8d7aeb2ef7bae11a88c (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/30/3b/62b921bcbb505e02e6c19cbc650778c2d656987aeb746a733aebbdc59cf3/Glances-2.8.8.tar.gz#md5=cbc9dabeb82c8f152a8a42bb45ba0215 (from https://pypi.python.org/simple/glances/), version: 2.8.8
    Found link https://pypi.python.org/packages/35/e3/58f61aefb2b105d92af2f3add4865bd02869b312909576faa5b579f89c06/Glances-2.1.2.tar.gz#md5=35c2aeafec7a52c8b25ddf02385447dc (from https://pypi.python.org/simple/glances/), version: 2.1.2
    Found link https://pypi.python.org/packages/36/71/7f6003765bc6dcc7a988ab688ca238df661b11f1687a090a229fa7d32e16/Glances-2.6.2.tar.gz#md5=3c6bc4c4ded2dbebc964b7affa6fee79 (from https://pypi.python.org/simple/glances/), version: 2.6.2
    Found link https://pypi.python.org/packages/38/18/3cedaf71e1ae5ce38b098b5a4f477082b1eb4e25da29139b504763461c5a/Glances-1.7.tar.gz#md5=c6e623151a0d343b894bbc91f2816e30 (from https://pypi.python.org/simple/glances/), version: 1.7
    Skipping link https://pypi.python.org/packages/3b/4f/aad51721f0f187e5d29695cb466a4b07ebc13723bba3cd46ce19ec2e8dfe/Glances-2.8.4-py3.6.egg#md5=baca5234362e3dc3114a565f9209fc46 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/3b/e2/c34877d77bcdc63508870d813cd4e62b9a683eedf0cde0c3a51cd93d8a81/Glances-2.9.1-py3.5.egg#md5=52c858d31ac7c774b8517d4d89482372 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/3c/73/2e808cfa1bfa247424fd2e28b6ebe94edd87acdac054c709d02da41efbbc/Glances-2.4.1.tar.gz#md5=72f8f2f3765219f177327c238857bc63 (from https://pypi.python.org/simple/glances/), version: 2.4.1
    Found link https://pypi.python.org/packages/3e/ac/69d4268940943537bcdeaafcaa3b0c785dfee475c04a3a10ad7668b49082/Glances-2.8.2.tar.gz#md5=c0c2ab53948449f848adbec8fc3473c7 (from https://pypi.python.org/simple/glances/), version: 2.8.2
    Found link https://pypi.python.org/packages/42/c3/21301528ddc895a4cb9c0f606e39bd301c42ec6837a2ff24c52eae4493b3/Glances-2.7.tar.gz#md5=117bc54e2e16d8e02f581b100ea40f74 (from https://pypi.python.org/simple/glances/), version: 2.7
    Skipping link https://pypi.python.org/packages/47/a7/06f74524a870ce4e14e3e4f56ff0c51dda2ac5fd136cc1d2ac652fdddee1/Glances-2.9.1-py3.4.egg#md5=45ebdfef2722a5061e86c812a2f52844 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/48/98/da3e2ce15e09c37012136a16401905ba4e8f7247a5a8cfa070a4064c156f/Glances-2.0.1.tar.gz#md5=313bc2a161fb6820f554bd3e850f3f8d (from https://pypi.python.org/simple/glances/), version: 2.0.1
    Found link https://pypi.python.org/packages/4f/b1/9f11eba4a1b309a9ff7634481c88832667d0c68940beb2dd22ef81d1128c/Glances-2.8.3.tar.gz#md5=7e6dfe54adc8a42cf53fdefd257ecec1 (from https://pypi.python.org/simple/glances/), version: 2.8.3
    Found link https://pypi.python.org/packages/4f/b7/7b3f8d308550cafd96b07b55574538b46f718de236390bf526be536cf53f/Glances-2.8.tar.gz#md5=359ca7c9c4ececbd9b327046d66bd77b (from https://pypi.python.org/simple/glances/), version: 2.8
    Found link https://pypi.python.org/packages/52/2b/cd6929c584ab492ff74e50cff88ba1c48e0a19c7c44b90e5aca36fa7f476/Glances-1.7.7.tar.gz#md5=9f9c9adf2d9a89ad37eda18574a5207b (from https://pypi.python.org/simple/glances/), version: 1.7.7
    Found link https://pypi.python.org/packages/52/a0/f837a1d2bd76553575ed96a79649db6fcb5173eefffd63e818626a11b697/Glances-1.7.2.tar.gz#md5=0af31aa93237d86778fe837406327a10 (from https://pypi.python.org/simple/glances/), version: 1.7.2
    Skipping link https://pypi.python.org/packages/57/50/609e4f364b07fbb91b27d3ddb03df27d0d298ec2fdbc2cd9e28f2259c19d/Glances-2.8.8-py3.5.egg#md5=f8abd00df8c042f9967ba1f527718bb6 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/5a/07/9921bbadc9ac25c7f4ddd8c9db81334bf0b5623385f82c41230f27aae791/Glances-2.8.7-py3.3.egg#md5=71ca817d2bd815df9ba26af6321c4e65 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/5c/78/9e4276a1979df1e65d3c116b88295970a9179bcf50f6b201d8458ec0d2a8/Glances-2.8.8-py3.4.egg#md5=19433ed45e6add458b5544350ea2f3fc (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/63/38/81e46c4c574dba8a9479a94f5e960885c947ca0521cf0dd93b1f2acebb47/Glances-2.8.4-py3.5.egg#md5=a8bf5c144b5d544c7ba096a57711616b (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/65/16/a87f1e01c2041e03026aff1d7b48ea7af60b27cd460e079715a50dc3f034/Glances-2.9.1-py2.7.egg#md5=28fd1c1a3231aefdc05dce250e2c2094 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/65/ed/b8b1f755b8c5c34759e91343bf0b175524bbb978a86a18b65cd1cc0d36a9/Glances-2.9.1.tar.gz#md5=b34f70d3626def4e31bd1198e188744b (from https://pypi.python.org/simple/glances/), version: 2.9.1
    Skipping link https://pypi.python.org/packages/67/7f/27bf8c6c19fc35a5dd84989f4d93f9443238c7c606a968d68f4e8f180184/Glances-2.8.1-py3.4.egg#md5=46f666c74133af55535eab9bedd3b17f (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/6d/e2/c3521843710bfd9118114c4595456029332d0fb8d8ad678b07b05003091d/Glances-2.8.1-py3.6.egg#md5=a3a7bdea765a3fcce27ba4116564d8de (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/77/f8/9ccd48a2489bcdcd53fed2cddaa4e9fa6b168a49b2267922418673bbbe2e/Glances-2.8.1-py2.7.egg#md5=2201ed829e9bd2a82170284126d7063a (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/78/35/732cce187cf444511fc47d74057f0d4907e517d6fdc5e00a306f58a72d55/Glances-2.8.2-py3.5.egg#md5=3d96f6a71009c4eae0162fff90ca2212 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/7a/16/535f3da61d7ba7ffaa5c17a8acbaf5cdee2ae09951d5e5f6f8b52ce96bb2/Glances-1.7.6.tar.gz#md5=a8d306674a09d774d98affecd4437e8a (from https://pypi.python.org/simple/glances/), version: 1.7.6
    Skipping link https://pypi.python.org/packages/7a/2e/2a4aee405e88286c1c5d78810649888eca346941c65c08ef9a50e04f52be/Glances-2.9.0-py3.6.egg#md5=8aaed064bc3b316224e90a5721ca53a9 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/7a/6e/2dd509ec32f4c99bf99a1a1ce2117a4b4c973bf647e9c9a4c8542cd9610c/Glances-2.8.4-py3.4.egg#md5=184c06ef3ff4d25e25a35a6d977c4f43 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/7c/dc/8065f66c90bf0df5abc0aec4e44d9cfe32b54a03cd1ae41410937c3487a8/Glances-2.8.4-py2.7.egg#md5=50eda73b19fbefb737ee764f93225758 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/80/90/599bfa826f75a413f35806fc8f30dc307b0a40e7d09765faf904672e5276/Glances-2.8.8-py2.7.egg#md5=3ae35c60de7bf14200e245da5b2b4a3a (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/82/f4/f3b52bc33bfccfeab1f64316a7db29b9811610d27cbcf35c5a9234d2611e/Glances-2.8.4.tar.gz#md5=f19a53a831048187fe7040a87a9af2eb (from https://pypi.python.org/simple/glances/), version: 2.8.4
    Found link https://pypi.python.org/packages/83/64/a6276f912aa412f534660eae818b3e5f362a24f3652a2cd850311422f342/Glances-2.8.1.tar.gz#md5=6c33f583484b2c87da723099246ef9a9 (from https://pypi.python.org/simple/glances/), version: 2.8.1
    Found link https://pypi.python.org/packages/85/22/6daec93b29df56fd5685efe17f9c2e0da65380e6f2e78066a7ab9a1c7af0/Glances-1.7.3.tar.gz#md5=ab335ae071687540dd0b30058b6ed4d0 (from https://pypi.python.org/simple/glances/), version: 1.7.3
    Found link https://pypi.python.org/packages/8b/7e/f9151b8088cc61e6a6fcf458128c75771b069f50c5c7956d9daea249d301/Glances-2.4.tar.gz#md5=c9c4e55227ba8eb1742857275459e96e (from https://pypi.python.org/simple/glances/), version: 2.4
    Skipping link https://pypi.python.org/packages/8d/bf/2ffaf57dbb77673c45855b1ce12afa11cb7e43c10547d420cd7ce1df899c/Glances-2.8.6-py3.3.egg#md5=d6309a01d2c5a479a09b2a6d2c99270b (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/8e/31/85449ac344dbdc91764aea025eef741b6f1e5176765355ce6f23dedf6db4/Glances-2.1.1.tar.gz#md5=1c06a637d64fef94ecfe303188e6ab8a (from https://pypi.python.org/simple/glances/), version: 2.1.1
    Skipping link https://pypi.python.org/packages/8f/f4/0f580c233e843cb20059b6b8a0b35b9eb26e8a1af9ff4fa633d41559bde5/Glances-2.8.8-py3.6.egg#md5=34c7bc06af759ff02143ac4d35d1b959 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/93/a6/b88fdff5c8af076f92da174bf7407bb47f73358f7016f076ff8d5d32b28d/Glances-2.9.1-py3.3.egg#md5=12c4988ab3ddaf35a05f291874086860 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/97/06/eefd44312fa7daa1160c1f1ac4b945b65eb2e8c3e534e1ec1034c66b0a5d/Glances-1.7.5.tar.gz#md5=8481a7cf632dcd9b749478928d292a70 (from https://pypi.python.org/simple/glances/), version: 1.7.5
    Found link https://pypi.python.org/packages/98/71/060dd4113d4aeb3ff2bf0af359b9506b57242c08d61e49a7e6809385bfa7/Glances-2.3.tar.gz#md5=0022bac9891c914e2e6e86c0c300e58d (from https://pypi.python.org/simple/glances/), version: 2.3
    Skipping link https://pypi.python.org/packages/98/df/e5bad95eb846cddc72615a33265bc3c26bd3bee1bc0b2cd6a134137180f8/Glances-2.8.6-py3.6.egg#md5=01fca81382806b980443f3ae2af0b153 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/9a/8f/d320af7a0615c3c890aae24f363d75cfefbb66a30ef4c15ccca529f6aa3d/Glances-2.8.4-py3.3.egg#md5=9c9473d6c6a23709b945f91affde5072 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/9d/85/2563a0af9df906e648ad6b01eef686839d44307f07e288cbfb29d3c26c0a/Glances-2.8.5.tar.gz#md5=01ac6061aacef1f42b8f92e9fb65b84e (from https://pypi.python.org/simple/glances/), version: 2.8.5
    Skipping link https://pypi.python.org/packages/9e/ee/acb6e0c40e1f7a2d4f018fdaa6c9931073772ba089ad3b23f057f70efa83/Glances-2.8.6-py2.7.egg#md5=c2e22dfa3b28a7411c4ed091085a649c (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/9f/69/ff963c0d41ba0cdcf9dee8e73ab68fa4b6b95c4b4afda08e743604fc34c9/Glances-2.8.7.tar.gz#md5=7d9c36bbbd51fb266b871838bd1a9c9d (from https://pypi.python.org/simple/glances/), version: 2.8.7
    Skipping link https://pypi.python.org/packages/a0/9e/8d463fbb69557ac40d9ce3e10c14a6edb53426847aaeee2c1ed9faa13b9b/Glances-2.8.5-py3.4.egg#md5=d2e96530d66bf949197b72a1d30fbef5 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/a3/67/8a075e95fd6cad04be16f74e844af060f34bacaf72210622c7eb76b7a0ae/Glances-2.8.1-py3.5.egg#md5=e31ab32204420612fb3b1b7c2b83c296 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/b7/d5/df2ade81a198ecded82c69dd61ae693d3ac0f2662bd7df48bfa9d7791bf5/Glances-2.0.tar.gz#md5=4073889587195386df476f826256b81b (from https://pypi.python.org/simple/glances/), version: 2.0
    Skipping link https://pypi.python.org/packages/c1/1b/6f27fa0b8c3ff95b8843f0906e84e1de88b2eb6d52c476bf726e5cbb42d9/Glances-2.8.5-py2.7.egg#md5=b53ea2f1ce68f7f79bfde082d334c4ae (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/c2/80/2aeb57bb55cae8f2c6497b1d503317f9d3102e7f6c451139e8eda0d230e4/Glances-2.8.1-py3.3.egg#md5=e7408921b94641de012476c926c278cd (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/c3/ed/60462e0d28516132e7374b384fa698d7612a2371832314a30f66d6c908ba/Glances-2.6.1.tar.gz#md5=576e1cb937c1d1f384edaf20e4e33d98 (from https://pypi.python.org/simple/glances/), version: 2.6.1
    Skipping link https://pypi.python.org/packages/d2/04/7542a492dc07bf4809797e2b3d6932a13f0e8f4d4ea0ad4954635f9682da/Glances-2.8.8-py3.3.egg#md5=eb6149998e579e911ee0e0ca3f697b24 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/d5/d4/1299a8df135db47b911e82398285049e788b90576f39ebbe51f3d77e9281/Glances-2.5.1.tar.gz#md5=b8a7815353cf10e1aafffc6f4f235926 (from https://pypi.python.org/simple/glances/), version: 2.5.1
    Found link https://pypi.python.org/packages/d7/31/71fc63ba2358b018dc037e15bd7d19f952a3120ff284c35e70cfb45b8546/Glances-1.7.1.tar.gz#md5=8235f9ac59758cf752ce78d6fb8e6f27 (from https://pypi.python.org/simple/glances/), version: 1.7.1
    Found link https://pypi.python.org/packages/dc/b7/a63916e892fe1aadcc68d4610e3c722eab903e709daddebd3511a93388c3/Glances-2.8.6.tar.gz#md5=c708e1d16892ac870e7c20633478ae5c (from https://pypi.python.org/simple/glances/), version: 2.8.6
    Skipping link https://pypi.python.org/packages/e0/0d/04c9914cee163c41306a1d4c44f9b2c4c58f0f26d2a60415b966d15abc92/Glances-2.8.2-py3.4.egg#md5=e9674b19c2f4bbe928573096dc70d622 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/e3/ca/6fbbdd78949383f210e07dc0ae2fe7ab8d57fc77917aacf8d3d668412a51/Glances-2.2.1.tar.gz#md5=b5d7526cf87e3da364f87ec00d2877dd (from https://pypi.python.org/simple/glances/), version: 2.2.1
    Found link https://pypi.python.org/packages/ed/99/84f76cdd91c2b3542cc842d98d2a8d1e79c76381724d4ed79fa1d1f0f12c/Glances-2.2.tar.gz#md5=c55ba9dac01509828353c0508dbe95d6 (from https://pypi.python.org/simple/glances/), version: 2.2
    Skipping link https://pypi.python.org/packages/ed/a8/99392179494956e8b84e4129ddb510704ba41dd79752ba55602f2b8976ec/Glances-2.9.0-py2.7.egg#md5=04856fccf59a9b5710e850f29fe9b99c (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/f2/26/893bb4d9557bf1aeb192bc8a411a4abe862d825176340098ea446641a7e1/Glances-2.8.5-py3.5.egg#md5=acc4e6ebbed6efad650b1c013fb48a3e (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/f3/ce/bc69fbc1cf006d5b3bb988803fff6eb17dec73ede1ec7f7d737722226392/Glances-2.1.tar.gz#md5=6adebaf54015daa5a0e40aa44f4c3d96 (from https://pypi.python.org/simple/glances/), version: 2.1
    Found link https://pypi.python.org/packages/f5/81/2a3cd2a3f214b9392ae392f7b3bde5b3af23f34904e9d29e6e7bfce24f1f/Glances-2.4.2.tar.gz#md5=21d8ca9d780bb52101a365c33e65869d (from https://pypi.python.org/simple/glances/), version: 2.4.2
    Skipping link https://pypi.python.org/packages/fa/52/df8fd0ec9801071153189d83091c3ea72d5616d514ccba689f000be1ca6d/Glances-2.9.0-py3.5.egg#md5=f8aae5da76003a217a479992da772bb8 (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/fb/b8/accaded336ddf395b2db5de62c377b1e777e6aa8263463171611687f79d3/Glances-2.9.0-py3.4.egg#md5=f3b8223eed321a2c7a14bff1d30e4cda (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/fc/54/ab58b56122fd55cf89fb703773219b38fbddd6f2f750e4c3d6b114cac143/Glances-2.9.0.tar.gz#md5=c8e8d66e5f940a4fa1cc8085e7c22d83 (from https://pypi.python.org/simple/glances/), version: 2.9.0
    Skipping link https://pypi.python.org/packages/fc/df/d44fe3fbcf735a48c6ac491e54646af59f505a8d896e8412fd165097ab8e/Glances-2.8.7-py3.6.egg#md5=1e4ed29ab9dcb508e07883907eb1fbdd (from https://pypi.python.org/simple/glances/); unknown archive format: .egg
  Using version 2.9.1 (newest of versions: 2.9.1, 2.9.0, 2.8.8, 2.8.7, 2.8.6, 2.8.5, 2.8.4, 2.8.3, 2.8.2, 2.8.1, 2.8, 2.7.1, 2.7, 2.6.2, 2.6.1, 2.6, 2.5.1, 2.5, 2.4.2, 2.4.1, 2.4, 2.3, 2.2.1, 2.2, 2.1.2, 2.1.1, 2.1, 2.0.1, 2.0, 1.7.7, 1.7.6, 1.7.5, 1.7.4, 1.7.3, 1.7.2, 1.7.1, 1.7)
  Downloading from URL https://pypi.python.org/packages/65/ed/b8b1f755b8c5c34759e91343bf0b175524bbb978a86a18b65cd1cc0d36a9/Glances-2.9.1.tar.gz#md5=b34f70d3626def4e31bd1198e188744b (from https://pypi.python.org/simple/glances/)
  Running setup.py (path:/tmp/pip-build-pAuAwz/glances/setup.py) egg_info for package glances
    error in Glances setup command: Invalid environment marker: python_version<"3.5"
    Complete output from command python setup.py egg_info:
    error in Glances setup command: Invalid environment marker: python_version<"3.5"

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-pAuAwz/glances
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-pAuAwz/glances


```

**Comment by nicolargo** [comment]
Please open this issue on the autoinstallscript Github repo: https://github.com/nicolargo/glancesautoinstall
