### ISSUE TITLE
Create a Snap of Glances

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1101]
#### Description

Snap is an universal package manager for GNU/Linux system: https://snapcraft.io/

The goal is to create a snapcraft.yaml file. Glances is already register and the Glances Snap will be automatically created when the snapcraft.yaml will be pushed on the master branch.

How to create Snap package for Python programs ?

* https://blog.simos.info/how-to-create-a-snap-for-a-python-app-with-networking-using-snapcraft-in-ubuntu-16-04/
* https://github.com/snapcore/snapcraft/blob/master/demos/py2-project/snap/snapcraft.yaml

**Comment by nicolargo** [comment]
First step done with basic lib: PsUtil and Bottle

**Comment by nicolargo** [comment]
Solved by removing the PsUtil parts (already included by the Glances requirements.txt file).

**Comment by nicolargo** [comment]
Glances snap is published: https://dashboard.snapcraft.io/dev/snaps/7881/

**Comment by paranoicogm** [comment]
KDE Neon 5.10.3 Kernel 4.8.0-58-generic

`sudo snap install glances
` OK

`sudo glances` or `sudo snap run glances` FAIL

`Warning: Unable to set locale. Expect encoding problems.
/snap/glances/1/lib/python3.5/site-packages/psutil/_pslinux.py:502: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 13] Permission denied: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/snap/glances/1/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.10', 'console_scripts', 'glances')()
  File "/snap/glances/1/lib/python3.5/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/snap/glances/1/lib/python3.5/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/snap/glances/1/lib/python3.5/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/snap/glances/1/lib/python3.5/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/snap/glances/1/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 882, in wrapper
    ret = fct(self, *args, **kw)
  File "/snap/glances/1/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 891, in wrapper
    ret = fct(*args, **kw)
  File "/snap/glances/1/lib/python3.5/site-packages/glances/plugins/glances_fs.py", line 106, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/snap/glances/1/lib/python3.5/site-packages/psutil/__init__.py", line 2029, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/snap/glances/1/lib/python3.5/site-packages/psutil/_pslinux.py", line 1077, in disk_partitions
    partitions = cext.disk_partitions()
PermissionError: [Errno 13] Permission denied: '/etc/mtab'
`

**Comment by dhoomakethu** [comment]
on Ubunut snappy 16.04,  I am having the same error , Permission denied on `/etc/mtab`

**Comment by NatoBoram** [comment]
We should probably create a separate issue for the `PermissionError`.

```yaml
OS: Ubuntu 18.04.1 LTS x86_64 
Kernel: 4.15.0-33-generic 
Uptime: 19 mins 
Packages: 1854 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.28.3 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Ubuntu-mono-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 3628MiB / 7922MiB 
```

```yaml
Warning: Unable to set locale. Expect encoding problems.
/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py:1150: RuntimeWarning: ignoring PermissionError(13, 'Permission denied')
  warnings.warn("ignoring %r" % err, RuntimeWarning)
/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py:1191: RuntimeWarning: ignoring PermissionError(13, 'Permission denied')
  warnings.warn("ignoring %r" % err, RuntimeWarning)
/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py:515: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 13] Permission denied: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/snap/glances/5/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_fs.py", line 107, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/snap/glances/5/lib/python3.5/site-packages/psutil/__init__.py", line 1979, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py", line 1102, in disk_partitions
    partitions = cext.disk_partitions()
PermissionError: [Errno 13] Permission denied: '/etc/mtab'
```
