### ISSUE TITLE
Installing GPU plugin crashes entire glances

### ISSUE THREAD

**Issue by mackeyja92** [nicolargo/glances#1102]
#### Description

after installing the gpu plugin with `sudo pip3 install glances[gpu]` I am no longer able to open glances without it crashing with a `KeyError`. I can however run glances with `glances --disable-gpu` and it works fine. 

#### Versions

$ glances -V
Glances v2.10 with psutil v5.2.2
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

#### Logs

This is the only traceback I was able to get. Might not be the whole thing due to when curses crashed it messed up my terminal all the text was skewed. 
```
Traceback (most recent call last):
File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.10', 'console_scripts', 'glances')()
File "/usr/local/lib/python3.5/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
File "/usr/local/lib/python3.5/dist-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
File "/usr/local/lib/python3.5/dist-packages/glances/standalone.py", line 115, in serve_forever
    self.__serve_forever()
File "/usr/local/lib/python3.5/dist-packages/glances/standalone.py", line 104, in __serve_forever
    self.screen.update(self.stats)
File "/usr/local/lib/python3.5/dist-packages/glances/outputs/glances_curses.py", line 978, in update
     self.flush(stats, cs_status=cs_status)
File "/usr/local/lib/python3.5/dist-packages/glances/outputs/glances_curses.py", line 956, in flush
     self.display(stats, cs_status=cs_status)
File "/usr/local/lib/python3.5/dist-packages/glances/outputs/glances_curses.py", line 571, in display
    self.__display_secondline(__stat_display, stats)
File "/usr/local/lib/python3.5/dist-packages/glances/outputs/glances_curses.py", line 678, in __display_secondline
    int(not self.args.disable_memswap and stat_display["memswap"]['msgdict'] != []) + 
KeyError: 'gpu'
```

**Comment by nicolargo** [comment]
As said in the documentation, the nvidia-ml-py library used by the GPU plugin is only compatible with Python 2. Nevertheless, Glances should not crash and only display a warning message if the plugin is installed and used with Python 3.

I take the action to publish a patch.

**Comment by nicolargo** [comment]
Additionnaly, i just patch the official NVIDIA binding. As NVIDIA do not have a public repository, i create my own one (https://github.com/nicolargo/nvidia-ml-py3) and publish it to Pypi (https://pypi.python.org/pypi/nvidia-ml-py3).

You can try:

   # pip3 install nvidia-ml-py3

The plugin should work...

**Comment by mackeyja92** [comment]
Sorry, I must've missed that piece in the documentation about it not being compatible with python3. 

I have installed the nvidia-ml-py3 library and it is working now. Looks like some byte data is being stringified instead of decoded. The name is showing as `GPU b'GeForce GTX`.
