### ISSUE TITLE
glances_network `OSError: [Errno 19] No such device`

### ISSUE THREAD

**Issue by grst** [nicolargo/glances#1106]
#### Description

Since some time ago glances regularly fails with 
```
Traceback (most recent call last):
  File "/home/sturm/bin/anaconda3/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 882, in wrapper
    ret = fct(self, *args, **kw)
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 891, in wrapper
    ret = fct(*args, **kw)
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/glances/plugins/glances_network.py", line 99, in update
    netstatus = psutil.net_if_stats()
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 2189, in net_if_stats
    return _psplatform.net_if_stats()
  File "/home/sturm/bin/anaconda3/lib/python3.6/site-packages/psutil/_pslinux.py", line 977, in net_if_stats
    duplex, speed = cext.net_if_duplex_speed(name)
OSError: [Errno 19] No such device
```

glances runs as usual, then gets aborted with the above error. Once the error occured, I cannot restart the program, it will immediately fail with the above error. I have not observed a clear pattern yet, but the only device that I have been plugging in and out are (1) my charger (2) a USB drive (3) a USB mouse.

#### Versions

* Version (glances -V)
```Glances v2.10 with psutil v5.2.2```

* Operating System (lsb_release -a):
```
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 17.1 Rebecca
Release:	17.1
Codename:	rebecca
```

**Comment by grst** [comment]
I nailed it down: it's the charger.

**Comment by nicolargo** [comment]
Corrected in the latest commit.

Can you test the DEVELOP branch ?

**Comment by grst** [comment]
works :) 
Thank you!
