### ISSUE TITLE
ImportError: No module named influxdb

### ISSUE THREAD

**Issue by soliverprofesional** [nicolargo/glances#1110]
Fedora release 25 (Twenty Five)
Linux atsoliver.atsistemas 4.11.3-200.fc25.x86_64 #1 SMP Thu May 25 19:03:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Glances v2.5.1 with psutil v4.3.0

[root@atsoliver etc]# glances --export-influxdb
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 122, in main
    args=core.get_args())
  File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 42, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/core/glances_stats.py", line 60, in __init__
    self.load_exports(args=args)
  File "/usr/lib/python2.7/site-packages/glances/core/glances_stats.py", line 125, in load_exports
    export_module = __import__(os.path.basename(item)[:-3])
  File "/usr/lib/python2.7/site-packages/glances/exports/glances_influxdb.py", line 33, in <module>
    from influxdb import InfluxDBClient
ImportError: No module named influxdb

I have tried several ways, putting config file in several locations, using -C option, always same result. Thanks a lot for the help

**Comment by nicolargo** [comment]
@soliverprofesional as said in the documentation, you need the Python InfluxdDB lib to export Glances stats to an InfluxDB database.

    # sudo pip install influxdb

Note: you Glances version (2.5.1) is old and deprecated... Please install the new version... by reading the doc ==> https://github.com/nicolargo/glances#glances---an-eye-on-your-system

**Comment by still-L** [comment]
我也遇到了这个问题。
[root@localhost GlencesIG]# glances -V
Glances v3.1.0 with psutil v5.6.2
--------------------------------------------------------------------
[root@localhost GlencesIG]# glances --export influxdb
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==3.1.0', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 49, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 47, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 101, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 167, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/lib/python2.7/site-packages/glances/exports/glances_influxdb.py", line 27, in <module>
    from influxdb import InfluxDBClient
ImportError: No module named influxdb
[root@localhost GlencesIG]# pip install influxdb
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: influxdb in /usr/lib/python2.7/site-packages (5.2.2)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/lib/python2.7/site-packages (from influxdb) (2.8.0)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/site-packages (from influxdb) (1.11.0)
Requirement already satisfied: pytz in /usr/lib/python2.7/site-packages (from influxdb) (2019.1)
Requirement already satisfied: requests>=2.17.0 in /usr/lib/python2.7/site-packages (from influxdb) (2.20.1)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.17.0->influxdb) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.17.0->influxdb) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.17.0->influxdb) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.17.0->influxdb) (2018.10.15)
---------------------------------------------------------------------
请问该如何解决？
