### ISSUE TITLE
GPU plugin. <class 'TypeError'>:b'GeForce GTX 1070' is not JSON serializable">

### ISSUE THREAD

**Issue by redjoe** [nicolargo/glances#1112]
Bug: Try get all the stats from API. Glances run as server side. I have gpu nvidia 1070. 
```
>>> import xmlrpc.client
>>> s = xmlrpc.client.ServerProxy("http://localhost:61209")
>>> s.getAll()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1322, in parse_response
    return u.close()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'TypeError'>:b'GeForce GTX 1070' is not JSON serializable">
```
And in standalone mode, see:
```
2 GPU b'GeForce G
0: 85% mem:  18%
1: 2% mem:   8%
```
#### Steps

- Install glances.
sudo pip3 install glances

- Update psutil.
sudo pip3 install --upgrade psutil

- Add support GPU plugin.
sudo pip3 install nvidia-ml-py3

- start:
glances -s

- run python3
```
import xmlrpc.client
xmlrpc.client.ServerProxy("http://localhost:61209")
s.getAll()
```

#### Versions

- Glances (glances -V):
`Glances v2.10 with psutil v5.2.2`

- Operating System (lsb_release -a):
`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
`

**Comment by nicolargo** [comment]
Another boring encoding issue with Python 3...

In Python 2:

```
>>> import json
>>> json.dumps(b'GeForce GTX 1070')
'"GeForce GTX 1070"'
```

In Python 3:

```
>>> import json
>>> json.dumps(b'GeForce GTX 1070')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'GeForce GTX 1070' is not JSON serializable
```

**Comment by nicolargo** [comment]
Should be corrected by the latest commit. @redjoe please can you test the DEVELOP branch ?

Thanks !

**Comment by redjoe** [comment]
Now all works fine.
@nicolargo Thank you!
