### ISSUE TITLE
Fedora 25 docker issues

### ISSUE THREAD

**Issue by karlbateman** [nicolargo/glances#1119]
#### Description

I am trying to launch `glances` on Fedora 25 amd64 but I'm getting the following error.

```
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 122, in main
    args=core.get_args())
  File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/lib/python2.7/site-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 654, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_docker.py", line 152, in update
    self.docker_client = self.connect()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_docker.py", line 97, in connect
    ret = docker.Client(base_url='unix://var/run/docker.sock')
AttributeError: 'module' object has no attribute 'Client'
```
Docker has been installed with `curl -sSL 'https://get.docker.com' | sh`.

#### Versions

```
Glances v2.5.1
PSutil v4.3.0
Python 2.7.13
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive
```

**Comment by nicolargo** [comment]
Please upgrade your Glances and Docker-Py version.

If you have install Glances through Pipy, just enter the following command:

    pip install --upgrade docker
    pip install --upgrade glances
