### ISSUE TITLE
`UnicodeDecodeError` on mountpoints with non-breaking spaces

### ISSUE THREAD

**Issue by LGD-Fr** [nicolargo/glances#1128]
#### Description

While an external HDD of mine, with a NTFS partition named `HDD TOURO LGD` (with non-breaking spaces, of course non-ASCII) is connected to my PC (running Fedora 25 on x86_64) and its filesystem automatically mounted on `/run/media/lgd/HDD TOURO LGD`, when I run `glances`, I only see the traceback written lower (`UnicodeDecodeError…`), and the software exits with the status `1`.

###### Steps to reproduce

- Create a NTFS partition named with non-breaking spaces on an external hard drive.
- Connect the HDD to a Fedora 25-running PC, and let the OS mount the filesystem automatically to `/run/media/username/<name with non-breakin spaces`
- Run `glances`

#### Versions

* Glances (glances -V): 2.10
* PSutil (glances -V): 5.2.2
* Operating System (lsb_release -a): Fedora release 25 (Twenty Five)

#### Logs

Stderr:
```
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.10', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 882, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 891, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_fs.py", line 135, in update
    'mnt_point': fs.mountpoint.replace(u'\u00A0', ' '),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 18: ordinal not in range(128)
```

Logs: https://framabin.org/?9c0473075bd0f73b#3sFyq4nCw2aJ3l7X/9NMTssCxBwQ9RtBVwdaaXYGgkM=

**Comment by nicolargo** [comment]
Simple question, how can i set the name of an USB key with non-breaking spaces on my Ubuntu system ?

**Comment by nicolargo** [comment]
Nevermind, it's alt Gr + space...

**Comment by nicolargo** [comment]
@LGD-Fr Should be corrected in the latest commit (on the DEVELOP branch).

Correction will be merged in the master branch for the next version (Glances 2.11).

Thanks for the issue report.

**Comment by LGD-Fr** [comment]
Thanks!
