### ISSUE TITLE
 no attribute 'get_physmem'

### ISSUE THREAD

**Issue by kalgecin** [nicolargo/glances#115]
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==1.5b', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/Glances-1.5b-py2.7.egg/glances/glances.py", line 66, in <module>
    import psutil
  File "/usr/lib/python2.7/dist-packages/psutil/**init**.py", line 89, in <module>
    TOTAL_PHYMEM = _psplatform.phymem_usage()[0]
  File "/usr/lib/python2.7/dist-packages/psutil/_pslinux.py", line 135, in phymem_usage
    total, free, buffers = _psutil_linux.get_physmem()
AttributeError: 'module' object has no attribute 'get_physmem'

**Comment by dpcsuresh** [comment]
its not working.. can you tested
