### ISSUE TITLE
Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by Webysther** [nicolargo/glances#1156]
#### Description

Just running glances, installed using bash.

#### Versions

* Glances: 2.11.1
* PSutil: 5.3.1
* Operating System: Ubuntu 16.04.3 LTS

#### Logs

 ```shell
Failed to connect to bus: No such file or directory
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/glances/glances/amps/glances_systemd.py", line 73, in update
    res = check_output(self.get('systemctl_cmd').split())
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'/bin/systemctl', u'--plain']' returned non-zero exit status 1
```

**Comment by nicolargo** [comment]
Workaround, disable (enable=false) the AMP plugin in the Glances configuration file:

```
[amp_systemd]
# Use the Systemd AMP
enable=false
regex=\/lib\/systemd\/systemd
refresh=30
one_line=true
systemctl_cmd=/bin/systemctl --plain
```

**Comment by nicolargo** [comment]
Catch added in the latest commit in the DEVELOP branch.
