### ISSUE TITLE
glances_plugin.py has a problem with specific docker output 

### ISSUE THREAD

**Issue by muhahacz** [nicolargo/glances#1160]
#### Description

Seems that /usr/lib/python3.6/site-packages/glances/plugins/glances_plugin.py has a problem with specific docker output (maybe .State). I did not look at code.

#### Versions

* Glances (glances -V): 2.11.1
* PSutil (glances -V): 5.3.1
* Operating System (lsb_release -a): Alpine 3.6

#### Logs
```
user@user-Virtual-Machine:~/Docker/docker-glances$ sudo docker ps --no-trunc
CONTAINER ID                                                       IMAGE               COMMAND                                                                              CREATED             STATUS                         PORTS               NAMES
d9e4106cf276936a39857ca52157780a2f25b619ae8defc58ab21cf19d4a6db2   mynetdata           "/bin/sh -c '/usr/sbin/netdata -D -s /host -u root  -c /tmp/netdata/netdata.conf'"   30 seconds ago      Restarting (1) 2 seconds ago                       netdata

user@user-Virtual-Machine:~/Docker/docker-glances$  sudo docker logs glances
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.6/site-packages/glances/outputs/glances_bottle.py", line 533, in _enable_cors
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/glances/outputs/glances_bottle.py", line 164, in _index
    self.__update__()
  File "/usr/lib/python3.6/site-packages/glances/outputs/glances_bottle.py", line 89, in __update__
    self.stats.update()
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_docker.py", line 269, in update
    container['io'] = self.get_docker_io(container['Id'], self.thread_list[container['Id']].stats)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_docker.py", line 453, in get_docker_io
    ior = [i for i in iocounters['io_service_bytes_recursive'] if i['op'] == 'Read'][0]['value']
TypeError: 'NoneType' object is not iterable
```

**Comment by nicolargo** [comment]
Corrected in the latest commit.

Target release: Glances 3.0
