### ISSUE TITLE
Crash on startup: KeyError: 'hz_actual_raw' on Raspbian 9.1

### ISSUE THREAD

**Issue by JobbeDeluxe** [nicolargo/glances#1170]
#### Description
i installed glances from apt-get. but it was told me every time after colse that is out of date. so i tried many ways of install from here. but aufter houers of install, it won't start at all.
i get all the time Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/plugins/glances_quicklook.py", line 86, in update
    self.stats['cpu_hz_current'] = cpu_info['hz_actual_raw'][0]
KeyError: 'hz_actual_raw'

#### Versions
Glances v2.11.1 with psutil v5.4.0

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch

#### Logs

[glances-jobbe.log](https://github.com/nicolargo/glances/files/1405332/glances-jobbe.log)

**Comment by nicolargo** [comment]
I don't know what version is ran...

Please clean your system:

    # apt-get remove glances

Then install it with the standard way:

    # pip install glances

**Comment by JobbeDeluxe** [comment]
jobbe@Rserver:~ $ sudo apt-get remove glances
[sudo] Passwort für jobbe: 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paket »glances« ist nicht installiert, wird also auch nicht entfernt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
jobbe@Rserver:~ $ pip install glances
Collecting glances
Collecting psutil>=2.0.0 (from glances)
Installing collected packages: psutil, glances
Successfully installed glances-2.11.1 psutil-5.4.0

and i am not able to start:
jobbe@Rserver:~ $ glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/home/jobbe/.local/lib/python2.7/site-packages/glances/plugins/glances_quicklook.py", line 86, in update
    self.stats['cpu_hz_current'] = cpu_info['hz_actual_raw'][0]
KeyError: 'hz_actual_raw'

**Comment by JobbeDeluxe** [comment]
Even after uninstall over pip it will still able to "start":
```
Proceed (y/n)? y
  Successfully uninstalled Glances-2.11.1
jobbe@Rserver:~ $ glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_quicklook.py", line 86, in update
    self.stats['cpu_hz_current'] = cpu_info['hz_actual_raw'][0]
KeyError: 'hz_actual_raw'
```

it seams to be somthing is still on my system

**Comment by nicolargo** [comment]
Corrected in the DEVELOP branch.
