### ISSUE TITLE
NameError: name 'mode' is not defined in case of interrupt shortly after starting the server mode

### ISSUE THREAD

**Issue by languitar** [nicolargo/glances#1175]
#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

A `NameError` can be triggered in case the server mode (`-s` option) is interrupted with Ctrl+C shortly after starting the process:

```
languitar@jaco ~/thesis (master)> glances -s
Glances XML-RPC server is running on 0.0.0.0:61209
^CTraceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/server.py", line 224, in __init__
    self.server.register_instance(GlancesInstance(config, args))
  File "/usr/lib/python3.6/site-packages/glances/server.py", line 140, in __init__
    self.stats.update()
  File "/usr/lib/python3.6/site-packages/glances/stats_server.py", line 46, in update
    super(GlancesStatsServer, self).update()
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "/usr/lib/python3.6/site-packages/glances/processes.py", line 429, in update
    standard_stats=self.max_processes is None)
  File "/usr/lib/python3.6/site-packages/glances/processes.py", line 385, in __get_process_stats
    procstat = proc.as_dict(attrs=['pid'])
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 576, in as_dict
    with self.oneshot():
  File "/usr/lib/python3.6/contextlib.py", line 159, in helper
    return _GeneratorContextManager(func, args, kwds)
  File "/usr/lib/python3.6/contextlib.py", line 66, in __init__
    self.__doc__ = doc
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 68, in __signal_handler
    end()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 73, in end
    mode.end()
NameError: name 'mode' is not defined
```

#### Versions

Glances v2.11.1 with psutil v5.4.0

Archlinux 64 bit

**Comment by nicolargo** [comment]
Also reproduced o the DEVELOP branch.

**Comment by nicolargo** [comment]
Done.
