### ISSUE TITLE
Key error 'address' in the IP plugin

### ISSUE THREAD

**Issue by aftabnaveed** [nicolargo/glances#1176]
#### Description

When trying to --export-restful glances throws this error

```
glances --export-restful
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 117, in serve_forever
vagrant@vagrant-ubuntu-trusty-64:~$ glances --export-restful
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 104, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 978, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 956, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 528, in display
    __stat_display = self.__get_stat_display(stats, plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 492, in __get_stat_display
    ret[p] = stats.get_plugin(p).get_stats_display(args=self.args)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 762, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_ip.py", line 134, in msg_curse
    msg = '{}'.format(self.stats['address'])
KeyError: 'address'
```
Here is my configuration /etc/glances/glances.conf
```ini
[restful]
# Configuration for the --export-restful option
# Example, export to http://localhost:6789/
host=api.app.local
port=80
protocol=http
path=/api/glances/stats
```
#### Versions

* Version:   Glances v2.11.1
* PSutil (glances -V): psutil v5.4.0
* Operating System (lsb_release -a): Ubuntu 14.04

**Comment by aftabnaveed** [comment]
When I tried it with `glances --export-restful --disable-ip`  I started getting a new error which was 

```request() got an unexpected keyword argument 'json'```

I went and upgraded `sudo pip install --upgrade requests` which fixed the issue. 

But why is the IP module not working for me here?

**Comment by nicolargo** [comment]
The issue did not come from the export module but by the IP Plugins.

I will add a try/catch on the 'address' key.

**Comment by nicolargo** [comment]
Done

**Comment by aftabnaveed** [comment]
@nicolargo looks like this fix is still sitting in the develop branch, when is it expected to be merged?

**Comment by appositeit** [comment]
I just had this error (April 2020) and it was because my DNS resolution was broken. As soon as DNS resolved, glances worked fine.

btw- great program! I really like it. I've been using "top" forever and I've wholesale switched. Thank you for all your work!
