### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by y2kbug-hk** [nicolargo/glances#1178]
I have installed Glances on a 8GB-RAM Vultr instance, accessing via SSH.
Sometimes an error shows up after the UI is shown for several seconds.

```
Traceback (most recent call last): 
 File "/usr/local/bin/glances", line 11, in <module> 
   load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')() 
 File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main 
   start(config=config, args=args) 
 File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 103, in start 
   mode.serve_forever() 
 File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 117, in serve_forever 
   self.schedule.run() 
 File "/usr/lib/python2.7/sched.py", line 117, in run 
   action(*argument) 
 File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 100, in __serve_forever 
   self.stats.update() 
 File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 192, in update 
   self._plugins[p].update() 
 File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 884, in wrapper 
   ret = fct(self, *args, **kw) 
 File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 893, in wrapper 
   ret = fct(*args, **kw) 
 File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_docker.py", line 269, in update 
   container['io'] = self.get_docker_io(container['Id'], self.thread_list[container['Id']].stats) 
 File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_docker.py", line 453, in get_docker_io 
   ior = [i for i in iocounters['io_service_bytes_recursive'] if i['op'] == 'Read'][0]['value'] 
TypeError: 'NoneType' object is not iterable
```
Glances v2.11.1 with psutil v5.4.0
Ubuntu 16.04.3 LTS

log:
https://pastebin.com/j0ZjJgKZ

**Comment by nicolargo** [comment]
Workaround: disable the Docker plugin (--disable-docker).

What is your Docker version ?

**Comment by nicolargo** [comment]
REJECTED: cause duplicated

**Comment by davidmaxwaterman** [comment]
This is still a problem on the version shipped with Ubuntu, and this:

> Workaround: disable the Docker plugin (--disable-docker).

does not seem to be accurate. For anyone else looking for this, the following seems to work (I guess most people could figure it out for themselves, but no harm in being explicit):

```glances --disable-plugin docker```
