### ISSUE TITLE
Permission denied: '/etc/mtab' with the Glances' Snap version

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1181]
#### Description

Install Glances using Snap on Ubuntu.

Snap configuration file: https://github.com/nicolargo/glances/blob/develop/snap/snapcraft.yaml

Run Glances (same issue with or without sudo):

```
$ /snap/bin/glances 
Warning: Unable to set locale. Expect encoding problems.
/snap/glances/4/lib/python3.5/site-packages/psutil/_pslinux.py:1153: RuntimeWarning: ignoring PermissionError(13, 'Permission denied')
  warnings.warn("ignoring %r" % err, RuntimeWarning)
/snap/glances/4/lib/python3.5/site-packages/psutil/_pslinux.py:1194: RuntimeWarning: ignoring PermissionError(13, 'Permission denied')
  warnings.warn("ignoring %r" % err, RuntimeWarning)
Traceback (most recent call last):
  File "/snap/glances/4/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/snap/glances/4/lib/python3.5/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/snap/glances/4/lib/python3.5/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/snap/glances/4/lib/python3.5/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/snap/glances/4/lib/python3.5/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/snap/glances/4/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/snap/glances/4/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/snap/glances/4/lib/python3.5/site-packages/glances/plugins/glances_fs.py", line 107, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/snap/glances/4/lib/python3.5/site-packages/psutil/__init__.py", line 2062, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/snap/glances/4/lib/python3.5/site-packages/psutil/_pslinux.py", line 1105, in disk_partitions
    partitions = cext.disk_partitions()
PermissionError: [Errno 13] Permission denied: '/etc/mtab'
```

Note: also reproduced by others users. See https://github.com/nicolargo/glances/issues/1101

#### Versions

* Glances (glances -V): Glances 2.11.1
* PSutil (glances -V): PsUtil 2.5.4
* Operating System (lsb_release -a): Ubuntu 16.04 LTS

**Comment by nicolargo** [comment]
Glances must access to system information. I just add all the interfaces (https://docs.snapcraft.io/reference/interfaces) needed by Glances, so please update your Glances Snap installation with the 5 release.

If it doesn't work after the upgrade, please enter the following commands lines:

```
sudo snap connect glances:network
sudo snap connect glances:system-observe
sudo snap connect glances:mount-observe
sudo snap connect glances:hardware-observe
sudo snap connect glances:log-observe
sudo snap connect glances:network-observe
sudo snap connect glances:physical-memory-observe
sudo snap connect glances:upower-observe
```
@paranoicogm and  dhoomakethu : Can you test on your system and tell me if it's works (directly or after the commands lines) ?

Thanks and happy new years !

**Comment by dhoomakethu** [comment]
I will let you know how it goes in some days.

**Comment by dhoomakethu** [comment]
@nicolargo I could no longer see this issue, how ever when I started the web interface , I could see the following errors . 

```
$ glances -w
Warning: Unable to set locale. Expect encoding problems.
Glances web server started on http://0.0.0.0:61208/
Traceback (most recent call last):
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('192.168.128.247', 62190)
Traceback (most recent call last):
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/glances/x1/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/snap/glances/x1/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/snap/glances/x1/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/snap/glances/x1/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/simple_server.py", line 138, in handle
    handler.run(self.server.get_app())
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/simple_server.py", line 36, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
Traceback (most recent call last):
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('192.168.128.247', 62191)
Traceback (most recent call last):
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/glances/x1/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/snap/glances/x1/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/snap/glances/x1/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/snap/glances/x1/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/simple_server.py", line 138, in handle
    handler.run(self.server.get_app())
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/snap/glances/x1/usr/lib/python3.5/wsgiref/simple_server.py", line 36, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```
----------------------------------------
