### ISSUE TITLE
Glances stopped When it ran after a period of time

### ISSUE THREAD

**Issue by halolah** [nicolargo/glances#1183]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances (glances -V):master
* PSutil (glances -V): 5.3.0
* Operating System (lsb_release -a): Centos 7.2

#### Logs
Traceback (most recent call last):01 11:47:48 (ongoing) - LOAD (Min:1.5 Mean:1.6 Max:1.7)
  File "/usr/bin/glances", line 12, in <module>
    sys.exit(main())
  File "/home/soft/glances/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/home/soft/glances/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/home/soft/glances/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/lib64/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/home/soft/glances/glances/standalone.py", line 100, in __serve_forever
    self.stats.update()
  File "/home/soft/glances/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/home/soft/glances/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "/home/soft/glances/glances/processes.py", line 429, in update
    standard_stats=self.max_processes is None)
  File "/home/soft/glances/glances/processes.py", line 388, in __get_process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "/home/soft/glances/glances/processes.py", line 286, in __get_mandatory_stats
    proc_io = proc.io_counters()
  File "/home/soft/glances-venv/lib/python2.7/site-packages/psutil/__init__.py", line 807, in io_counters
    return self._proc.io_counters()
  File "/home/soft/glances-venv/lib/python2.7/site-packages/psutil/_pslinux.py", line 1369, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/soft/glances-venv/lib/python2.7/site-packages/psutil/_pslinux.py", line 1506, in io_counters
    name, value = line.split(b': ')
ValueError: need more than 1 value to unpack
You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
What is your Glances version 2.11.1 ?

Look like a PsUtil issue...

**Comment by halolah** [comment]
The Glances version is 2.11.0,the PsUtil version is 5.4.0

**Comment by gwh-cpnet** [comment]
I have Glances (2.11.1) and psutil (5.4.3), running as a pip installation based on a container based debian:stretch-slim image. 

The glances web server failed to respond in a few minutes, but nothing logged in /tmp. 

```dockerfile
FROM debian:stretch-slim

RUN apt-get update && apt-get -y install --no-install-recommends gcc python3 python3-pip python3-dev lm-sensors wireless-tools && rm -rf /var/lib/apt/lists/*

RUN pip3 install -U pip setuptools wheel
RUN pip3 install psutil glances[cpuinfo,docker,ip,web,wifi]

EXPOSE 61209
EXPOSE 61208
CMD glances -w
```

**Comment by nicolargo** [comment]
What about a docker logs command on the container Id ?

**Comment by gwh-cpnet** [comment]
@nicolargo nothing special
