### ISSUE TITLE
KeyError: 'memory_info' on stats sum

### ISSUE THREAD

**Issue by yhcharles** [nicolargo/glances#1188]
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/standalone.py", line 104, in __serve_forever
    self.screen.update(self.stats)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/outputs/glances_curses.py", line 978, in update
    self.flush(stats, cs_status=cs_status)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/outputs/glances_curses.py", line 956, in flush
    self.display(stats, cs_status=cs_status)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/outputs/glances_curses.py", line 528, in display
    __stat_display = self.__get_stat_display(stats, plugin_max_width)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/outputs/glances_curses.py", line 492, in __get_stat_display
    ret[p] = stats.get_plugin(p).get_stats_display(args=self.args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 762, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/plugins/glances_processlist.py", line 461, in msg_curse
    self.__msg_curse_sum(ret, args=args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/plugins/glances_processlist.py", line 527, in __msg_curse_sum
    msg = '{:>6}'.format(self.auto_unit(self.__sum_stats('memory_info', indice=1, mmm=mmm), low_precision=False))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/glances/plugins/glances_processlist.py", line 616, in __sum_stats
    ret += p[key][indice]
KeyError: 'memory_info'
```

**Comment by nicolargo** [comment]
Please can you fill the issue with the following information:

#### Versions

* Glances (glances -V):
* PSutil (glances -V):
* Operating System (lsb_release -a):

**Comment by yhcharles** [comment]
$ glances -V
Glances v2.11.1 with psutil v5.4.0
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by nicolargo** [comment]
Corrected in the latest commit.

Will be release in Glances 3.0.
