### ISSUE TITLE
Run Glances in Background through Supervisord

### ISSUE THREAD

**Issue by aftabnaveed** [nicolargo/glances#1194]
#### Description

I am trying to run glances in backround through Supervisord process management service, but it's failing due to the curses library being used and I get the below error:

```_curses.error: setupterm: could not find terminal```

Is there a way to run glances in background with export flags such as glances --restful-export? 

#### Versions

* Glances v2.11.1
* PSutil: v5.3.1
* Operating System (lsb_release -a):  Ubuntu 16.04.2 LTS

#### Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 80, in __init__
    self.screen = GlancesCursesStandalone(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 104, in __init__
    self.screen = curses.initscr()
  File "/usr/lib/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 80, in __init__
    self.screen = GlancesCursesStandalone(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 104, in __init__
    self.screen = curses.initscr()
  File "/usr/lib/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 80, in __init__
    self.screen = GlancesCursesStandalone(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 104, in __init__
    self.screen = curses.initscr()
  File "/usr/lib/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 80, in __init__
    self.screen = GlancesCursesStandalone(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 104, in __init__
    self.screen = curses.initscr()
  File "/usr/lib/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal

```

**Comment by nicolargo** [comment]
If you want to run Glances in background, you should use:

glances -s 

or 

glances -w

Please read the manual: http://glances.readthedocs.io/en/stable/quickstart.html

**Comment by aftabnaveed** [comment]
@nicolargo sorry for a long break though the issue is now closed but I am still getting the issue when I run  glances with an export flag such as `glances --export-restful`. This does not work with suprvisor and if I try to include -s flag  I get this error

`Export is only available in standalone or client mode`


Thank you.

**Comment by renegadeirfan** [comment]
today i faced same issue. I want to run glances in background and want logs to be available on my api endpoint. But it does not work.
@nicolargo is it possible? If yes, then can you guide what should be proper setup or command?

**Comment by nicolargo** [comment]
@renegadeirfan you had to wait Glances version 3.0 (will be available soon) to export data without the interface.

**Comment by Jannick-v** [comment]
You can run Glances in the background by using the `-q` option.
I successfully used Glances to monitor system resources and export it into a json format by issuing the following command (use `-t` to specify the refresh rate in seconds):
```glances --export-json resource_log.json -q -t 1 &```

**Comment by ErikKalkoken** [comment]
Using the `-q` option does not work for web server mode sadly.

But you can run it as service in web server mode with `supervisorctl`.

Check out [this page](https://www.tecmint.com/glances-monitor-remote-linux-in-web-server-mode/) for further instructions.

Adding to this I installed glances via pypi into a virtual environment under `/opt/glances` and are running it with its own non-sudo user. 

Here is my unit file:

```
[Unit]
Description = Glances in Web Server Mode
After = network.target

[Service]
User = glances
ExecStart = /opt/glances/venv/bin/glances -w -t 5

[Install]
WantedBy = multi-user.target
```

**Comment by visonforcoding** [comment]
> Using the `-q` option does not work for web server mode sadly.
> 
> But you can run it as service in web server mode with `supervisorctl`.
> 
> Check out [this page](https://www.tecmint.com/glances-monitor-remote-linux-in-web-server-mode/) for further instructions.
> 
> Adding to this I installed glances via pypi into a virtual environment under `/opt/glances` and are running it with its own non-sudo user.
> 
> Here is my unit file:
> 
> ```
> [Unit]
> Description = Glances in Web Server Mode
> After = network.target
> 
> [Service]
> User = glances
> ExecStart = /opt/glances/venv/bin/glances -w -t 5
> 
> [Install]
> WantedBy = multi-user.target
> ```



> Using the `-q` option does not work for web server mode sadly.
> 
> But you can run it as service in web server mode with `supervisorctl`.
> 
> Check out [this page](https://www.tecmint.com/glances-monitor-remote-linux-in-web-server-mode/) for further instructions.
> 
> Adding to this I installed glances via pypi into a virtual environment under `/opt/glances` and are running it with its own non-sudo user.
> 
> Here is my unit file:
> 
> ```
> [Unit]
> Description = Glances in Web Server Mode
> After = network.target
> 
> [Service]
> User = glances
> ExecStart = /opt/glances/venv/bin/glances -w -t 5
> 
> [Install]
> WantedBy = multi-user.target
> ```

-q option is working for me.
