### ISSUE TITLE
Another encoding issue... With both Python 2 and Python 3

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1197]
#### Description

Add the following line to the glances.conf file:

```
[amp_teststr]
enable=true
regex=.*python.*
refresh=30
one_line=true
command=echo "éùà"
```

Start Glances with Python 2:

```
  File "glances/stats.py", line 115, in _load_plugin
    self._plugins[name] = plugin.Plugin(args=args, config=config)
  File "/home/nicolargo/Dropbox/dev/glances/glances/plugins/glances_amps.py", line 40, in __init__
    self.glances_amps = glancesAmpsList(self.args, self.config)
  File "glances/amps_list.py", line 52, in __init__
    self.load_configs()
  File "glances/amps_list.py", line 87, in load_configs
    self.__amps_dict[amp_conf_name].load_config(self.config)
  File "glances/amps/glances_amp.py", line 97, in load_config
    logger.debug("{}: Load parameter: {} = {}".format(self.NAME, param, self.configs[param]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-8: ordinal not in range(128)
```

Start Glances with Python 3:

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nicolargo/Dropbox/dev/glances/glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/home/nicolargo/Dropbox/dev/glances/glances/amps/glances_default.py", line 71, in update
    self.set_result(to_ascii(msg.rstrip()))
  File "/home/nicolargo/Dropbox/dev/glances/glances/compat.py", line 67, in to_ascii
    return str(s, 'utf-8')
TypeError: decoding str is not supported
```

#### Versions

* Glances (glances -V): Glances 3.0 (DEVELOP BRANCH)

**Comment by nicolargo** [comment]
@asergi Encoding... Can you have a look on this issue and more generally refactor the encoding of string in Glances for the future version 3.0 ? (please !!!)

**Comment by mbirth** [comment]
I have the `TypeError: decoding str is not supported` even without any foreign characters, like:

```
[amp_fr24feed]
enable=true
regex=.*fr24feed.*
refresh=30
one_line=true
countmin=1
command=tail -n 1 /var/log/fr24feed.log.1
```

and

```
[amp_caddy]
enable=true
regex=.*caddy.*
refresh=30
one_line=true
countmin=1
command=journalctl -o cat -q -n 1 --no-pager -u caddy
```

These are the only two AMPs that have a `command` parameter.

**Comment by nicolargo** [comment]
@mbirth can you pastebin the Glances log file ?

**Comment by nicolargo** [comment]
More or less relative issue: https://github.com/nicolargo/glances/issues/1201

**Comment by mbirth** [comment]
@nicolargo Here it is: https://hastebin.com/ugalanisav.scala

The exceptions thrown are:

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/usr/local/lib/python3.6/dist-packages/glances/amps/glances_default.py", line 71, in update
    self.set_result(to_ascii(msg.rstrip()))
  File "/usr/local/lib/python3.6/dist-packages/glances/compat.py", line 67, in to_ascii
    return str(s, 'utf-8')
TypeError: decoding str is not supported

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/usr/local/lib/python3.6/dist-packages/glances/amps/glances_default.py", line 71, in update
    self.set_result(to_ascii(msg.rstrip()))
  File "/usr/local/lib/python3.6/dist-packages/glances/compat.py", line 67, in to_ascii
    return str(s, 'utf-8')
TypeError: decoding str is not supported
```

**Comment by nicolargo** [comment]
@mbirth Can you try with the latest commit (eef4fd7) in the DEVELOP branch ?

**Comment by mbirth** [comment]
@nicolargo Now the original problem seems to be fixed, but it's giving this:

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mbirth/glances/glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/home/mbirth/glances/glances/amps/glances_systemd.py", line 79, in update
    for r in to_ascii(res).split('\n')[1:-8]:
TypeError: a bytes-like object is required, not 'str'
```

Which seems to come from this section of my config:

```
[amp_systemd]
# Use the Systemd AMP
enable=true
regex=\/lib\/systemd\/systemd
refresh=30
one_line=true
systemctl_cmd=/bin/systemctl --plain
```

(I run it like: `python3 -m glances -C /opt/mbirth/glances.conf -1 -t 5 -d`)

On a sidenote: The docker plugin is not configured in my config, yet it shows this in the glances.log:

```
2017-12-16 15:53:08,429 -- CRITICAL -- Error while initializing the docker plugin (module 'docker' has no attribute 'from_env')
2017-12-16 15:53:08,434 -- ERROR -- Traceback (most recent call last):
  File "/home/mbirth/glances/glances/stats.py", line 117, in _load_plugin
    self._plugins[name] = plugin.Plugin(args=args)
  File "/home/mbirth/glances/glances/plugins/glances_docker.py", line 59, in __init__
    self.docker_client = self.connect()
  File "/home/mbirth/glances/glances/plugins/glances_docker.py", line 100, in connect
    return docker.from_env()
AttributeError: module 'docker' has no attribute 'from_env'
```

and also gives an exception on launch:

```
Error while initializing the docker plugin (module 'docker' has no attribute 'from_env')
[...]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mbirth/glances/glances/__main__.py", line 29, in <module>
    glances.main()
  File "/home/mbirth/glances/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/home/mbirth/glances/glances/__init__.py", line 109, in start
    mode.serve_forever()
  File "/home/mbirth/glances/glances/standalone.py", line 112, in serve_forever
    self.__serve_forever()
  File "/home/mbirth/glances/glances/standalone.py", line 107, in __serve_forever
    duration=self.refresh_time - counter.get())
  File "/home/mbirth/glances/glances/outputs/glances_curses.py", line 990, in update
    self.flush(stats, cs_status=cs_status)
  File "/home/mbirth/glances/glances/outputs/glances_curses.py", line 963, in flush
    self.display(stats, cs_status=cs_status)
  File "/home/mbirth/glances/glances/outputs/glances_curses.py", line 548, in display
    self.get_stats_display_height(__stat_display["docker"])
KeyError: 'docker'
```

And glances (develop) terminates itself, the last line in the logfile is:

```
2017-12-16 15:53:11,565 -- DEBUG -- cloud plugin - Cannot connect to the AWS EC2 API http://169.254.169.254/latest/meta-data/ami-id: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/ami-id (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x754af0d0>, 'Connection to 169.254.169.254 timed out. (connect timeout=3)'))
```

On subsequent tries, I also got `(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75cf1eb0>: Failed to establish a new connection: [Errno 113] No route to host',))`.

**Comment by nicolargo** [comment]
Ok, the last commit (205bed0) should resolve your encoding issue. Can you try (again) ?

**Comment by nicolargo** [comment]
Concerning the Docker issue, you should update your Docker Python lib:

    pip install --upgrade docker

And finally the last line in the log file is a debug message. You can ignore it.

**Comment by mbirth** [comment]
@nicolargo Awesome, after upgrading the docker lib, all problems are gone. Tested with python3 and 2.

**Comment by GJay17** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 40, in ManageMotion
    motion.GetInformationOnNextFrame()
  File "/home/js13/Desktop/SmartMirror-master/Motion/motion.py", line 76, in GetInformationOnNextFrame
    if Motion.previousFrame == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
