### ISSUE TITLE
Glances crashes when mountpoint with non ASCII characters exists

### ISSUE THREAD

**Issue by IIIMADDINIII** [nicolargo/glances#1201]
#### Description
If a mountpoint with an non ASCII character exists or is created, glances craches with the Tracheback below.

#### Versions
Glances v2.11.1 with psutil v5.4.2
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

#### Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 104, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 978, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 956, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 528, in display
    __stat_display = self.__get_stat_display(stats, plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 483, in __get_stat_display
    args=self.args, max_width=plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 762, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_fs.py", line 240, in msg_curse
    msg = '{:{width}}'.format(mnt_point, width=fsname_max_width)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 4: ordinal not in range(128)
```

**Comment by nicolargo** [comment]
Corrected in the develop branch.

Will be available in the next Glances 3.0 release.
