### ISSUE TITLE
autostart on AWS ?

### ISSUE THREAD

**Issue by drandreaskrueger** [nicolargo/glances#1215]
#### Description

I want the simplest route to autostarting 

    glances -s

and unfortunately the **AWS Amazon** default instances do not seem to have the [systemd](https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd) `sudo systemctl` command.

#### Partial solution

I am trying to wiggle myself into the `init.d` labyrinth, but so far no full success. Using a script adapted from [moumoul/scripting/initd/glances](https://github.com/moumoul/scripting/blob/master/initd/glances) --> [my version](https://gist.github.com/drandreaskrueger/4ba370787a2bc5bd9a107958d093b357) ... like this:

    sudo cp glances /etc/init.d/
    sudo ln -s /etc/init.d/glances /etc/rc.d/rc3.d/S97glances
    sudo reboot

and yes it does something, PID and LOCK file are created, but after rebooting, I do not see glances with

    ps aux | grep glances

#### Odd:

Strangely, when starting it manually as a user, it (kind of) works:

```
$ /etc/init.d/glances start

touch: cannot touch ‘/var/lock/subsys/glances’: Permission denied
$ Glances XML-RPC server is running on 0.0.0.0:61209
Announce the Glances server on the LAN (using 172.31.2.99 IP address)

$ ps aux | grep glances
ec2-user  3342  0.0  0.3 115612  3056 pts/0    S    16:14   0:00 /bin/sh /etc/init.d/glances start
ec2-user  3345  0.0  0.2 113096  2748 pts/0    S    16:14   0:00 /bin/bash -c ulimit -S -c 0 >/dev/null 2>&1 ; /home/ec2-user/env/glances/bin/glances -s
ec2-user  3346  2.2  2.9 545096 29600 pts/0    Sl   16:14   0:00 /home/ec2-user/env/glances/bin/python2.7 /home/ec2-user/env/glances/bin/glances -s
ec2-user  3378  0.0  0.2 110468  2044 pts/0    S+   16:14   0:00 grep --color=auto glances
```

I think I am almost there ... but I already have a big virtual bump on my head due to running against the same invisible wall for too long now ;-)
    
any idea?

**Comment by drandreaskrueger** [comment]
I see a logfile: 

```
cat /tmp/glances-ec2-user.log 
```

```
2018-01-08 17:13:56,153 -- INFO -- Start Glances 2.11.1
2018-01-08 17:13:56,153 -- INFO -- CPython 2.7.12 and PSutil 5.4.3 detected
2018-01-08 17:13:56,162 -- INFO -- Start GlancesServer mode
2018-01-08 17:13:56,854 -- WARNING -- Choked at offset 112 while unpacking '\x00\x00\x84\x00\x00\x00\x00\x04\x00\x00\x00\x00\x08_glances\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x0e\x10\x00\x17\x14ip-172-31-2-99:61209\xc0\x0c\xc0+\x00!\x00\x01\x00\x00\x0e\x10\x00\x16\x00\x00\x00\x00\xef\x19\x0eip-172-31-2-99\x00\xc0+\x00\x10\x00\x01\x00\x00\x0e\x10\x00\x00\xc0S\x00\x01\x00\x01\x00\x00\x0e\x10\x00\x04\xac\x1f\x02c'
2018-01-08 17:13:56,855 -- WARNING -- Exception occurred:
Traceback (most recent call last):
  File "/home/ec2-user/env/glances/local/lib/python2.7/site-packages/zeroconf.py", line 620, in __init__
    self.read_others()
  File "/home/ec2-user/env/glances/local/lib/python2.7/site-packages/zeroconf.py", line 673, in read_others
    domain = self.read_name()
  File "/home/ec2-user/env/glances/local/lib/python2.7/site-packages/zeroconf.py", line 727, in read_name
    length = indexbytes(self.data, off)
  File "/home/ec2-user/env/glances/local/lib/python2.7/site-packages/six.py", line 661, in indexbytes
    return ord(buf[i])
IndexError: string index out of range

```

**Comment by nicolargo** [comment]
@drandreaskrueger Can you try to run Glances with the --disable-autodiscover option ?

**Comment by nicolargo** [comment]
Any head up ?

**Comment by drandreaskrueger** [comment]
> simplest route to autostarting

my simplistic workaround worked - adding it to `/etc/rc.local`

```
LOGFILE=/tmp/glances-log.txt
COMMAND="/home/ec2-user/env/glances/bin/glances -s"
COMMAND_WITH_REDIRECTION="$COMMAND >> $LOGFILE 2>&1 &"

if [[ $1 == "serverservice" ]]; then
    SCRIPT=/etc/rc.local
    echo appending this to the autostarted system script $SCRIPT
    echo $COMMAND_WITH_REDIRECTION | sudo tee -a $SCRIPT
    echo and starting it manually now
    sudo rm $LOGFILE
    $COMMAND > $LOGFILE 2>&1 &
fi
```

so I never needed to look back.

AWS machines are dead now; perhaps next time we deploy, I could try your `--disable-autodiscover `. Why would that improve the situation?
