### ISSUE TITLE
ZeroDivisionError in IO Rate (ProcessList)

### ISSUE THREAD

**Issue by oppianmatt** [nicolargo/glances#1220]
#### Description

Hard to reproduce specifically but happens often enough.

#### Versions

* Glances (glances -V):
* PSutil (glances -V):
* Operating System (lsb_release -a):

Using docker version, hard to run -V as it's saying glances not in path.

nicolargo/glances                                        latest                          7f5f318d63df

```
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it docker.io/nicolargo/glances glances -V
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"glances\": executable file not found in $PATH": unknown.


> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it docker.io/nicolargo/glances -V
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"-V\": executable file not found in $PATH": unknown.
```

#### Logs

```
Traceback (most recent call last):
                                                                                                                                                   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
                                           "__main__", fname, loader, pkg_name)
                                                                                 File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
                                                                                                                                              exec code in run_globals
                                                                                                                                                                        File "/glances/glances/__main__.py", line 29, in <module>
                                                     glances.main()
                                                                     File "glances/__init__.py", line 140, in main
                                                                                                                      start(config=config, args=args)
                                                                                                                                                       File "glances/__init__.py", line 109, in start
                         mode.serve_forever()
                                               File "glances/standalone.py", line 138, in serve_forever
                                                                                                           loop = self.__serve_forever()
                                                                                                                                          File "glances/standalone.py", line 126, in __serve_forever
                        duration=self.refresh_time - counter.get())
                                                                     File "glances/outputs/glances_curses.py", line 952, in update
                                                                                                                                      self.flush(stats, cs_status=cs_status)
                                                                                                                                                                              File "glances/outputs/glances_curses.py", line 925, in flush
                                                              self.display(stats, cs_status=cs_status)
                                                                                                        File "glances/outputs/glances_curses.py", line 549, in display
                                                                                                                                                                          'processlist').get_stats_display(args=self.args)
                                            File "glances/plugins/glances_plugin.py", line 776, in get_stats_display
                                                                                                                        'msgdict': self.msg_curse(args),
                                                                                                                                                          File "/glances/glances/plugins/glances_processlist.py", line 475, in msg_curse
                                                            ret.extend(self.get_process_curses_data(p, first, args))
                                                                                                                      File "/glances/glances/plugins/glances_processlist.py", line 329, in get_process_curses_data
                                      io_rs = int((p['io_counters'][0] - p['io_counters'][2]) / p['time_since_update'])
                                                                                                                       ZeroDivisionError: float division by zero
```

The screen gets messed up and so the traceback isn't formatted nicely. 

I suspect `time_since_update` somehow is 0.

**Comment by nicolargo** [comment]
Almost sure that this issue came from: https://github.com/nicolargo/glances/issues/1105

I will have a look. 

Thanks !

**Comment by nicolargo** [comment]
Should be corrected. You had to wait that the continious delivery process generate thenew Docker image...

Keep me inform if the patch solves the issue.

Thanks for the report.
