### ISSUE TITLE
OSX - Python 3 and empty percent and res

### ISSUE THREAD

**Issue by notFloran** [nicolargo/glances#1251]
#### Description

With Python 3 I have the following "empty" lines that broke the sorting of the list : 

![capture d ecran 2018-04-23 a 15 02 33](https://user-images.githubusercontent.com/523981/39128217-7e296cae-4707-11e8-826f-3b6e53fdeb95.png)

With Python 2 no problem.

WebUI crash with:

```
angular.js:14800 TypeError: Cannot read property '1' of null
    at loadData (controller.js:25)
    at GlancesPluginProcesslistController.vm.$onInit (controller.js:9)
    at angular.js:9966
    at forEach (angular.js:416)
    at nodeLinkFn (angular.js:9955)
    at angular.js:10347
    at processQueue (angular.js:17169)
    at angular.js:17217
    at Scope.$digest (angular.js:18352)
    at Scope.$apply (angular.js:18649)
```

#### Versions

* Glances (glances -V): Glances v3.0.rc2 
* PSutil (glances -V): psutil v5.4.5
* Operating System (lsb_release -a): macOS

**Comment by nicolargo** [comment]
Hi @notFloran ,

do you have the same issue with the Curse interface ?

**Comment by notFloran** [comment]
@nicolargo yes, the screenshot is from the curse interface

**Comment by notFloran** [comment]
@nicolargo no problem  when I run Glances with sudo

**Comment by nicolargo** [comment]
Can you try this (from a standard user (no sudo)):

```
# python3
>>>  import psutil
>>> psutil.__version__
>>> standard_attrs = ['cmdline', 'cpu_percent', 'cpu_times', 'memory_info',
                          'memory_percent', 'name', 'nice', 'pid', 'ppid',
                          'status', 'username', 'status', 'num_threads']
>>> [p.info for p in psutil.process_iter(attrs=standard_attrs, ad_value=None)]
```

And same with python2

**Comment by notFloran** [comment]
Python 2: https://pastebin.com/kPY1GbHG

Python 3: https://pastebin.com/Sfim3w3r

**Comment by nicolargo** [comment]
The structure are identical for Python 2 and 3...

Most of the stats are only updated when process_iter is called twice. Please can you pastebin the result of this (for both Python 2 and Python 3):

```
>>> import time
>>> import psutil
>>> psutil.__version__
>>> standard_attrs = ['cmdline', 'cpu_percent', 'cpu_times', 'memory_info',
                          'memory_percent', 'name', 'nice', 'pid', 'ppid',
                          'status', 'username', 'status', 'num_threads']
>>> notusefull = [p.info for p in psutil.process_iter(attrs=standard_attrs, ad_value=None)]
>>> time.sleep(3)
>>> [p.info for p in psutil.process_iter(attrs=standard_attrs, ad_value=None)]
```

**Comment by notFloran** [comment]
I have updated the pastebins with the new results.

**Comment by nicolargo** [comment]
If i take the AppleCameraAssis process (filled with ? in your screenshot), i have:

For Python 2:

```
>>> d1 = {'status': 'running', 'username': '_cmiodalassistants', 'cpu_times': None, 'name': 'AppleCameraAssis', 'num_threads': None, 'cpu_percent': None, 'pid': 200, 'cmdline': None, 'memory_percent': None, 'memory_info': None, 'ppid': 1, 'nice': 0}
```

and for Python 3:

```
>>> d2 = {'cmdline': None, 'cpu_percent': None, 'name': 'AppleCameraAssis', 'pid': 200, 'nice': 0, 'num_threads': None, 'memory_percent': None, 'username': '_cmiodalassistants', 'cpu_times': None, 'ppid': 1, 'memory_info': None, 'status': 'running'}
```

and...

```
>>> d1 == d2
True
```

How can it works in Python 2 ? 

And the main question: why does processes are filled with None stats... ?

Can you do another check (always with Python 2&3).

Run Glances and get the PID of a non working processes (for example 20 fir AppleCameraAssis).

Then:

```
>>> import psutil
>>> p = psutil.Process(200)
>>> p.as_dict()
```

Thanks !

**Comment by notFloran** [comment]
Same result between python2 and python3: https://pastebin.com/81qStYtG

<img width="1679" alt="capture d ecran 2018-05-09 a 19 21 44" src="https://user-images.githubusercontent.com/523981/39829392-949b70d6-53be-11e8-87e7-b89b7e90a3f8.png">

After some tests I think the bug is present with python2 and 3 : the difference is that the sorting is not done in the same way and that the processes in error are not visible with python2.

With python2 if I filter the processes list with one of the process with None data, I get the following error : 

```
Traceback (most recent call last):
                                                                                                                                                       File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
                                                       "__main__", fname, loader, pkg_name)
                                                                                             File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
                                                                                                                                                                                                                                exec code in run_globals
            File "/Users/floranbrutel/dev/glances/glances/__main__.py", line 29, in <module>
                                                                                                glances.main()
                                                                                                                File "glances/__init__.py", line 140, in main
                                                                                                                                                                 start(config=config, args=args)
                                                                                                                                                                                                  File "glances/__init__.py", line 109, in start
      mode.serve_forever()
                            File "glances/standalone.py", line 139, in serve_forever
                                                                                        loop = self.__serve_forever()
                                                                                                                       File "glances/standalone.py", line 113, in __serve_forever
                                                                                                                                                                                     self.stats.update()
                                                                                                                                                                                                          File "glances/stats.py", line 221, in update
            self._plugins[p].update()
                                       File "/Users/floranbrutel/dev/glances/glances/plugins/glances_processcount.py", line 64, in update
                                                                                                                                             glances_processes.update()
                                                                                                                                                                         File "glances/processes.py", line 345, in update
                                                                                                                                                                                                                             self.set_max_values(k, max(i[k] for i in self.processlist
                                        ValueError: max() arg is an empty sequence
```
