### ISSUE TITLE
Reverse Proxy with nginx fails (Error: 403 Forbidden)

### ISSUE THREAD

**Issue by megamorphf** [nicolargo/glances#1254]
#### Description

I have tried to reverse proxy glances using NGINX, I used your official wiki NGINX config and modified mine, but both yielded same results the "Error: 403 Forbidden" error (see. screenshot).  Glances web interface works fine if I provide the host ant the port e.g. 192.168.0.123:61208.

I am using let's encrypt ssl certificates. One thing I noticed while reviewing logs is that for some reason url scheme ( in stack trace contains) http not *https*.  I personally think It is _allowed hosts_ issue, but I can't verify that.

#### Versions

* Glances (glances -V):  v2.7.1
* PSutil (glances -V):  v5.0.1
* Operating System (lsb_release -a): 
    Distributor ID: Debian
    Description:    Debian GNU/Linux 9.4 (stretch)
    Release:        9.4
    Codename:       stretch

#### NGINX conf snippet

```
  location /sys-monitor/ {
      proxy_pass http://192.168.0.8:61208;

      rewrite ^/sys-monitor(.*) /$1 break;
      port_in_redirect off;

      proxy_set_header    Host            $host;
      proxy_set_header    X-Real-IP       $remote_addr;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

#### Logs

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/usr/lib/python3/dist-packages/glances/amps/glances_nginx.py", line 80, in update
    res = requests.get(self.get('status_url'))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 190, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'localhost' doesn't match 'xxxx.yyyy.com'
```
![image 30-04-2018 at 21 34](https://user-images.githubusercontent.com/13219260/39443877-8816fb5c-4cbe-11e8-8ce2-7e5d4ea05245.jpg)

where xxxx.yyyy.com & black redacted text in the image is my domain

**Comment by notFloran** [comment]
Same error but nothing in the log.

@megamorphf for the error in the log I think is related to amp/ngix config. See `[amp_nginx]` and `status_url`

**Comment by spike008t** [comment]
Could you try to add the tailing / on `proxy_pass clause`?

```
  location /sys-monitor/ {
      proxy_pass http://192.168.0.8:61208/; <=== here tailing slash

      rewrite ^/sys-monitor(.*) /$1 break;
      port_in_redirect off;

      proxy_set_header    Host            $host;
      proxy_set_header    X-Real-IP       $remote_addr;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

**Comment by megamorphf** [comment]
hmm. I have just upgraded glances to `Glances v2.11.1 with psutil v5.4.5` and it started working. Not sure what was wrong there. I updated glances with pip.
