### ISSUE TITLE
glances --browser crashed when more than 40 glances servers on screen 78x45

### ISSUE THREAD

**Issue by serheang** [nicolargo/glances#1256]
#### Description

Whenever run "glances --browser" to view more than 40 glances servers in a screen size 78x45, it will crashed with error:
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/client_browser.py", line 244, in serve_forever
    return self.__serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/client_browser.py", line 232, in __serve_forever
    self.screen.update(self.get_servers_list())
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses_browser.py", line 131, in update
    self.flush(servers_list)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses_browser.py", line 156, in flush
    self.display(servers_list)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses_browser.py", line 267, in display
    y, xc, format(server_stat[c[0]]), c[2], self.colors_list[v['status']])
_curses.error: addnstr() returned ERR

#### Versions

* Glances (glances -V): v2.11.1
* PSutil (glances -V): v2.2.1
* Operating System (lsb_release -a):
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core

#### Logs

[glances-setan.log](https://github.com/nicolargo/glances/files/1965575/glances-setan.log)

**Comment by nicolargo** [comment]
Corrected in the DEVELOP branch (Glances 3.0 RC3).
Will be available in Glances 3.0.

Thanks for the report @serheang !

**Comment by serheang** [comment]
Thank you.

Thank you.
Warmest regards,
Ser Heang TAN
