### ISSUE TITLE
Crashes when influxdb option set

### ISSUE THREAD

**Issue by mark9064** [nicolargo/glances#1260]
#### Description

Glances crashes when the influxdb option is set. It works fine during normal operation. The influxdb server is running and the glances database exists within influxdb. I have tried running glances with sudo but it didn't help.

Tracebacks:

```
glances -C ~/.config/glances.conf --export-influxdb -q -d
Error while initializing the sensors plugin ([Errno 2] No such file or directory: '/sys/class/power_supply')
Error while initializing the batpercent plugin ([Errno 2] No such file or directory: '/sys/class/power_supply')
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/glances/exports/glances_export.py", line 155, in update
    all_stats = stats.getAllExportsAsDict(plugin_list=self.plugins_to_export())
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 237, in getAllExportsAsDict
    return {p: self._plugins[p].get_export() for p in plugin_list}
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 237, in <dictcomp>
    return {p: self._plugins[p].get_export() for p in plugin_list}
AttributeError: 'dict' object has no attribute 'get_export'

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 119, in serve_forever
    self.end()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 127, in end
    self.stats.end()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 280, in end
    self._plugins[p].exit()
AttributeError: 'dict' object has no attribute 'exit'
```

#### Versions
glances -V
Glances v2.11.1 with psutil v5.4.5
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:    xenial

#### Logs

##Start logfile
```
2018-05-12 16:59:35,530 -- INFO -- Start Glances 2.11.1
2018-05-12 16:59:35,531 -- INFO -- CPython 2.7.12 and PSutil 5.4.5 detected
2018-05-12 16:59:35,629 -- INFO -- Read configuration file '/home/server/.config/glances.conf'
2018-05-12 16:59:35,674 -- INFO -- Start GlancesStandalone mode
2018-05-12 16:59:36,103 -- CRITICAL -- Error while initializing the sensors plugin ([Errno 2] No such file or directory: '/sys/class/power_supply')
2018-05-12 16:59:36,141 -- ERROR -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 112, in _load_plugin
    plugin = __import__(plugin_script[:-3])
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_sensors.py", line 26, in <module>
    from glances.plugins.glances_batpercent import Plugin as BatPercentPlugin
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_batpercent.py", line 38, in <module>
    psutil.sensors_battery()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 2246, in sensors_battery
    return _psplatform.sensors_battery()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1228, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

2018-05-12 16:59:36,310 -- CRITICAL -- Error while initializing the batpercent plugin ([Errno 2] No such file or directory: '/sys/class/power_supply')
2018-05-12 16:59:36,312 -- ERROR -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 112, in _load_plugin
    plugin = __import__(plugin_script[:-3])
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_batpercent.py", line 38, in <module>
    psutil.sensors_battery()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 2246, in sensors_battery
    return _psplatform.sensors_battery()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1228, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

2018-05-12 16:59:36,911 -- INFO -- Stats will be exported to InfluxDB server: http://localhost:8086
```
##End logfile

**Comment by nicolargo** [comment]
Can you try this:

    $ glances -C ~/.config/glances.conf --export-influxdb -q -d --disable-sensors

**Comment by mark9064** [comment]
Same traceback in console.

It seems I copied the wrong debug long last time. Attached is the full debug log

[glances_debug_log.txt](https://github.com/nicolargo/glances/files/1997927/glances_debug_log.txt)

**Comment by mark9064** [comment]
I should probably note that I am running glances on an armhf system

**Comment by nicolargo** [comment]
Can you try with the DEVELOP branch ?

https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version

**Comment by mark9064** [comment]
```
~/tmp/glances-develop$ LANGUAGE=en_US.utf8  ~/glances-venv/bin/python -m glances -C ~/tmp/glances-develop/conf/glances.conf --export-influxdb -q -d
usage: glances [-h] [-V] [-d] [-C CONF_FILE] [--modules-list]
               [--disable-plugin DISABLE_PLUGIN] [--disable-process]
               [--disable-webui] [--light] [-0] [-1] [-2] [-3] [-4] [-5] [-6]
               [--disable-history] [--disable-bold] [--disable-bg]
               [--enable-irq] [--enable-process-extended] [--export EXPORT]
               [--export-csv-file EXPORT_CSV_FILE]
               [--export-json-file EXPORT_JSON_FILE]
               [--export-graph-path EXPORT_GRAPH_PATH] [-c CLIENT] [-s]
               [--browser] [--disable-autodiscover] [-p PORT]
               [-B BIND_ADDRESS] [--username] [--password]
               [--snmp-community SNMP_COMMUNITY] [--snmp-port SNMP_PORT]
               [--snmp-version SNMP_VERSION] [--snmp-user SNMP_USER]
               [--snmp-auth SNMP_AUTH] [--snmp-force] [-t TIME] [-w]
               [--cached-time CACHED_TIME] [--open-web-browser] [-q]
               [-f PROCESS_FILTER] [--process-short-name] [--stdout STDOUT]
               [--hide-kernel-threads] [-b] [--diskio-show-ramfs]
               [--diskio-iops] [--fahrenheit] [--fs-free-space]
               [--theme-white] [--disable-check-update]
glances: error: unrecognized arguments: --export-influxdb
```
Any ideas?

**Comment by nicolargo** [comment]
The syntax have change.

Now it is - - export influxdb (with a space between export and influxdb).

**Comment by nicolargo** [comment]
@mark9064 Just publish a patch on the DEVELOP branch, please update and test again.

Thanks !

**Comment by mark9064** [comment]
It's working! Thanks! Going to close for now as issue is resolved. If I have any more problems I will reopen the issue. :smile:
