### ISSUE TITLE
Unable to connect to glances server

### ISSUE THREAD

**Issue by GMishx** [nicolargo/glances#1278]
#### Description

I have a server running on Debian Jessie (8) and installed glances using `apt`. After that I ran `glances -s` to run glances in server mode and ran `glances -c <ip>` on my client. It produced following error message:
```
Traceback (most recent call last):
                                    File "/usr/bin/glances", line 9, in <module>
                                                                                    load_entry_point('Glances==2.3', 'console_scripts', 'glances')()
                                                                                                                                                      File "/usr/lib/python3/dist-packages/glances/__init__.py", line 151, in main
                          client.serve_forever()
                                                  File "/usr/lib/python3/dist-packages/glances/core/glances_client.py", line 230, in serve_forever
                                                                                                                                                      cs_status = self.update()
                                                                                                                                                                                 File "/usr/lib/python3/dist-packages/glances/core/glances_client.py", line 176, in update
                                                                  return self.update_glances()
                                                                                                File "/usr/lib/python3/dist-packages/glances/core/glances_client.py", line 203, in update_glances
                                                                                                                                                                                                     self.stats.update(server_stats)
                          File "/usr/lib/python3/dist-packages/glances/core/glances_stats.py", line 306, in update
                                                                                                                      self._plugins[p].update_views()
                                                                                                                                                       File "/usr/lib/python3/dist-packages/glances/plugins/glances_cpu.py", line 152, in update_views
                                              self.views['total']['decoration'] = self.get_alert_log(self.stats['total'], header="system")
                                                                                                                                          KeyError: 'total'
```

##### Server
* Glances & psutil (glances -V): Glances v2.1.1 with psutil v2.1.1
* Operating System (lsb_release -a):
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie
```
##### Client
* Glances & psutil (glances -V): Glances v2.3 with psutil v3.4.2
* Operating System (lsb_release -a):
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

##### Server
```
2018-06-22 10:10:47,097 -- INFO -- Start Glances 2.1.1
2018-06-22 10:10:47,097 -- INFO -- CPython 3.4.2 and PSutil 2.1.1 detected
2018-06-22 10:10:47,100 -- INFO -- Read configuration file /etc/glances/glances.conf
2018-06-22 10:10:47,100 -- INFO -- Start server mode
2018-06-22 10:12:23,665 -- INFO -- Stop Glances server (with CTRL-C)
```
##### Client
```
2018-06-22 10:10:24,146 -- INFO -- Start Glances 2.3
2018-06-22 10:10:24,146 -- INFO -- CPython 3.5.2 and PSutil 3.4.2 detected
2018-06-22 10:10:24,150 -- INFO -- Read configuration file '/etc/glances/glances.conf'
2018-06-22 10:10:24,150 -- INFO -- Start client mode
```

**Comment by shawngiese** [comment]
Is it because they are running different versions of Glances? I had that problem where pip installed a different version than yum.

**Comment by GMishx** [comment]
Sorry to keep you guys hanging. Just updated the glances to same version on both machines and it started working.
