### ISSUE TITLE
Glances crash with extended process stats 

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1283]
#### Description

glances
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/lib64/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 100, in __serve_forever
    self.stats.update()
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "/usr/lib/python2.7/site-packages/glances/processes.py", line 521, in update
    extended_stats=first)
  File "/usr/lib/python2.7/site-packages/glances/processes.py", line 394, in __get_process_stats
    procstat = self.__get_extended_stats(proc, procstat)
  File "/usr/lib/python2.7/site-packages/glances/processes.py", line 371, in __get_extended_stats
    procstat['tcp'] = len(proc.connections(kind="tcp"))
  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 1157, in connections
    return self._proc.connections(kind)
  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 1413, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=758, name='python')

#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.4.5
* Operating System (lsb_release -a): CentOS 7.3

**Comment by nicolargo** [comment]
Corrected in latest commit.
