### ISSUE TITLE
Disabling docker plugin not possible

### ISSUE THREAD

**Issue by ctron** [nicolargo/glances#1287]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

When the docker plugin cannot be loaded properly, I would still be able to run glances without it:

Run:

~~~
glances --disable-docker
~~~

#### Versions

* Glances & psutil (glances -V): Glances v2.5.1 with psutil v2.2.1
* Operating System (lsb_release -a):

~~~
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.5 (Maipo)
Release:	7.5
Codename:	Maipo
~~~

#### Logs

~~~
[root@node ~]# glances --disable-docker
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 122, in main
    args=core.get_args())
  File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/lib/python2.7/site-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 654, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_docker.py", line 152, in update
    self.docker_client = self.connect()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_docker.py", line 97, in connect
    ret = docker.Client(base_url='unix://var/run/docker.sock')
AttributeError: 'module' object has no attribute 'Client'
~~~

**Comment by ctron** [comment]
Deleting the plugin file results in the next problem:

~~~
[root@node ~]# glances --disable-docker
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 476, in display
    stats_docker = stats.get_plugin('docker').get_stats_display(
AttributeError: 'NoneType' object has no attribute 'get_stats_display'

~~~

**Comment by nicolargo** [comment]
It is a know bug already solved in the latest version of Glances. Please update your Glances installation.
