### ISSUE TITLE
Pin zeroconf dependency on 0.19 to maintain python 2 compatibility

### ISSUE THREAD

**Issue by Birne94** [nicolargo/glances#1293]
#### Description

[zeroconf](https://github.com/jstasiak/python-zeroconf) which is used for service discovery has recently removed support for python 2. In order to maintain compatibility with python 2, the dependency [should be pinned at 0.19.1](https://github.com/nicolargo/glances/blob/1cf84dfcef7f59435ccf10d2e4afd7bb8aeef948/setup.py#L83) which is the last python 2 compatible release.

#### Versions

```
root@8f989ad5e0a9:/glances# python -m glances -V
Glances v3.0.rc5 with psutil v5.4.3

root@8f989ad5e0a9:/glances# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

#### Container Logs

```
Glances XML-RPC server is running on 0.0.0.0:61208
Exception in thread zeroconf-Engine:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1133, in run
reader.handle_read(socket_)
File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1175, in handle_read
msg = DNSIncoming(data)
File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 644, in __init__
self.read_questions()
File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 667, in read_questions
name = self.read_name()
File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 756, in read_name
t = length & 0xC0
TypeError: unsupported operand type(s) for &: 'str' and 'int'

```

**Comment by nicolargo** [comment]
Done. Thanks for the head up.
