### ISSUE TITLE
Glances Terminal Interface Crash on OFFLINE servers

### ISSUE THREAD

**Issue by SecKarma** [nicolargo/glances#1295]
When you setup glances with --browser and do the configuration inside `glances.conf`
if a server went or is offline while / or after listing the servers, if you hit enter or try to access the offline marked server glances crash and gives the following:

```
Exception in thread Thread-7 (most likely raised during interpreter shutdown):Exception in thread Thread-13 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/Glances-3.0rc5-py2.7.egg/glances/plugins/glances_ip.py", line 180, in _get_ip_public
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1196, in do_open
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/Glances-3.0rc5-py2.7.egg/glances/plugins/glances_ip.py", line 180, in _get_ip_public
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1196, in do_open
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-11 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/Glances-3.0rc5-py2.7.egg/glances/plugins/glances_ip.py", line 180, in _get_ip_public
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1196, in do_open
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
root@glances-test-01:~# glances --browser --disable-autodiscover
Exception in thread Thread-56 (most likely raised during interpreter shutdown):Exception in thread Thread-58 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

  File "/usr/lib/python2.7/threading.py", line 754, in runTraceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "/usr/local/lib/python2.7/dist-packages/Glances-3.0rc5-py2.7.egg/glances/plugins/glances_ip.py", line 180, in _get_ip_public

  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen  File "/usr/lib/python2.7/threading.py", line 754, in run

  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1196, in do_open
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
  File "/usr/local/lib/python2.7/dist-packages/Glances-3.0rc5-py2.7.egg/glances/plugins/glances_ip.py", line 180, in _get_ip_public
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1196, in do_open
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

OS: **Ubuntu 16.04**

Glances Version: **Glances v3.0.rc5**
Psutil: **psutil v5.4.2**
from source branch "**develop**"

Glances Version: **Glances 2.11**
Psutil: **psutil v5.4.2**
from source branch "**master**"

**Comment by nicolargo** [comment]
Not reproduced on my side (with Glances v3.0.rc5).

I declare two Glances server in my glances.conf file (same computer but different TCP listening ports).

I start the two servers.

I start Glances Browser with:

    python -m glances --browser -C ~/data/glances-browser-test.conf --disable-autodiscover

The two servers are displayed in green. Everything is ok.

I stop the first server. It become red in the browser list.

When i select it and press enter, it try to connect and came back to the list without error (more or less 5 second later).

If i restart the first server, it become green. Get back to normal state...

**Comment by SecKarma** [comment]
what python version are you using? maybe it's because of that.
because everything you mentioned is exactly i'm doing in here but i get a crash on offline access.
so it's a python issue from my side.
