### ISSUE TITLE
KeyError: 'address' (trying to run glances --export-influxdb)

### ISSUE THREAD

**Issue by kramer65** [nicolargo/glances#1308]
#### Description

We're looking for an easy monitoring tool for our servers and Glances with Grafana seems like a perfect solution for us. So as a test I'm trying it out on a fresh DigitalOcean Ubuntu 18.04 server. I installed glances with pip and influxdb and grafana using apt. I can run glances in the terminal and also the web interface runs fine. Following [the suggestions here](https://glances.readthedocs.io/en/latest/gw/influxdb.html) I then created a database in InfluxDB called `glances`, created `/etc/glances/glances.conf` containing the suggested contents and  I ran `glances --export-influxdb`. That runs a couple seconds, after which it ends in the following error:

```
root@test-grafana:/etc/glances# glances --export-influxdb
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 104, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 978, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 956, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 528, in display
    __stat_display = self.__get_stat_display(stats, plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 492, in __get_stat_display
    ret[p] = stats.get_plugin(p).get_stats_display(args=self.args)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 762, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_ip.py", line 134, in msg_curse
    msg = '{}'.format(self.stats['address'])
KeyError: 'address'
```

#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.4.7
* Operating System (lsb_release -a):

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.1 LTS
> Release:	18.04
> Codename:	bionic
> 

Does anybody know what might be going wrong here? All tips are welcome!

**Comment by nicolargo** [comment]
Hi @kramer65,

can you try the following workaround ?

Run Glances with:

```
# glances --export-influxdb --disable-ip
```

**Comment by kramer65** [comment]
Yes, that works! Thanks!

I do get an empty Grafana dashboard though (see screenshot below) even though I do have output in the Glances terminal output (see second screenshot). Any idea what could still be wrong here? Any tips on where to start debugging this would be welcome as well.

![emptygrafana](https://user-images.githubusercontent.com/596581/45492057-9bea3000-b76b-11e8-93cf-4ff97dea231a.png)
![schermafdruk van 2018-09-13 15-41-29](https://user-images.githubusercontent.com/596581/45492061-9ee52080-b76b-11e8-8dd5-7fad12f51343.png)

**Comment by nicolargo** [comment]
@kramer65 Please read https://www.tecmint.com/install-glances-influxdb-grafana-to-monitor-centos-7/
