### ISSUE TITLE
Snap : Permission denied : "/etc/mtab"

### ISSUE THREAD

**Issue by NatoBoram** [nicolargo/glances#1310]
Before filling this issue, please read the [manual](https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the [database](https://github.com/nicolargo/glances/issues).

The issue was mentioned in #1101.

#### Description

Glances crashes on start.

Steps to reproduce : 

```bash
sudo snap install glances
glances
```

Result : 

```yaml
Warning: Unable to set locale. Expect encoding problems.
/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py:1150: RuntimeWarning: ignoring PermissionError(13, 'Permission denied')
  warnings.warn("ignoring %r" % err, RuntimeWarning)
/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py:1191: RuntimeWarning: ignoring PermissionError(13, 'Permission denied')
  warnings.warn("ignoring %r" % err, RuntimeWarning)
/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py:515: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 13] Permission denied: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/snap/glances/5/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_fs.py", line 107, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/snap/glances/5/lib/python3.5/site-packages/psutil/__init__.py", line 1979, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py", line 1102, in disk_partitions
    partitions = cext.disk_partitions()
PermissionError: [Errno 13] Permission denied: '/etc/mtab'
```

#### Versions

* Glances & psutil (glances -V)

```bash
glances -V

Warning: Unable to set locale. Expect encoding problems.
Glances v2.11.1 with psutil v5.4.2
```

* Operating System (lsb_release -a):

```bash
neofetch --off

OS: Ubuntu 18.04.1 LTS x86_64 
Kernel: 4.15.0-33-generic 
Uptime: 19 mins 
Packages: 1854 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.28.3 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Ubuntu-mono-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 3628MiB / 7922MiB 
```

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

```log
2018-08-26 01:11:59,166 -- INFO -- Start Glances 2.11.1
2018-08-26 01:11:59,166 -- INFO -- CPython 3.5.2 and PSutil 5.4.2 detected
2018-08-26 01:11:59,217 -- INFO -- Start GlancesStandalone mode
2018-08-26 01:11:59,639 -- ERROR -- Could not import pynvml.  NVIDIA stats will not be collected.
2018-08-26 01:13:45,100 -- INFO -- Start Glances 2.11.1
2018-08-26 01:13:45,100 -- INFO -- CPython 3.5.2 and PSutil 5.4.2 detected
2018-08-26 01:13:45,121 -- INFO -- Start GlancesStandalone mode
2018-08-26 01:13:45,392 -- ERROR -- Could not import pynvml.  NVIDIA stats will not be collected.
2018-08-26 01:15:55,255 -- INFO -- Start Glances 2.11.1
2018-08-26 01:15:55,255 -- INFO -- CPython 3.5.2 and PSutil 5.4.2 detected
2018-08-26 01:19:30,959 -- INFO -- Start Glances 2.11.1
2018-08-26 01:19:30,959 -- INFO -- CPython 3.5.2 and PSutil 5.4.2 detected
2018-08-26 01:19:30,980 -- INFO -- Start GlancesStandalone mode
2018-08-26 01:19:30,985 -- DEBUG -- Pystache library not found (action scripts won't work)
2018-08-26 01:19:30,988 -- DEBUG -- AMPs list: []
2018-08-26 01:19:30,989 -- DEBUG -- batpercent plugin - Batinfo library not found. Trying fallback to PsUtil.
2018-08-26 01:19:31,155 -- DEBUG -- cloud plugin - Create thread for AWS EC2
2018-08-26 01:19:31,161 -- DEBUG -- Starting new HTTP connection (1): 169.254.169.254
2018-08-26 01:19:31,164 -- DEBUG -- Stats history activated for plugin cpu (items: ['user', 'system'])
2018-08-26 01:19:31,185 -- DEBUG -- Stats history activated for plugin diskio (items: ['read_bytes', 'write_bytes'])
2018-08-26 01:19:31,255 -- DEBUG -- Stats history activated for plugin fs (items: ['percent'])
2018-08-26 01:19:31,257 -- ERROR -- Could not import pynvml.  NVIDIA stats will not be collected.
2018-08-26 01:19:31,257 -- DEBUG -- pynvml error: No module named 'pynvml'
2018-08-26 01:19:31,257 -- DEBUG -- pynvml could not be initialized.
2018-08-26 01:19:31,453 -- DEBUG -- Stats history activated for plugin load (items: ['min1', 'min5', 'min15'])
2018-08-26 01:19:31,455 -- DEBUG -- Stats history activated for plugin mem (items: ['percent'])
2018-08-26 01:19:31,456 -- DEBUG -- Stats history activated for plugin memswap (items: ['percent'])
2018-08-26 01:19:31,458 -- DEBUG -- Stats history activated for plugin network (items: ['rx', 'tx'])
2018-08-26 01:19:31,463 -- DEBUG -- No [ports] section in the configuration file. Cannot load ports list.
2018-08-26 01:19:31,463 -- DEBUG -- No [ports] section in the configuration file. Cannot load ports list.
2018-08-26 01:19:31,471 -- DEBUG -- pymdstat library not found. Glances cannot grab RAID info.
2018-08-26 01:19:31,473 -- DEBUG -- batpercent plugin - Batinfo library not found. Trying fallback to PsUtil.
2018-08-26 01:19:31,478 -- DEBUG -- Wifi library not found. Glances cannot grab Wifi info.
2018-08-26 01:19:31,478 -- DEBUG -- Available plugins list: ['folders', 'quicklook', 'hddtemp', 'raid', 'ip', 'docker', 'uptime', 'diskio', 'wifi', 'processcount', 'percpu', 'core', 'load', 'psutilversion', 'fs', 'network', 'alert', 'cpu', 'processlist', 'memswap', 'mem', 'batpercent', 'system', 'gpu', 'cloud', 'sensors', 'irq', 'ports', 'now', 'help', 'amps']
2018-08-26 01:19:31,478 -- DEBUG -- Available exports modules list: []
2018-08-26 01:19:31,478 -- DEBUG -- Load limit: quicklook_cpu_careful = 50.0
2018-08-26 01:19:31,478 -- DEBUG -- Load limit: quicklook_cpu_warning = 70.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: quicklook_cpu_critical = 90.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: quicklook_mem_careful = 50.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: quicklook_mem_warning = 70.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: quicklook_mem_critical = 90.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: quicklook_swap_careful = 50.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: quicklook_swap_warning = 70.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: quicklook_swap_critical = 90.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: percpu_user_careful = 50.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: percpu_user_warning = 70.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: percpu_user_critical = 90.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: percpu_system_careful = 50.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: percpu_system_warning = 70.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: percpu_system_critical = 90.0
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: load_careful = 0.7
2018-08-26 01:19:31,479 -- DEBUG -- Load limit: load_warning = 1.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: load_critical = 5.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: fs_careful = 50.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: fs_warning = 70.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: fs_critical = 90.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: network_rx_careful = 50.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: network_rx_warning = 70.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: network_rx_critical = 90.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: network_tx_careful = 50.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: network_tx_warning = 70.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: network_tx_critical = 90.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: cpu_user_careful = 50.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: cpu_user_warning = 70.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: cpu_user_critical = 90.0
2018-08-26 01:19:31,480 -- DEBUG -- Load limit: cpu_system_careful = 50.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_system_warning = 70.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_system_critical = 90.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_steal_careful = 50.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_steal_warning = 70.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_steal_critical = 90.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_iowait_careful = 20.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_iowait_warning = 22.5
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_iowait_critical = 25.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_ctx_switches_careful = 11200.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_ctx_switches_warning = 12600.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: cpu_ctx_switches_critical = 14000.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: processlist_cpu_careful = 50.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: processlist_cpu_warning = 70.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: processlist_cpu_critical = 90.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: processlist_mem_careful = 50.0
2018-08-26 01:19:31,481 -- DEBUG -- Load limit: processlist_mem_warning = 70.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: processlist_mem_critical = 90.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: memswap_careful = 50.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: memswap_warning = 70.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: memswap_critical = 90.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: mem_careful = 50.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: mem_warning = 70.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: mem_critical = 90.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_temperature_core_careful = 60.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_temperature_core_warning = 70.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_temperature_core_critical = 80.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_temperature_hdd_careful = 45.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_temperature_hdd_warning = 52.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_temperature_hdd_critical = 60.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_battery_careful = 80.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_battery_warning = 90.0
2018-08-26 01:19:31,482 -- DEBUG -- Load limit: sensors_battery_critical = 95.0
2018-08-26 01:19:31,483 -- DEBUG -- Extended stats for top process are disabled
2018-08-26 01:19:31,483 -- DEBUG -- Plugin folders update return []
2018-08-26 01:19:31,483 -- DEBUG -- Plugin quicklook update return {'mem': 43.3, 'percpu': [{'key': 'cpu_number', 'iowait': 0.0, 'system': 1.5, 'softirq': 0.0, 'guest': 0.0, 'irq': 0.0, 'cpu_number': 0, 'total': 9.1, 'user': 7.6, 'steal': 0.0, 'idle': 90.9, 'guest_nice': 0.0, 'nice': 0.0}, {'key': 'cpu_number', 'iowait': 0.0, 'system': 3.0, 'softirq': 1.5, 'guest': 0.0, 'irq': 0.0, 'cpu_number': 1, 'total': 12.1, 'user': 7.6, 'steal': 0.0, 'idle': 87.9, 'guest_nice': 0.0, 'nice': 0.0}, {'key': 'cpu_number', 'iowait': 0.0, 'system': 1.5, 'softirq': 0.0, 'guest': 0.0, 'irq': 0.0, 'cpu_number': 2, 'total': 33.3, 'user': 31.8, 'steal': 0.0, 'idle': 66.7, 'guest_nice': 0.0, 'nice': 0.0}, {'key': 'cpu_number', 'iowait': 0.0, 'system': 4.4, 'softirq': 0.0, 'guest': 0.0, 'irq': 0.0, 'cpu_number': 3, 'total': 70.6, 'user': 66.2, 'steal': 0.0, 'idle': 29.4, 'guest_nice': 0.0, 'nice': 0.0}], 'cpu': 31.3, 'swap': 0.0}
2018-08-26 01:19:31,483 -- DEBUG -- Cannot connect to an HDDtemp server (127.0.0.1:7634 => [Errno 111] Connection refused)
2018-08-26 01:19:31,483 -- DEBUG -- Disable the HDDtemp module. Use the --disable-hddtemp to hide the previous message.
2018-08-26 01:19:31,483 -- DEBUG -- Plugin hddtemp update return []
2018-08-26 01:19:31,484 -- DEBUG -- Can not grab RAID stats (name 'MdStat' is not defined)
2018-08-26 01:19:31,484 -- DEBUG -- Plugin raid update return {}
2018-08-26 01:19:31,484 -- DEBUG -- Plugin ip update return {}
2018-08-26 01:19:31,484 -- DEBUG -- Trying paths: ['/home/nato/snap/glances/5/.docker/config.json', '/home/nato/snap/glances/5/.dockercfg']
2018-08-26 01:19:31,484 -- DEBUG -- No config file found
2018-08-26 01:19:31,485 -- DEBUG -- docker plugin - Can't connect to the Docker server (('Connection aborted.', FileNotFoundError(2, 'No such file or directory')))
2018-08-26 01:19:31,485 -- DEBUG -- Plugin docker update return {}
2018-08-26 01:19:31,486 -- DEBUG -- Plugin uptime update return 0:25:43
2018-08-26 01:19:31,486 -- DEBUG -- Plugin diskio update return []
2018-08-26 01:19:31,486 -- DEBUG -- Plugin wifi update return []
2018-08-26 01:19:31,628 -- DEBUG -- Plugin percpu update return [{'key': 'cpu_number', 'iowait': 0.0, 'system': 1.5, 'softirq': 0.0, 'guest': 0.0, 'irq': 0.0, 'cpu_number': 0, 'total': 9.1, 'user': 7.6, 'steal': 0.0, 'idle': 90.9, 'guest_nice': 0.0, 'nice': 0.0}, {'key': 'cpu_number', 'iowait': 0.0, 'system': 3.0, 'softirq': 1.5, 'guest': 0.0, 'irq': 0.0, 'cpu_number': 1, 'total': 12.1, 'user': 7.6, 'steal': 0.0, 'idle': 87.9, 'guest_nice': 0.0, 'nice': 0.0}, {'key': 'cpu_number', 'iowait': 0.0, 'system': 1.5, 'softirq': 0.0, 'guest': 0.0, 'irq': 0.0, 'cpu_number': 2, 'total': 33.3, 'user': 31.8, 'steal': 0.0, 'idle': 66.7, 'guest_nice': 0.0, 'nice': 0.0}, {'key': 'cpu_number', 'iowait': 0.0, 'system': 4.4, 'softirq': 0.0, 'guest': 0.0, 'irq': 0.0, 'cpu_number': 3, 'total': 70.6, 'user': 66.2, 'steal': 0.0, 'idle': 29.4, 'guest_nice': 0.0, 'nice': 0.0}]
2018-08-26 01:19:31,629 -- DEBUG -- Plugin load update return {'min1': 0.55, 'cpucore': 4, 'min5': 0.63, 'min15': 0.49}
2018-08-26 01:19:31,629 -- DEBUG -- Plugin psutilversion update return (5, 4, 2)
2018-08-26 01:19:34,166 -- DEBUG -- cloud plugin - Cannot connect to the AWS EC2 API http://169.254.169.254/latest/meta-data/placement/availability-zone: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/placement/availability-zone (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f1e429f28>, 'Connection to 169.254.169.254 timed out. (connect timeout=3)'))
```

**Comment by nicolargo** [comment]
@NatoBoram Have you try this: https://github.com/nicolargo/glances/issues/1181#issuecomment-354645551

**Comment by NatoBoram** [comment]
It works!

![image](https://user-images.githubusercontent.com/10495562/45056008-9f8d0100-b05f-11e8-8b49-ed38eb0711a0.png)

I had to `refresh glances` and create a new terminal to make it work.

```bash
sudo snap refresh glances
sudo snap connect glances:network
sudo snap connect glances:system-observe
sudo snap connect glances:mount-observe
sudo snap connect glances:hardware-observe
sudo snap connect glances:log-observe
sudo snap connect glances:network-observe
sudo snap connect glances:physical-memory-observe
sudo snap connect glances:upower-observe
exit
```
