### ISSUE TITLE
TypeError: '<' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by IchSchreiGleich** [nicolargo/glances#1315]
#### Description

If I start Glances and want to sort by process name, Glances stop working.

- Start Glances with "glances --disable-plugin sensors"
- Press "P"-Key to sort by process name

#### Versions

* Glances v3.0.1 with psutil v5.4.7
* FreeBSD 11.2-RELEASE-p2

#### Logs

I am so sorry, but this is excactly what I am get, when it crashes:

```
2018-09-06 15:54:56 CET                No warning or critical alert detectedTraceback (most recent call last):
                                                                                                                File "/usr/local/lib/python3.6/site-packages/glances/processes.py", line 408, in sort_stats
        reverse=reverse)
                        TypeError: '<' not supported between instances of 'float' and 'str'

                                                                                           During handling of the above exception, another exception occurred:

                                                                                                                                                              Traceback (most recent call last):
                                                                                                                                                                                                  File "/usr/local/bin/glances", line 11, in <module>
                                                  load_entry_point('Glances==3.0.1', 'console_scripts', 'glances')()
                                                                                                                      File "/usr/local/lib/python3.6/site-packages/glances/__init__.py", line 140, in main
       start(config=config, args=args)
                                        File "/usr/local/lib/python3.6/site-packages/glances/__init__.py", line 109, in start
                                                                                                                                 mode.serve_forever()
                                                                                                                                                       File "/usr/local/lib/python3.6/site-packages/glances/standalone.py", line 141, in serve_forever
                                                   loop = self.__serve_forever()
                                                                                  File "/usr/local/lib/python3.6/site-packages/glances/standalone.py", line 128, in __serve_forever
                                                                                                                                                                                       duration=self.refresh_time - counter.get())
                             File "/usr/local/lib/python3.6/site-packages/glances/outputs/glances_curses.py", line 984, in update
                                                                                                                                     self.flush(stats, cs_status=cs_status)
                                                                                                                                                                             File "/usr/local/lib/python3.6/site-packages/glances/outputs/glances_curses.py", line 939, in flush
                                                                             self.display(stats, cs_status=cs_status)
                                                                                                                       File "/usr/local/lib/python3.6/site-packages/glances/outputs/glances_curses.py", line 552, in display
                         'processlist').get_stats_display(args=self.args)
                                                                           File "/usr/local/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 789, in get_stats_display
                                                                                                                                                                                              'msgdict': self.msg_curse(args),
                         File "/usr/local/lib/python3.6/site-packages/glances/plugins/glances_processlist.py", line 422, in msg_curse
                                                                                                                                         for p in self.__sort_stats(process_sort_key):
                                                                                                                                                                                        File "/usr/local/lib/python3.6/site-packages/glances/plugins/glances_processlist.py", line 629, in __sort_stats
                                                                                                    reverse=glances_processes.sort_reverse)
                                                                                                                                             File "/usr/local/lib/python3.6/site-packages/glances/processes.py", line 411, in sort_stats
                                     reverse=False)
                                                   TypeError: '<' not supported between instances of 'NoneType' and 'str'

```

**Comment by nicolargo** [comment]
Hi @IchSchreiGleich !

Not reproduced on my Linux system. Could you please paste/bin us the Glances log file (/tmp/glances-$USER.log) ?

Thanks

**Comment by IchSchreiGleich** [comment]
Hi @nicolargo 

Sure: https://pastebin.com/cbruDZZw
Possibly the last line is interesting?
```
2018-09-07 12:56:05,488 -- DEBUG -- Keypressed (code: [112, -1])
```

**Comment by nicolargo** [comment]
Nope, it is not related to the issue...

Are the others sorts working without error ?

**Comment by IchSchreiGleich** [comment]
Latest release from DEVELOP branch works now, as expected. Good job.
Maybe interesting: Building with no errors, installing with this one:
```
Extracting Glances-3.1.0b0-py2.7.egg to /usr/local/lib/python2.7/site-packages
  File "/usr/local/lib/python2.7/site-packages/Glances-3.1.0b0-py2.7.egg/glances/exports/glances_mqtt.py", line 95
    topic = '/'.join([self.topic, self.hostname, name, *sensor])
                                                       ^
SyntaxError: invalid syntax
```
Anyway, sorting is fine. :)

**Comment by atriwidada** [comment]
not sure if this is the same error, but still happened on 3.1.0 beta:
called with params:  glances --disable-plugin amps,alert
also error if called without params.

Glances v3.1.0_beta with psutil v5.4.7

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.0b0', 'console_scripts', 'glances')()
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/__init__.py", line 109, in start
    mode.serve_forever()
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/standalone.py", line 141, in serve_forever
    loop = self.__serve_forever()
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/standalone.py", line 128, in __serve_forever
    duration=self.refresh_time - counter.get())
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/outputs/glances_curses.py", line 966, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/outputs/glances_curses.py", line 939, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/outputs/glances_curses.py", line 524, in display
    __stat_display = self.__get_stat_display(stats, layer=cs_status)
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/outputs/glances_curses.py", line 498, in __get_stat_display
    max_width=plugin_max_width)
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/plugins/glances_plugin.py", line 785, in get_stats_display
    'msgdict': self.msg_curse(args, max_width=max_width),
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/plugins/glances_network.py", line 283, in msg_curse
    for i in self.sorted_stats():
  File "/usr/local/lib/python3.6/dist-packages/Glances-3.1.0b0-py3.6.egg/glances/plugins/glances_plugin.py", line 297, in sorted_stats
    return sorted(self.stats, key=lambda stat: tuple(map(
TypeError: '<' not supported between instances of 'int' and 'str'
