### ISSUE TITLE
FileNotFoundError (/system/etc/mtab) on Android (termux)

### ISSUE THREAD

**Issue by stephengmatthews** [nicolargo/glances#1344]
I installed glances according to the README on Android (7) under termux. When I run glances, it returns:
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.0.2', 'console_scripts', 'glances')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/standalone.py", line 73, in __init__
    self.stats.update()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/stats.py", line 222, in update
    self._plugins[p].update()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/plugins/glances_plugin.py", line 911, in wrapper''
ret = fct(self, *args, **kw)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/plugins/glances_plugin.py", line 920, in wrapper
    ret = fct(*args, **kw)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/plugins/glances_fs.py", line 99, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/psutil/__init__.py", line 1990, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/psutil/_pslinux.py", line 1162, in disk_partitions
    partitions = cext.disk_partitions(mtab_path)
FileNotFoundError: [Errno 2] No such file or directory: '/system/etc/mtab'
```

Is there any other information I can provide?

**Comment by nicolargo** [comment]
Can you try to disable the fs plugin:

```
glances --disable-plugin fs
```

**Comment by stephengmatthews** [comment]
Thanks for your help. I tried it and got this response.

```
$ glances --disable-plugin fs
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.0.2', 'console_scripts', 'glances')()
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/__init__.py",
line 140, in main
    start(config=config, args=args)
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/__init__.py",
line 106, in start
    mode = GlancesMode(config=config, args=args)
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/standalone.py",
line 73, in __init__
    self.stats.update()
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/stats.py",
line 222, in update
    self._plugins[p].update()
File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/plugins/glances_processcount.py",
line 71, in update
    glances_processes.update()
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/processes.py",
line 247, in update
    ad_value=None)
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/glances/processes.py",
line 246, in <listcomp>
    self.processlist = [p.info for p in
psutil.process_iter(attrs=standard_attrs,
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/psutil/__init__.py",
line 1434, in process_iter
    yield add(pid)
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/psutil/__init__.py",
line 1416, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/psutil/__init__.py",
line 525, in as_dict
    ret = meth()
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/psutil/__init__.py",
line 749, in io_counters
    return self._proc.io_counters()
  File
"/data/data/com.termux/files/usr/lib/python3.7/site-packages/psutil/_pslinux.py",
line 1677, in io_counters
    "too old?)" % self.pid)
NotImplementedError: couldn't find /proc/1546/io (kernel too old?)
```

**Comment by nicolargo** [comment]
Strange...

@giampaolo Any idea ? Did you test PsUtil with the latest Android version ?

**Comment by giampaolo** [comment]
Does `/etc/mtab` exist? It's weird it looks for `/system/etc/mtab`.

> NotImplementedError: couldn't find /proc/1546/io (kernel too old?)

As for this one, psutil should probably avoid to expose `Process.io_counters()` methods in case this is not available. I'll file a ticket.

**Comment by stephengmatthews** [comment]
```/etc/mtab``` does not exist.

**Comment by nicolargo** [comment]
I close this issue.

Please track the PsUtil issue here: https://github.com/giampaolo/psutil/issues/1357
