### ISSUE TITLE
Crashes upon start

### ISSUE THREAD

**Issue by meepmeep22** [nicolargo/glances#1360]
Good Evening,

I am wondering if anyone has experienced this error before.
If anyone knows how to fix it please let me know.
I have reinstalled it and it has not repaired it, so Im assuming there is something wrong with my environment.

meepmeep22@ubuntuMax:~$ glances
^CTraceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 73, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 222, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 911, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 920, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_hddtemp.py", line 57, in update
    stats = self.glancesgrabhddtemp.get()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_hddtemp.py", line 159, in get
    self.__update__()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_hddtemp.py", line 99, in __update__
    data = self.fetch()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_hddtemp.py", line 152, in fetch
    if data != "":
UnboundLocalError: local variable 'data' referenced before assignment
meepmeep22@ubuntuMax:~$

**Comment by nicolargo** [comment]
What is you Glances version ? Please follow the template when you open an issue...
