### ISSUE TITLE
Crashes while running on CentOs 7

### ISSUE THREAD

**Issue by bitchecker** [nicolargo/glances#1361]
#### Description

during its use it stops working randomly reporting the following error message to the console.

#### Versions

* Glances & psutil (glances -V): `Glances v2.5.1 with psutil v2.2.1`
* Operating System (lsb_release -a): `CentOS Linux release 7.5.1804 (Core)`

#### Logs
```
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 578, in display
    'quicklook').get_stats_display(max_width=quicklook_width, args=self.args)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 547, in get_stats_display
    'msgdict': self.msg_curse(args, max_width=max_width),
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_quicklook.py", line 121, in msg_curse
    bar.percent = cpu['total']
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_bars.py", line 73, in percent
    raise AssertionError('The percent must be between 0 and 100.')
AssertionError: The percent must be between 0 and 100.
```

**Comment by nicolargo** [comment]
Rejected. Duplicated https://github.com/nicolargo/glances/issues/709

Please upgrade your Glances version.
