### ISSUE TITLE
TypeError on opening (Wifi plugin)

### ISSUE THREAD

**Issue by G4Zz0L1** [nicolargo/glances#1373]
#### Description

At the start of Glances it errors out with this. It started today, but I see nothing 'pythonish' in the pacman update log. The debug file seems to contains nothing useful, but I'll attach it down below. I don't know where to look for other errors.

```
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.0.2', 'console_scripts', 'glances')()
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/standalone.py", line 73, in __init__
    self.stats.update()
  File "/usr/lib/python3.7/site-packages/glances/stats.py", line 226, in update
    self._plugins[p].update_views()
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_wifi.py", line 155, in update_views
    self.views[i[self.get_key()]]['signal']['decoration'] = self.get_alert(i['signal'])
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_wifi.py", line 136, in get_alert
    if value <= self.get_limit('critical', stat_name=self.plugin_name):
TypeError: '<=' not supported between instances of 'NoneType' and 'float'

```

#### Versions

* Glances & psutil (glances -V):
Glances v3.0.2 with psutil v5.4.8
* Operating System (lsb_release -a):
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

#### Logs

Glanced debug log
https://pastebin.com/sbdJSgTi

**Comment by nicolargo** [comment]
Should be corrected by the latest commit (229710d6) on the DEVELOP branch.

@G4Zz0L1  Can you test it ?

Thanks

**Comment by nicolargo** [comment]
Another day, another patch.

Can you test it agaib @G4Zz0L1 ?

**Comment by G4Zz0L1** [comment]
It seems to work now, but it doesn't fetch wifi info

![image](https://user-images.githubusercontent.com/13220636/50384312-6b4b5800-06c3-11e9-87a4-a50f2932668e.png)

**Comment by nicolargo** [comment]
Yes because your Wifi network interface enp3s0 did not support scanning (see in your log file).

```
2018-12-18 20:45:03,028 -- DEBUG -- WIFI plugin: Scan InterfaceError (b"enp3s0    Interface doesn't support scanning.")
2018-12-18 20:45:03,030 -- DEBUG -- Plugin wifi update return [{'key': 'ssid', 'ssid': '[redacted]', 'signal': None, 'quality': None, 'encrypted': True, 'encryption_type': 'wpa2'}, {'key': 'ssid', 'ssid': '[redacted]', 'signal': None, 'quality': None, 'encrypted': True, 'encryption_type': 'wpa2'}]
```

**Comment by G4Zz0L1** [comment]
That's the wired one, the wifi one it's the wlp0. What command should I use for testing this?

**Comment by nicolargo** [comment]
What is the result of print(c) ?

**Comment by G4Zz0L1** [comment]
![image](https://user-images.githubusercontent.com/13220636/50384668-56bd8e80-06c8-11e9-9580-ee49f68c05be.png)

But I can correctly scan it with the system command

```
╰─ iwlist wlp0s20u12 scan
wlp0s20u12  Scan completed :
          Cell 01 - Address: [redacted]
                    ESSID:"[redacted]"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.412 GHz (Channel 1)
                    Encryption key:on
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 18 Mb/s
                              24 Mb/s; 36 Mb/s; 54 Mb/s; 6 Mb/s; 9 Mb/s
                              12 Mb/s; 48 Mb/s
                    Extra:rsn_ie=30140100000fac040100000fac040100000fac020c00
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD800050F204104A0001101044000102103B0001031047001065C59B47F8B937331C80A89190C8DF3E1021000842726F6164636F6D1023000842726F6164636F6D1024000631323334353610420004313233341054000800060050F20400011011000A42726F6164636F6D4150100800020106103C0001031049000600372A000120
                    Signal level=100/100  
          Cell 02 - Address: [redacted]
                    ESSID:"[redacted]"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.457 GHz (Channel 10)
                    Encryption key:on
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 9 Mb/s
                              18 Mb/s; 36 Mb/s; 54 Mb/s; 6 Mb/s; 12 Mb/s
                              24 Mb/s; 48 Mb/s
                    Extra:rsn_ie=30140100000fac040100000fac040100000fac020000
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD270050F204104A000100104400010210470010BC329E001DD811B2860164D1A311E746103C000101
                    Signal level=58/100  

```

**Comment by nicolargo** [comment]
Same issue here with Python 3. Work fine with Python 2...

The issue came from the Wifi lib (only compatible with Python 3.3...) and the project is unmaintained...

I will open another issue to find a new lib...
