### ISSUE TITLE
Replace the Wifi lib by a new one

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1377]
#### Description

The Wifi lib (https://github.com/rockymeza/wifi) used by the Wifi plugin is unmaintained and did not work for Python > 3.3 (see https://github.com/nicolargo/glances/issues/1373#issuecomment-449640936).

Had to find a new lib...

For the moment, the plugin will be disable for Python 3...

**Comment by nicolargo** [comment]
**Status**

Current lib: Wifi (https://pypi.org/project/wifi/) version 0.3.8 (march 2016)
Problem: not compatible with Python 3.3 or higher.

https://user-images.githubusercontent.com/13220636/50384616-799b7300-06c7-11e9-940e-3fc211da7933.png

Other lib: Python-Wifi (version 0.61 november 2015...)
Problem: not compatible with Python 3 or higher.

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from pythonwifi.iwlibs import Wireless
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nicolargo/virtualenv/glances-python3.6/lib/python3.6/site-packages/pythonwifi/iwlibs.py", line 113
    except IOError, (errno, strerror):
                  ^
SyntaxError: invalid syntax
>>> 
```

**Comment by nicolargo** [comment]
One of the solution is to clone the existing lib and patch it for Python 3....

https://github.com/rockymeza/wifi

**Comment by nicolargo** [comment]
A PR has been proposed: https://github.com/rockymeza/wifi/pull/116

Wait and see...

**Comment by muuvmuuv** [comment]
Would this also add support for macOS?

**Comment by nicolargo** [comment]
Other solution is to grab the stats directly from /proc/net/wireless (but only for Linux)...

https://itectec.com/unixlinux/how-to-interpret-wireless-quality-indicators/

Examples:

Connected:

```
cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
wlp2s0: 0000   43.  -67.  -256        0      0      0      0  20525        0
```

Air plane mode:

```
cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
```

**Comment by muuvmuuv** [comment]
On macOS we now have:

```
; networkQuality -h

USAGE: networkQuality [-C <configuration_url>] [-c] [-h] [-I <interfaceName>] [-s] [-v]
    -C: override Configuration URL
    -c: Produce computer-readable output
    -h: Show help (this message)
    -I: Bind test to interface (e.g., en0, pdp_ip0,...)
    -s: Run tests sequentially instead of parallel upload/download
    -v: Verbose output

; networkQuality
current download capacity: 191.413 Mbps - current upload capacity: 20.653 Mbps

; networkQuality -cv
{
  "base_rtt" : 16.999959945678711,
  "dl_flows" : 12,
  "dl_throughput" : 204809712,
  "end_date" : "24.01.22, 14:01:56",
  "lud_foreign_h2_req_resp" : [
    134,
    133,
    137,
    135,
    141,
    138,
    136,
    126
  ],
  "lud_foreign_tcp_handshake_443" : [
    151,
    154,
    154,
    156,
    154,
    156,
    156,
    156
  ],
  "lud_self_dl_h2" : [
    452.4080810546875,
    515.7509765625,
    449.65899658203125,
    475.29495239257812,
    567.0379638671875,
    595.20599365234375,
    782.009033203125,
    894.166015625,
    896.32501220703125,
    891.5870361328125,
    872.8800048828125,
    860.9259033203125,
    877.63092041015625,
    941.05401611328125,
    1016.5440063476562
  ],
  "lud_self_ul_h2" : [
    86.042045593261719,
    122.78700256347656,
    174.95393371582031,
    116.465087890625,
    100.67498779296875,
    101.26709747314453,
    111.85502624511719,
    92.481971740722656,
    149.04106140136719,
    104.11298370361328,
    326.43997192382812,
    110.05509185791016,
    351.42398071289062,
    551.71502685546875,
    303.18307495117188,
    126.03092193603516
  ],
  "os_version" : "Version 12.1 (Build 21C52)",
  "responsiveness" : 414,
  "start_date" : "24.01.22, 14:01:39",
  "ul_flows" : 20,
  "ul_throughput" : 28142540
}
```

**Comment by Achourarbi** [comment]
I had the same issue for python-wifi 0.6.1 lib, it works only on Python 2.7 or less. But I've found another python lib that works on most of the Python versions which is https://pypi.org/project/pywifi/. This lib works on Linux and Windows.

**Comment by nicolargo** [comment]
@Achourarbi thanks for the information, i will have a look but it seams that the project is not very active. Last commit date is January 2019... https://github.com/awkman/pywifi/commits/master

**Comment by nicolargo** [comment]
Ok to implement a limited version only compliant with Linux OS by reading /proc:

```
# cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
wlp2s0: 0000   42.  -68.  -256        0      0      0      0   5294        0
```

**Comment by nicolargo** [comment]
Ok implementation done in the develop branch.

Plugin is only available on Linux operating system and limited to local Wifi interface (no hotspots).
