### ISSUE TITLE
Drive name with special characters causes crash

### ISSUE THREAD

**Issue by argorain** [nicolargo/glances#1383]
#### Description

For a bug: When my drive is connected, glances immediately crashes or won't start if drive is connected before glances start. It seems it doesn't like some characters in it's name. 

#### Versions

* Glances & psutil (glances -V): Glances v3.0.2 with psutil v5.4.1
* Operating System (lsb_release -a):
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux buster/sid
Release:	testing
Codename:	buster

#### Logs
```
╭─rain@pegasus ~  
╰─$ glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 73, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 224, in update
    self._plugins[p].update_stats_history()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 185, in update_stats_history
    str(l[item_name]) + '_' + i['name'],
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfd' in position 15: ordinal not in range(128)
╭─rain@pegasus ~  
╰─$                                                                                                                                1 ↵
```

**Comment by nicolargo** [comment]
Corrected by the latest commit on the DEVELOP branch.

@argorain Can you test it ?

**Comment by argorain** [comment]
Tested using this: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version#standalone-mode - it works. Thank you for quick bugfix. Good job.

**Comment by nicolargo** [comment]
You are welcome !
