### ISSUE TITLE
Prometheus integration broken with latest prometheus_client

### ISSUE THREAD

**Issue by joeyfeldberg** [nicolargo/glances#1397]
#### Description

This affects prometheus integration only.
In version prometheus_client 0.5.0, integration breaks with an error:

     No label names were set when constructing <prometheus_client.metrics.Gauge object at ...>

It works with prometheus_client 0.4.*

#### Versions

* Glances & psutil (glances -V): Glances v3.1.0 with psutil v5.4.8
* Operating System (lsb_release -a): Ubuntu 16.04.5 LTS
* prometheus-client: 0.5.0

#### Logs

File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/glances/exports/glances_export.py", line 169, in update
    self.export(plugin, export_names, export_values)
  File "/usr/local/lib/python3.6/dist-packages/glances/exports/glances_prometheus.py", line 94, in export
    self._metric_dict[metric_name].labels(**labels).set(v)
  File "/usr/local/lib/python3.6/dist-packages/prometheus_client/metrics.py", line 129, in labels
    raise ValueError('No label names were set when constructing %s' % self)
ValueError: No label names were set when constructing <prometheus_client.metrics.Gauge object at 0x7fe45a1879e8>

**Comment by utdrmac** [comment]
Any updates here? I just discovered Glances yesterday and trying to set this up for home NAS on Docker:

```
docker run -it --rm --network metrics-net \
  --name glances -v glances-conf:/etc/glances \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --pid host -p 61208-61209:61208-61209 \
  -e GLANCES_OPT="-q --fahrenheit --export prometheus -C /etc/glances/glances.conf"  \
  nicolargo/glances

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "glances/exports/glances_export.py", line 183, in update
    self.export(plugin, export_names, export_values)
  File "/glances/glances/exports/glances_prometheus.py", line 94, in export
    self._metric_dict[metric_name].labels(**labels).set(v)
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/metrics.py", line 129, in labels
    raise ValueError('No label names were set when constructing %s' % self)
ValueError: No label names were set when constructing <prometheus_client.metrics.Gauge object at 0x7f94a8b4ed90>
```

**Comment by utdrmac** [comment]
Is there an easy way to downgrade the prometheus client to 0.4 until Glances gets a fix?

**Comment by kmatt** [comment]
Adding a labels section to the config fixed this for me: https://github.com/nicolargo/glances/issues/1255

**Comment by nicolargo** [comment]
labels is now mandatory and checked when Glances starts.

Thanks for the issue report.
