### ISSUE TITLE
Crash on start on Debian 9

### ISSUE THREAD

**Issue by pguizeline** [nicolargo/glances#1422]
Hi, I'm trying to execute glances on Debian 9, I've installed it via apt, but I'm getting the following error:

#### Description

```
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 127, in main
    args=core.get_args())
  File "/usr/lib/python3/dist-packages/glances/standalone.py", line 42, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3/dist-packages/glances/stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3/dist-packages/glances/stats.py", line 76, in load_modules
    self.load_plugins(args=args)
  File "/usr/lib/python3/dist-packages/glances/stats.py", line 101, in load_plugins
    self._plugins[plugin_name] = plugin.Plugin(args=args, config=self.config)
  File "/usr/lib/python3/dist-packages/glances/plugins/glances_ports.py", line 51, in __init__
    self.stats = GlancesPortsList(config=config, args=args).get_ports_list()
  File "/usr/lib/python3/dist-packages/glances/ports_list.py", line 51, in __init__
    self._ports_list = self.load(config)
  File "/usr/lib/python3/dist-packages/glances/ports_list.py", line 71, in load
    new_port['host'] = netifaces.gateways()['default'][netifaces.AF_INET][0]
KeyError: 2
```

#### Versions

* Glances & psutil (glances -V):
`Glances v2.7.1 with psutil v5.0.1`

* Operating System (lsb_release -a):
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.7 (stretch)
Release:        9.7
Codename:       stretch
```

#### Logs

[https://pastebin.com/EGFMktwH](https://pastebin.com/EGFMktwH)

Thanks in advance for any help!!

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/651

Please upgrade your Glances version.
