### ISSUE TITLE
Glances PsUtil ValueError on IoCounter with TASK kernel options

### ISSUE THREAD

**Issue by timcowchip** [nicolargo/glances#1440]
#### Description

{'invalid attr name 'io_counters'}

#### Versions

*Glances v3.1.0 with psutil v5.6.1
*Crux-3.4

#### Logs

glances
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.0', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/standalone.py", line 74, in __init__
    self.stats.update()
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 222, in update
    self._plugins[p].update()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_processcount.py", line 71, in update
    glances_processes.update()
  File "/usr/lib/python3.6/site-packages/glances/processes.py", line 247, in update
    ad_value=None)
  File "/usr/lib/python3.6/site-packages/glances/processes.py", line 246, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 1562, in process_iter
    yield add(pid)
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 1539, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'

[https://github.com/timcowchip/timcowchip/blob/master/glances/Pkgfile](url)
[https://github.com/timcowchip/timcowchip/blob/master/python3-psutil/Pkgfile](url)

**Comment by nicolargo** [comment]
Not reproduce with the same Glances/Psutil version...

**Comment by pymenow** [comment]
I am having the same issue psutils 5.6.1

**Comment by DeepDarkOdyssey** [comment]
Same issue with psutils 5.6.1 on arm64 device with debian

**Comment by pymenow** [comment]
Seen this issue if your kernel doent have the below config options enabled.
CONFIG_TASKSTATS=y
CONFIG_TASK_DELAY_ACCT=y
CONFIG_TASK_XACCT=y
CONFIG_TASK_IO_ACCOUNTING=y

**Comment by xpue** [comment]
Same here, custom kernel with aforementioned options disabled.

**Comment by nicolargo** [comment]
@giampaolo Do you think that it is a PsUtil issue ?

**Comment by JacerOmri** [comment]
having this issue on WSL, could be because of it?

**Comment by matheussouza9** [comment]
I'm also having this issue on WSL.

**Comment by theonewolf** [comment]
Observed on WSL2.

**Comment by nicolargo** [comment]
Should be corrected for WSL.

Anyone can test the DEVELOP branch ?

**Comment by lengthmin** [comment]
![image](https://user-images.githubusercontent.com/13938334/62415055-718cb400-b656-11e9-9dc1-323386e3a403.png)


still error.
maybe the kernel's problem
---
OS: Debian GNU/Linux 10 (buster) on Windows 10 x86_64
Kernel: 4.19.57-microsoft-standard
Glances-3.1.2b0

**Comment by Karmak23** [comment]
Hi, on OpenWRT the kernel also doesn't have TASK. Thus the bug is still present (glances 3.1.2, psutil 5.6.3). The patch should include OpenWRT (uname -a says `Linux hostname 4.9.184 #0 SMP Thu Jun 27 12:18:52 2019 aarch64 GNU/Linux`, which could be not meaningfull enough. You could test against the presence of `/bin/opkg` binary ?

**Comment by kedare** [comment]
Same issue here on the ChromeOS Debian LXC container (Debian 10): `Linux penguin 4.19.60-06185-g54aa50936831 #1 SMP PREEMPT Wed Aug 14 01:17:34 PDT 2019 x86_64 GNU/Linux`

**Comment by leoherzog** [comment]
Same here, Chrome 78, Debian 10 in Crostini.

```bash
username@penguin:~$ glances
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.0', 'console_scripts', 'glances')()
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3/dist-packages/glances/standalone.py", line 74, in __init__
    self.stats.update()
  File "/usr/lib/python3/dist-packages/glances/stats.py", line 222, in update
    self._plugins[p].update()
  File "/usr/lib/python3/dist-packages/glances/plugins/glances_processcount.py", line 71, in update
    glances_processes.update()
  File "/usr/lib/python3/dist-packages/glances/processes.py", line 247, in update
    ad_value=None)
  File "/usr/lib/python3/dist-packages/glances/processes.py", line 246, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1539, in process_iter
    yield add(pid)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1521, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 619, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'
```

**Comment by giampaolo** [comment]
`Process.io_counters()` (or `/proc/PID/io` file) is not available on all kernels, so Glances should determine that at runtime.

**Comment by rdvrey** [comment]
> Seen this issue if your kernel doent have the below config options enabled.
> CONFIG_TASKSTATS=y
> CONFIG_TASK_DELAY_ACCT=y
> CONFIG_TASK_XACCT=y
> CONFIG_TASK_IO_ACCOUNTING=y

I have those options on:
"# CPU/Task time and stats accounting
#
CONFIG_TICK_CPU_ACCOUNTING=y
# CONFIG_VIRT_CPU_ACCOUNTING_GEN is not set
CONFIG_IRQ_TIME_ACCOUNTING=y
CONFIG_HAVE_SCHED_AVG_IRQ=y
CONFIG_BSD_PROCESS_ACCT=y
CONFIG_BSD_PROCESS_ACCT_V3=y
CONFIG_TASKSTATS=y
CONFIG_TASK_DELAY_ACCT=y
CONFIG_TASK_XACCT=y
CONFIG_TASK_IO_ACCOUNTING=y
CONFIG_CPU_ISOLATION=y
#
# RCU Subsystem
#"
and still get the error "ValueError: invalid attr name 'io_counters'
"
Robert
