### ISSUE TITLE
Glances freezes up in browser caused by 404 error

### ISSUE THREAD

**Issue by asuna** [nicolargo/glances#1457]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description
Loop at loading page and 404 errors in chrome console.
A similar issue: https://github.com/nicolargo/glances/issues/1393, seems fixed in version 3.1, but...
![glances_loading_loop.gif](https://i.loli.net/2019/04/03/5ca4c03832f72.gif)
![glances_log.png](https://i.loli.net/2019/04/03/5ca4bfd00a617.png)
![chrome_404.png](https://i.loli.net/2019/04/03/5ca4c079264c8.png)
![glances_web_error.png](https://i.loli.net/2019/04/03/5ca4c1624dd7c.png)

#### Versions

* Glances & psutil (glances -V):Glances v3.1.1b0 with psutil v5.6.1
* Operating System (lsb_release -a):Windows 10 Pro Ver.1809 Build 17763.379
* Python:2.7.16

**Comment by nicolargo** [comment]
@notFloran Can you have a look on it ?

**Comment by notFloran** [comment]
The error `Cannot get view ("utf8" codec can't decode byte 0xd2 in position 0: invalid continuation byte)` seems to be throw by the core of glances, is not related to the webUI.

I think one of the disk/sensor/network/fs has a weird character in his name.

Maybe we can get more data in the debug log ?

**Comment by asuna** [comment]
Because of my os language is Chinese, some device name contain Chinese character, such as network interface name.

Here is debug log:
[Glances_Debug_LOG](https://cfp.vim-cn.com/cbfxb)

btw: it works on Anaconda (Python 3.7.1).

**Comment by notFloran** [comment]
@nicolargo is seems it's an encoding problem from the core of glances with python 2

Example in the log: `interface_name': '\xc0\xb6\xd1\xc0\xcd\xf8\xc2\xe7\xc1\xac\xbd\xd3'`

**Comment by nicolargo** [comment]
@asuna Please can you try the DEVELOP branch ? I just push a patch.

**Comment by asuna** [comment]
> @asuna Please can you try the DEVELOP branch ? I just push a patch.

Can't launch glances web interface, error message:

`C:\Users\user\glances>glances -w
Traceback (most recent call last):
  File "C:\Python27\Scripts\glances-script.py", line 11, in <module>
    load_entry_point('Glances==3.1.1b0', 'console_scripts', 'glances')()
  File "c:\python27\lib\site-packages\glances-3.1.1b0-py2.7.egg\glances\__init__.py", line 140, in main
    start(config=config, args=args)
  File "c:\python27\lib\site-packages\glances-3.1.1b0-py2.7.egg\glances\__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "c:\python27\lib\site-packages\glances-3.1.1b0-py2.7.egg\glances\webserver.py", line 41, in __init__
    self.stats.update()
  File "c:\python27\lib\site-packages\glances-3.1.1b0-py2.7.egg\glances\stats.py", line 222, in update
    self._plugins[p].update()
  File "c:\python27\lib\site-packages\glances-3.1.1b0-py2.7.egg\glances\plugins\glances_plugin.py", line 915, in wrapper
    ret = fct(self, *args, **kw)
  File "c:\python27\lib\site-packages\glances-3.1.1b0-py2.7.egg\glances\plugins\glances_plugin.py", line 924, in wrapper
    ret = fct(*args, **kw)
  File "c:\python27\lib\site-packages\glances-3.1.1b0-py2.7.egg\glances\plugins\glances_load.py", line 89, in update
    load = self._getloadavg()
  File "c:\python27\lib\site-packages\glances-3.1.1b0-py2.7.egg\glances\plugins\glances_load.py", line 74, in _getloadavg
    return os.getloadavg()
AttributeError: 'module' object has no attribute 'getloadavg'`

**Comment by nicolargo** [comment]
@asuna Can you try again, i have corrected the AttributeError...

**Comment by asuna** [comment]
It works now. :)
