### ISSUE TITLE
Stack trace when starts Glances on CentOS

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1470]
#### Description

Bug when Glances starts: 

```
Traceback (most recent call last):
                                    File "/usr/bin/glances", line 11, in <module>
                                                                                     load_entry_point('Glances==3.1.0', 'console_scripts', 'glances')()
                                    File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 140, in main
                                                                                                                      start(config=config, args=args)
                                  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 109, in start
                                                                                                                     mode.serve_forever()
                      File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 149, in serve_forever
                                                                                                                   loop = self.__serve_forever()
                             File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 136, in __serve_forever
       ret = not self.screen.update(self.stats, duration=adapted_refresh)
                                                                           File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 973, in update
                                                        self.flush(stats, cs_status=cs_status)
                                                                                                File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 948, in flush
                                                                            self.display(stats, cs_status=cs_status)
                                                                                                                      File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 593, in display
                                                                                                    self.__display_right(__stat_display)
                     File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 762, in __display_right
           self.display_plugin(stat_display[p])
                                               KeyError: 'docker'
                                                                 [nhe:~]↥ 4s 1 $ 
```

#### Versions

* Glances & psutil (glances -V): 3.1.0
* Operating System (lsb_release -a): CentOS 7.3

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Corrected by latest commit in the DEVELOP branch.
