### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u25cf' - Raspbian stretch

### ISSUE THREAD

**Issue by fluxtendu** [nicolargo/glances#1483]
Hi,
glances look nice but after letting it running for one or two minutes I get this error (and it scramble the screen):
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/usr/local/lib/python2.7/dist-packages/glances/amps/glances_nginx.py", line 83, in update
    self.set_result(res.text.rstrip())
  File "/usr/local/lib/python2.7/dist-packages/glances/amps/glances_amp.py", line 186, in set_result
    self.configs['result'] = str(result)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u25cf' in position 668: ordinal not in range(128)
```
Glances v3.1.0 with psutil v5.6.2 
Raspbian GNU/Linux 9.8 (stretch)

I have tried without succes:
- sudo glances
- LANG=en_US.UTF-8 LC_ALL= glances
- LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 glances
- LANG=fr_FR.UTF-8 LC_ALL= glances

**Comment by nicolargo** [comment]
Reproduced by setting a simple AMP as following:

```
[amp_teststr]
enable=true
regex=.*python.*
refresh=30
one_line=true
command=echo "éùà"
```

**Comment by nicolargo** [comment]
Should be corrected b the latest commit.

Can you test the DEVELOP branch ?

**Comment by fluxtendu** [comment]
It works, thanks!
Will it be released soon or should I look to replace my normal install?

ps: you should add "future" to the libs list on [https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version](https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version)
