### ISSUE TITLE
Glances does not start on Gentoo with ValueError: invalid attr name 'io_counters'

### ISSUE THREAD

**Issue by kanyck** [nicolargo/glances#1489]
#### Description
glances 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/glances", line 11, in <module>
    load_entry_point('Glances==3.0.2', 'console_scripts', 'glances')()
  File "/usr/lib64/python2.7/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/lib64/python2.7/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib64/python2.7/site-packages/glances/standalone.py", line 73, in __init__
    self.stats.update()
  File "/usr/lib64/python2.7/site-packages/glances/stats.py", line 222, in update
    self._plugins[p].update()
  File "/usr/lib64/python2.7/site-packages/glances/plugins/glances_processcount.py", line 71, in update
    glances_processes.update()
  File "/usr/lib64/python2.7/site-packages/glances/processes.py", line 247, in update
    ad_value=None)
  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 1562, in process_iter
    yield add(pid)
  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 1539, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'

#### Versions
psutil-5.6.0
glances-3.0.2,3.1.0
OS Gentoo
Most probably some other package is built without some feature needed by glances, but I've no idea which one. Starts fine on Funtoo.

**Comment by nicolargo** [comment]
Strange because as said in the PsUtil documentation (https://psutil.readthedocs.io/en/latest/#psutil.Process.io_counters), io_counters is available for Linux, BSD, Windows, AIX OS...

Same behavor if your run Glances as root ?

**Comment by kanyck** [comment]
Yes, the same for the root and the regular user.

**Comment by kanyck** [comment]
And it's even more strange that it runs OK on Funtoo which shares ebuild tree with Gentoo. So it may be USE flag differences (that triggers package's config options) or maybe the kernel configuration or something like that.

**Comment by gyakovlev** [comment]
@kanyck I maintain glances in gentoo.

you are likely missing required kernel options.

ebuild check and warns you but does not abort if you have not set required kernel options

make sure the following options are enabled in kernel
```
CONFIG_TASK_IO_ACCOUNTING
CONFIG_TASK_DELAY_ACCT
CONFIG_TASKSTATS
```

**Comment by kanyck** [comment]
@gyakovlev 
Sure you were right. I was seduced by tempting "Say N if unsure" on TASK_XATTR :) I suspected something like this, but haven't found the right option...
Please add this information to postinstall, or better, make emerge warn about needed kernel options as many packages do (not everyone check elogs. I often don't). Thanks! Closed.
