### ISSUE TITLE
Stracktrace after installation, "DistributionNotFound"

### ISSUE THREAD

**Issue by philippgille** [nicolargo/glances#1500]
#### Description

I get a stack trace after installing Glances (at the end of the installation):

```
$ curl -L https://bit.ly/glances | /bin/bash

[...]
sudo apt-get install -y --force-yes python-pip python-dev gcc lm-sensors wireless-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version.
python-dev is already the newest version.
wireless-tools is already the newest version.
lm-sensors is already the newest version.
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Install dependancies
sudo pip install --upgrade pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==8.1.2
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 67, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==8.1.2
```

#### Versions

* Glances & psutil (glances -V): /
* Operating System (lsb_release -a):  
  ```
  No LSB modules are available.
  Distributor ID:	Ubuntu
  Description:	Ubuntu 14.04.6 LTS
  Release:	14.04
  Codename:	trusty
    ```

**Comment by philippgille** [comment]
A similar issue was this one in 2014: https://github.com/nicolargo/glances/issues/330

But that could be solved with

```
apt-get install build-essential python-dev
pip install --upgrade Glances
```

Which doesn't work in my case.

**Comment by philippgille** [comment]
Ok so apparently the version of pip on my system was old: pip-1.5.4

Running `curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"` and `python get-pip.py` updated that to `pip-19.1.1`

Maybe that should be part of the Glances installation script?

Now when doing `pip install glances` I get:

```
[...]
Successfully built glances psutil
Installing collected packages: psutil, glances
  Found existing installation: psutil 1.2.1
ERROR: Cannot uninstall 'psutil'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Trying instead with the previously used bash script there is the same error message and a bunch of additional ones, all related to software / library versions. I guess Ubuntu 14.04 is just too old.

I couldn't find anything about the OS version requirements in the repo's README or documentation, so maybe that can be added?
