### ISSUE TITLE
AttributeError: 'Container' object has no attribute 'image'

### ISSUE THREAD

**Issue by sivabudh** [nicolargo/glances#1504]
#### Description

I cannot run Glances.

#### Versions

* Glances & psutil (glances -V): Glances v3.1.0 with psutil v5.6.3
* Operating System (lsb_release -a):

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

#### Logs

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.0/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.0', 'console_scripts', 'glances')()
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glances/standalone.py", line 74, in __init__
    self.stats.update()
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glances/stats.py", line 222, in update
    self._plugins[p].update()
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 914, in wrapper
    ret = fct(self, *args, **kw)
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 923, in wrapper
    ret = fct(*args, **kw)
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glances/plugins/glances_docker.py", line 214, in update
    container_stats['Image'] = container.image.tags
AttributeError: 'Container' object has no attribute 'image'
```

**Comment by nicolargo** [comment]
Any relevant messages in the Glance log file (/tmp/glances-*.log) when ran in debug mode (-d) ?
