### ISSUE TITLE
HDDTEMP config IP?

### ISSUE THREAD

**Issue by vsc55** [nicolargo/glances#1508]
Hi,

It is possible to implement a configuration to be able to specify IP of HDDTEMP and not to use only 127.0.0.1.

Best regards.

**Comment by kamilmirza** [comment]
yes it is possible but with a workaround 
you can replace `127.0.0.1` to `192.168.0.1` in `/glances/plugins/glances_hddtemp.py`
I am doing this on docker with using my modified `hddtemp.py` file and `expose` port to `7634`

**Comment by vsc55** [comment]
Hi,
If so I have solved it for now.
But the good thing would be that it can be configured from the configuration file and thus avoid having to modify the program.
Regards.

**Comment by kamilmirza** [comment]
yes it would be great to have it in the config file

**Comment by nicolargo** [comment]
Implemented by the latest commit on the DEVELOP branch.

Please can you test it ?

I do not have any hddtemp compliant disk on my dev computer...

**Comment by vsc55** [comment]
Hi Nicolargo,

I have tried and it does not work, so it seems to use the configuration data.
Config file:
```
hddtemp_host=192.168.0.250
hddtemp_port=7634
```

Debug file:
```
2019-08-13 12:57:51,741 -- INFO -- Search glances.conf file in /etc/glances/glances.conf
2019-08-13 12:57:51,743 -- INFO -- Read configuration file '/etc/glances/glances.conf'
...
2019-08-13 12:57:51,804 -- DEBUG -- Load limit: sensors_hddtemp_host = [u'192.168.0.250']
2019-08-13 12:57:51,804 -- DEBUG -- Load limit: sensors_hddtemp_port = 7634.0
...
2019-08-13 12:57:51,823 -- DEBUG -- Cannot connect to an HDDtemp server (127.0.0.1:7634 => [Errno 111] Conexión rehusada)
2019-08-13 12:57:51,823 -- DEBUG -- Disable the HDDtemp module. Use the --disable-hddtemp to hide the previous message.
2019-08-13 12:57:51,823 -- DEBUG -- Plugin hddtemp update return []
2019-08-13 12:57:51,823 -- DEBUG -- Cannot connect to an HDDtemp server (127.0.0.1:7634 => [Errno 111] Conexión rehusada)
2019-08-13 12:57:51,823 -- DEBUG -- Disable the HDDtemp module. Use the --disable-hddtemp to hide the previous message.
2019-08-13 12:57:51,823 -- DEBUG -- Plugin plugins.glances_hddtemp update return []
....
2019-08-13 12:57:51,898 -- DEBUG -- Cannot connect to an HDDtemp server (127.0.0.1:7634 => [Errno 111] Conexión rehusada)
2019-08-13 12:57:51,898 -- DEBUG -- Disable the HDDtemp module. Use the --disable-hddtemp to hide the previous message.
```

Best regards.

**Comment by nicolargo** [comment]
I see... The issue came from the fact that "limits" are loaded after plugin initialization: https://github.com/nicolargo/glances/blob/develop/glances/stats.py#L46-L50

Have to find a way to have a better init function...

It change lot of think. Not sure to be ready to implement this on the next release...

**Comment by vsc55** [comment]
Hi,
I am testing and I have detected that the configuration would not be defined in the [sensors] section, it would have to be defined in the [hddtemp] section.

```
[hddtemp]
# Define hddtemp server IP and port (default is 127.0.0.1 and 7634 (TCP))
hddtemp_host=127.0.0.1
hddtemp_port=7634
```

**Comment by vsc55** [comment]
Hi,
I've been testing this:
https://github.com/vsc55/glances/commit/64444b7ab048abd4aa537d4f6c1a5d055ff9a8aa

And I have obtained this:
```
('Antes H:', '127.0.0.1')
('host:', [u'192.168.0.250'])
('port:', 7634.0)
('limits:', {'history_size': 28800.0, u'hddtemp_hddtemp_port': 7634.0, u'hddtemp_hddtemp_host': [u'192.168.0.250']})

('Antes H:', '127.0.0.1')
('host:', '127.0.0.1')
('port:', '7634')
('limits:', {})
```

The first update runs correctly, but in the rest of the update the content of limit is empty.

Can it be that the first update is an object, and the rest of the updates run another object that does not load the limits?

**Comment by nicolargo** [comment]
Hi @vsc55 

i just push a new version on the DEVELOP branch.

Please can you try it and add the following section to your config file:

```
[hddtemp]
# Define hddtemp server IP and port (default is 127.0.0.1 and 7634 (TCP))
host=127.0.0.1
port=7634
```

**Comment by vsc55** [comment]
Hi @nicolargo 

I have tested the latest version and function, now get the data correctly.  👍 

The only thing, now those errors appear:
```
...
2019-08-17 12:22:23,493 -- CRITICAL -- Error while initializing the batpercent plugin (__init__() got an unexpected keyword argument 'config')
2019-08-17 12:22:23,493 -- ERROR -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Glances-3.1.2b0-py2.7.egg/glances/stats.py", line 119, in _load_plugin
    self._plugins[name] = plugin.Plugin(args=args, config=config)
TypeError: __init__() got an unexpected keyword argument 'config'
....
2019-08-17 12:22:23,499 -- CRITICAL -- Error while initializing the hddtemp plugin (__init__() got an unexpected keyword argument 'config')
2019-08-17 12:22:23,499 -- ERROR -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Glances-3.1.2b0-py2.7.egg/glances/stats.py", line 119, in _load_plugin
    self._plugins[name] = plugin.Plugin(args=args, config=config)
TypeError: __init__() got an unexpected keyword argument 'config'
....
```
