### ISSUE TITLE
_curses.error: setupterm: could not find terminal

### ISSUE THREAD

**Issue by RinHZ** [nicolargo/glances#1512]
I can not run glances.There are the following errors.

Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
Traceback (most recent call last):
  File "/Users/rin/Documents/glances/glances/__main__.py", line 29, in <module>
    glances.main()
  File "/Users/rin/Documents/glances/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/Users/rin/Documents/glances/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/Users/rin/Documents/glances/glances/standalone.py", line 93, in __init__
    self.screen = GlancesCursesStandalone(config=config, args=args)
  File "/Users/rin/Documents/glances/glances/outputs/glances_curses.py", line 121, in __init__
    self.screen = curses.initscr()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal

**Comment by RinHZ** [comment]
I try to use PyCharm to run glances on MacOS and get those errors.Help me plz.
