### ISSUE TITLE
Glances Snap doesn't run on Orange Pi Zero running Ubuntu Core 16

### ISSUE THREAD

**Issue by jpbourgeon** [nicolargo/glances#1517]
Hi,

#### Description

I try to monitor my Orange Pi Zero running Ubuntu Core 16 with Glances.

I installed Glances in edge mode since stable channel isn't available for me.
``snap install glances --edge``

``glances`` or ``sudo glances`` fails to run. The debug mode doesn't provide more info on the error. I don't see any useful command line option that would help me start the monitoring. See the logs below for a full error dump.

Do you know a way to make it work on my system ?

#### Versions

* Glances & psutil (glances -V): Glances v3.1.1 with psutil v5.6.3
* Operating System (hostnamectl):
    * Operating System: Ubuntu Core 16
    * Kernel: Linux 4.9-orangepi-zero
    * Architecture: arm

#### Logs

```
/$ glances
Traceback (most recent call last):
  File "/snap/glances/410/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.1', 'console_scripts', 'glances')()
  File "/snap/glances/410/lib/python3.5/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/snap/glances/410/lib/python3.5/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/snap/glances/410/lib/python3.5/site-packages/glances/standalone.py", line 74, in __init__
    self.stats.update()
  File "/snap/glances/410/lib/python3.5/site-packages/glances/stats.py", line 228, in update
    self._plugins[p].update()
  File "/snap/glances/410/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 915, in wrapper
    ret = fct(self, *args, **kw)
  File "/snap/glances/410/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 924, in wrapper
    ret = fct(*args, **kw)
  File "/snap/glances/410/lib/python3.5/site-packages/glances/plugins/glances_fs.py", line 100, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/snap/glances/410/lib/python3.5/site-packages/psutil/__init__.py", line 2133, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/snap/glances/410/lib/python3.5/site-packages/psutil/_pslinux.py", line 1167, in disk_partitions
    partitions = cext.disk_partitions(mounts_path)
PermissionError: [Errno 13] Permission denied: '/proc/4287/mounts'
```

Regards

--
Jean-Philippe

**Comment by nicolargo** [comment]
@jpbourgeon can you try the following workaround .

```
glances --disable-plugin fs
```

**Comment by nicolargo** [comment]
The last commit should correct this issue...

**Comment by jpbourgeon** [comment]
Thanks !
