### ISSUE TITLE
Arch Linux error with release 3.1.1

### ISSUE THREAD

**Issue by arcolinuxz** [nicolargo/glances#1519]
ArchLinux has your package in the community repo at https://www.archlinux.org/packages/community/any/glances/.

I tried rebuilding it with this pkgbuild and got the same error.

`[erik@ArcoLinux Desktop]$ glances
Traceback (most recent call last):
  File "/usr/bin/glances", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'future' distribution was not found and is required by Glances`

Is anything missing in our pkgbuild?
Can you think of a reason why the application is not working?
We have python 3.7.3 on Arch.
python-setuptools 1:41.0.1-1 

Ask for further info if needed.

**Comment by arcolinuxz** [comment]
I should have checked on the bug forum on Arch Linux.

It needs a new dependency now

`sudo pacman -S python-future`
