### ISSUE TITLE
Glances crashes immediately due to python error

### ISSUE THREAD

**Issue by GalRogozinski** [nicolargo/glances#1532]
#### Description

I start glances and it immediately crashes.

#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.4.2

* Operating System (lsb_release -a): Ubuntu 18.04 LTS

* Python -V: 2.7.15rc

*Python3 -V: 3.6.5

#### Logs
The error keeps on changing:

```
glances
Warning: Unable to set locale. Expect encoding problems.
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/lib/python3/dist-packages/glances/standalone.py", line 113, in serve_forever
    self.schedule.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/usr/lib/python3/dist-packages/glances/standalone.py", line 96, in __serve_forever
    self.stats.update()
  File "/usr/lib/python3/dist-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/usr/lib/python3/dist-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python3/dist-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3/dist-packages/glances/plugins/glances_docker.py", line 269, in update
    container['io'] = self.get_docker_io(container['Id'], self.thread_list[container['Id']].stats)
  File "/usr/lib/python3/dist-packages/glances/plugins/glances_docker.py", line 453, in get_docker_io
    ior = [i for i in iocounters['io_service_bytes_recursive'] if i['op'] == 'Read'][0]['value']
TypeError: 'NoneType' object is not iterable
```

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/1160

Please upgrade your Glances version or disable the Docker plugin (--disable-docker)
