### ISSUE TITLE
Glances crashes with eclipse 

### ISSUE THREAD

**Issue by colucu** [nicolargo/glances#1533]
#### Description

When I use Eclipse IDE for my project, Glances immediately crashed.
But Glances still work when I reboot computer and start Glances only.
What can I do for Glances working with Eclipse?

#### Versions

* Glances v3.1.1 with psutil v5.6.3
* Ubuntu 18.04.3 LTS
* Eclipse Version: 2019-06 (4.12.0)

#### Logs
Traceback (most recent call last):
File "/usr/local/bin/glances", line 10, in <module>
	sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 140, in main
        start(config=config, args=args)
File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 109, in start
	mode.serve_forever()
File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 149, in serve_forever
	loop = self.__serve_forever()
File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 136, in __serve_forever
	ret = not self.screen.update(self.stats, duration=adapted_refresh)
File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 980, in update
	self.flush(stats, cs_status=cs_status)
File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 955, in flush
	self.display(stats, cs_status=cs_status)
File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 595, in display
	self.__display_right(__stat_display)
File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 767, in __display_right
	max_y=(self.screen.getmaxyx()[0] - self.get_stats_display_height(stat_display['alert']) - 2))
File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 890, in display_plugin
	if m['msg'].startswith('\n'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 287: ordinal not in range(128)

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by colucu** [comment]
Sorry I got it.
Problem was Python version.
