### ISSUE TITLE
Cant start glances with glances --export mqtt

### ISSUE THREAD

**Issue by Quart666** [nicolargo/glances#1581]
#### Versions

* Glances & psutil (glances -V):
Glances v3.1.3 with psutil v5.6.7

* Operating System (lsb_release -a):
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

#### Logs

Get this errors:
Traceback (most recent call last):
  File "/home/kabj/.local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/home/kabj/.local/lib/python2.7/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/home/kabj/.local/lib/python2.7/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/home/kabj/.local/lib/python2.7/site-packages/glances/standalone.py", line 51, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/home/kabj/.local/lib/python2.7/site-packages/glances/stats.py", line 48, in __init__
    self.load_modules(self.args)
  File "/home/kabj/.local/lib/python2.7/site-packages/glances/stats.py", line 103, in load_modules
    self.load_exports(args=args)
  File "/home/kabj/.local/lib/python2.7/site-packages/glances/stats.py", line 184, in load_exports
    config=self.config)
  File "/home/kabj/.local/lib/python2.7/site-packages/glances/exports/glances_mqtt.py", line 60, in __init__
    self.tls = (self.tls.lower() == 'false')
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by nicolargo** [comment]
Corrected in the latest commit.

As a workaround, please add the following line to the mqtt section of your Glances configuration file:

    tls=false

or true if you use tls
