### ISSUE TITLE
Glances don't want to run on Crostini (LXC Container, Debian 10, python 3.7.3)

### ISSUE THREAD

**Issue by simeneriks1** [nicolargo/glances#1600]
#### Description
Program refuses to start, after being installed with pip (python3).
I am running a linux container on my chromebook.
On ChromeOS 79, I used Debian Stretch (Debian 9) and it worked fine then. Debian 10 (introduced with new version of chromeos) it fails.

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 10, in <module>
    sys.exit(main())
  File "/home/simen.eriksen/.local/lib/python3.7/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/home/simen.eriksen/.local/lib/python3.7/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/home/simen.eriksen/.local/lib/python3.7/site-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/home/simen.eriksen/.local/lib/python3.7/site-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/home/simen.eriksen/.local/lib/python3.7/site-packages/glances/plugins/glances_processcount.py", line 73, in update
    glances_processes.update()
  File "/home/simen.eriksen/.local/lib/python3.7/site-packages/glances/processes.py", line 247, in update
    ad_value=None)
  File "/home/simen.eriksen/.local/lib/python3.7/site-packages/glances/processes.py", line 246, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 1565, in process_iter
    yield add(pid)
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 1542, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 628, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'
```
#### Versions

Glances v3.1.3 with psutil v5.6.7

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by nicolargo** [comment]
Looks like this issue: https://github.com/nicolargo/glances/issues/1489

**Comment by nicolargo** [comment]
Patch implemented in the DEVELOP branch.

Will be release in Glances 3.1.4.

Thanks for the issue report @simeneriks1
