### ISSUE TITLE
[diskio] Aliases Display Incorrectly/Not at All, and Glances Throws Error on Exit

### ISSUE THREAD

**Issue by imdebating** [nicolargo/glances#1618]
### Description
When using aliases in the [diskio] section of the config file: 
````properties
...
[diskio]
hide=^sd[b-d]$,^sd[f-z]$,sr0,^md0p1,dm-[2345]
dm-0_alias=Root_LVM
dm-1_alias=Swap_LVM
dm-6_alias=DataVolume
dm-7_alias=Docker_LVM
dm-8_alias=SSD_LVM
sda_alias=P400_LV1_(md0)
md0_alias=External
sdb1_alias=P400_LV2_(dm-7)
sdc1_alias=P410_LV5_(Boot)
sdc2_alias=P410_LV5_(dm-8)
sdc3_alias=P410_LV5_(dm-01)
sdd1_alias=P410_LV1_(dm-6)
sde_alias=P410_LV2
sdf1_alias=P410_LV3_(dm-6)
sdg1_alias=P410_LV4_(--)
sdh1_alias=USB1_(md0)
sdi1_alias=USB2_(md0)
...
```` 
the aliases either:
 A. Do not show at all on a client connecting to the server's daemon
![2020-03-01_13-35-56](https://user-images.githubusercontent.com/13614128/75694549-b0c7c580-5c76-11ea-9477-ce14fffa85ec.png)
B. Show incorrectly and Glances throws an error on exit
![2020-03-02_10-43-13](https://user-images.githubusercontent.com/13614128/75709152-1d02f300-5c90-11ea-80b5-a6eb675d7fd3.png)
````
Exception ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/usr/local/lib/python3.6/site-packages/glances/__init__.py", line 68, in __signal_handler
    end()
  File "/usr/local/lib/python3.6/site-packages/glances/__init__.py", line 83, in end
    sys.exit(0)
SystemExit: 0
````
The error occurs when using "q" to quit, and does not occur when force quitting with Ctrl-c.

### Versions

* Glances & psutil (glances -V): 
   * Client: `Glances v3.1.3 with psutil v5.6.3`
   * Server: `Glances v3.1.3 with psutil v5.6.7`

* Operating System (lsb_release -a):
   * Client:
   ````
      System Software Overview:
      System Version: macOS 10.15.2 (19C57)
      Kernel Version: Darwin 19.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Macbook Pro
      User Name: User (****)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 2:05
   ````
   * Server:
   ````
      LSB Version:	:core-4.1-amd64:core-4.1-noarch
      Distributor ID:	RedHatEnterpriseServer
      Description:	Red Hat Enterprise Linux Server release 7.7 (Maipo)
      Release:	7.7
      Codename:	Maipo
   ````
#### Server
Regular logs are shown below. Debug logs are available on [Pastebin](https://pastebin.com/raw/QXg1VcVd)
````access log
2020-03-02 11:14:36,098 -- INFO -- Start Glances 3.1.3
2020-03-02 11:14:36,099 -- INFO -- CPython 3.6.8 and psutil 5.6.7 detected
2020-03-02 11:14:36,103 -- INFO -- Search glances.conf file in /home/user/.config/glances/glances.conf
2020-03-02 11:14:36,104 -- INFO -- Search glances.conf file in /etc/glances/glances.conf
2020-03-02 11:14:36,106 -- INFO -- Read configuration file '/etc/glances/glances.conf'
2020-03-02 11:14:36,118 -- INFO -- Start GlancesStandalone mode
2020-03-02 11:14:36,896 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2020-03-02 11:14:36,906 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2020-03-02 11:14:39,504 -- INFO -- Stop Glances (keypressed: 113)
2020-03-02 11:14:45,641 -- INFO -- Glances stopped (keypressed: CTRL-C)
````
#### Client
Client debug logs are avialable on [Pastebin](https://pastebin.com/raw/126cf6Aj)

**Comment by nicolargo** [comment]
A first patch correct the display of long alias name: 2c9e80b4

For the other issue (threading exception i can not reproduce). @imdebating can you please tun Glances in debug mode (-d) and pastebin us the result of the log file.

Thanks !

**Comment by imdebating** [comment]
Tested and the aliases are displaying properly when run locally on the server. This part of the fix functions as expected
When running from the client machine, I still only see the original names (like picture A in orig post). Perhaps my setup is incorrect: on the client, I do not have a config file, I'm relying on the server to send aliases across. If this isn't correct and I should have the aliases on the client, how do I differentiate between sda1 on server A and sda1 on server B in my client config file?
Thanks for your help and great product!
PS. I was consistently receiving the error on exit, but now I am consistently not receiving it, so perhaps that was the ghost in my machine.
