### ISSUE TITLE
Windows 10 [OSError: [WinError 998] Invalid access to memory location]

### ISSUE THREAD

**Issue by quietsoviet** [nicolargo/glances#1622]
Hi i am sorry is this was solved but i did not find and cant find help for it.

#### Description

After installing python and using pip install glances i constantly get this error "OSError: [WinError 998] Invalid access to memory location"

#### Versions

Glances v3.1.3 with psutil v5.7.0
Windows 10.0.18363.0

#### Logs
This is from PowerShell when run "glances -d"
Traceback (most recent call last):
  File "C:\Python38\Scripts\glances-script.py", line 11, in <module>
    load_entry_point('Glances==3.1.3', 'console_scripts', 'glances')()
  File "c:\python38\lib\site-packages\glances\__init__.py", line 143, in main
    start(config=config, args=args)
  File "c:\python38\lib\site-packages\glances\__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "c:\python38\lib\site-packages\glances\webserver.py", line 41, in __init__
    self.stats.update()
  File "c:\python38\lib\site-packages\glances\stats.py", line 234, in update
    self._plugins[p].update()
  File "C:\Python38\lib\site-packages\glances\plugins\glances_processcount.py", line 73, in update
    glances_processes.update()
  File "c:\python38\lib\site-packages\glances\processes.py", line 246, in update
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "c:\python38\lib\site-packages\glances\processes.py", line 246, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "c:\python38\lib\site-packages\psutil\__init__.py", line 1457, in process_iter
    yield add(pid)
  File "c:\python38\lib\site-packages\psutil\__init__.py", line 1434, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "c:\python38\lib\site-packages\psutil\__init__.py", line 538, in as_dict
    ret = meth()
  File "c:\python38\lib\site-packages\psutil\__init__.py", line 690, in cmdline
    return self._proc.cmdline()
  File "c:\python38\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "c:\python38\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "c:\python38\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\python38\lib\site-packages\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\python38\lib\site-packages\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
OSError: [WinError 998] Invalid access to memory location

Here is log 
[glances-matija.log](https://github.com/nicolargo/glances/files/4313089/glances-matija.log)

And here is old log from time i try to first run glances
[glances-matija-old.log](https://github.com/nicolargo/glances/files/4313096/glances-matija-old.log)

**Comment by nicolargo** [comment]
@quietsoviet Thanks for the issue report.

Can you try to run Glances as administrator and check if the issue happens.

**Comment by quietsoviet** [comment]
It was all run as administrator i tried to run it powershell without admin privileges and funny thing happened...it run normally. So with admin rights it tell that error, without admin it just run.
Here is log first one is run without admin rights, and second one is run with admin right. I did it if it will help you in any way. Thanks nonetheless
[glances-matija.log](https://github.com/nicolargo/glances/files/4315293/glances-matija.log)

**Comment by elliottmarter** [comment]
@quietsoviet did you ever solve your issue, I am having the exact same problem.

**Comment by quietsoviet** [comment]
My error was that i was trying to run as powershell(admin).
When opened normal powershell and runned command it worked fine.

**Comment by 8YdEo37** [comment]
Hi All,

I can confirm this issue on Windows Server 2019 (Hyper-V), 10.0.17763.

Glances==3.1.4.1

In Admin window = OSError: [WinError 998] Invalid access to memory location
Non admin = failed to create process.

Windows 10 2004 (19041.329) under admin or non-admin window **works well without described problems.**

@nicolargo Thanks for great work so far!

**Comment by mmohoney** [comment]
Same issue here, Windows Server 2019 Host Hyper V Build 1809. Running as Admin. 

`OSError: [WinError 998] Invalid access to memory location`

Willing to help out any way I can
