### ISSUE TITLE
Glances on Synology DSM6.2.2

### ISSUE THREAD

**Issue by ciechompl** [nicolargo/glances#1624]
#### Description
I'm trying to install (get working) glances on Synology NAS with DSM6.2.2
I tried to install in native system and also in opt env. 
In both cases the same result -> glances do not start and I only getting error as presented below. 

```
ash-4.3# glances
Traceback (most recent call last):
  File "/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_processcount.py", line 73, in update
    glances_processes.update()
  File "/usr/lib/python2.7/site-packages/glances/processes.py", line 269, in update
    ad_value=None)
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 1565, in process_iter
    yield add(pid)
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 1542, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 639, in as_dict
    ret = meth()
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 853, in gids
    return self._proc.gids()
  File "/usr/local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1517, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/psutil/_pslinux.py", line 2095, in gids
    real, effective, saved = _gids_re.findall(data)[0]
IndexError: list index out of range
ash-4.3#
```

the most funny thing is that yesterday everything worked fine .. today simply stopped and I'm almost sure that I have not made any changes in the system in a menatime.

installed like this: 
```
ash-4.3# pip install glances
/usr/local/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /root/.cache/pip/wheels/8e/79/75/3f799d334873ea30a1d91e6767b6dab3328d4d8446662c9734/Glances-3.1.4-py2-none-any.whl
Requirement already satisfied: psutil>=5.3.0 in /usr/local/lib/python2.7/site-packages (from glances) (5.6.7)
Requirement already satisfied: future in /usr/lib/python2.7/site-packages (from glances) (0.18.2)
Installing collected packages: glances
Successfully installed glances-3.1.4
ash-4.3#
```

#### Versions

* Glances & psutil (glances -V):

#glances -V
Glances v3.1.4 with PsUtil v5.6.7
Log file: /tmp/glances-root.log

# python -V
Python 2.7.12

* Operating System (lsb_release -a):
ash-4.3# uname -a
Linux DSHome1 3.10.105 #24922 SMP Wed Jul 3 16:34:56 CST 2019 x86_64 GNU/Linux synology_braswell_916+

#### Logs
```
ash-4.3# cat /tmp/glances-root.log
2020-03-15 01:05:06,250 -- INFO -- Start Glances 3.1.4
2020-03-15 01:05:06,251 -- INFO -- CPython 2.7.12 and psutil 5.6.7 detected
2020-03-15 01:05:06,261 -- INFO -- Search glances.conf file in /root/.config/glances/glances.conf
2020-03-15 01:05:06,261 -- INFO -- Search glances.conf file in /etc/glances/glances.conf
2020-03-15 01:05:06,280 -- INFO -- Start GlancesStandalone mode
2020-03-15 01:05:06,493 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named docker)
2020-03-15 01:05:06,494 -- ERROR -- docker plugin - Can not connect to Docker (global name 'docker' is not defined)
2020-03-15 01:05:06,496 -- ERROR -- Cannot grab battery status [Errno 2] No such file or directory: '/sys/class/power_supply'.
2020-03-15 01:05:06,874 -- WARNING -- Missing Python Lib (No module named pymdstat), Raid plugin is disabled
2020-03-15 01:05:06,902 -- WARNING -- Sparklines module not found (No module named sparklines)
2020-03-15 01:05:06,903 -- WARNING -- Missing Python Lib (No module named cpuinfo), Quicklook plugin will not display CPU info
2020-03-15 01:05:06,906 -- WARNING -- Missing Python Lib (No module named pySMART), HDD Smart plugin is disabled
2020-03-15 01:05:06,911 -- WARNING -- Missing Python Lib (No module named wifi.scan), Wifi plugin is disabled
2020-03-15 01:05:06,912 -- WARNING -- Missing Python Lib (No module named py3nvml.py3nvml), Nvidia GPU plugin is disabled
ash-4.3#
```

**Comment by pseudomix** [comment]
Hello,

I have the same issue. Installed with Docker:
Glances v3.1.6_b1 with PsUtil v5.7.2
Python 3.8.2
Linux fde2df7329f1 4.4.59+ #25426 SMP PREEMPT Wed Jul 8 03:21:29 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

Any News?
Thanks for your help
