### ISSUE TITLE
UnicodeDecodeError on fresh install (Debian 10)

### ISSUE THREAD

**Issue by iBelow** [nicolargo/glances#1633]
```
glances -V
Glances v3.1.4.1 with PsUtil v5.7.0
Log file: /root/.local/share/glances/glances.log
```

after installing on clear debian

```
⚡ root@apollodebian  -> glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 923, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 933, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_connections.py", line 116, in update
    logger.debug('Can not get network connections track ({})'.format(e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 10: ordinal not in range(128)
```

**Comment by nicolargo** [comment]
Can your try this ?

    LANG=en_US.UTF-8 LC_ALL= glances

**Comment by iBelow** [comment]
> Can your try this ?
> 
> ```
> LANG=en_US.UTF-8 LC_ALL= glances
> ```

Yeah, it's work, but
if I change the size of the terminal, then everything breaks. but nonetheless it works if you immediately set the size of the terminal to fit -
