### ISSUE TITLE
Fix gpu plugin to handle multiple gpus with different reporting capabilities

### ISSUE THREAD

**Issue by jrinkinen** [nicolargo/glances#1634]
#### Description

Bug: Computers with multiple Nvidia GPUs may have different level of compute capability and ability to report GPU % and GPU mem % utilization rates. For example GTX 780 with compute capability 3.5 is not able to provide those measurements while RTX 2080 Ti can provide measurements. 

Fix is provided as follows for python 3 against Glances version 3.1.5:
```diff
$ git diff
diff --git a/glances/plugins/glances_gpu.py b/glances/plugins/glances_gpu.py
index 9fd1c292..9f2510fc 100644
--- a/glances/plugins/glances_gpu.py
+++ b/glances/plugins/glances_gpu.py
@@ -226,11 +226,11 @@ class Plugin(GlancesPlugin):
                 id_msg = '{}'.format(gpu_stats['gpu_id'])
                 try:
                     proc_msg = '{:>3.0f}%'.format(gpu_stats['proc'])
-                except ValueError:
+                except (ValueError, TypeError):
                     proc_msg = '{:>4}'.format('N/A')
                 try:
                     mem_msg = '{:>3.0f}%'.format(gpu_stats['mem'])
-                except ValueError:
+                except (ValueError, TypeError):
                     mem_msg = '{:>4}'.format('N/A')
                 msg = '{}: {} mem: {}'.format(id_msg,
                                               proc_msg,
```

#### Versions

* Glances & psutil (glances -V):
Glances v3.1.5_DEVELOP with PsUtil v5.7.0

* Operating System (lsb_release -a):
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	19.0.2
Codename:	Kyria

* Gpustat (```pip install gpustat```)
```bash
$ gpustat 
ryzen6-pc               Mon Apr  6 13:08:57 2020  440.64
[0] GeForce GTX 780     | 42'C,  ?? % |  1201 /  3018 MB | (Not Supported)
[1] GeForce RTX 2080 Ti | 33'C,   0 % |    13 / 11019 MB | gdm(5M) jrin(5M)
```

#### Logs

Glances fails with error with heterogeneous GPUs as other provides values and other does not.

Traceback:
```
Traceback (most recent call last):
File "/data/p/Cloudnn/cloudnn_model/p3env/bin/glances", line 8, in <module>
  sys.exit(main())
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/__init__.py", line 143, in main
  start(config=config, args=args)
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/__init__.py", line 112, in start
  mode.serve_forever()
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/standalone.py", line 154, in serve_forever
  loop = self.__serve_forever()
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/standalone.py", line 141, in __serve_forever
  ret = not self.screen.update(self.stats, duration=adapted_refresh)
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/outputs/glances_curses.py", line 962, in update
  self.flush(stats, cs_status=cs_status)
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/outputs/glances_curses.py", line 937, in flush
  self.display(stats, cs_status=cs_status)
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/outputs/glances_curses.py", line 515, in display
  __stat_display = self.__get_stat_display(stats, layer=cs_status)
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/outputs/glances_curses.py", line 488, in __get_stat_display
  ret[p] = stats.get_plugin(p).get_stats_display(args=self.args,
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/plugins/glances_plugin.py", line 801, in get_stats_display
  'msgdict': self.msg_curse(args),
File "/data/p/Cloudnn/cloudnn_model/p3env/lib/python3.8/site-packages/glances/plugins/glances_gpu.py", line 228, in msg_curse
  proc_msg = '{:>3.0f}%'.format(gpu_stats['proc'])
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by nicolargo** [comment]
Merged in the DEVELOP branch, thanks for the patch @jrinkinen !
