### ISSUE TITLE
Glances to Elastic 7.6 broken

### ISSUE THREAD

**Issue by perfecto25** [nicolargo/glances#1638]
#### Description

trying to export glances to Elastic

#### Versions
Glances v3.1.4.1 with PsUtil v5.7.0
CentOS Linux release 7.7.1908 (Core)

python 2.7.5

```
root@testbox /u/l/s/system# glances --export elasticsearch
/usr/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.4.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 51, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 48, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 103, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 184, in load_exports
    config=self.config)
  File "/usr/lib/python2.7/site-packages/glances/exports/glances_elasticsearch.py", line 53, in __init__
    self.client = self.init()
  File "/usr/lib/python2.7/site-packages/glances/exports/glances_elasticsearch.py", line 105, in init
    es.indices.create(index=self.index,body=template_body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 104, in create
    "PUT", _make_path(index), params=params, headers=headers, body=body
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 362, in perform_request
    timeout=timeout,
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 244, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, u'mapper_parsing_exception', u'Root mapping definition has unsupported parameters:  [glances : {dynamic_templates=[{integers={mapping={type=integer}, match_mapping_type=long}}, {strings={mapping={fields={raw={ignore_above=256, type=keyword}}, type=text}, match_mapping_type=string}}]}]')

```

**Comment by nicolargo** [comment]
Hi @perfecto25 ,

What is your ELK Python lib version ?

    # pip show elasticsearch

Did you try to upgrade your ElasticSearch Python lib ?

    # pip install --upgrade elasticsearch

Nicolas

**Comment by perfecto25** [comment]
```
root@testbox:mreider $ pip show elasticsearch
/usr/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
---
Metadata-Version: 2.1
Name: elasticsearch
Version: 7.6.0
Summary: Python client for Elasticsearch
Home-page: https://github.com/elastic/elasticsearch-py
Author: Honza Král, Nick Lang
Author-email: honza.kral@gmail.com, nick@nicklang.com
Installer: pip
License: Apache-2.0
Location: /usr/lib/python2.7/site-packages
Requires: urllib3
Classifiers:
  Development Status :: 5 - Production/Stable
  License :: OSI Approved :: Apache Software License
  Intended Audience :: Developers
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Programming Language :: Python :: 3.7
  Programming Language :: Python :: 3.8
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```


``` 
root@testbox:mreider $ pip install -U elasticsearch
/usr/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Requirement already up-to-date: elasticsearch in /usr/lib/python2.7/site-packages
Collecting urllib3>=1.21.1 (from elasticsearch)
  Downloading https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 6.1MB/s 
Installing collected packages: urllib3
  Found existing installation: urllib3 1.25.8
    Uninstalling urllib3-1.25.8:
      Successfully uninstalled urllib3-1.25.8
Successfully installed urllib3-1.25.9
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
``` 

Looks like export Elasticsearch is not an option,

```
root@testbox:mreider $ glances --export elasticsearch
/usr/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
usage: glances [-h] [-V] [-d] [-C CONF_FILE] [-3] [-4] [--disable-cpu]
               [--disable-mem] [--disable-swap] [--disable-load]
               [--disable-network] [--disable-ip] [--disable-diskio]
               [--disable-fs] [--disable-sensors] [--disable-hddtemp]
               [--disable-raid] [--disable-docker] [-2] [--disable-process]
               [--disable-log] [--disable-bold] [--enable-process-extended]
               [--enable-history] [--path-history PATH_HISTORY]
               [--export-csv EXPORT_CSV] [--export-influxdb]
               [--export-opentsdb] [--export-statsd] [--export-rabbitmq]
               [-c CLIENT] [-s] [--browser] [--disable-autodiscover] [-p PORT]
               [-B BIND_ADDRESS] [--password]
               [--snmp-community SNMP_COMMUNITY] [--snmp-port SNMP_PORT]
               [--snmp-version SNMP_VERSION] [--snmp-user SNMP_USER]
               [--snmp-auth SNMP_AUTH] [--snmp-force] [-t TIME] [-w] [-q]
               [-f PROCESS_FILTER] [--process-short-name] [-0]
               [--hide-kernel-threads] [--tree] [-b] [--fahrenheit] [-1]
               [--fs-free-space] [--theme-white]
glances: error: ambiguous option: --export could match --export-rabbitmq, --export-csv, --export-influxdb, --export-opentsdb, --export-statsd
```

**Comment by perfecto25** [comment]
I think I see the issue, 

I inititally installed Glances via RPM which was version glances-2.5.1-1.el7.noarch 

I removed rpm, installed via pip, and version is now Glances v3.1.4.1 with PsUtil v5.6.7

Now its exporting to elastic
