### ISSUE TITLE
Inability to launch.

### ISSUE THREAD

**Issue by ergcode** [nicolargo/glances#1698]
I get an undocumented error on startup.
Installed via `curl -L https://bit.ly/glances | /bin/bash` and at the same time a hell of a bunch of dependencies were installed that I now don't know how to remove. Also, I don't know how to remove glances.

OS: KDE neon 5.19

```Traceback (most recent call last):
File "/usr/local/bin/glances", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 143, in main
start(config=config, args=args)
File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 108, in start
mode = GlancesMode(config=config, args=args)
File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 78, in __init__
self.stats.update()
File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 234, in update
self._plugins[p].update()
File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 923, in wrapper
ret = fct(self, *args, **kw)
File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 933, in wrapper
ret = fct(*args, **kw)
File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_connections.py", line 116, in update
logger.debug('Can not get network connections track ({})'.format(e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 10: ordinal not in range(128)
```

**Comment by nicolargo** [comment]
Hi,

can you try this:

LANG=en_US.UTF-8 LC_ALL= glances

Nicolas

**Comment by RazCrimson** [comment]
Closing as stale issue.
