### ISSUE TITLE
Errors when running Glances as web service

### ISSUE THREAD

**Issue by ajgringo619** [nicolargo/glances#1702]
#### Description

My system journal is getting flooded with the following errors when running Glances as a web service:
```
Aug 02 19:25:19 glances[3955]: Traceback (most recent call last):
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
Aug 02 19:25:19 glances[3955]:     self.finish_response()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
Aug 02 19:25:19 glances[3955]:     self.write(data)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
Aug 02 19:25:19 glances[3955]:     self.send_headers()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 332, in send_headers
Aug 02 19:25:19 glances[3955]:     self.send_preamble()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 255, in send_preamble
Aug 02 19:25:19 glances[3955]:     ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
Aug 02 19:25:19 glances[3955]:     result = self.stdout.write(data)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/socketserver.py", line 803, in write
Aug 02 19:25:19 glances[3955]:     self._sock.sendall(b)
Aug 02 19:25:19 glances[3955]: BrokenPipeError: [Errno 32] Broken pipe
Aug 02 19:25:19 glances[3955]: ----------------------------------------
Aug 02 19:25:19 glances[3955]: Exception happened during processing of request from ('192.168.0.11', 47502)
Aug 02 19:25:19 glances[3955]: Traceback (most recent call last):
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
Aug 02 19:25:19 glances[3955]:     self.finish_response()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
Aug 02 19:25:19 glances[3955]:     self.write(data)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
Aug 02 19:25:19 glances[3955]:     self.send_headers()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 332, in send_headers
Aug 02 19:25:19 glances[3955]:     self.send_preamble()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 255, in send_preamble
Aug 02 19:25:19 glances[3955]:     ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
Aug 02 19:25:19 glances[3955]:     result = self.stdout.write(data)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/socketserver.py", line 803, in write
Aug 02 19:25:19 glances[3955]:     self._sock.sendall(b)
Aug 02 19:25:19 glances[3955]: BrokenPipeError: [Errno 32] Broken pipe
Aug 02 19:25:19 glances[3955]: During handling of the above exception, another exception occurred:
Aug 02 19:25:19 glances[3955]: Traceback (most recent call last):
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
Aug 02 19:25:19 glances[3955]:     self.handle_error()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
Aug 02 19:25:19 glances[3955]:     self.finish_response()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
Aug 02 19:25:19 glances[3955]:     self.write(data)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
Aug 02 19:25:19 glances[3955]:     self.send_headers()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
Aug 02 19:25:19 glances[3955]:     if not self.origin_server or self.client_is_modern():
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
Aug 02 19:25:19 glances[3955]:     return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
Aug 02 19:25:19 glances[3955]: TypeError: 'NoneType' object is not subscriptable
Aug 02 19:25:19 glances[3955]: During handling of the above exception, another exception occurred:
Aug 02 19:25:19 glances[3955]: Traceback (most recent call last):
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
Aug 02 19:25:19 glances[3955]:     self.process_request(request, client_address)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
Aug 02 19:25:19 glances[3955]:     self.finish_request(request, client_address)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
Aug 02 19:25:19 glances[3955]:     self.RequestHandlerClass(request, client_address, self)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
Aug 02 19:25:19 glances[3955]:     self.handle()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/simple_server.py", line 133, in handle
Aug 02 19:25:19 glances[3955]:     handler.run(self.server.get_app())
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
Aug 02 19:25:19 glances[3955]:     self.close()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
Aug 02 19:25:19 glances[3955]:     self.status.split(' ',1)[0], self.bytes_sent
Aug 02 19:25:19 glances[3955]: AttributeError: 'NoneType' object has no attribute 'split'
Aug 02 19:25:19 glances[3955]: ----------------------------------------
Aug 02 19:25:19 glances[3955]: Traceback (most recent call last):
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
Aug 02 19:25:19 glances[3955]:     self.finish_response()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
Aug 02 19:25:19 glances[3955]:     self.write(data)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
Aug 02 19:25:19 glances[3955]:     self.send_headers()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 332, in send_headers
Aug 02 19:25:19 glances[3955]:     self.send_preamble()
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 255, in send_preamble
Aug 02 19:25:19 glances[3955]:     ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
Aug 02 19:25:19 glances[3955]:     result = self.stdout.write(data)
Aug 02 19:25:19 glances[3955]:   File "/usr/lib/python3.6/socketserver.py", line 803, in write
Aug 02 19:25:19 glances[3955]:     self._sock.sendall(b)
Aug 02 19:25:19 glances[3955]: BrokenPipeError: [Errno 32] Broken pipe
```
The version of Glances I'm running was installed via pip. I've already tried upgrading with no changes.

#### Versions

Glances v3.1.4.1 with PsUtil v5.5.1
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia

#### Logs

See above.

**Comment by nicolargo** [comment]
Should be corrected on the develop branch.
