### ISSUE TITLE
Elasticsearch version 7.x or higher is not supported

### ISSUE THREAD

**Issue by kaleyroy** [nicolargo/glances#1714]
#### Description

how can i setup the elasticsearch with http auth?
i can't  find the options to set the username and password? 
there are only three options:  [host] [port] [index] under the [elasticsearch] in glances.conf file.

#### Versions

* Glances & psutil (glances -V): Glances v3.1.5 with PsUtil v5.7.2
* Operating System (lsb_release -a):

#### Logs

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/glances/exports/glances_elasticsearch.py", line 101, in init
    index_count = es.count(index=self.index)['count']
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 528, in count
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 300, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/glances-es-2020.08.27/_count]')

**Comment by kaleyroy** [comment]
**Sorry, it's my mistake!**

After read the elasticsearch document, i updated the config [host=http://user:pass@ip], 
but when try to run "glances --export elasticsearch“  again, i got the error bellow, any suggestion for this?


### Logs

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/glances/exports/glances_elasticsearch.py", line 101, in init
    index_count = es.count(index=self.index)['count']
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 528, in count
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 300, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [glances-2020.08.27]', glances-2020.08.27, index_or_alias)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python3.8/dist-packages/glances/standalone.py", line 51, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/local/lib/python3.8/dist-packages/glances/stats.py", line 48, in __init__
    self.load_modules(self.args)
  File "/usr/local/lib/python3.8/dist-packages/glances/stats.py", line 103, in load_modules
    self.load_exports(args=args)
  File "/usr/local/lib/python3.8/dist-packages/glances/stats.py", line 183, in load_exports
    self._exports[export_name] = export_module.Export(args=args,
  File "/usr/local/lib/python3.8/dist-packages/glances/exports/glances_elasticsearch.py", line 53, in __init__
    self.client = self.init()
  File "/usr/local/lib/python3.8/dist-packages/glances/exports/glances_elasticsearch.py", line 105, in init
    es.indices.create(index=self.index,body=template_body)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/indices.py", line 119, in create
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 300, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [glances : {dynamic_templates=[{integers={mapping={type=integer}, match_mapping_type=long}}, {strings={mapping={type=text, fields={raw={ignore_above=256, type=keyword}}}, match_mapping_type=string}}]}]')

**Comment by nicolargo** [comment]
Tested with my old Elasticsearch server version 5.6.9 and ElasticSearch-Py Python Lib version 5.5.0 and everything is ok.

What is you ElasticSearch server and Python lib version ?

```
curl http://127.0.0.1:9200
pip freeze | grep elasticsearch
```

Thanks

**Comment by kaleyroy** [comment]
**Ok, i've found the cause of the issue.** 

Very sorry i didn't mention my ElasticSearch version before, i am using **ElasticSearch:7.9** 
and i've compared the **Index Template** used in [glances_elasticsearch.py](https://github.com/nicolargo/glances/blob/develop/glances/exports/glances_elasticsearch.py)  with the current [ElasticSearch Index Template](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-templates.html), the Index Template schema  had changed after the **ES 6+**, the nested [**mapping**] property does not supported anymore. Now using the [**properties**] instead. so the current implementation would work in **_OLD ElasticSearch_** version , but not work in new Version yet (maybe ES 6 +).

## Current Index Template

`{
  "index_patterns": ["te*", "bar*"],
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "_doc": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z yyyy"
        }
      }
    }
  }
}`

## Index Template used in glances_elasticsearch.py

`template_body =  {
          "mappings": {
            "glances": {
              "dynamic_templates": [
                {
                  "integers": {
                    "match_mapping_type": "long",
                    "mapping": {
                      "type": "integer"
                    }
                  }
                },
                {
                  "strings": {
                    "match_mapping_type": "string",
                    "mapping": {
                      "type": "text",
                      "fields": {
                        "raw": {
                          "type":  "keyword",
                          "ignore_above": 256
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }`

**Comment by nicolargo** [comment]
Hi @kaleyroy 

i just have a look on this enhancement request.

A first version, compatible with ELK 7.x is available in this branch: https://github.com/nicolargo/glances/tree/issue1714

I also change the data model. Each plugin write one document with all the metrics as key/value:

![image](https://user-images.githubusercontent.com/776747/105641499-8c736980-5e84-11eb-91bd-94044c48cad6.png)

What do you think ?

**Comment by nicolargo** [comment]
Merge into DEVELOP branch
