### ISSUE TITLE
OpenBSD 6.8; python 3.8; glances runtime error

### ISSUE THREAD

**Issue by hucste** [nicolargo/glances#1747]
On OpenBSD 6.8, now we have python 3.8, and glances exits with runtime error

```# /usr/local/bin/glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')()
  File "/usr/local/lib/python3.8/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/local/lib/python3.8/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python3.8/site-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/usr/local/lib/python3.8/site-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.8/site-packages/glances/plugins/glances_processcount.py", line 73, in update
    glances_processes.update()
  File "/usr/local/lib/python3.8/site-packages/glances/processes.py", line 268, in update
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/local/lib/python3.8/site-packages/glances/processes.py", line 268, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/local/lib/python3.8/site-packages/psutil/__init__.py", line 1437, in process_iter
    yield add(pid)
  File "/usr/local/lib/python3.8/site-packages/psutil/__init__.py", line 1419, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/local/lib/python3.8/site-packages/psutil/__init__.py", line 528, in as_dict
    ret = meth()
  File "/usr/local/lib/python3.8/site-packages/psutil/__init__.py", line 855, in num_threads
    return self._proc.num_threads()
  File "/usr/local/lib/python3.8/site-packages/psutil/_psbsd.py", line 504, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/psutil/_psbsd.py", line 679, in num_threads
    return len(self.threads())
  File "/usr/local/lib/python3.8/site-packages/psutil/_psbsd.py", line 504, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/psutil/_psbsd.py", line 691, in threads
    rawlist = cext.proc_threads(self.pid)
RuntimeError: kvm_openfiles() syscall failed
```

#### Versions

* Glances & psutil (glances -V): 3.1.5
* Operating System (lsb_release -a): OpenBSD 6.8

#### Logs

```
2020-10-18 21:36:09,517 -- INFO -- Start Glances 3.1.5
2020-10-18 21:36:09,519 -- INFO -- CPython 3.8.6 and psutil 5.4.3 detected
2020-10-18 21:36:09,555 -- INFO -- Search glances.conf file in /root/.config/glances/glances.conf
2020-10-18 21:36:09,556 -- INFO -- Search glances.conf file in /usr/local/etc/glances/glances.conf
2020-10-18 21:36:09,576 -- DEBUG -- PsUtil can grab processes io_counters
2020-10-18 21:36:09,577 -- DEBUG -- PsUtil can grab processes gids
2020-10-18 21:36:09,631 -- INFO -- Start GlancesStandalone mode
2020-10-18 21:36:09,649 -- DEBUG -- Pystache library not found (action scripts won't work)
2020-10-18 21:36:09,655 -- DEBUG -- Load section alert in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:09,656 -- DEBUG -- Plugin glances_alert.py started in 0.02328 seconds
2020-10-18 21:36:09,662 -- DEBUG -- Load section amps in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:09,664 -- DEBUG -- AMPs list: []
2020-10-18 21:36:09,664 -- DEBUG -- Plugin glances_amps.py started in 0.007117 seconds
2020-10-18 21:36:10,750 -- DEBUG -- Load section cloud in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,751 -- DEBUG -- cloud plugin - Create thread for OpenStack metadata
2020-10-18 21:36:10,757 -- DEBUG -- Plugin glances_cloud.py started in 1.091948 seconds
2020-10-18 21:36:10,766 -- DEBUG -- Load section connections in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,767 -- DEBUG -- Plugin glances_connections.py started in 0.008477 seconds
2020-10-18 21:36:10,784 -- DEBUG -- Starting new HTTP connection (1): 169.254.169.254:80
2020-10-18 21:36:10,788 -- DEBUG -- Load section core in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,790 -- DEBUG -- Plugin glances_core.py started in 0.021251 seconds
2020-10-18 21:36:10,792 -- DEBUG -- cloud plugin - Cannot connect to the OpenStack metadata API http://169.254.169.254/latest/meta-data/ami-id: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/ami-id (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x458250f71c0>: Failed to establish a new connection: [Errno 13] Permission denied'))
2020-10-18 21:36:10,801 -- DEBUG -- Stats history activated for plugin cpu (items: ['user', 'system'])
2020-10-18 21:36:10,802 -- DEBUG -- Load section cpu in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,804 -- DEBUG -- Load limit: cpu_user_careful = 50.0
2020-10-18 21:36:10,805 -- DEBUG -- Load limit: cpu_user_warning = 70.0
2020-10-18 21:36:10,806 -- DEBUG -- Load limit: cpu_user_critical = 90.0
2020-10-18 21:36:10,807 -- DEBUG -- Load limit: cpu_system_careful = 50.0
2020-10-18 21:36:10,808 -- DEBUG -- Load limit: cpu_system_warning = 70.0
2020-10-18 21:36:10,809 -- DEBUG -- Load limit: cpu_system_critical = 90.0
2020-10-18 21:36:10,810 -- DEBUG -- Load limit: cpu_steal_careful = 50.0
2020-10-18 21:36:10,810 -- DEBUG -- Load limit: cpu_steal_warning = 70.0
2020-10-18 21:36:10,811 -- DEBUG -- Load limit: cpu_steal_critical = 90.0
2020-10-18 21:36:10,812 -- DEBUG -- Load limit: cpu_iowait_careful = 20.0
2020-10-18 21:36:10,813 -- DEBUG -- Load limit: cpu_iowait_warning = 22.5
2020-10-18 21:36:10,814 -- DEBUG -- Load limit: cpu_iowait_critical = 25.0
2020-10-18 21:36:10,815 -- DEBUG -- Load limit: cpu_ctx_switches_careful = 160000.0
2020-10-18 21:36:10,816 -- DEBUG -- Load limit: cpu_ctx_switches_warning = 180000.0
2020-10-18 21:36:10,817 -- DEBUG -- Load limit: cpu_ctx_switches_critical = 200000.0
2020-10-18 21:36:10,818 -- DEBUG -- Plugin glances_cpu.py started in 0.025147 seconds
2020-10-18 21:36:10,822 -- DEBUG -- Stats history activated for plugin diskio (items: ['read_bytes', 'write_bytes'])
2020-10-18 21:36:10,823 -- DEBUG -- Load section diskio in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,824 -- DEBUG -- Plugin glances_diskio.py started in 0.00498 seconds
2020-10-18 21:36:10,830 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named 'docker')
2020-10-18 21:36:10,832 -- DEBUG -- Stats history activated for plugin docker (items: ['cpu_percent'])
2020-10-18 21:36:10,833 -- DEBUG -- Load section docker in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,834 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
2020-10-18 21:36:10,834 -- DEBUG -- Plugin glances_docker.py started in 0.009834 seconds
2020-10-18 21:36:10,841 -- DEBUG -- Load section folders in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,842 -- DEBUG -- Plugin glances_folders.py started in 0.006529 seconds
2020-10-18 21:36:10,846 -- DEBUG -- Stats history activated for plugin fs (items: ['percent'])
2020-10-18 21:36:10,847 -- DEBUG -- Load section fs in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,848 -- DEBUG -- Load limit: fs_careful = 50.0
2020-10-18 21:36:10,849 -- DEBUG -- Load limit: fs_warning = 70.0
2020-10-18 21:36:10,850 -- DEBUG -- Load limit: fs_critical = 90.0
2020-10-18 21:36:10,851 -- DEBUG -- Plugin glances_fs.py started in 0.008152 seconds
2020-10-18 21:36:10,863 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2020-10-18 21:36:10,864 -- DEBUG -- Load section gpu in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,865 -- DEBUG -- pynvml could not be initialized.
2020-10-18 21:36:10,866 -- DEBUG -- Plugin glances_gpu.py started in 0.014334 seconds
2020-10-18 21:36:10,870 -- DEBUG -- Load section help in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,872 -- DEBUG -- Plugin glances_help.py started in 0.005162 seconds
2020-10-18 21:36:10,878 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2020-10-18 21:36:10,879 -- DEBUG -- Load section ip in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,881 -- DEBUG -- Plugin glances_ip.py started in 0.007959 seconds
2020-10-18 21:36:10,885 -- DEBUG -- Load section irq in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,886 -- DEBUG -- Plugin glances_irq.py started in 0.004407 seconds
2020-10-18 21:36:10,890 -- DEBUG -- Stats history activated for plugin load (items: ['min1', 'min5', 'min15'])
2020-10-18 21:36:10,891 -- DEBUG -- Load section load in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,892 -- DEBUG -- Load limit: load_careful = 0.7
2020-10-18 21:36:10,893 -- DEBUG -- Load limit: load_warning = 1.0
2020-10-18 21:36:10,894 -- DEBUG -- Load limit: load_critical = 5.0
2020-10-18 21:36:10,895 -- DEBUG -- Plugin glances_load.py started in 0.008259 seconds
2020-10-18 21:36:10,899 -- DEBUG -- Stats history activated for plugin mem (items: ['percent'])
2020-10-18 21:36:10,900 -- DEBUG -- Load section mem in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,901 -- DEBUG -- Load limit: mem_careful = 50.0
2020-10-18 21:36:10,902 -- DEBUG -- Load limit: mem_warning = 70.0
2020-10-18 21:36:10,903 -- DEBUG -- Load limit: mem_critical = 90.0
2020-10-18 21:36:10,904 -- DEBUG -- Plugin glances_mem.py started in 0.007886 seconds
2020-10-18 21:36:10,907 -- DEBUG -- Stats history activated for plugin memswap (items: ['percent'])
2020-10-18 21:36:10,908 -- DEBUG -- Load section memswap in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,910 -- DEBUG -- Load limit: memswap_careful = 50.0
2020-10-18 21:36:10,911 -- DEBUG -- Load limit: memswap_warning = 70.0
2020-10-18 21:36:10,911 -- DEBUG -- Load limit: memswap_critical = 90.0
2020-10-18 21:36:10,912 -- DEBUG -- Plugin glances_memswap.py started in 0.00786 seconds
2020-10-18 21:36:10,916 -- DEBUG -- Stats history activated for plugin network (items: ['rx', 'tx'])
2020-10-18 21:36:10,918 -- DEBUG -- Load section network in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,919 -- DEBUG -- Load limit: network_rx_careful = 50.0
2020-10-18 21:36:10,920 -- DEBUG -- Load limit: network_rx_warning = 70.0
2020-10-18 21:36:10,921 -- DEBUG -- Load limit: network_rx_critical = 90.0
2020-10-18 21:36:10,922 -- DEBUG -- Load limit: network_tx_careful = 50.0
2020-10-18 21:36:10,923 -- DEBUG -- Load limit: network_tx_warning = 70.0
2020-10-18 21:36:10,923 -- DEBUG -- Load limit: network_tx_critical = 90.0
2020-10-18 21:36:10,924 -- DEBUG -- Plugin glances_network.py started in 0.01124 seconds
2020-10-18 21:36:10,928 -- DEBUG -- Load section now in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,929 -- DEBUG -- Plugin glances_now.py started in 0.00398 seconds
2020-10-18 21:36:10,933 -- DEBUG -- Stats history activated for plugin percpu (items: ['user', 'system'])
2020-10-18 21:36:10,934 -- DEBUG -- Load section percpu in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,935 -- DEBUG -- Load limit: percpu_user_careful = 50.0
2020-10-18 21:36:10,936 -- DEBUG -- Load limit: percpu_user_warning = 70.0
2020-10-18 21:36:10,937 -- DEBUG -- Load limit: percpu_user_critical = 90.0
2020-10-18 21:36:10,938 -- DEBUG -- Load limit: percpu_system_careful = 50.0
2020-10-18 21:36:10,939 -- DEBUG -- Load limit: percpu_system_warning = 70.0
2020-10-18 21:36:10,940 -- DEBUG -- Load limit: percpu_system_critical = 90.0
2020-10-18 21:36:10,941 -- DEBUG -- Plugin glances_percpu.py started in 0.010624 seconds
2020-10-18 21:36:10,950 -- DEBUG -- Load section ports in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,951 -- DEBUG -- No [ports] section in the configuration file. Cannot load ports list.
2020-10-18 21:36:10,952 -- DEBUG -- No [ports] section in the configuration file. Cannot load ports list.
2020-10-18 21:36:10,953 -- DEBUG -- Plugin glances_ports.py started in 0.011353 seconds
2020-10-18 21:36:10,956 -- DEBUG -- Stats history activated for plugin processcount (items: ['total', 'running', 'sleeping', 'thread'])
2020-10-18 21:36:10,957 -- DEBUG -- Load section processcount in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,958 -- DEBUG -- Plugin glances_processcount.py started in 0.004973 seconds
2020-10-18 21:36:10,963 -- DEBUG -- Load section processlist in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,965 -- DEBUG -- Load limit: processlist_cpu_careful = 50.0
2020-10-18 21:36:10,966 -- DEBUG -- Load limit: processlist_cpu_warning = 70.0
2020-10-18 21:36:10,967 -- DEBUG -- Load limit: processlist_cpu_critical = 90.0
2020-10-18 21:36:10,967 -- DEBUG -- Load limit: processlist_mem_careful = 50.0
2020-10-18 21:36:10,968 -- DEBUG -- Load limit: processlist_mem_warning = 70.0
2020-10-18 21:36:10,969 -- DEBUG -- Load limit: processlist_mem_critical = 90.0
2020-10-18 21:36:10,983 -- DEBUG -- Plugin glances_processlist.py started in 0.023548 seconds
2020-10-18 21:36:10,987 -- DEBUG -- Load section psutilversion in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:10,988 -- DEBUG -- Plugin glances_psutilversion.py started in 0.003867 seconds
2020-10-18 21:36:10,998 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2020-10-18 21:36:11,002 -- WARNING -- Missing Python Lib (No module named 'cpuinfo'), Quicklook plugin will not display CPU info
2020-10-18 21:36:11,003 -- DEBUG -- Stats history activated for plugin quicklook (items: ['cpu', 'percpu', 'mem', 'swap'])
2020-10-18 21:36:11,004 -- DEBUG -- Load section quicklook in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,005 -- DEBUG -- Load limit: quicklook_cpu_careful = 50.0
2020-10-18 21:36:11,006 -- DEBUG -- Load limit: quicklook_cpu_warning = 70.0
2020-10-18 21:36:11,007 -- DEBUG -- Load limit: quicklook_cpu_critical = 90.0
2020-10-18 21:36:11,008 -- DEBUG -- Load limit: quicklook_mem_careful = 50.0
2020-10-18 21:36:11,009 -- DEBUG -- Load limit: quicklook_mem_warning = 70.0
2020-10-18 21:36:11,010 -- DEBUG -- Load limit: quicklook_mem_critical = 90.0
2020-10-18 21:36:11,011 -- DEBUG -- Load limit: quicklook_swap_careful = 50.0
2020-10-18 21:36:11,012 -- DEBUG -- Load limit: quicklook_swap_warning = 70.0
2020-10-18 21:36:11,013 -- DEBUG -- Load limit: quicklook_swap_critical = 90.0
2020-10-18 21:36:11,013 -- DEBUG -- Plugin glances_quicklook.py started in 0.025133 seconds
2020-10-18 21:36:11,019 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2020-10-18 21:36:11,021 -- DEBUG -- Load section raid in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,022 -- DEBUG -- Plugin glances_raid.py started in 0.007209 seconds
2020-10-18 21:36:11,033 -- DEBUG -- batinfo library not found. Fallback to psutil.
2020-10-18 21:36:11,034 -- ERROR -- Cannot grab battery status module 'psutil' has no attribute 'sensors_battery'.
2020-10-18 21:36:11,038 -- DEBUG -- Load section sensors in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,040 -- DEBUG -- Load limit: sensors_temperature_core_careful = 60.0
2020-10-18 21:36:11,041 -- DEBUG -- Load limit: sensors_temperature_core_warning = 70.0
2020-10-18 21:36:11,042 -- DEBUG -- Load limit: sensors_temperature_core_critical = 80.0
2020-10-18 21:36:11,043 -- DEBUG -- Load limit: sensors_temperature_hdd_careful = 45.0
2020-10-18 21:36:11,044 -- DEBUG -- Load limit: sensors_temperature_hdd_warning = 52.0
2020-10-18 21:36:11,045 -- DEBUG -- Load limit: sensors_temperature_hdd_critical = 60.0
2020-10-18 21:36:11,046 -- DEBUG -- Load limit: sensors_battery_careful = 80.0
2020-10-18 21:36:11,047 -- DEBUG -- Load limit: sensors_battery_warning = 90.0
2020-10-18 21:36:11,048 -- DEBUG -- Load limit: sensors_battery_critical = 95.0
2020-10-18 21:36:11,049 -- DEBUG -- Cannot grab temperatures. Platform not supported.
2020-10-18 21:36:11,050 -- DEBUG -- Cannot grab fans speed. Platform not supported.
2020-10-18 21:36:11,050 -- DEBUG -- Generic sensor plugin init duration: 0.001514 seconds
2020-10-18 21:36:11,051 -- DEBUG -- Load section hddtemp in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,053 -- DEBUG -- HDDTemp sensor plugin init duration: 0.0014 seconds
2020-10-18 21:36:11,054 -- DEBUG -- Load section batpercent in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,055 -- DEBUG -- Battery sensor plugin init duration: 0.00125 seconds
2020-10-18 21:36:11,055 -- DEBUG -- Plugin glances_sensors.py started in 0.033081 seconds
2020-10-18 21:36:11,061 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2020-10-18 21:36:11,062 -- DEBUG -- Load section smart in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,063 -- DEBUG -- Plugin glances_smart.py started in 0.007246 seconds
2020-10-18 21:36:11,067 -- DEBUG -- Load section system in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,068 -- DEBUG -- Plugin glances_system.py started in 0.004216 seconds
2020-10-18 21:36:11,072 -- DEBUG -- Load section uptime in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,073 -- DEBUG -- Plugin glances_uptime.py started in 0.004231 seconds
2020-10-18 21:36:11,080 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2020-10-18 21:36:11,081 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2020-10-18 21:36:11,082 -- DEBUG -- Load section wifi in ['/root/.config/glances/glances.conf', '/usr/local/etc/glances/glances.conf']
2020-10-18 21:36:11,083 -- DEBUG -- Plugin glances_wifi.py started in 0.009106 seconds
2020-10-18 21:36:11,085 -- DEBUG -- Active plugins list: ['alert', 'amps', 'cloud', 'connections', 'core', 'cpu', 'diskio', 'docker', 'folders', 'fs', 'gpu', 'help', 'ip', 'irq', 'load', 'mem', 'memswap', 'network', 'now', 'percpu', 'ports', 'processcount', 'processlist', 'psutilversion', 'quicklook', 'raid', 'sensors', 'smart', 'system', 'uptime', 'wifi']
2020-10-18 21:36:11,088 -- DEBUG -- Active exports modules list: []
2020-10-18 21:36:11,089 -- DEBUG -- Plugins initialisation duration: 1.457349 seconds
2020-10-18 21:36:11,090 -- DEBUG -- Extended stats for top process are disabled
2020-10-18 21:36:11,091 -- DEBUG -- Plugin amps update return [] in 8.4e-05 seconds
2020-10-18 21:36:11,092 -- DEBUG -- Plugin cloud update return {} in 5e-05 seconds
2020-10-18 21:36:11,112 -- DEBUG -- Can not get network connections track ([Errno 2] No such file or directory: '/proc/sys/net/netfilter/nf_conntrack_count')
2020-10-18 21:36:11,113 -- DEBUG -- Plugin connections update return {'LISTEN': 68, 'ESTABLISHED': 12, 'SYN_SENT': 0, 'SYN_RECV': 0, 'initiated': 0, 'terminated': 0} in 0.019922 seconds
2020-10-18 21:36:11,115 -- DEBUG -- Plugin cpu update return {'total': 27.9, 'user': 19.9, 'system': 8.0, 'idle': 72.1, 'nice': 0.0, 'irq': 0.0} in 0.000575 seconds
2020-10-18 21:36:11,117 -- DEBUG -- Plugin diskio update return [] in 0.000266 seconds
2020-10-18 21:36:11,118 -- DEBUG -- Plugin docker update return {} in 3.8e-05 seconds
2020-10-18 21:36:11,119 -- DEBUG -- docker plugin - Docker export error 'containers'
2020-10-18 21:36:11,120 -- DEBUG -- Plugin folders update return [] in 5.8e-05 seconds
2020-10-18 21:36:11,124 -- DEBUG -- Plugin fs update return [{'device_name': '/dev/sd0a', 'fs_type': 'ffs', 'mnt_point': '/', 'size': 2117531648, 'used': 202637312, 'free': 1809018880, 'percent': 10.1, 'key': 'mnt_point'}, {'device_name': '/dev/sd1n', 'fs_type': 'ffs', 'mnt_point': '/home', 'size': 44586987520, 'used': 221609984, 'free': 42136029184, 'percent': 0.5, 'key': 'mnt_point'}, {'device_name': '/dev/sd1d', 'fs_type': 'ffs', 'mnt_point': '/tmp', 'size': 5283739648, 'used': 8192, 'free': 5019545600, 'percent': 0.0, 'key': 'mnt_point'}, {'device_name': '/dev/sd1f', 'fs_type': 'ffs', 'mnt_point': '/usr', 'size': 6344488960, 'used': 1254404096, 'free': 4772861952, 'percent': 20.8, 'key': 'mnt_point'}, {'device_name': '/dev/sd1g', 'fs_type': 'ffs', 'mnt_point': '/usr/X11R6', 'size': 1057339392, 'used': 254148608, 'free': 750325760, 'percent': 25.3, 'key': 'mnt_point'}, {'device_name': '/dev/sd1h', 'fs_type': 'ffs', 'mnt_point': '/usr/local', 'size': 21133588480, 'used': 614076416, 'free': 19462834176, 'percent': 3.1, 'key': 'mnt_point'}, {'device_name': '/dev/sd1k', 'fs_type': 'ffs', 'mnt_point': '/usr/obj', 'size': 10570905600, 'used': 2048, 'free': 10042359808, 'percent': 0.0, 'key': 'mnt_point'}, {'device_name': '/dev/sd1j', 'fs_type': 'ffs', 'mnt_point': '/usr/src', 'size': 4231280640, 'used': 2048, 'free': 4019716096, 'percent': 0.0, 'key': 'mnt_point'}, {'device_name': '/dev/sd1e', 'fs_type': 'ffs', 'mnt_point': '/var', 'size': 10570905600, 'used': 62265344, 'free': 9980096512, 'percent': 0.6, 'key': 'mnt_point'}, {'device_name': '/dev/sd1l', 'fs_type': 'ffs', 'mnt_point': '/var/log', 'size': 5283756032, 'used': 1253376, 'free': 5018316800, 'percent': 0.0, 'key': 'mnt_point'}, {'device_name': '/dev/sd1m', 'fs_type': 'ffs', 'mnt_point': '/var/www', 'size': 10570905600, 'used': 565420032, 'free': 9476941824, 'percent': 5.6, 'key': 'mnt_point'}] in 0.003047 seconds
2020-10-18 21:36:11,129 -- DEBUG -- Plugin gpu update return [] in 3.6e-05 seconds
2020-10-18 21:36:11,130 -- DEBUG -- Plugin ip update return {} in 4.8e-05 seconds
2020-10-18 21:36:11,131 -- DEBUG -- Plugin irq update return [] in 3.7e-05 seconds
2020-10-18 21:36:11,132 -- DEBUG -- Plugin load update return {'min1': 0.14013671875, 'min5': 0.1572265625, 'min15': 0.1513671875, 'cpucore': 4} in 0.000553 seconds
2020-10-18 21:36:11,134 -- DEBUG -- Plugin mem update return {'total': 2036154368, 'available': 1643999232, 'percent': 19.3, 'used': 392155136, 'free': 1643999232, 'active': 215920640, 'inactive': 427646976, 'buffers': 0, 'cached': 347807744, 'wired': 3153920, 'shared': 0} in 0.000338 seconds
2020-10-18 21:36:11,136 -- DEBUG -- Plugin memswap update return {'total': 4301824512, 'used': 0, 'free': 4301824512, 'percent': 0.0, 'sin': 0, 'sout': 0} in 0.000163 seconds
2020-10-18 21:36:11,138 -- DEBUG -- Plugin network update return [] in 0.001349 seconds
2020-10-18 21:36:11,141 -- DEBUG -- Plugin percpu update return [{'key': 'cpu_number', 'cpu_number': 0, 'total': 15.1, 'user': 0.0, 'system': 15.1, 'idle': 84.9, 'nice': 0.0, 'irq': 0.0}, {'key': 'cpu_number', 'cpu_number': 1, 'total': 16.3, 'user': 14.1, 'system': 2.2, 'idle': 83.7, 'nice': 0.0, 'irq': 0.0}, {'key': 'cpu_number', 'cpu_number': 2, 'total': 2.3, 'user': 1.4, 'system': 0.9, 'idle': 97.7, 'nice': 0.0, 'irq': 0.0}, {'key': 'cpu_number', 'cpu_number': 3, 'total': 81.8, 'user': 69.6, 'system': 12.1, 'idle': 18.2, 'nice': 0.0, 'irq': 0.0}] in 0.000982 seconds
2020-10-18 21:36:11,143 -- DEBUG -- ports plugin - Create thread for scan list []
2020-10-18 21:36:11,145 -- DEBUG -- Plugin ports update return [] in 0.002588 seconds
2020-10-18 21:36:43,739 -- INFO -- Start Glances 3.1.5
2020-10-18 21:36:43,741 -- INFO -- CPython 3.8.6 and psutil 5.4.3 detected
```

**Comment by nicolargo** [comment]
Look like a PsUtil issue ==> https://github.com/giampaolo/psutil/pull/1673

Please upgrade your Python PsUtil lib version to 5.7.0 or higher (your current version is 5.4.3)

**Comment by hucste** [comment]
OK, I updated with the ultimate proposed (5.7.2), and it runs!
Thanks. :+1:
