### ISSUE TITLE
Prometheus export doesn't export any metircs

### ISSUE THREAD

**Issue by Strixx76** [nicolargo/glances#1750]
#### Description

When running in Docker with "--export prometheus" there is no system information exported. Only the Python and process metrics is exported. But in web server mode I can view the system info.

docker compose file:
```
glances:
  image: nicolargo/glances
  container_name: glances
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/strixx/docker/volumes/glances/glances.conf:/glances/conf/glances.conf
  environment:
    GLANCES_OPT: --export prometheus
  restart: unless-stopped
  network_mode: host
  pid: host
  privileged: true
```

relevant part of glances.conf:
```
[prometheus]
host=192.168.56.101
port=9091
prefix=glances
labels=src:glances
```

And the metrics published on http://192.168.56.101:9091/:
```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 581.0
python_gc_objects_collected_total{generation="1"} 319.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 91.0
python_gc_collections_total{generation="1"} 8.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="2",version="3.8.2"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 6.61180416e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 3.7900288e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.60353809183e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 9.25
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 32.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
```

#### Versions

Docker image nicolargo/glances:latest pulled today (2020-10-24)

* Glances & psutil (glances -V): Glances v3.1.6_b1 with PsUtil v5.7.2
* Operating System (lsb_release -a): 20.04.1 LTS (Focal Fossa)
(even though https://hub.docker.com/r/nicolargo/glances/dockerfile claims it should be Alpine as base images)

#### Logs

docker log:
```
today at 15:09 Traceback (most recent call last):
today at 15:09 File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
today at 15:09 return _run_code(code, main_globals, None,
today at 15:09 File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
today at 15:09 exec(code, run_globals)
today at 15:09 File "/usr/local/lib/python3.8/dist-packages/glances/__main__.py", line 29, in <module>
today at 15:09 glances.main()
today at 15:09 File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 145, in main
today at 15:09 start(config=config, args=args)
today at 15:09 File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 110, in start
today at 15:09 mode = GlancesMode(config=config, args=args)
today at 15:09 File "/usr/local/lib/python3.8/dist-packages/glances/standalone.py", line 98, in __init__
today at 15:09 self.screen = GlancesCursesStandalone(config=config, args=args)
today at 15:09 File "/usr/local/lib/python3.8/dist-packages/glances/outputs/glances_curses.py", line 123, in __init__
today at 15:09 self.screen = curses.initscr()
today at 15:09 File "/usr/lib/python3.8/curses/__init__.py", line 29, in initscr
today at 15:09 setupterm(term=_os.environ.get("TERM", "unknown"),
today at 15:09 _curses.error: setupterm: could not find terminal
```

/tmp/glances-root.log (inside the container):
```
2020-10-24 13:09:22,719 -- INFO -- Start Glances 3.1.6_b1
2020-10-24 13:09:22,720 -- INFO -- CPython 3.8.2 and psutil 5.7.2 detected
2020-10-24 13:09:22,722 -- INFO -- Search glances.conf file in /glances/conf/glances.conf
2020-10-24 13:09:22,724 -- INFO -- Read configuration file '/glances/conf/glances.conf'
2020-10-24 13:09:22,729 -- INFO -- Start GlancesStandalone mode
2020-10-24 13:09:22,734 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2020-10-24 13:09:22,744 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2020-10-24 13:09:22,842 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2020-10-24 13:09:23,126 -- INFO -- Start Prometheus exporter on 192.168.56.101:9091
```

**Comment by nicolargo** [comment]
Hi @Strixx76 

in order to avoid the use of the Curse interface, you need to add the --quiet option to Glances.

Another thing, are you sure that your Glances doker can reach your Promtheus instance ?

**Comment by Strixx76** [comment]
I was investigating the output directly from Glances by browsing to ....:9091/metrics and it was posted above.

Any way, by adding the option "--quiet" it started working. Now I have all the expected metrics!
