### ISSUE TITLE
glances with docker: ModuleNotFoundError: No module named ...

### ISSUE THREAD

**Issue by montagesepp** [nicolargo/glances#1751]
#### Description
When running glances Docker container (I'm on Ubuntu 18.04 with arm64 arch) with "--export influxdb" (also tried "--export prometheus"), I get "ModuleNotFoundError: No module named 'influxdb'"
In web server mode I can view the system info, but there is no info about docker containers, though I set [docker] disable=False in the glances.conf.

Docker-compose file:

```
  glances:
    image: nicolargo/glances:dev
    container_name: glances
    restart: unless-stopped
    privileged: true
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "$GLANCES_PORT:61208"
    pid: host
    volumes:
      - $USERDIR/docker/glances/conf/glances.conf:/glances/conf/glances.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: "--quiet --export influxdb"
      TZ: $TZ
	  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "8086:8086"
    volumes:
      - $USERDIR/docker/influxdb/db:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=glances
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=root
      - INFLUXDB_HTTP_AUTH_ENABLED=true
```

#### Versions
Docker image nicolargo/glances:dev pulled yesterday (2020-10-28)
Operating System: Ubuntu 18.04.5 LTS, arm64 architecture
Docker:  Server Version: 19.03.13, Kernel Version: 4.9.230-76

#### Docker Logs
```
glances         | 2020-10-29T12:15:38.579728792Z Traceback (most recent call last):
glances         | 2020-10-29T12:15:38.579790462Z   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
glances         | 2020-10-29T12:15:38.579881591Z     return _run_code(code, main_globals, None,
glances         | 2020-10-29T12:15:38.579904800Z   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
glances         | 2020-10-29T12:15:38.580052057Z     exec(code, run_globals)
glances         | 2020-10-29T12:15:38.580066975Z   File "/glances/glances/__main__.py", line 29, in <module>
glances         | 2020-10-29T12:15:38.580167313Z     glances.main()
glances         | 2020-10-29T12:15:38.580181605Z   File "/glances/glances/__init__.py", line 145, in main
glances         | 2020-10-29T12:15:38.580332529Z     start(config=config, args=args)
glances         | 2020-10-29T12:15:38.580345821Z   File "/glances/glances/__init__.py", line 110, in start
glances         | 2020-10-29T12:15:38.580509287Z     mode = GlancesMode(config=config, args=args)
glances         | 2020-10-29T12:15:38.580525496Z   File "/glances/glances/standalone.py", line 51, in __init__
glances         | 2020-10-29T12:15:38.580643168Z     self.stats = GlancesStats(config=config, args=args)
glances         | 2020-10-29T12:15:38.580656544Z   File "/glances/glances/stats.py", line 48, in __init__
glances         | 2020-10-29T12:15:38.580765674Z     self.load_modules(self.args)
glances         | 2020-10-29T12:15:38.580778633Z   File "/glances/glances/stats.py", line 103, in load_modules
glances         | 2020-10-29T12:15:38.580914306Z     self.load_exports(args=args)
glances         | 2020-10-29T12:15:38.580927681Z   File "/glances/glances/stats.py", line 178, in load_exports
glances         | 2020-10-29T12:15:38.581071313Z     export_module = __import__(self._exports_all[export_name])
glances         | 2020-10-29T12:15:38.581083730Z   File "/glances/glances/exports/glances_influxdb.py", line 27, in <module>
glances         | 2020-10-29T12:15:38.581191360Z     from influxdb import InfluxDBClient
glances         | 2020-10-29T12:15:38.581203528Z ModuleNotFoundError: No module named 'influxdb'
```
/tmp/glances-root.log (inside the container), when run in web-server mode (instead of GLANCES_OPT: "--quiet --export influxdb", with which the container crashes):
```
2020-10-29 14:06:21,347 -- INFO -- Start Glances 3.1.6_b1
2020-10-29 14:06:21,348 -- INFO -- CPython 3.9.0 and psutil 5.7.2 detected
2020-10-29 14:06:21,356 -- INFO -- Search glances.conf file in /glances/conf/glances.conf
2020-10-29 14:06:21,362 -- INFO -- Read configuration file '/glances/conf/glances.conf'
2020-10-29 14:06:21,421 -- INFO -- Start GlancesWebServer mode
2020-10-29 14:06:21,452 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2020-10-29 14:06:21,473 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2020-10-29 14:06:21,474 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2020-10-29 14:06:21,479 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2020-10-29 14:06:21,483 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2020-10-29 14:06:21,535 -- WARNING -- Missing Python Lib (No module named 'requests'), cannot load nginx AMP
2020-10-29 14:06:21,552 -- WARNING -- Missing Python Lib (No module named 'requests'), Ports plugin is limited to port scanning
2020-10-29 14:06:21,596 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2020-10-29 14:06:21,597 -- WARNING -- Missing Python Lib (No module named 'cpuinfo'), Quicklook plugin will not display CPU info
2020-10-29 14:06:21,625 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named 'docker')
2020-10-29 14:06:21,626 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
2020-10-29 14:06:21,630 -- WARNING -- Missing Python Lib (No module named 'requests'), Cloud plugin is disabled
2020-10-29 14:06:21,666 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2020-10-29 14:06:21,965 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
2020-10-29 14:06:21,972 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/
```

**Comment by bjornidar** [comment]
Same issue here, found this one [#1110](https://github.com/nicolargo/glances/issues/1110) but can't figure out what to do...

**Comment by nicolargo** [comment]
Hi all,

the nicolargo/glances:dev image only include PsUtil and Bottle.

If you want a full image, please use nicolargo/glances:latest

Nicolas

**Comment by nicolargo** [comment]
@BlackDark can you have a look on this issue and perhaps change the way the nicolargo/glances:dev Docker image is built. Just add pip install -r /glances/optional-requirements.txt should fix it ?

**Comment by montagesepp** [comment]
> 
> 
> Hi all,
> 
> the nicolargo/glances:dev image only include PsUtil and Bottle.
> 
> If you want a full image, please use nicolargo/glances:latest
> 
> Nicolas

Thanks for the replies! I already tried the :latest tag, but it doesn't pull the correct architecture (arm64)

**Comment by BlackDark** [comment]
> @BlackDark can you have a look on this issue and perhaps change the way the nicolargo/glances:dev Docker image is built. Just add pip install -r /glances/optional-requirements.txt should fix it ?

Hey, i will take a look as soon as i can :)

**Comment by BlackDark** [comment]
If i install all the dependencies on every arch the build time explodes and the given runtime for pipeline is not enough.
Not sure how to boost the compilation performance with the docker multi build setup yet.
