### ISSUE TITLE
crash on startup on Illumos when no swap is configured

### ISSUE THREAD

**Issue by DrHyde** [nicolargo/glances#1767]
#### Description

`glances` crashes on startup on Illumos (the free version of Solaris) when there is no swap configured:

```
~$ glances
No swap devices configured
Traceback (most recent call last):
  File "/usr/bin/glances", line 33, in <module>
    sys.exit(load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')())
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/usr/lib/python3.7/site-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_plugin.py", line 925, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_plugin.py", line 935, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_quicklook.py", line 84, in update
    stats['swap'] = psutil.swap_memory().percent
  File "/usr/lib/python3.7/site-packages/psutil/__init__.py", line 1980, in swap_memory
    return _psplatform.swap_memory()
  File "/usr/lib/python3.7/site-packages/psutil/_pssunos.py", line 150, in swap_memory
    raise RuntimeError("'swap -l' failed (retcode=%s)" % p.returncode)
RuntimeError: 'swap -l' failed (retcode=1)
```

#### Versions

* Glances v3.1.5 with PsUtil v5.7.3
* SunOS illumos 5.11 omnios-r151036-4a32ffb911 i86pc i386 i86pc

Also relevant:

```
~$ swap -l
No swap devices configured
~$ echo $?
1
```

#### Logs

```
~$ cat /tmp/glances-david.log
2020-12-11 23:06:35,669 -- INFO -- Start Glances 3.1.5
2020-12-11 23:06:35,670 -- INFO -- CPython 3.7.9 and psutil 5.7.3 detected
2020-12-11 23:06:35,699 -- INFO -- Search glances.conf file in /home/david/.config/glances/glances.conf
2020-12-11 23:06:35,700 -- INFO -- Search glances.conf file in /etc/glances/glances.conf
2020-12-11 23:06:35,715 -- WARNING -- PsUtil can not grab processes io_counters ('Process' object has no attribute 'io_counters')
2020-12-11 23:06:35,763 -- INFO -- Start GlancesStandalone mode
2020-12-11 23:06:35,790 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2020-12-11 23:06:35,796 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2020-12-11 23:06:35,807 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2020-12-11 23:06:35,810 -- WARNING -- Missing Python Lib (No module named 'cpuinfo'), Quicklook plugin will not display CPU info
2020-12-11 23:06:35,861 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named 'docker')
2020-12-11 23:06:35,864 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
2020-12-11 23:06:35,871 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2020-12-11 23:06:35,872 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2020-12-11 23:06:35,915 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2020-12-11 23:06:35,974 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2020-12-11 23:06:35,995 -- ERROR -- Cannot grab battery status module 'psutil' has no attribute 'sensors_battery'.
2020-12-11 23:06:36,000 -- WARNING -- Missing Python Lib (No module named 'requests'), Cloud plugin is disabled
2020-12-11 23:06:36,013 -- WARNING -- Missing Python Lib (No module named 'requests'), Ports plugin is limited to port scanning
```

**Comment by nicolargo** [comment]
Corrected in the DEVELOP branch.

**Comment by DrHyde** [comment]
Thanks

**Comment by DrHyde** [comment]
Looks like there's the same problem in glances_memswap.py:

```
Traceback (most recent call last):
  File "/usr/bin/glances", line 33, in <module>
    sys.exit(load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')())
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/usr/lib/python3.7/site-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_plugin.py", line 925, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_plugin.py", line 935, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_memswap.py", line 69, in update
    sm_stats = psutil.swap_memory()
  File "/usr/lib/python3.7/site-packages/psutil/__init__.py", line 1980, in swap_memory
    return _psplatform.swap_memory()
  File "/usr/lib/python3.7/site-packages/psutil/_pssunos.py", line 150, in swap_memory
    raise RuntimeError("'swap -l' failed (retcode=%s)" % p.returncode)
```

**Comment by nicolargo** [comment]
Last commit should solve the second issue.

Thanks for the report..

**Comment by DrHyde** [comment]
And there's yet another related crash a bit further on:

```
Traceback (most recent call last):
  File "/usr/bin/glances", line 33, in <module>
    sys.exit(load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')())
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/usr/lib/python3.7/site-packages/glances/stats.py", line 238, in update
    self._plugins[p].update_views()
  File "/usr/lib/python3.7/site-packages/glances/plugins/glances_memswap.py", line 140, in update_views
    self.views['used']['decoration'] = self.get_alert_log(self.stats['used'], maximum=self.stats['total'])
KeyError: 'used'
```

Would you like an account on the machine so you can figure it out in situ? Or alternatively, if you can tell me how to run it from a git checkout (I don't know the python toolchain at all) I'll figure it out and create a PR.

**Comment by nicolargo** [comment]
It should be ok now... :)

**Comment by DrHyde** [comment]
The next one is ...

```
...
  File "/usr/lib/python3.7/site-packages/glances/outputs/glances_bars.py", line 74, in percent
    if value <= self.min_value:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```
