### ISSUE TITLE
Failed to start glances with MacBook Air M1

### ISSUE THREAD

**Issue by lexrus** [nicolargo/glances#1769]
#### Description

Failed to start glances. Installed via pip.

#### Versions

Glances v3.1.5 with PsUtil v5.7.3
macOS Big Sur 11.0.1

#### Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/local/lib/python3.9/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python3.9/site-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/usr/local/lib/python3.9/site-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.9/site-packages/glances/plugins/glances_processcount.py", line 73, in update
    glances_processes.update()
  File "/usr/local/lib/python3.9/site-packages/glances/processes.py", line 268, in update
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/local/lib/python3.9/site-packages/glances/processes.py", line 268, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/local/lib/python3.9/site-packages/psutil/__init__.py", line 1437, in process_iter
    yield add(pid)
  File "/usr/local/lib/python3.9/site-packages/psutil/__init__.py", line 1414, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/local/lib/python3.9/site-packages/psutil/__init__.py", line 523, in as_dict
    ret = meth()
  File "/usr/local/lib/python3.9/site-packages/psutil/__init__.py", line 675, in cmdline
    return self._proc.cmdline()
  File "/usr/local/lib/python3.9/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/psutil/_psosx.py", line 429, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
```

**Comment by nicolargo** [comment]
@giampaolo : is PsUtil compatible with M1 processor ?

@lexrus : can you try to run Glances with sudo ?

**Comment by giampaolo** [comment]
Hey @nicolargo. I've seen that error already happening on macOS != M1 so AFAICT it's unrelated. The solution is probably gonna be turning it into `AccessDenied`.

**Comment by lexrus** [comment]
@nicolargo yep, `sudo glances` has the same error.

**Comment by trueb2** [comment]
Here is the same trace with a little more info. I am on an M1 mac mini on BigSur 11.1. My homebrew installation is in /opt/homebrew with glances 3.1.5 installed from brew (poured by glances-3.1.5.arm64_big_sur.bottle.tar.gz)

`glances` and `sudo glances` have identical output.

```
Error while initializing the quicklook plugin (py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/bin/glances", line 33, in <module>
    sys.exit(load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')())
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/lib/python3.9/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/lib/python3.9/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/lib/python3.9/site-packages/glances/standalone.py", line 78, in __init__
    self.stats.update()
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/lib/python3.9/site-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/lib/python3.9/site-packages/glances/plugins/glances_processcount.py", line 73, in update
    glances_processes.update()
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/lib/python3.9/site-packages/glances/processes.py", line 268, in update
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/lib/python3.9/site-packages/glances/processes.py", line 268, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/vendor/lib/python3.9/site-packages/psutil/__init__.py", line 1459, in process_iter
    yield add(pid)
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/vendor/lib/python3.9/site-packages/psutil/__init__.py", line 1436, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/vendor/lib/python3.9/site-packages/psutil/__init__.py", line 542, in as_dict
    ret = meth()
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/vendor/lib/python3.9/site-packages/psutil/__init__.py", line 694, in cmdline
    return self._proc.cmdline()
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/vendor/lib/python3.9/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/glances/3.1.5/libexec/vendor/lib/python3.9/site-packages/psutil/_psosx.py", line 429, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
```

**Comment by giampaolo** [comment]
This was supposed to be fixed in psutil 5.8.0.

**Comment by trueb2** [comment]
Okay, I have 5.7.2. It did not update with the brew install glances.

I see https://github.com/nicolargo/glances/issues/1784 looks related

**Comment by trueb2** [comment]
Indeed `brew install glances` installed and used v5.7.2 of PsUtil, even with a local `pip install psutil` installing 5.8.0.

`brew uninstall glances` and `pip install glances` now kinda works. 

From brew
```
user@host ~ % glances -V
Glances v3.1.5 with PsUtil v5.7.2
```

From pip
```
user@host ~ % glances -V
Glances v3.1.5 with PsUtil v5.8.0
```

It seems like a decent amount of info is missing or incorrect. CPU percent utilization is effectively 0%, memory and cpu usage bars are missing, and the network info on the top banner is missing. These may all be separate issues since htop is also reporting bad CPU percent utilization. https://github.com/htop-dev/htop/issues/368

**Comment by giampaolo** [comment]
Not sure about brew, but psutil 5.8.0 is the first release providing wheels for OSX (hence not requiring XCode), so you should uninstall anything installed via brew and install again via "pip install psutil".

**Comment by trueb2** [comment]
This issue is 24 days old. The 5.8.0 package is 18 days old. I installed via pip and started glances alright, so this issue can probably be closed.

@lexrus can you confirm this issue is resolved for you?

**Comment by lexrus** [comment]
Perfect! Nice work.
Thank you.

<img width="1170" alt="Screen Shot 2021-01-06 at 9 58 28 AM" src="https://user-images.githubusercontent.com/219689/103720493-676aa400-5006-11eb-99e9-06c74ab2f49b.png">
