### ISSUE TITLE
OSError: [WinError 1815] The specified resource language ID cannot be found in the image file

### ISSUE THREAD

**Issue by OrrinGradwell** [nicolargo/glances#1780]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

Install glances and psutil on Windows machine via pip.
no issues during this process.

When attempting to execute 'glances' in powershell, powershell (elevated), CMD or CMD (elvated), then I recieve the below Issue.

>PS C:\Users\redacted> glances -w                                                                                          Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python39-32\Scripts\glances-script.py", line 33, in <module>
    sys.exit(load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')())
  File "c:\users\redacted\appdata\local\programs\python\python39-32\lib\site-packages\glances\__init__.py", line 143, in main
    start(config=config, args=args)
  File "c:\users\redacted\appdata\local\programs\python\python39-32\lib\site-packages\glances\__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "c:\users\redacted\appdata\local\programs\python\python39-32\lib\site-packages\glances\webserver.py", line 41, in __init__
    self.stats.update()
  File "c:\users\redacted\appdata\local\programs\python\python39-32\lib\site-packages\glances\stats.py", line 234, in update
    self._plugins[p].update()
  File "c:\users\redacted\appdata\local\programs\python\python39-32\lib\site-packages\glances\plugins\glances_plugin.py", line 925, in wrapper
    ret = fct(self, *args, **kw)
  File "c:\users\redacted\appdata\local\programs\python\python39-32\lib\site-packages\glances\plugins\glances_plugin.py", line 935, in wrapper
    ret = fct(*args, **kw)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\glances\plugins\glances_load.py", line 92, in update
    load = self._getloadavg()
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\glances\plugins\glances_load.py", line 73, in _getloadavg
    return psutil.getloadavg()
  File "c:\users\redacted\appdata\local\programs\python\python39-32\lib\site-packages\psutil\_pswindows.py", line 338, in getloadavg
    cext.init_loadavg_counter()
OSError: [WinError 1815] The specified resource language ID cannot be found in the image file

#### Versions

* Glances 3.1.5
* psutil 5.7.3
* Windows 10 Enterprise 10.0.18363 Build 18363 (x64)

#### Logs

>2020-12-29 09:42:16,027 -- INFO -- Start Glances 3.1.5
2020-12-29 09:42:16,027 -- INFO -- CPython 3.9.0 and psutil 5.7.3 detected
2020-12-29 09:42:16,031 -- INFO -- Search glances.conf file in C:\Users\orring\AppData\Roaming\glances\glances.conf
2020-12-29 09:42:16,031 -- INFO -- Search glances.conf file in C:\Users\orring\AppData\Roaming\glances\glances.conf
2020-12-29 09:42:16,033 -- WARNING -- PsUtil can not grab processes gids ('Process' object has no attribute 'gids')
2020-12-29 09:42:16,044 -- INFO -- Start GlancesWebServer mode
2020-12-29 09:42:17,771 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled

**Comment by nicolargo** [comment]
Never heard about this...

@giampaolo : Any idea ?

**Comment by giampaolo** [comment]
Looks like a bug, but can't tell where it originated from so I committed https://github.com/giampaolo/psutil/commit/51eb1dae7bf96dcc7dae51641d5770fd0d99d0ac.

**Comment by Motik68** [comment]
Just installed glances on a Windows machine and got the same error. Had installed on another windows machine last night without any error. psutil is not installed on either system.

FWIW, as the error message is about a "resource language ID", both my Windows machines use the French language.
