### ISSUE TITLE
Issue with exporting to influxdb

### ISSUE THREAD

**Issue by roborick** [nicolargo/glances#1788]
when running the command glances --export influxdb

I get this error:
Traceback (most recent call last):
File "/usr/local/bin/glances", line 11, in
load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')()
File "/usr/local/lib/python2.7/dist-packages/glances/init.py", line 143, in main
start(config=config, args=args)
File "/usr/local/lib/python2.7/dist-packages/glances/init.py", line 108, in start
mode = GlancesMode(config=config, args=args)
File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 51, in init
self.stats = GlancesStats(config=config, args=args)
File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 48, in init
self.load_modules(self.args)
File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 103, in load_modules
self.load_exports(args=args)
File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 178, in load_exports
export_module = import(self._exports_all[export_name])
File "/usr/local/lib/python2.7/dist-packages/glances/exports/glances_influxdb.py", line 27, in
from influxdb import InfluxDBClient
ImportError: No module named influxdb

I do have influxdb installed as I'm using varken

**Comment by nicolargo** [comment]
You had to install the influxdb client lib for Python.
