### ISSUE TITLE
setupterm: could not find terminal via SSH

### ISSUE THREAD

**Issue by alexkutsan** [nicolargo/glances#1790]
**Describe the bug**
Unable to start glances via ssh

**To Reproduce**

1. `ssh barrier@192.168.1.5 -C "nix-shell -p glances --run glances"`

```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/barrier/.local/lib/python3.7/site-packages/glances/__main__.py", line 29, in <module>
    glances.main()
  File "/home/barrier/.local/lib/python3.7/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/home/barrier/.local/lib/python3.7/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/home/barrier/.local/lib/python3.7/site-packages/glances/standalone.py", line 98, in __init__
    self.screen = GlancesCursesStandalone(config=config, args=args)
  File "/home/barrier/.local/lib/python3.7/site-packages/glances/outputs/glances_curses.py", line 123, in __init__
    self.screen = curses.initscr()
  File "/usr/lib/python3.7/curses/__init__.py", line 30, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal
```

**Expected behavior**
Glances UI

**Screenshots**

**Desktop (please complete the following information):**
 - OS: raspberrian
 - Glances v3.1.5 with PsUtil v5.5.1
 - Glances logs file 
[glances.log](https://github.com/nicolargo/glances/files/5789822/glances.log)

**Comment by alexkutsan** [comment]
Not a glances issue just use : `ssh -t barrier@192.168.1.5 -C "nix-shell -p glances --run glances"`
