### ISSUE TITLE
Can't launch 3.1.6 on a Raspberry Pi 4

### ISSUE THREAD

**Issue by screendriver** [nicolargo/glances#1805]
**Describe the bug**

With version `3.1.6` and `3.1.6.1` I'm getting following exception:

```sh
❯ glances
You are using Glances version 3.1.6, however version 3.1.6.1 is available.
You should consider upgrading using: pip install --upgrade glances
Exception ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/home/pi/.local/lib/python3.7/site-packages/glances/__init__.py", line 70, in __signal_handler
    end()
  File "/home/pi/.local/lib/python3.7/site-packages/glances/__init__.py", line 85, in end
    sys.exit(0)
SystemExit: 0
```

When I downgrade to `3.1.5` everything is working as expected.

**To Reproduce**

1. Try to start Glances `3.1.6` or `3.1.6.1` on a Raspberry Pi 4

**Expected behavior**

Should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Glances Version: Glances v3.1.5 with PsUtil v5.7.2 (which is working)
 - Glances logs file

```
2021-01-30 12:42:28,960 -- INFO -- CPython 3.7.3 and psutil 5.7.2 detected
2021-01-30 12:42:45,696 -- INFO -- Start Glances 3.1.6.1
2021-01-30 12:42:45,697 -- INFO -- CPython 3.7.3 and psutil 5.7.2 detected
2021-01-30 12:42:45,706 -- INFO -- Search glances.conf file in /home/pi/.config/glances/glances.conf
2021-01-30 12:42:45,707 -- INFO -- Read configuration file '/home/pi/.config/glances/glances.conf'
2021-01-30 12:42:45,725 -- INFO -- Start GlancesStandalone mode
2021-01-30 12:42:45,839 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2021-01-30 12:42:46,408 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2021-01-30 12:42:46,428 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2021-01-30 12:42:48,711 -- INFO -- Glances stopped (keypressed: CTRL-C)
```

**Additional context**

My glances configuration:

```sh
❯ cat ~/.config/glances/glances.conf 
[global]
check_update=True

[network]
hide=br-*,lo,veth*

[diskio]
hide=loop*
```

**Comment by jdenoy** [comment]
Hello,

same problem here on Arch Linux with version 3.1.6 and above
python = 3.9.1
psutil = 5.8.0

**Comment by nicolargo** [comment]
Can you please try to start Glances with the following options:

```
glances --disable-check-update
```

What's the result ?

**Comment by screendriver** [comment]
Oh, it's working again with `3.1.6.2` 🎉
