### ISSUE TITLE
Package influxdb is not installed in standard docker image (nicolargo/glances)

### ISSUE THREAD

**Issue by number4jazz** [nicolargo/glances#1808]
**Describe the bug**
The docker image of Glances does not contain the Python package "influxdb". So it fails to run when configured to connect to an influxdb.

**To Reproduce**
1. Start Glances with the followings options:

docker run (...) --env "GLANCES_OPT=--quiet --export influxdb" nicolargo/glances

2. run the container, it will turn into a restart loop
3. docker logs $container_id

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/glances/glances/__main__.py", line 29, in <module>
    glances.main()
  File "/glances/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/glances/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/glances/glances/standalone.py", line 49, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/glances/glances/stats.py", line 47, in __init__
    self.load_modules(self.args)
  File "/glances/glances/stats.py", line 101, in load_modules
    self.load_exports(args=args)
  File "/glances/glances/stats.py", line 167, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/glances/glances/exports/glances_influxdb.py", line 27, in <module>
    from influxdb import InfluxDBClient
**ModuleNotFoundError: No module named 'influxdb'**

**Expected behavior**

**Screenshots**
See logfile copy/paste.

**Desktop (please complete the following information):**

Not really relevant. I think the issue is clear.

**Additional context**

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/1605
