### ISSUE TITLE
ModuleNotFoundError: No module named 'paho'

### ISSUE THREAD

**Issue by Anian-igor** [nicolargo/glances#1811]
**Describe the bug**
Cannot connect to mqtt from docker image

**To Reproduce**
Docker-compose install from image: nicolargo/glances:latest

**Expected behavior**
Connect to mqtt

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Glances Version 3.1.6.1
 - Glances logs:
 ```
glances-mqtt    | Traceback (most recent call last):
glances-mqtt    |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
glances-mqtt    |     return _run_code(code, main_globals, None,
glances-mqtt    |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
glances-mqtt    |     exec(code, run_globals)
glances-mqtt    |   File "/usr/local/lib/python3.9/site-packages/glances/__main__.py", line 29, in <module>
glances-mqtt    |     glances.main()
glances-mqtt    |   File "/usr/local/lib/python3.9/site-packages/glances/__init__.py", line 145, in main
glances-mqtt    |     start(config=config, args=args)
glances-mqtt    |   File "/usr/local/lib/python3.9/site-packages/glances/__init__.py", line 110, in start
glances-mqtt    |     mode = GlancesMode(config=config, args=args)
glances-mqtt    |   File "/usr/local/lib/python3.9/site-packages/glances/standalone.py", line 51, in __init__
glances-mqtt    |     self.stats = GlancesStats(config=config, args=args)
glances-mqtt    |   File "/usr/local/lib/python3.9/site-packages/glances/stats.py", line 48, in __init__
glances-mqtt    |     self.load_modules(self.args)
glances-mqtt    |   File "/usr/local/lib/python3.9/site-packages/glances/stats.py", line 103, in load_modules
glances-mqtt    |     self.load_exports(args=args)
glances-mqtt    |   File "/usr/local/lib/python3.9/site-packages/glances/stats.py", line 178, in load_exports
glances-mqtt    |     export_module = __import__(self._exports_all[export_name])
glances-mqtt    |   File "/usr/local/lib/python3.9/site-packages/glances/exports/glances_mqtt.py", line 30, in <module>
glances-mqtt    |     import paho.mqtt.client as paho
glances-mqtt    | ModuleNotFoundError: No module named 'paho'

```

**Comment by nicolargo** [comment]
For an an image with full plugins dependancies, please use **nicolargo/glances:dev** instead of nicolargo/glances:latest.

**Comment by Anian-igor** [comment]
Works, thanks
