### ISSUE TITLE
Errore in MacOS Catalina in client mode

### ISSUE THREAD

**Issue by terna** [nicolargo/glances#1837]
glances -c 192.168.1.3
produces:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/glances", line 33, in <module>
    sys.exit(load_entry_point('Glances==3.1.6.2', 'console_scripts', 'glances')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glances/__init__.py", line 145, in main
    start(config=config, args=args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glances/__init__.py", line 114, in start
    mode.serve_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glances/client.py", line 238, in serve_forever
    if not self.login():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glances/client.py", line 162, in login
    if not self._login_glances():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glances/client.py", line 130, in _login_glances
    self.stats.set_plugins(json.loads(self.client.getAllPlugins()))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glances/stats_client.py", line 59, in set_plugins
    self._plugins[item] = plugin.Plugin(args=self.args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glances/plugins/glances_diskio.py", line 56, in __init__
    self.hide_zero = config.get_bool_value(
AttributeError: 'NoneType' object has no attribute 'get_bool_value'

**Comment by nicolargo** [comment]
What is your server version ?

**Comment by terna** [comment]
Glances v3.1.6.2 with PsUtil v5.8.0

Il 03/04/21 18:04, Nicolas Hennion ha scritto:

**Comment by terna** [comment]
What kind of info?
OS is Catalina, Glances is 3.1.6.2 and Python 3.9.2
The computers are in my LAN

**Comment by nicolargo** [comment]
@terna sorry for the delay.

It should be corrected in Glances 3.1.7.

Any chance to test it on your side ?
