### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'current

### ISSUE THREAD

**Issue by mnshsnghl** [nicolargo/glances#1875]
As soon as glances is started, I see below stack -
$ glances 
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.2.0b0', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/Glances-3.2.0b0-py3.6.egg/glances/__init__.py", line 149, in main
    start(config=core.get_config(), args= core.get_args())
  File "/usr/lib/python3.6/site-packages/Glances-3.2.0b0-py3.6.egg/glances/__init__.py", line 109, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/Glances-3.2.0b0-py3.6.egg/glances/standalone.py", line 79, in __init__
    self.stats.update()
  File "/usr/lib/python3.6/site-packages/Glances-3.2.0b0-py3.6.egg/glances/stats.py", line 230, in update
    self._plugins[p].update()
  File "/usr/lib/python3.6/site-packages/Glances-3.2.0b0-py3.6.egg/glances/plugins/glances_plugin.py", line 1037, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python3.6/site-packages/Glances-3.2.0b0-py3.6.egg/glances/plugins/glances_plugin.py", line 1052, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3.6/site-packages/Glances-3.2.0b0-py3.6.egg/glances/plugins/glances_quicklook.py", line 83, in update
    stats['cpu_name'] = cpu_percent.get_info()['cpu_name']
  File "/usr/lib/python3.6/site-packages/Glances-3.2.0b0-py3.6.egg/glances/cpu_percent.py", line 69, in get_info
    self.cpu_info['cpu_hz_current'] = cpu_freq.current
AttributeError: 'NoneType' object has no attribute 'current'

# glances -V
Glances v3.2.0b0 with PsUtil v5.4.8
Log file: /tmp/glances-root.log

**Comment by nicolargo** [comment]
Should be correct in the beta 2.

@mnshsnghl  Please can you test ?
