### ISSUE TITLE
DSM 6 docker error crash /sys/class/power_supply

### ISSUE THREAD

**Issue by Salvora** [nicolargo/glances#1921]
**Describe the bug**
Synology docker installation method with latest tag.
My glances container got updated and it just doesn't start anymore with error.

`Error while initializing the sensors plugin ([Errno 2] No such file or directory: '/sys/class/power_supply')`

**To Reproduce**
1. Update glances to the latest in synology docker
2. wait for it

**Desktop (please complete the following information):**
 - OS: DSM DSM 6.2.4-25556
 - Glances Version:
 Glances v3.2.3 with PsUtil v5.8.0
Log file: /tmp/glances-root.log
 - Glances logs file [output of tail -10 <glances logs file>]

```
2021-08-15 22:44:48,063 -- INFO -- Start Glances 3.2.3
2021-08-15 22:44:48,063 -- INFO -- CPython 3.9.6 and psutil 5.8.0 detected
2021-08-15 22:44:48,080 -- INFO -- Read configuration file '/glances/conf/glances.conf'
2021-08-15 22:44:48,162 -- INFO -- Start GlancesWebServer mode
2021-08-15 22:44:49,426 -- ERROR -- Cannot grab battery status [Errno 2] No such file or directory: '/sys/class/power_supply'.
2021-08-15 22:44:49,438 -- CRITICAL -- Error while initializing the sensors plugin ([Errno 2] No such file or directory: '/sys/class/power_supply')
2021-08-15 22:44:49,441 -- ERROR -- Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/glances/stats.py", line 117, in _load_plugin
    self._plugins[name] = plugin.Plugin(args=args, config=config)
  File "/usr/local/lib/python3.9/site-packages/glances/plugins/glances_sensors.py", line 66, in __init__
    self.batpercent_plugin = BatPercentPlugin(args=args, config=config)
  File "/usr/local/lib/python3.9/site-packages/glances/plugins/sensors/glances_batpercent.py", line 59, in __init__
    self.glancesgrabbat = GlancesGrabBat()
  File "/usr/local/lib/python3.9/site-packages/glances/plugins/sensors/glances_batpercent.py", line 96, in __init__
    self.bat = batinfo.batteries()
  File "/usr/local/lib/python3.9/site-packages/batinfo/battery.py", line 104, in __init__
    self.update()
  File "/usr/local/lib/python3.9/site-packages/batinfo/battery.py", line 113, in update
    for dirname in os.listdir(self.bat_root_path):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply'

2021-08-15 22:44:49,494 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2021-08-15 22:44:50,188 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
2021-08-15 22:44:50,195 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/
2021-08-15 22:48:01,735 -- INFO -- Start Glances 3.2.3
2021-08-15 22:48:01,735 -- INFO -- CPython 3.9.6 and psutil 5.8.0 detected
```
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)
```
Error while initializing the sensors plugin ([Errno 2] No such file or directory: '/sys/class/power_supply')
=========================================================
Glances version 3.2.3 with PsUtil 5.8.0
=========================================================
alert         [OK]    0.00005s []
amps          [OK]    0.00002s []
cloud         [OK]    0.00002s {}
connections   [OK]    0.00002s {'LISTEN': 2, 'ESTABLISHED': 2, 'SYN_SENT': 1, 'SYN_RECV': 0, 'initiated': 1, 'terminated': 1, 'nf_conntrack_
core          [OK]    0.00120s {'phys': 4, 'log': 4}
cpu           [OK]    0.00002s {'total': 45.5, 'user': 33.6, 'nice': 0.0, 'system': 10.5, 'idle': 53.8, 'iowait': 0.7, 'irq': 0.0, 'softirq'
diskio        [OK]    0.00002s key=disk_name [{'time_since_update': 1, 'disk_name': 'sda', 'read_count': 0, 'write_count': 0, 'read_bytes': 
docker        [OK]    0.00057s key=name [{'key': 'name', 'name': 'LAXSS-Glances', 'Names': ['LAXSS-Glances'], 'Id': '3d574deb32cccb7defd6489
folders       [OK]    0.00003s []
fs            [OK]    0.00002s key=mnt_point [{'device_name': '/dev/vg1/volume_1', 'fs_type': 'btrfs', 'mnt_point': '/', 'size': 95960266547
gpu           [OK]    0.00002s []
help          [OK]    0.00001s None
ip            [OK]    0.00002s {'address': '172.19.0.2', 'mask': '255.255.0.0', 'mask_cidr': 16, 'gateway': '172.19.0.1', 'public_address': 
irq           [OK]    0.00002s key=irq_line [{'irq_line': '0_timer', 'irq_rate': 0, 'key': 'irq_line', 'time_since_update': 1}, {'irq_line':
load          [OK]    0.00002s {'min1': 1.06, 'min5': 1.07, 'min15': 0.75, 'cpucore': 4}
mem           [OK]    0.00002s {'total': 16624627712, 'available': 15029374976, 'percent': 9.6, 'used': 1595252736, 'free': 15029374976, 'ac
memswap       [OK]    0.00001s {'total': 12121452544, 'used': 0, 'free': 12121452544, 'percent': 0.0, 'sin': 0, 'sout': 0, 'time_since_updat
network       [OK]    0.00097s key=interface_name [{'interface_name': 'sit0', 'alias': None, 'time_since_update': 0.4114389419555664, 'cumul
now           [OK]    0.00003s 2021-08-15 22:50:21 +03
percpu        [OK]    0.00002s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 66.7, 'user': 54.8, 'system': 11.9, 'idle': 3
ports         [OK]    0.00002s []
processcount  [OK]    0.00002s {'total': 510, 'running': 2, 'sleeping': 504, 'thread': 994, 'pid_max': 0}
processlist   [OK]    0.00008s key=pid [{'memory_info': pmem(rss=255578112, vms=3121209344, shared=107712512, text=4096, lib=0, data=2496573
psutilversion [OK]    0.00003s (5, 8, 0)
quicklook     [OK]    0.00002s {'cpu': 45.5, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 66.7, 'user': 54.8, 'system': 11.9, 
raid          [OK]    0.00002s {'md2': {'status': 'active', 'type': 'raid1', 'components': {'sda5': '0', 'sdb5': '1'}, 'available': '2', 'us
smart         [OK]    0.00001s []
system        [OK]    0.00002s {'os_name': 'Linux', 'hostname': '3d574deb32cc', 'platform': '64bit', 'linux_distro': 'Debian GNU/Linux 10', 
uptime        [OK]    0.00002s {'seconds': 20696}
wifi          [OK]    0.00003s []
```

**Comment by nicolargo** [comment]
The last Docker version includes Batinfo (https://github.com/nicolargo/batinfo). The error message comes from this lib.

This is strange because this error is not critical. No the sensor plugin is not loaded but Glances should work...

A a work arround try to downgrade the Docker images to the version 3.2.1 or 3.2.2.

**Comment by Salvora** [comment]
I did downgrade  it to 3.2.1 and it works.

**Comment by nicolargo** [comment]
I just commit a patch on the develop branch in order to catch the error message coming from batinfo and disable the battery plugin if an error occurs.

@Salvora can you please test the dev (or alpine-dev) Docker image on your Synology ? Additional question, where do you find the procedure to install Glances on DSM device ?

**Comment by Salvora** [comment]
> 
> 
> I just commit a patch on the develop branch in order to catch the error message coming from batinfo and disable the battery plugin if an error occurs.
> 
> @Salvora can you please test the dev (or alpine-dev) Docker image on your Synology ? Additional question, where do you find the procedure to install Glances on DSM device ?

I tested the dev tag. It runs without a problem.
I installed glances with docker-compose.

```
version: "2.1"
services:
  app:
    image: nicolargo/glances:dev
    container_name: LAXDISKSTATION-Glances
    restart: always
    privileged: true
    pid: "host"
    environment:
      - TZ=Europe/Istanbul
      - "GLANCES_OPT= -w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock/:ro
      - /volume1/docker/Glances/conf:/glances/conf
    ports:
      - 61208:61208
      - 61209:61209
```

**Comment by nicolargo** [comment]
@Salvora Glances version 3.2.3.1 is released and correct this issue.

**Comment by Salvora** [comment]
I switched to latest-full image and got the same error in my logs. Though, it didn't crash this time.
