### ISSUE TITLE
Failure to start on Apple M1 Max

### ISSUE THREAD

**Issue by epelc** [nicolargo/glances#1939]
**Describe the bug**
Glances fails to start on a new m1 max macbook pro with macOS Monterey 12.0.1

Possibly related to #1827

**To Reproduce**

- Install via `pip install glances`
- Run glances

# Error on start

```
> glances
Traceback (most recent call last):
  File "/opt/homebrew/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/glances/__init__.py", line 149, in main
    start(config=core.get_config(), args= core.get_args())
  File "/opt/homebrew/lib/python3.9/site-packages/glances/__init__.py", line 109, in start
    mode = GlancesMode(config=config, args=args)
  File "/opt/homebrew/lib/python3.9/site-packages/glances/standalone.py", line 80, in __init__
    self.stats.update()
  File "/opt/homebrew/lib/python3.9/site-packages/glances/stats.py", line 230, in update
    self._plugins[p].update()
  File "/opt/homebrew/lib/python3.9/site-packages/glances/plugins/glances_plugin.py", line 1051, in wrapper
    ret = fct(self, *args, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/glances/plugins/glances_plugin.py", line 1066, in wrapper
    ret = fct(*args, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/glances/plugins/glances_quicklook.py", line 83, in update
    cpu_info = cpu_percent.get_info()
  File "/opt/homebrew/lib/python3.9/site-packages/glances/cpu_percent.py", line 68, in get_info
    cpu_freq = psutil.cpu_freq()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))

```

**Expected behavior**
Glances runs

**Desktop (please complete the following information):**
 - OS: [e.g. GNU/Linux Ubuntu 20.04] macOS montery 12.0.1
 - Glances Version [output of glances -V] Glances v3.2.3.1 with PsUtil v5.8.0
 - Glances logs file [output of tail -10 <glances logs file>]

```
2021-10-27 11:19:21,667 -- INFO -- Glances stopped (keypressed: CTRL-C)
2021-10-27 11:19:41,200 -- WARNING -- PsUtil can not grab processes io_counters ('Process' object has no attribute 'io_counters')
2021-10-27 11:19:41,201 -- INFO -- Start Glances 3.2.3.1
2021-10-27 11:19:41,201 -- INFO -- CPython 3.9.7 and psutil 5.8.0 detected
2021-10-27 11:19:41,206 -- INFO -- Start GlancesStandalone mode
2021-10-27 11:19:41,237 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2021-10-27 11:19:41,294 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2021-10-27 11:19:41,295 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2021-10-27 11:19:41,299 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2021-10-27 11:19:41,300 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2021-10-27 11:19:41,302 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2021-10-27 11:19:41,303 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2021-10-27 11:21:29,310 -- INFO -- Glances stopped (keypressed: CTRL-C)
2021-10-27 11:21:31,526 -- WARNING -- PsUtil can not grab processes io_counters ('Process' object has no attribute 'io_counters')
2021-10-27 11:21:31,526 -- INFO -- Start Glances 3.2.3.1
2021-10-27 11:21:31,527 -- INFO -- CPython 3.9.7 and psutil 5.8.0 detected
```

 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

```
glances --issue
Traceback (most recent call last):
  File "/opt/homebrew/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/glances/__init__.py", line 149, in main
    start(config=core.get_config(), args= core.get_args())
  File "/opt/homebrew/lib/python3.9/site-packages/glances/__init__.py", line 109, in start
    mode = GlancesMode(config=config, args=args)
  File "/opt/homebrew/lib/python3.9/site-packages/glances/standalone.py", line 80, in __init__
    self.stats.update()
  File "/opt/homebrew/lib/python3.9/site-packages/glances/stats.py", line 230, in update
    self._plugins[p].update()
  File "/opt/homebrew/lib/python3.9/site-packages/glances/plugins/glances_plugin.py", line 1051, in wrapper
    ret = fct(self, *args, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/glances/plugins/glances_plugin.py", line 1066, in wrapper
    ret = fct(*args, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/glances/plugins/glances_quicklook.py", line 83, in update
    cpu_info = cpu_percent.get_info()
  File "/opt/homebrew/lib/python3.9/site-packages/glances/cpu_percent.py", line 68, in get_info
    cpu_freq = psutil.cpu_freq()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
```

**Additional context**
Python was updated via `brew install python` to get 3.9.7

**Comment by nicolargo** [comment]
I just patch the Glances function to except the error.

@epelc / @ericshape  You can test the develop branch using:

```
pip install -i https://test.pypi.org/simple/ Glances
```

Let me know, i am not a happy M1 owner... :(

Under the wood, it is a PSUtil issue ==> https://github.com/giampaolo/psutil/pull/1895 
It will be corrected in PSUtil version 5.8.1 ==> https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#581-in-development

So for the moment, the M1 CPU information will not be displayed in Glances.
