### ISSUE TITLE
Update WebUI dependencies (Security Issues)

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1942]
The dependabot has detected some issues:

https://github.com/nicolargo/glances/security/dependabot

The WebUI should be updated.

**Comment by nicolargo** [comment]
cc: @notFloran / @spike008t

**Comment by nicolargo** [comment]
What have been done:

1) Creation of a dedicated branch: https://github.com/nicolargo/glances/tree/issue1942
2) Run the make webui-force command (will force an  npm audit fix --force)
3) Update the https://github.com/nicolargo/glances/blob/issue1942/glances/outputs/static/webpack.config.js

But unfortunately, i have the following error:

```
...
ERROR in glances.map.js
glances.map.js from Terser plugin
Unexpected token: punc (:) [glances.map.js:1,10]
    at js_error (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:1288:9)
    at semicolon (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:1326:56)
    at simple_statement (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:1583:73)
    at statement (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:1369:47)
    at _embed_tokens_wrapper (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:1339:26)
    at block_ (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:2172:20)
    at statement (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/terser/dist/bundle.min.js:1403:29)

webpack 5.61.0 compiled with 1 error and 1 warning in 10505 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `webpack --bail --progress --profile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
make: *** [Makefile:45: webui-force] Error 1
```

Complete log here: https://pastebin.com/URFaWvSB

@notFloran : Any idea ?

**Comment by notFloran** [comment]
Hi !

I had started doing all the updates a few weeks ago, I took some time this morning to finish it. 
I just opened a PR for it: https://github.com/nicolargo/glances/pull/1948

The "issue1942" branch is in error because webpack has been updated but not all its plugins/loaders.

**Comment by nicolargo** [comment]
Merged into develop.

Thanks to @notFloran  !!!
