### ISSUE TITLE
Version locking of psutil module allows for version of psutil that is too old to statisfy application dependencies

### ISSUE THREAD

**Issue by markandrewj** [nicolargo/glances#1952]
Hello,

We recently tried upgrading Glances, afterwards Glances was failing to run because the version of psutil installed was too old to satisfy the application requirements.

```
$ /sysadmin/arch/linux-x86_64/bin/glances

Traceback (most recent call last):
File "/sysadmin/arch/linux-x86_64/bin/glances", line 11, in <module>
sys.exit(main())
File "/sysadmin/arch/linux-x86_64/lib/python2.7/site-packages/glances/__init__.py", line 149, in main
start(config=core.get_config(), args= core.get_args())
File "/sysadmin/arch/linux-x86_64/lib/python2.7/site-packages/glances/__init__.py", line 109, in start
mode = GlancesMode(config=config, args=args)
File "/sysadmin/arch/linux-x86_64/lib/python2.7/site-packages/glances/standalone.py", line 80, in __init__
self.stats.update()
File "/sysadmin/arch/linux-x86_64/lib/python2.7/site-packages/glances/stats.py", line 230, in update
self._plugins[p].update()
File "/sysadmin/arch/linux-x86_64/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 1051, in wrapper
ret = fct(self, *args, **kw)
File "/sysadmin/arch/linux-x86_64/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 1066, in wrapper
ret = fct(*args, **kw)
File "/sysadmin/arch/linux-x86_64/lib/python2.7/site-packages/glances/plugins/glances_quicklook.py", line 85, in update
stats['cpu_hz_current'] = self._mhz_to_hz(cpu_info['cpu_hz_current']) if cpu_info['cpu_hz_current'] is not None else None
KeyError: 'cpu_hz_current'
```

It looks like setup.py is allowing versions of psutil that do not contain the newest methods required for Glances to work.

```
$ sudo /sysadmin/arch/linux-x86_64/bin/pip2 install --trusted-host xxx.corp.ads --no-index --find-links=https://xxx.corp.ads/pub/xxx/glances/ glances
Looking in links: https://satellite.corp.ads/pub/xxx/glances/
Requirement already satisfied: glances in /sysadmin/arch/linux-x86_64/lib/python2.7/site-packages (3.2.3.1)
Requirement already satisfied: defusedxml in /sysadmin/arch/linux-x86_64/lib/python2.7/site-packages (from glances) (0.7.1)
Requirement already satisfied: future in /sysadmin/arch/linux-x86_64/lib/python2.7/site-packages (from glances) (0.18.2)
Requirement already satisfied: psutil>=5.3.0 in /sysadmin/arch/linux-x86_64/lib/python2.7/site-packages (from glances) (5.4.6)
```

I think that the minimum allowed version of psutil in setup.py should be bumped to a newer version.

```
def get_install_requires():
    requires = ['psutil>=5.3.0', 'defusedxml', 'future']
    if sys.platform.startswith('win'):
        requires.append('bottle')
        requires.append('requests')
```
Issue references #1941, user opened issue, but resolved issue by hand and closed the issue afterwards.

**Comment by nicolargo** [comment]
What is your Glances version please @markandrewj  ?

**Comment by nicolargo** [comment]
Should be corrected in this patch https://github.com/nicolargo/glances/commit/3a96a9c607795a05e9e0b4d8097536a70be2aa9f

**Comment by markandrewj** [comment]
Hey @nicolargo sorry for the slow response, we went from Glances v2.11.1 with psutil v5.6.7, to Glances 3.2.3.1 with psutil 5.8.0. We removed psutil completely, and then reinstalled which pulled in the latest version with the methods Glances required. Thanks for making a patch, I would have submitted one but there is a firewall stopping me from do so at the moment.
