### ISSUE TITLE
Missing dependency when using pip install

### ISSUE THREAD

**Issue by inks007** [nicolargo/glances#1955]
**Describe the bug**
'pip install glances' does not install the 'packaging' dependency.

**To Reproduce**
1. pip install glances
2. glances (fail)
3. pip install packaging
4. glances (works)

**Expected behavior**
Automatic installation of 'packaging' as a dependency.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS on RasPi4
 - PIP: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Additional context**
See console output below.
```
# pip install glances
Collecting glances
  Downloading Glances-3.2.4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 5.3 MB/s
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 7.2 MB/s
Collecting psutil>=5.3.0
  Downloading psutil-5.8.0.tar.gz (470 kB)
     |████████████████████████████████| 470 kB 7.4 MB/s
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Building wheels for collected packages: future, psutil
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=c9498895906b753a3e30d412bc73bab9c823a67355a51b4411f90e39887935c4
  Stored in directory: /root/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for psutil (setup.py) ... done
  Created wheel for psutil: filename=psutil-5.8.0-cp38-cp38-linux_aarch64.whl size=301363 sha256=cd5259190e50eedf1c02153f18048fb3a8f49e5375913d0c83e688b07fb277b4
  Stored in directory: /root/.cache/pip/wheels/a9/92/74/7694cd5d3f10ea335ef507c10e877b2150de20975a986782b9
Successfully built future psutil
Installing collected packages: future, psutil, defusedxml, glances
Successfully installed defusedxml-0.7.1 future-0.18.2 glances-3.2.4 psutil-5.8.0
# glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 150, in main
    start(config=core.get_config(), args= core.get_args())
  File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 96, in start
    from glances.standalone import GlancesStandalone as GlancesMode
  File "/usr/local/lib/python3.8/dist-packages/glances/standalone.py", line 34, in <module>
    from glances.outdated import Outdated
  File "/usr/local/lib/python3.8/dist-packages/glances/outdated.py", line 23, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
# pip install packaging
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 803 kB/s
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 959 kB/s
Installing collected packages: pyparsing, packaging
Successfully installed packaging-21.3 pyparsing-3.0.6
# glances
```

**Comment by nicolargo** [comment]
Thanks !

Corrected in Glances 3.2.4.1.
