### ISSUE TITLE
OSError: [WinError 87] on Windows 10

### ISSUE THREAD

**Issue by Charrey** [nicolargo/glances#1965]
#### Description

When installing freshly from Windows 10 and running glances, a Python error message is shown.

To reproduce:
(run PowerShell as administrator)
> pip install glances
> pip install windows-curses
> glances

```
PS C:\Windows\system32> pip install glances
Collecting glances
  Using cached Glances-3.2.4.2-py3-none-any.whl (1.6 MB)
Requirement already satisfied: future in c:\python\python310\lib\site-packages (from glances) (0.18.2)
Requirement already satisfied: psutil>=5.3.0 in c:\python\python310\lib\site-packages (from glances) (5.8.0)
Requirement already satisfied: packaging in c:\python\python310\lib\site-packages (from glances) (21.3)
Requirement already satisfied: defusedxml in c:\python\python310\lib\site-packages (from glances) (0.7.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\python\python310\lib\site-packages (from packaging->glances) (3.0.6)
Installing collected packages: glances
Successfully installed glances-3.2.4.2
PS C:\Windows\system32> pip install windows-curses
Collecting windows-curses
  Using cached windows_curses-2.3.0-cp310-cp310-win_amd64.whl (88 kB)
Installing collected packages: windows-curses
Successfully installed windows-curses-2.3.0
PS C:\Windows\system32> glances
Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\glances.exe\__main__.py", line 7, in <module>
  File "C:\Python\Python310\lib\site-packages\glances\__init__.py", line 150, in main
    start(config=core.get_config(), args=core.get_args())
  File "C:\Python\Python310\lib\site-packages\glances\__init__.py", line 109, in start
    mode = GlancesMode(config=config, args=args)
  File "C:\Python\Python310\lib\site-packages\glances\standalone.py", line 80, in __init__
    self.stats.update()
  File "C:\Python\Python310\lib\site-packages\glances\stats.py", line 230, in update
    self._plugins[p].update()
  File "C:\Python\Python310\lib\site-packages\glances\plugins\glances_plugin.py", line 1158, in wrapper
    ret = fct(self, *args, **kw)
  File "C:\Python\Python310\lib\site-packages\glances\plugins\glances_plugin.py", line 1173, in wrapper
    ret = fct(*args, **kw)
  File "C:\Python\Python310\Lib\site-packages\glances\plugins\glances_load.py", line 111, in update
    load = self._getloadavg()
  File "C:\Python\Python310\Lib\site-packages\glances\plugins\glances_load.py", line 92, in _getloadavg
    return psutil.getloadavg()
  File "C:\Python\Python310\lib\site-packages\psutil\_pswindows.py", line 338, in getloadavg
    cext.init_loadavg_counter()
OSError: [WinError 87] The parameter is incorrect
```

#### Versions

* Glances & psutil (glances -V): Glances v3.2.4.2 with PsUtil v5.8.0
* Operating System (lsb_release -a): Windows 10 Home 21H2

#### Logs
https://pastebin.com/tw9Lvgy1

**Comment by nicolargo** [comment]
@Charrey: the error came from the PSUtil lib.

Please can you test:

```
./venv/bin/python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.getloadavg()
(0.62, 0.87, 0.72)
>>> exit()
```

**Comment by Charrey** [comment]
> @Charrey: the error came from the PSUtil lib.
> 
> Please can you test:
> 
> ```
> ./venv/bin/python
> Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import psutil
> >>> psutil.getloadavg()
> (0.62, 0.87, 0.72)
> >>> exit()
> ```

You're right.

```
PS C:\Windows\system32> python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.getloadavg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python310\lib\site-packages\psutil\_pswindows.py", line 338, in getloadavg
    cext.init_loadavg_counter()
OSError: [WinError 87] The parameter is incorrect
>>> exit()
PS C:\Windows\system32>
```
