### ISSUE TITLE
Display uptime of a docker container

### ISSUE THREAD

**Issue by AgingOrange** [nicolargo/glances#2004]
It would be nice to see uptime on a docker container to see just that, or notice that one has failed and has been restarted, if a restart was successful, etc.

Under the status column could be a good place, like the output of `docker ps`.

**Comment by nicolargo** [comment]
Note dor dev: can be done through the ctnr.attrs['State']['StartedAt'] (source: https://github.com/docker/docker-py/issues/1708#issuecomment-322271207)

**Comment by nicolargo** [comment]
Available in the develop branch.

@AgingOrange Please can you test on your system ?

**Comment by AgingOrange** [comment]
I tried `pip install --user -i https://test.pypi.org/simple/ Glances` (both with and without sudo, I have it installed for all users) and I don't think it installed it.
```
❯ sudo pip install --user -i https://test.pypi.org/simple/ Glances             
[sudo] password for charles: 
Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: Glances in /usr/local/lib/python3.8/dist-packages (3.2.4.2)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from Glances) (0.18.2)
Requirement already satisfied: psutil>=5.3.0 in /usr/local/lib/python3.8/dist-packages (from Glances) (5.9.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.8/dist-packages (from Glances) (0.7.1)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from Glances) (20.3)
```
What's the correct procedure to do this?

**Comment by nicolargo** [comment]
My bad. There is an issue on the unitaries tests so the new version from the develop branch has not been uploaded to pypi test.
I will have a look as soon as possible.

**Comment by nicolargo** [comment]
@AgingOrange  Try this:

```
pip install --user --upgrade https://test.pypi.org/simple/ Glances
```

The version 3.2.5_beta01 should be installed.

**Comment by AgingOrange** [comment]
@nicolargo 
``` 
❯ pip install --log ./pip.log --user --upgrade https://test.pypi.org/simple/ Glances
Collecting https://test.pypi.org/simple/
  Using cached https://test.pypi.org/simple/ (7.2 MB)
  ERROR: Cannot unpack file /tmp/pip-unpack-l8b8qk8b/simple (downloaded from /tmp/pip-req-build-pes9getm, content-type: text/html; charset=UTF-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-pes9getm

❯ cat pip.log
2022-03-06T11:39:15,544 User install by explicit request
2022-03-06T11:39:15,600 Created temporary directory: /tmp/pip-ephem-wheel-cache-5tgnfbur
2022-03-06T11:39:15,600 Created temporary directory: /tmp/pip-req-tracker-v610me5u
2022-03-06T11:39:15,600 Initialized build tracking at /tmp/pip-req-tracker-v610me5u
2022-03-06T11:39:15,600 Created build tracker: /tmp/pip-req-tracker-v610me5u
2022-03-06T11:39:15,600 Entered build tracker: /tmp/pip-req-tracker-v610me5u
2022-03-06T11:39:15,601 Created temporary directory: /tmp/pip-install-owou9j_f
2022-03-06T11:39:15,601 Collecting https://test.pypi.org/simple/
2022-03-06T11:39:15,602   Created temporary directory: /tmp/pip-req-build-pes9getm
2022-03-06T11:39:15,602   Created temporary directory: /tmp/pip-unpack-l8b8qk8b
2022-03-06T11:39:15,602   Getting credentials from keyring for test.pypi.org
2022-03-06T11:39:15,602   Looking up "https://test.pypi.org/simple/" in the cache
2022-03-06T11:39:15,611   Current age based on date: 15
2022-03-06T11:39:15,611   Freshness lifetime from max-age: 600
2022-03-06T11:39:15,611   The response is "fresh", returning cached response
2022-03-06T11:39:15,611   600 > 15
2022-03-06T11:39:15,612   Using cached https://test.pypi.org/simple/ (7.2 MB)
2022-03-06T11:39:15,618   ERROR: Cannot unpack file /tmp/pip-unpack-l8b8qk8b/simple (downloaded from /tmp/pip-req-build-pes9getm, content-type: text/html; charset=UTF-8); cannot detect archive format
2022-03-06T11:39:15,618 Cleaning up...
2022-03-06T11:39:15,618 Removed build tracker: '/tmp/pip-req-tracker-v610me5u'
2022-03-06T11:39:15,618 ERROR: Cannot determine archive format of /tmp/pip-req-build-pes9getm
2022-03-06T11:39:15,618 Exception information:
2022-03-06T11:39:15,618 Traceback (most recent call last):
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
2022-03-06T11:39:15,618     status = self.run(options, args)
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
2022-03-06T11:39:15,618     resolver.resolve(requirement_set)
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
2022-03-06T11:39:15,618     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
2022-03-06T11:39:15,618     abstract_dist = self._get_abstract_dist_for(req_to_install)
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
2022-03-06T11:39:15,618     abstract_dist = self.preparer.prepare_linked_requirement(req)
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
2022-03-06T11:39:15,618     local_path = unpack_url(
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 282, in unpack_url
2022-03-06T11:39:15,618     return unpack_http_url(
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 164, in unpack_http_url
2022-03-06T11:39:15,618     unpack_file(from_path, location, content_type)
2022-03-06T11:39:15,618   File "/usr/lib/python3/dist-packages/pip/_internal/utils/unpacking.py", line 270, in unpack_file
2022-03-06T11:39:15,618     raise InstallationError(
2022-03-06T11:39:15,618 pip._internal.exceptions.InstallationError: Cannot determine archive format of /tmp/pip-req-build-pes9getm
```

**Comment by nicolargo** [comment]
Strabeg, same behavor on my side when i try to use test.pypi.org.

You can also try this procedure to test the develop branch: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version#use-a-python-virtual-environment-the-easy-and-standard-way

**Comment by AgingOrange** [comment]
Sorry to cause so much trouble, I'm not a Python developer.

```
❯ make test                     
./venv/bin/python ./unitest.py
psutil library not found. Glances cannot start.
make: *** [Makefile:29: test] Error 1

❯ ./venv/bin/python --version
Python 3.8.10

❯ sudo pip install psutil
Requirement already satisfied: psutil in /usr/local/lib/python3.8/dist-packages (5.9.0)

❯ python -c "import psutil" 
(no output)

❯ ./venv/bin/python -c "import psutil"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'psutil'
```

**Comment by nicolargo** [comment]
Try

./venv/bin/pip install -r requirements.txt

**Comment by AgingOrange** [comment]
@nicolargo Here's some excerpts:

`Error while initializing the docker plugin (No module named 'dateutil')`
`ModuleNotFoundError: No module named 'requests'`

`make run` does fire up glances, but without the Docker plugin.

Here's a full console session: https://paste.ec/paste/LTHUpL7m#GweFb7Hd6P-stxZttgWoyx9qWyoFL1Oka+SkLpFg752

**Comment by maverickk89** [comment]
hello, issue is still present in 3.2.5, how to solve?

**Comment by hulmgulm** [comment]
@nicolargo I encounter the same issue with the official 3.2.5 docker image:

Error while initializing the docker plugin (No module named 'dateutil')

**Comment by hulmgulm** [comment]
Update: using latest-full image instead of latest works. using alpine-latest-full does not work. There I get the error:

Error while initializing the docker plugin (No module named 'six')

**Comment by EDIflyer** [comment]
@hulmgulm agree - same issue still present today with the alpine images. @nicolargo will it be possible to fix these? I wasn't sure if it was only expected to work in the `-full` subset or not but if it could work in `alpine` itself that would be even better as 30MB vs 80MB 😃  Have temporarily switched to `latest-full` (ie non-alpine), but in general try to have most of my containers running off alpine images if possible.
