### ISSUE TITLE
Docker plugin broken in 3.2.5

### ISSUE THREAD

**Issue by ntompson** [nicolargo/glances#2040]
#### Description

Today I upgraded glances (running in a docker container) from 3.2.4.2 to 3.2.5. Mostly OK, but the docker plugin appears to be broken. In the container log, I see:

```
Error while initializing the docker plugin (No module named 'dateutil')
```

Looking at the glances web interface, the reporting block for currently running docker containers is missing. Rolling back to 3.2.4.2 fixes the problem.

#### Versions

* Docker image: 
    `docker.io/nicolargo/glances:3.2.5`
* Glances & psutil (`glances -V` inside container):
    `Glances v3.2.5 with PsUtil v5.9.0`
* Operating System (`lsb_release -a` of host):
    ```
    No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux 11 (bullseye)
    Release:	11
    Codename:	bullseye
    ```

#### Logs

Log inside container:

```
root@289ff1cf7e80:/# cat /tmp/glances-root.log
2022-04-28 01:19:08,847 -- INFO -- Start Glances 3.2.5
2022-04-28 01:19:08,847 -- INFO -- CPython 3.9.12 (/usr/local/bin/python3) and psutil 5.9.0 detected
2022-04-28 01:19:08,854 -- INFO -- Read configuration file '/glances/conf/glances.conf'
2022-04-28 01:19:08,878 -- INFO -- Start GlancesWebServer mode
2022-04-28 01:19:08,891 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2022-04-28 01:19:08,908 -- CRITICAL -- Error while initializing the docker plugin (No module named 'dateutil')
2022-04-28 01:19:08,909 -- ERROR -- Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/glances/stats.py", line 115, in _load_plugin
    plugin = __import__(plugin_script[:-3])
  File "/usr/local/lib/python3.9/site-packages/glances/plugins/glances_docker.py", line 26, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'

2022-04-28 01:19:10,264 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
2022-04-28 01:19:10,268 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/
2022-04-28 01:19:59,352 -- INFO -- Start Glances 3.2.5
2022-04-28 01:19:59,352 -- INFO -- CPython 3.9.12 (/usr/local/bin/python) and psutil 5.9.0 detected
2022-04-28 01:21:43,392 -- INFO -- Start Glances 3.2.5
2022-04-28 01:21:43,392 -- INFO -- CPython 3.9.12 (/usr/local/bin/python) and psutil 5.9.0 detected
```

**Comment by ntompson** [comment]
Hi @RazCrimson - yes that did the trick. The docker plugin works fine for me using the `3.2.5-full` image.

I'm curious: what's the difference?

**Comment by RazCrimson** [comment]
@ntompson It's just a missing dependency for the docker plugin in the default image.

It is present in the `full` image, so the plugin works.

**Comment by Generator** [comment]
Got it working after installing ```python-dateutil```manually.
Im using pipenv, didn't work out-of-box.
```
PIPENV_VENV_IN_PROJECT=1 pipenv install glances[docker] python-dateutil
```
