### ISSUE TITLE
Error in psutil: PdhAddEnglishCounterW failed

### ISSUE THREAD

**Issue by Madelena** [nicolargo/glances#2045]
**Describe the bug**
Cannot run Glances on an older Windows 10 computer.

```
Error while initializing the docker plugin (No module named 'dateutil')
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\glances.exe\__main__.py", line 7, in <module>
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\__init__.py", line 189, in main
    start(config=core.get_config(), args=core.get_args())
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-package    mode = GlancesMode(config=config, args=args)
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\standalone.py", line 80, in __init__
    self.stats.update()
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\stats.py", line 221, in update
    self._plugins[p].update()
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_plugin.py", line 1157, in wrapper
    ret = fct(self, *args, **kw)
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_plugin.py", line 1174, in wrapper
    ret = fct(*args, **kw)
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_load.py", line 116, in update
    load = self._getloadavg()
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_load.py", line 97, in _getloadavg
    return psutil.getloadavg()
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\psutil\_pswindows.py", line 347, in getloadavg
    cext.init_loadavg_counter()
RuntimeError: PdhAddEnglishCounterW failed
```

**To Reproduce**
1. Start glances normally by typing 'glances' in the Windows Terminal

**Expected behavior**
Glances should run on this computer.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - OS Build: 19044.1645
 - Python: 3.10.4
 - Glances v3.2.5 with PsUtil v5.9.0

```
2022-05-06 01:06:17,639 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2022-05-06 01:06:17,644 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2022-05-06 01:06:17,673 -- WARNING -- Missing Python Lib (No module named 'requests'), Ports plugin is limited to port scanning
2022-05-06 01:06:17,684 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2022-05-06 01:06:17,688 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2022-05-06 01:06:17,698 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2022-05-06 01:06:17,713 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2022-05-06 01:06:17,713 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2022-05-06 01:17:55,479 -- WARNING -- PsUtil can not grab processes gids ('Process' object has no attribute 'gids')
2022-05-06 01:17:55,483 -- INFO -- Start Glances 3.2.5
2022-05-06 01:17:55,484 -- INFO -- CPython 3.10.4 (C:\Users\Madelena\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe) and psutil 5.9.0 detected
2022-05-06 01:17:59,549 -- WARNING -- PsUtil can not grab processes gids ('Process' object has no attribute 'gids')
2022-05-06 01:17:59,553 -- INFO -- Start Glances 3.2.5
2022-05-06 01:17:59,554 -- INFO -- CPython 3.10.4 (C:\Users\Madelena\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe) and psutil 5.9.0 detected
2022-05-06 01:19:45,604 -- WARNING -- PsUtil can not grab processes gids ('Process' object has no attribute 'gids')
2022-05-06 01:19:45,607 -- INFO -- Start Glances 3.2.5
2022-05-06 01:19:45,607 -- INFO -- CPython 3.10.4 (C:\Users\Madelena\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe) and psutil 5.9.0 detected
2022-05-06 01:19:45,660 -- INFO -- Start GlancesStandalone mode
2022-05-06 01:19:45,674 -- WARNING -- Missing Python Lib (No module named 'requests'), Cloud plugin is disabled
2022-05-06 01:19:45,685 -- CRITICAL -- Error while initializing the docker plugin (No module named 'dateutil')
2022-05-06 01:19:45,687 -- ERROR -- Traceback (most recent call last):
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\stats.py", line 115, in _load_plugin
    plugin = __import__(plugin_script[:-3])
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_docker.py", line 26, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'

2022-05-06 01:19:45,693 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2022-05-06 01:19:45,697 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2022-05-06 01:19:45,726 -- WARNING -- Missing Python Lib (No module named 'requests'), Ports plugin is limited to port scanning
2022-05-06 01:19:45,736 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2022-05-06 01:19:45,740 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2022-05-06 01:19:45,749 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2022-05-06 01:19:45,762 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2022-05-06 01:19:45,763 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
```

**Additional context**

Python 3.10 is installed through Windows Store, though the same happened with my Python 3.8 installed through the Python official installer.

The computer had previously been run in Chinese many years ago but had since switched back to English, if that helps.

Also, I had tried this:

```
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.getloadavg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\psutil\_pswindows.py", line 347, in getloadavg
    cext.init_loadavg_counter()
RuntimeError: PdhAddEnglishCounterW failed
>>>
```

**Comment by nicolargo** [comment]
Hi @Madelena 

from my point of view, there is two issue. The first one is **ModuleNotFoundError: No module named 'dateutil'**. This problem is already solved in the develop branch and will be release in the next Glances version (3.2.5). As a workaround, you can install the lib manualy with the **pip install python-dateutil** command.

The second one is **RuntimeError: PdhAddEnglishCounterW** failed. It look like a PsUtil issue on Windows OS. Can you please open an issue on https://github.com/giampaolo/psutil ?

Thanks !
