### ISSUE TITLE
Add RRD files as new output for Glances

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#210]
Generate RRD files directly from Glances:

```
./glances.py --export-rrd /folder
```

Look at:
- http://oss.oetiker.ch/rrdtool/prog/rrdpython.en.html
- http://supportex.net/2011/09/rrd-python/

Install rrd-python (Pypi: requirment needed: https://github.com/pbanaszkiewicz/python-rrdtool)

**Comment by nicolargo** [comment]
Installation of the RRD-Python lib is a mess....

```
$ ▶ sudo pip install python-rrdtool
[sudo] password for nicolargo: 
The directory '/home/nicolargo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nicolargo/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-rrdtool
  Downloading python-rrdtool-1.4.7.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 552kB/s 
Installing collected packages: python-rrdtool
  Running setup.py install for python-rrdtool ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5SOqIq/python-rrdtool/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bKCpKf-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    running build_configure
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking for gcc... gcc
    checking for C compiler default output file name... a.out
    checking whether the C compiler works... yes
    checking whether we are cross compiling... no
    checking for suffix of executables...
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking minix/config.h usability... no
    checking minix/config.h presence... no
    checking for minix/config.h... no
    checking whether it is safe to define __EXTENSIONS__... yes
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking whether to enable maintainer-specific portions of Makefiles... no
    
    Audit Compilation Environment
    checking how to run the C preprocessor... gcc -E
    checking for gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking whether gcc and cc understand -c and -o together... yes
    checking for a sed that does not truncate output... /bin/sed
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for ar... ar
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking if gcc likes the -Werror flag... yes
    checking if gcc likes the -fno-strict-aliasing flag... yes
    checking if gcc likes the -Wall flag... yes
    checking if gcc likes the -std=gnu99 flag... yes
    checking if gcc likes the -pedantic flag... yes
    checking if gcc likes the -Wundef flag... yes
    checking if gcc likes the -Wshadow flag... yes
    checking if gcc likes the -Wpointer-arith flag... yes
    checking if gcc likes the -Wcast-align flag... yes
    checking if gcc likes the -Wmissing-prototypes flag... yes
    checking if gcc likes the -Wmissing-declarations flag... yes
    checking if gcc likes the -Wnested-externs flag... yes
    checking if gcc likes the -Winline flag... yes
    checking if gcc likes the -Wold-style-definition flag... yes
    checking if gcc likes the -W flag... yes
    
    Checking for Header Files
    checking for ANSI C header files... (cached) yes
    checking for dirent.h that defines DIR... yes
    checking for library containing opendir... none required
    checking langinfo.h usability... yes
    checking langinfo.h presence... yes
    checking for langinfo.h... yes
    checking for stdint.h... (cached) yes
    checking for inttypes.h... (cached) yes
    checking libgen.h usability... yes
    checking libgen.h presence... yes
    checking for libgen.h... yes
    checking features.h usability... yes
    checking features.h presence... yes
    checking for features.h... yes
    checking for sys/stat.h... (cached) yes
    checking for sys/types.h... (cached) yes
    checking fcntl.h usability... yes
    checking fcntl.h presence... yes
    checking for fcntl.h... yes
    checking fp_class.h usability... no
    checking fp_class.h presence... no
    checking for fp_class.h... no
    checking malloc.h usability... yes
    checking malloc.h presence... yes
    checking for malloc.h... yes
    checking for unistd.h... (cached) yes
    checking ieeefp.h usability... no
    checking ieeefp.h presence... no
    checking for ieeefp.h... no
    checking math.h usability... yes
    checking math.h presence... yes
    checking for math.h... yes
    checking sys/times.h usability... yes
    checking sys/times.h presence... yes
    checking for sys/times.h... yes
    checking sys/param.h usability... yes
    checking sys/param.h presence... yes
    checking for sys/param.h... yes
    checking sys/resource.h usability... yes
    checking sys/resource.h presence... yes
    checking for sys/resource.h... yes
    checking signal.h usability... yes
    checking signal.h presence... yes
    checking for signal.h... yes
    checking float.h usability... yes
    checking float.h presence... yes
    checking for float.h... yes
    checking stdio.h usability... yes
    checking stdio.h presence... yes
    checking for stdio.h... yes
    checking for stdlib.h... (cached) yes
    checking errno.h usability... yes
    checking errno.h presence... yes
    checking for errno.h... yes
    checking for string.h... (cached) yes
    checking ctype.h usability... yes
    checking ctype.h presence... yes
    checking for ctype.h... yes
    checking for an ANSI C-conforming const... yes
    checking whether time.h and sys/time.h may both be included... yes
    checking whether struct tm is in sys/time.h or time.h... time.h
    
    Test Library Functions
    checking for acos... no
    checking for acos in -lm... yes
    checking for strftime... yes
    checking for vprintf... yes
    checking for _doprnt... no
    checking whether byte ordering is bigendian... no
    checking for nl_langinfo... yes
    checking for tzset... yes
    checking for round... yes
    checking for rint... yes
    checking for fsync... yes
    checking for mbstowcs... yes
    checking for opendir... yes
    checking for readdir... yes
    checking for chdir... yes
    checking for chroot... yes
    checking for getuid... yes
    checking for strerror... yes
    checking for snprintf... yes
    checking for vsnprintf... yes
    checking for vasprintf... yes
    checking for fpclass... no
    checking for class... no
    checking for fp_class... no
    checking for isnan... yes
    checking for memmove... yes
    checking for strchr... yes
    checking for mktime... yes
    checking for getrusage... yes
    checking for gettimeofday... yes
    checking whether strerror_r is declared... yes
    checking for strerror_r... yes
    checking whether strerror_r returns char *... yes
    
    Map/Fadvis/Madvise checking
    checking for fdatasync... yes
    checking for fsync... (cached) yes
    checking for socket... yes
    checking for getaddrinfo... yes
    checking sys/mman.h usability... yes
    checking sys/mman.h presence... yes
    checking for sys/mman.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for mmap... yes
    checking for munmap... yes
    checking for msync... yes
    checking whether madvise is declared... yes
    checking for madvise... yes
    checking whether posix_fadvise is declared... yes
    checking for posix_fadvise... yes
    
    Libintl Processing
    checking whether NLS is requested... yes
    checking for msgfmt... /usr/bin/msgfmt
    checking for gmsgfmt... /usr/bin/msgfmt
    checking for xgettext... /usr/bin/xgettext
    checking for msgmerge... /usr/bin/msgmerge
    checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
    checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
    checking for shared library run path origin... done
    checking for CFPreferencesCopyAppValue... no
    checking for CFLocaleCopyCurrent... no
    checking for GNU gettext in libc... yes
    checking whether to use NLS... yes
    checking where the gettext function comes from... libc
    
    IEEE Math Checks
    checking for fpclassify... no
    checking for fpclassify with <math.h>... yes
    checking for isinf... yes
    checking whether isfinite is broken... no
    checking if IEEE math works out of the box... yes
    
    Resolve Portability Issues
    checking tm_gmtoff in struct tm... yes
    checking __tm_gmtoff in struct tm... no
    checking if msync with MS_ASYNC updates the files mtime... yes
    checking for _NL_TIME_WEEK_1STDAY... no
    checking for nl_langinfo(_NL_TIME_WEEK_1STDAY) with langinfo.h... yes
    checking for opterr... yes
    checking for getopt_long... yes
    checking if realloc can deal with NULL... yes
    checking if ctime_r need special care to act posixly correct... no
    checking for the pthreads library -lpthreads... no
    checking whether pthreads work without any flags... no
    checking whether pthreads work with -Kthread... no
    checking whether pthreads work with -kthread... no
    checking for the pthreads library -llthread... no
    checking whether pthreads work with -pthread... yes
    checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
    checking if more special flags are required for pthreads... no
    checking for cc_r... gcc
    checking do we need malloc/malloc.h... nope, works out of the box
    checking the type of time_t... checking size of time_t... 8
    time_t is 64 bit
    
    Find 3rd-Party Libraries
    checking dbi/dbi.h usability... no
    checking dbi/dbi.h presence... no
    checking for dbi/dbi.h... no
    checking tcpd.h usability... no
    checking tcpd.h presence... no
    checking for tcpd.h... no
    checking for cairo_font_options_create in -lcairo... no
    checking for pkg-config... pkg-config
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I found a copy of pkgconfig, but there is no cairo-png.pc file around.
      You may want to set the PKG_CONFIG_PATH variable to point to its
      location.
    ----------------------------------------------------------------------------
    
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I could not find a working copy of cairo-png. Check config.log for hints on why
      this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
      so that compiler and the linker can find libcairo and its header files. If
      you have not installed cairo-png, you can get it either from its original home on
    
         http://cairographics.org/releases/
    
      You can find also find an archive copy on
    
         http://oss.oetiker.ch/rrdtool/pub/libs
    
      The last tested version of cairo-png is 1.10.2.
    
           LIBS=-lm
       LDFLAGS=
      CPPFLAGS=
    
    ----------------------------------------------------------------------------
    
    checking for cairo_svg_surface_create in -lcairo... no
    checking for pkg-config... (cached) pkg-config
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I found a copy of pkgconfig, but there is no cairo-svg.pc file around.
      You may want to set the PKG_CONFIG_PATH variable to point to its
      location.
    ----------------------------------------------------------------------------
    
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I could not find a working copy of cairo-svg. Check config.log for hints on why
      this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
      so that compiler and the linker can find libcairo and its header files. If
      you have not installed cairo-svg, you can get it either from its original home on
    
         http://cairographics.org/releases/
    
      You can find also find an archive copy on
    
         http://oss.oetiker.ch/rrdtool/pub/libs
    
      The last tested version of cairo-svg is 1.10.2.
    
           LIBS=-lm
       LDFLAGS=
      CPPFLAGS=
    
    ----------------------------------------------------------------------------
    
    checking for cairo_pdf_surface_create in -lcairo... no
    checking for pkg-config... (cached) pkg-config
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I found a copy of pkgconfig, but there is no cairo-pdf.pc file around.
      You may want to set the PKG_CONFIG_PATH variable to point to its
      location.
    ----------------------------------------------------------------------------
    
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I could not find a working copy of cairo-pdf. Check config.log for hints on why
      this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
      so that compiler and the linker can find libcairo and its header files. If
      you have not installed cairo-pdf, you can get it either from its original home on
    
         http://cairographics.org/releases/
    
      You can find also find an archive copy on
    
         http://oss.oetiker.ch/rrdtool/pub/libs
    
      The last tested version of cairo-pdf is 1.10.2.
    
           LIBS=-lm
       LDFLAGS=
      CPPFLAGS=
    
    ----------------------------------------------------------------------------
    
    checking for cairo_ps_surface_create in -lcairo... no
    checking for pkg-config... (cached) pkg-config
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I found a copy of pkgconfig, but there is no cairo-ps.pc file around.
      You may want to set the PKG_CONFIG_PATH variable to point to its
      location.
    ----------------------------------------------------------------------------
    
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I could not find a working copy of cairo-ps. Check config.log for hints on why
      this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
      so that compiler and the linker can find libcairo and its header files. If
      you have not installed cairo-ps, you can get it either from its original home on
    
         http://cairographics.org/releases/
    
      You can find also find an archive copy on
    
         http://oss.oetiker.ch/rrdtool/pub/libs
    
      The last tested version of cairo-ps is 1.10.2.
    
           LIBS=-lm
       LDFLAGS=
      CPPFLAGS=
    
    ----------------------------------------------------------------------------
    
    checking for pango_cairo_context_set_font_options in -lpangocairo-1.0... no
    checking for pkg-config... (cached) pkg-config
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I found a copy of pkgconfig, but there is no pangocairo.pc file around.
      You may want to set the PKG_CONFIG_PATH variable to point to its
      location.
    ----------------------------------------------------------------------------
    
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I could not find a working copy of pangocairo. Check config.log for hints on why
      this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
      so that compiler and the linker can find libpangocairo-1.0 and its header files. If
      you have not installed pangocairo, you can get it either from its original home on
    
         http://ftp.gnome.org/pub/GNOME/sources/pango/1.28
    
      You can find also find an archive copy on
    
         http://oss.oetiker.ch/rrdtool/pub/libs
    
      The last tested version of pangocairo is 1.28.4.
    
           LIBS=-lm
       LDFLAGS=
      CPPFLAGS=
    
    ----------------------------------------------------------------------------
    
    checking for glib_check_version in -lglib-2.0... no
    checking for pkg-config... (cached) pkg-config
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I found a copy of pkgconfig, but there is no glib-2.0.pc file around.
      You may want to set the PKG_CONFIG_PATH variable to point to its
      location.
    ----------------------------------------------------------------------------
    
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I could not find a working copy of glib-2.0. Check config.log for hints on why
      this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
      so that compiler and the linker can find libglib-2.0 and its header files. If
      you have not installed glib-2.0, you can get it either from its original home on
    
         ftp://ftp.gtk.org/pub/glib/2.28/
    
      You can find also find an archive copy on
    
         http://oss.oetiker.ch/rrdtool/pub/libs
    
      The last tested version of glib-2.0 is 2.28.7.
    
           LIBS=-lm
       LDFLAGS=
      CPPFLAGS=
    
    ----------------------------------------------------------------------------
    
    checking for xmlParseFile in -lxml2... no
    checking for pkg-config... (cached) pkg-config
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I found a copy of pkgconfig, but there is no libxml-2.0.pc file around.
      You may want to set the PKG_CONFIG_PATH variable to point to its
      location.
    ----------------------------------------------------------------------------
    
    configure: WARNING:
    ----------------------------------------------------------------------------
    * I could not find a working copy of libxml-2.0. Check config.log for hints on why
      this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
      so that compiler and the linker can find libxml2 and its header files. If
      you have not installed libxml-2.0, you can get it either from its original home on
    
         http://xmlsoft.org/downloads.html
    
      You can find also find an archive copy on
    
         http://oss.oetiker.ch/rrdtool/pub/libs
    
      The last tested version of libxml-2.0 is 2.7.8.
    
           LIBS=-lm
       LDFLAGS=
      CPPFLAGS= -I/usr/include/libxml2
    
    ----------------------------------------------------------------------------
    
    configure: error: Please fix the library issues listed above and try again.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5SOqIq/python-rrdtool/setup.py", line 99, in <module>
        include_dirs=[include_dir],
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-5SOqIq/python-rrdtool/setup.py", line 68, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-5SOqIq/python-rrdtool/setup.py", line 62, in run
        subprocess.check_call(executable, cwd=os.path.dirname(executable))
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '/tmp/pip-build-5SOqIq/python-rrdtool/rrdtool-1.4.7/configure' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5SOqIq/python-rrdtool/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bKCpKf-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-5SOqIq/python-rrdtool/
```

**Comment by WirthmU** [comment]
Is this still a new feature on the list?
