### ISSUE TITLE
Windows Python 3 installation fails on dependency package "future"

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [nicolargo/glances#2109]
Since package "future" is required by Python 2, the install script should skip it for Python 3.

#### Description
```
pip install glances
Collecting glances
  Downloading Glances-3.2.7-py3-none-any.whl (1.6 MB)
Requirement already satisfied: packaging in c:\python\310\lib\site-packages (from glances) (21.3)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Temp\pip-install-phr_9b32\future_7cd8d419f30941c5a2f9e7a0ed293cc5\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]
```

#### Versions

OS: Windows 21H2
Python: 3.10.6
Glances: 3.2.7

**Comment by nicolargo** [comment]
Corrected on the develop branch.

Thanks you @Konstantin-Glukhov for the issue report.
