### ISSUE TITLE
Since the last update, using Glances with a password fails with a Python error

### ISSUE THREAD

**Issue by Antiz96** [nicolargo/glances#2159]
Hi,
First of all, thanks for your wonderful work with `glances`!

**Describe the bug**

The last docker image seems to fail when using a username/password. Indeed, after updating my glances container, I had the following Python error:

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 176, in main
    core = GlancesMain()
  File "/usr/lib/python3.10/site-packages/glances/main.py", line 99, in __init__
    self.args = self.parse_args()
  File "/usr/lib/python3.10/site-packages/glances/main.py", line 624, in parse_args
    args.password = self.__get_password(
  File "/usr/lib/python3.10/site-packages/glances/main.py", line 776, in __get_password
    password = GlancesPassword(username=username)
  File "/usr/lib/python3.10/site-packages/glances/password.py", line 33, in __init__
    self.password_dir = self.local_password_path()
  File "/usr/lib/python3.10/site-packages/glances/password.py", line 41, in local_password_path
    return self.config.get_value('passwords',
AttributeError: 'NoneType' object has no attribute 'get_value'
```

I tried to completely remove and reinstall the container but when launching the following command inside the container to choose my username and password, I get the exact same error I pasted above:
`glances -s --username --password` or `glances -s --password`

I tried with both the `lastest-full` and `alpine-latest-full` images and got the exact same issue.

The container runs on a Debian 11 (Bullseye) server with the latest docker version (`Docker version 20.10.20, build 9fdeb9c`).

**To Reproduce**

With an already existing username/password:

1. Run the Glances container this way: `sudo docker run -d --restart="unless-stopped" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w -u **username** --password" -v **path_to_the_password_file**:/root/.config/glances/**username**.pwd -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --name glances nicolargo/glances:alpine-latest-full`
2. Run: `sudo docker logs glances`
3. See error.

Without an already existing username/password:

1. Run the Glances container this way: `sudo docker run -d --restart="unless-stopped" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --name glances nicolargo/glances:alpine-latest-full`
2. Log into it: `sudo docker exec -it glances bash`
3. Launch the command to choose a username and password: `glances -s --username --password`
4. See error.

**Expected behavior**

Being able to use a username/password without the above Python error.

**Screenshots**

NA

**Desktop (please complete the following information):**
 - OS: Debian 11 (Bullseye)
 - Glances Version: Glances v3.3.0.1 with PsUtil v5.9.2 (using docker images latest-full/alpine-latest-full)
 - Glances logs file: I can't launch it with a username/password but launching it without them works fine
 ```
 bash-5.1# cat /tmp/glances-root.log
2022-10-23 08:20:53,992 -- INFO -- Start Glances 3.3.0.1
2022-10-23 08:20:53,992 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-10-23 08:20:53,996 -- INFO -- Read configuration file '/etc/glances.conf'
2022-10-23 08:20:54,003 -- INFO -- Start GlancesWebServer mode
2022-10-23 08:20:54,048 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2022-10-23 08:20:54,566 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
2022-10-23 08:20:54,568 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/
2022-10-23 08:21:22,644 -- INFO -- Start Glances 3.3.0.1
2022-10-23 08:21:22,644 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-10-23 08:23:13,823 -- INFO -- Start Glances 3.3.0.1
2022-10-23 08:23:13,823 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-10-23 08:23:33,484 -- INFO -- Start Glances 3.3.0.1
2022-10-23 08:23:33,484 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-10-23 08:44:37,454 -- INFO -- Start Glances 3.3.0.1
2022-10-23 08:44:37,454 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-10-23 08:44:39,277 -- INFO -- Start Glances 3.3.0.1
2022-10-23 08:44:39,277 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-10-23 08:45:52,748 -- INFO -- Start Glances 3.3.0.1
2022-10-23 08:45:52,748 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-10-23 08:46:20,336 -- INFO -- Start Glances 3.3.0.1
2022-10-23 08:46:20,336 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-10-23 08:46:20,348 -- INFO -- Start GlancesStandalone mode
2022-10-23 08:46:20,389 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2022-10-23 08:46:20,905 -- INFO -- Issue mode is ON
```
 - Glances test: Same statement as above
 ```
 bash-5.1# glances --issue
=============================================================================================================================================================================================
Glances 3.3.0.1 (/usr/lib/python3.10/site-packages/glances/__init__.py)
Python 3.10.5 (/usr/bin/python3)
PsUtil 5.9.2 (/usr/lib/python3.10/site-packages/psutil/__init__.py)
=============================================================================================================================================================================================
alert         [OK]    0.00001s []
amps          [OK]    0.00003s []
cloud         [OK]    0.00004s {}
connections   [OK]    0.00497s {'LISTEN': 1, 'ESTABLISHED': 0, 'SYN_SENT': 1, 'SYN_RECV': 0, 'initiated': 1, 'terminated': 1, 'nf_conntrack_count': 0.0, 'nf_conntrack_max': 262144
core          [OK]    0.00052s {'phys': 6, 'log': 12}
cpu           [OK]    0.00032s {'total': 7.6, 'user': 0.8, 'nice': 0.0, 'system': 0.2, 'idle': 98.9, 'iowait': 0.0, 'irq': 0.0, 'softirq': 0.0, 'steal': 0.0, 'guest': 0.5, 'guest_
diskio        [OK]    0.00037s key=disk_name [{'time_since_update': 2.029102325439453, 'disk_name': 'loop0', 'read_count': 0, 'write_count': 0, 'read_bytes': 0, 'write_bytes': 0,
docker        [OK]    0.00895s key=name [{'key': 'name', 'name': 'glances', 'Id': '01a8a16f9db52080726ab59f900415b00053b8d368537e795159cbfd3f30538d', 'Image': ['nicolargo/glances:
folders       [OK]    0.00002s []
fs            [OK]    0.00031s key=mnt_point [{'device_name': '/dev/sda3', 'fs_type': 'ext4', 'mnt_point': '/etc/resolv.conf', 'size': 24427446272, 'used': 6921789440, 'free': 174
gpu           [OK]    0.00001s []
help          [OK]    0.00000s None
ip            [OK]    0.00013s {'gateway': '172.17.0.1', 'address': '172.17.0.3', 'mask': '255.255.0.0', 'mask_cidr': 16, 'public_address': '176.132.84.82', 'public_info_human': '
irq           [OK]    0.00046s key=irq_line [{'irq_line': 'LOC', 'irq_rate': 4265, 'key': 'irq_line', 'time_since_update': 2.0381698608398438}, {'irq_line': 'CAL', 'irq_rate': 171
load          [OK]    0.00002s {'min1': 0.13525390625, 'min5': 0.05712890625, 'min15': 0.095703125, 'cpucore': 12}
mem           [OK]    0.00010s {'total': 33420357632, 'available': 21319839744, 'percent': 36.2, 'used': 12100517888, 'free': 21319839744, 'active': 2749235200, 'inactive': 956562
memswap       [OK]    0.00015s {'total': 4000313344, 'used': 0, 'free': 4000313344, 'percent': 0.0, 'sin': 0, 'sout': 0, 'time_since_update': 2.471700429916382}
network       [OK]    0.00021s key=interface_name [{'interface_name': 'lo', 'alias': None, 'time_since_update': 2.019062042236328, 'cumulative_rx': 38100, 'rx': 0, 'cumulative_tx'
now           [OK]    0.00001s 2022-10-23 08:48:13 UTC
percpu        [OK]    0.00007s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 84.0, 'user': 0.0, 'system': 0.0, 'idle': 16.0, 'nice': 0.0, 'iowait': 0.0, 'irq': 0
ports         [OK]    0.00012s []
processcount  [OK]    0.05357s {'total': 316, 'running': 1, 'sleeping': 213, 'thread': 512, 'pid_max': 0}
processlist   [OK]    0.00018s key=pid [{'cpu_percent': 4.8, 'gids': pgids(real=0, effective=0, saved=0), 'num_threads': 3, 'nice': 0, 'name': 'python3', 'io_counters': [0, 8192,
psutilversion [OK]    0.00002s (5, 9, 2)
quicklook     [OK]    0.00028s {'cpu': 7.6, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 84.0, 'user': 0.0, 'system': 0.0, 'idle': 16.0, 'nice': 0.0, 'iowait': 0.0,
raid          [OK]    0.00006s {}
sensors       [OK]    0.00001s key=label [{'label': 'acpitz 1', 'unit': 'C', 'value': 27, 'warning': 105, 'critical': 105, 'type': 'temperature_core', 'key': 'label'}, {'label': '
smart         [OK]    0.00047s []
system        [OK]    0.00001s {'os_name': 'Linux', 'hostname': '01a8a16f9db5', 'platform': '64bit', 'linux_distro': 'Alpine Linux 3.16.2', 'os_version': '5.15.64-1-pve', 'hr_name
uptime        [OK]    0.00008s {'seconds': 3321}
wifi          [OK]    0.00002s []
=============================================================================================================================================================================================
Total time to update all stats: 0.07443s
=============================================================================================================================================================================================
```

**Additional context**

Nothing to add I guess, don't hesitate to ask me more info if needed.
And once again, thanks a lot for your wonderful work with `glances`! :smiley:

**Comment by nicolargo** [comment]
Related to: https://github.com/nicolargo/glances/commit/0302cdcd57edc631bab28312c94429aada6a874d#commitcomment-87135935

**Comment by nicolargo** [comment]
Thanks for the bug report @Antiz96 !
 
It should be corrected by the latest commit.

Can you test the **dev** or **alpine-dev** images (build ready in one hour) ?

**Comment by Antiz96** [comment]
> Thanks for the bug report @Antiz96 !
> 
> It should be corrected by the latest commit.
> 
> Can you test the **dev** or **alpine-dev** images (build ready in one hour) ?

@nicolargo Sure! I'm testing the **dev** image right now. I'll be back with the results in few minutes.

**Comment by Antiz96** [comment]
@nicolargo Are the **devs** images ready yet?

I just tried the **dev** one and got the same issue:
```
[user@server ~]$ sudo docker pull nicolargo/glances:dev
[...]
[user@server ~]$ sudo docker images
REPOSITORY          TAG       IMAGE ID       CREATED             SIZE
nicolargo/glances   dev       2a65cfa7714f   About an hour ago   603MB
```
![image](https://user-images.githubusercontent.com/53110319/197387684-87c85430-16a4-4b9d-a282-62088bb39431.png)

```
[user@server ~]$ sudo docker run -d --restart="unless-stopped" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --name glances nicolargo/glances:dev
[user@server ~]$ sudo docker exec -it glances bash

root@18ebcd7ea9f8:/glances# glances -s --username --password
2022-10-23 10:42:00,624 -- INFO -- Start Glances 3.3.0.1
2022-10-23 10:42:00,624 -- INFO -- CPython 3.10.8 (/usr/local/bin/python) and psutil 5.9.2 detected
Define the Glances server username: username
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/glances/__init__.py", line 176, in main
    core = GlancesMain()
  File "/usr/local/lib/python3.10/site-packages/glances/main.py", line 99, in __init__
    self.args = self.parse_args()
  File "/usr/local/lib/python3.10/site-packages/glances/main.py", line 624, in parse_args
    args.password = self.__get_password(
  File "/usr/local/lib/python3.10/site-packages/glances/main.py", line 776, in __get_password
    password = GlancesPassword(username=username)
  File "/usr/local/lib/python3.10/site-packages/glances/password.py", line 33, in __init__
    self.password_dir = self.local_password_path()
  File "/usr/local/lib/python3.10/site-packages/glances/password.py", line 41, in local_password_path
    return self.config.get_value('passwords',
AttributeError: 'NoneType' object has no attribute 'get_value'
```

Maybe I tested a bit too early? :smile:

**Comment by nicolargo** [comment]
In the dev images Glances should be run with the following command line:

```
python3 -m glances -s --username --password
```

I just make a test on my side and it works.

**Comment by Antiz96** [comment]
> In the dev images Glances should be run with the following command line:
> 
> ```
> python3 -m glances -s --username --password
> ```
> 
> I just make a test on my side and it works.

Can confirm.
Error happens with the "classic" `glances -s --username --password`, but using `python3 -m glances -s --username --password` indeed works!

**Comment by Antiz96** [comment]
Oh well... Setting the password with `python3 -m glances -s --username --password` works but then glances docker logs says:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.10/site-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "/glances/glances/outputs/glances_bottle.py", line 616, in _enable_cors
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/bottle.py", line 2703, in wrapper
    if user is None or not check(user, password):
  File "/glances/glances/outputs/glances_bottle.py", line 130, in check_auth
    pwd = GlancesPassword()
  File "/glances/glances/password.py", line 35, in __init__
    self.password_file = os.path.join(self.password_dir, self.password_filename)
  File "/usr/local/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not function
```

And the web page returns an internal server error (500).

**Comment by nicolargo** [comment]
My bad.

The default case (when no configuration file) was not taken into account.

I just publish a new patch.

Docker image will be generated in 1 hour.

**Comment by Antiz96** [comment]
Alright, I'll try it in about an hour then!

Thanks a lot :)

**Comment by Antiz96** [comment]
@nicolargo Latest *dev* image works as intended!

**Comment by Antiz96** [comment]
Is there a rebuild planned for the *alpine-*latest-full docker image to integrates this fix?
I'm still using the dev image for now.
