### ISSUE TITLE
Glances server error when running with auto disccover

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2192]
**Describe the bug**

```
Glances XML-RPC server is running on 0.0.0.0:61209
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nhe/dev/glances/venv/lib/python3.6/site-packages/memory_profiler.py", line 1349, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "/home/nhe/dev/glances/venv/lib/python3.6/site-packages/memory_profiler.py", line 1250, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File "run.py", line 8, in <module>
    sys.exit(main())
  File "/home/nhe/dev/glances/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/home/nhe/dev/glances/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/home/nhe/dev/glances/glances/server.py", line 216, in __init__
    self.autodiscover_client = GlancesAutoDiscoverClient(socket.gethostname().split('.', 1)[0], args)
  File "/home/nhe/dev/glances/glances/autodiscover.py", line 174, in __init__
    self.zeroconf = Zeroconf()
  File "/home/nhe/dev/glances/venv/lib/python3.6/site-packages/zeroconf/_core.py", line 467, in __init__
    self.start()
  File "/home/nhe/dev/glances/venv/lib/python3.6/site-packages/zeroconf/_core.py", line 471, in start
    self.loop = get_running_loop()
  File "/home/nhe/dev/glances/venv/lib/python3.6/site-packages/zeroconf/_utils/asyncio.py", line 121, in get_running_loop
    return asyncio.get_running_loop()
AttributeError: module 'asyncio' has no attribute 'get_running_loop'
^CTraceback (most recent call last):
  File "./venv/bin/mprof", line 8, in <module>
Exception ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    sys.exit(main())
  File "/home/nhe/dev/glances/venv/lib/python3.6/site-packages/mprof.py", line 905, in main
    t.join()
    actions[get_action()]()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
  File "/home/nhe/dev/glances/venv/lib/python3.6/site-packages/mprof.py", line 285, in run_action
    multiprocess=args.multiprocess, stream=f, backend=args.backend)
  File "/home/nhe/dev/glances/venv/lib/python3.6/site-packages/memory_profiler.py", line 427, in memory_usage
    time.sleep(interval)
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
KeyboardInterrupt
    elif lock.acquire(block, timeout):
  File "/home/nhe/dev/glances/glances/__init__.py", line 65, in __signal_handler
    end()
  File "/home/nhe/dev/glances/glances/__init__.py", line 80, in end
    sys.exit(0)
SystemExit: 0
```

**To Reproduce**
Steps to reproduce the behavior: start Glances with -s

**Desktop (please complete the following information):**
 - OS: [e.g. GNU/Linux Ubuntu 20.04]: CentOS 7.9
 - Glances Version [output of glances -V]: 3.3.0.4

**Comment by nicolargo** [comment]
Note reproduced with latest lib (zeroconf).
