### ISSUE TITLE
Traceback thrown to do with un-named users

### ISSUE THREAD

**Issue by erincerys** [nicolargo/glances#2195]
**Describe the bug**
Stacktrace thrown periodically.

Presumably this has to do with processes running under un-named users, such as in Docker containers.

**To Reproduce**
Run a Docker container and then launch glances. Let it run for awhile.

**Expected behavior**
The program does not throw a traceback, and normal operation continues without having to restart it.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Glances Version: Glances v3.3.0 with PsUtil v5.9.3
 - Glances logs file:
 ```
2022-11-15 10:04:13,912 -- INFO -- Start Glances 3.3.0
2022-11-15 10:04:13,913 -- INFO -- CPython 3.10.8 (/usr/bin/python) and psutil 5.9.3 detected
2022-11-15 10:04:13,917 -- INFO -- Read configuration file '/home/erin/.config/glances/glances.conf'
2022-11-15 10:04:13,935 -- INFO -- Start GlancesStandalone mode
2022-11-15 10:04:13,941 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2022-11-15 10:04:14,031 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2022-11-15 10:04:14,031 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2022-11-15 10:04:14,053 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2022-11-15 10:04:14,058 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2022-11-15 10:04:14,061 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2022-11-16 05:07:19,822 -- INFO -- Glances stopped (key pressed: CTRL-C)
```
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)
```
============================================================================================================================================================
Glances 3.3.0 (/usr/lib/python3.10/site-packages/glances/__init__.py)
Python 3.10.8 (/usr/bin/python)
PsUtil 5.9.3 (/usr/lib/python3.10/site-packages/psutil/__init__.py)
============================================================================================================================================================
alert         [OK]    0.00001s []
amps          [OK]    0.19085s key=name [{'key': 'name', 'name': 'Dropbox', 'result': None, 'refresh': 3.0, 'timer': 3.551503896713257, 'count': 0
cloud         [OK]    0.00002s {}
connections   [NA]
core          [OK]    0.00055s {'phys': 12, 'log': 24}
cpu           [OK]    0.00021s {'total': 3.1, 'user': 1.1, 'nice': 0.0, 'system': 0.4, 'idle': 98.2, 'iowait': 0.2, 'irq': 0.1, 'softirq': 0.1, 's
diskio        [OK]    0.00088s key=disk_name [{'time_since_update': 3.3172473907470703, 'disk_name': 'sda', 'read_count': 0, 'write_count': 0, 're
docker        [OK]    0.01726s key=name [{'key': 'name', 'name': 'dge-aria-app-1', 'Id': '0d2ab096ea71f2be52fd1d443a758f2cc5648c1fb81ed4a3178ac408
folders       [OK]    0.00003s [{'indice': '1', 'path': '/media/hdd-array/video/porn', 'refresh': 360, 'careful': '500000', 'warning': '700000', '
fs            [OK]    0.00103s key=mnt_point [{'device_name': '/dev/mapper/linux-root', 'fs_type': 'ext4', 'mnt_point': '/', 'size': 52521566208,
gpu           [OK]    0.00002s []
help          [OK]    0.00000s None
ip            [NA]
irq           [OK]    0.00077s key=irq_line [{'irq_line': 'CAL', 'irq_rate': 27117, 'key': 'irq_line', 'time_since_update': 3.334759473800659}, {'
load          [OK]    0.00002s {'min1': 1.4677734375, 'min5': 1.033203125, 'min15': 0.80859375, 'cpucore': 24}
mem           [OK]    0.00007s {'total': 67345649664, 'available': 46467747840, 'percent': 31.0, 'used': 20877901824, 'free': 46467747840, 'active
memswap       [OK]    0.00011s {'total': 34359734272, 'used': 22361219072, 'free': 11998515200, 'percent': 65.1, 'sin': 8584577024, 'sout': 150241
network       [OK]    0.00086s key=interface_name [{'interface_name': 'enp8s0', 'alias': None, 'time_since_update': 2.217744827270508, 'cumulative
now           [OK]    0.00001s 2022-11-16 05:09:36 PST
percpu        [OK]    0.00048s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 19.7, 'user': 0.9, 'system': 1.2, 'idle': 80.3, 'ni
ports         [OK]    0.00000s [{'host': '192.168.1.1', 'port': 0, 'description': 'DefaultGateway', 'refresh': 30, 'timeout': 3, 'status': 0.00586
processcount  [OK]    0.07011s {'total': 637, 'running': 2, 'sleeping': 417, 'thread': 3556, 'pid_max': 0}
processlist   [OK]    0.00110s [{'time_since_update': 2.606914758682251, 'num_threads': 4, 'cpu_percent': 18.0, 'memory_percent': 0.07701707275641
psutilversion [OK]    0.00005s (5, 9, 3)
quicklook     [OK]    0.00027s {'cpu': 3.1, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 19.7, 'user': 0.9, 'system': 1.2, 'idle': 8
raid          [NA]
sensors       [OK]    0.00000s key=label [{'label': 'Composite', 'unit': 'C', 'value': 41, 'warning': 84, 'critical': 84, 'type': 'temperature_cor
smart         [NA]
system        [OK]    0.00000s {'os_name': 'Linux', 'hostname': 'chandra', 'platform': '64bit', 'linux_distro': 'Arch Linux', 'os_version': '6.0.7
uptime        [OK]    0.00007s {'seconds': 678805}
wifi          [NA]
============================================================================================================================================================
Total time to update all stats: 0.28749s
============================================================================================================================================================
You are using Glances version 3.3.0, however version 3.3.0.4 is available.
You should consider upgrading using: pip install --upgrade glances
```

**Additional context**
Here's the traceback:

    Traceback (most recent call last):
        File "/usr/bin/glances", line 33, in <module>
            sys.exit(load_entry_point('Glances==3.3.0', 'console_scripts', 'glances')())
        File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
            start(config=core.get_config(), args=core.get_args())
        File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 131, in start
            mode.serve_forever()
        File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 169, in serve_forever
            whileself.__serve_once():
        File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 135, in __serve_once
            self.stats.update()
        File "/usr/lib/python3.10/site-packages/glances/stats.py", line 216, in update
            self._plugins[p].update()
        File "/usr/lib/python3.10/site-packages/glances/plugins/glances_processlist.py", line 151, in update
            stats = processes_to_programs(stats)
        File "/usr/lib/python3.10/site-packages/glances/programs.py", line 56, in processes_to_programs
            p['username'] if p['username'] == programs_dict[p[key]]['username'] else '_'
        KeyError: 'username'

The issue does not occur immediately upon rendering a program line that is launched by an un-named user.

**Comment by nicolargo** [comment]
Corrected in the develop branch.

Will be release in next version.


Thanks for the issue report @erincerys !

**Comment by erincerys** [comment]
Damn, I shoulda submitted this sooner. Shits been plaguing me for months it feels like 🤣

Thanks for the quick patch!
