### ISSUE TITLE
"ModuleNotFoundError: No module named 'ujson'"

### ISSUE THREAD

**Issue by gregfr** [nicolargo/glances#2246]
**Describe the bug**
Glances doesn't start on any of my Debian 11 systems.

**To Reproduce**
1. Start Glances 

**Expected behavior**
Glances starts

**Screenshots**

```
# glances
Traceback (most recent call last):
  File "/root/.local/bin/glances", line 5, in <module>
    from glances import main
  File "/root/.local/pipx/venvs/glances/lib/python3.9/site-packages/glances/__init__.py", line 35, in <module>
    from glances.compat import PY3
  File "/root/.local/pipx/venvs/glances/lib/python3.9/site-packages/glances/compat.py", line 24, in <module>
    from glances.logger import logger
  File "/root/.local/pipx/venvs/glances/lib/python3.9/site-packages/glances/logger.py", line 20, in <module>
    from glances.globals import safe_makedirs
  File "/root/.local/pipx/venvs/glances/lib/python3.9/site-packages/glances/globals.py", line 16, in <module>
    import ujson
ModuleNotFoundError: No module named 'ujson'
```

```
# pip install ujson
Requirement already satisfied: ujson in /usr/local/lib/python3.9/dist-packages (5.7.0)
```

**Desktop (please complete the following information):**
 - OS: fresh install of Debian 11

**Additional context**
I've tried various ways of installing Glances (auto-script, pip, pipx), always the same error.

**Comment by nicolargo** [comment]
Solve by PR "setup: include ujson as required dependency" #2245

I will publish a new Glances 3.3.1.1 release as soon as possible.

**Comment by gregfr** [comment]
Thanks for the quick reaction!

I know nothing about python, and I still can't have it working with pipx

```
# pipx upgrade glances
upgraded package glances from 3.3.1 to 3.3.1.1 (location: /root/.local/pipx/venvs/glances)
```

```
# pipx run glances
⚠️  glances is already on your PATH and installed at /usr/local/bin/glances. Downloading and running anyway.
Traceback (most recent call last):
  File "/root/.local/pipx/.cache/d013979bdbd8878/bin/glances", line 5, in <module>
    from glances import main
  File "/root/.local/pipx/.cache/d013979bdbd8878/lib/python3.9/site-packages/glances/__init__.py", line 35, in <module>
    from glances.compat import PY3
  File "/root/.local/pipx/.cache/d013979bdbd8878/lib/python3.9/site-packages/glances/compat.py", line 24, in <module>
    from glances.logger import logger
  File "/root/.local/pipx/.cache/d013979bdbd8878/lib/python3.9/site-packages/glances/logger.py", line 20, in <module>
    from glances.globals import safe_makedirs
  File "/root/.local/pipx/.cache/d013979bdbd8878/lib/python3.9/site-packages/glances/globals.py", line 16, in <module>
    import ujson
ModuleNotFoundError: No module named 'ujson'
```

However the installed version is working.

Regards

**Comment by Japhys** [comment]
Yup same problem here

**Comment by mannibis** [comment]
So I ended up solving this by going into my site-packages directory and renaming `ujson.cpython-310-x86_64-linux-gnu.so` to `ujson.so` 

Importing ujson now works and so does glances. Not sure why it is named that to begin with after installing via pip.
