### ISSUE TITLE
Using Glances with docker-socket-proxy

### ISSUE THREAD

**Issue by gshlomi** [nicolargo/glances#2267]
Hi,
Running Glances in a container on an UNRAID machine.
Ever since I've added dockersocket proxy (https://github.com/Tecnativa/docker-socket-proxy) to protect the socket from being exposed online, I'm getting the following error on every restart of the Glances container:

The Command:
docker run -d --name='glances' --net='lsio' --privileged=true -e TZ="Asia/Jerusalem" -e HOST_OS="Unraid" -ee HOST_HOSTNAME="Small" -e HOST_CONTAINERNAME="glances" -e 'GLANCES_OPT'='-w' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:61208]/' -l net.unraid.docker.icon='https://github.com/nicolargo/glances/raw/master/glances/outputs/static/images/glances.png' -p '61208:61208/tcp' -p '61209:61209/tcp' -v '/mnt':'/mnt':'ro' -v '/var/run/docker.sock':'/var/run/docker.sock':'ro' --pid=host 'nicolargo/glances'

The Error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/d1c7e39252ade8534effadca5d1d536a442aeb310604cd82b927d4bbd74b2685/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/glances/__main__.py", line 19, in <module>
    glances.main()
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/webserver.py", line 31, in __init__
    self.stats.update()
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 216, in update
    self._plugins[p].update()
  File "/usr/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1114, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1131, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3.10/site-packages/glances/plugins/glances_docker.py", line 255, in update
    container_stats['Image'] = container.image.tags
  File "/usr/lib/python3.10/site-packages/docker/models/containers.py", line 40, in image
    return self.client.images.get(image_id.split(':')[1])
  File "/usr/lib/python3.10/site-packages/docker/models/images.py", line 335, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/d1c7e39252ade8534effadca5d1d536a442aeb310604cd82b927d4bbd74b2685/json: Not Found ("no such image: d1c7e39252ade8534effadca5d1d536a442aeb310604cd82b927d4bbd74b2685: No such image: sha256:d1c7e39252ade8534effadca5d1d536a442aeb310604cd82b927d4bbd74b2685")

**Comment by gshlomi** [comment]
P.S. I think this is relevant to #2125 as well

**Comment by BigWebstas** [comment]
I am experiencing the exact same issue on unraid as well. switching to latest-full branch/label doesnt seem to fix this issue on unraid.  Were you able to figure out a solution to your issue @gshlomi?

**Comment by gshlomi** [comment]
Unfortunately no, but it was closed as a duplicate (I assume to issue #2125)

**Comment by quincy5891** [comment]
Anyone find this issue. Only once I delete docker socket proxy does glances work. Are you able to user socket proxy instead of /var/run/docker.sock?

**Comment by RazCrimson** [comment]
@gshlomi @quincy5891 

Could you guys try out the steps mentioned here: https://github.com/nicolargo/glances/issues/2233#issuecomment-1515099159

I think the issue specific to unraid as mentioned in #2233

**Comment by quincy5891** [comment]
No longer works with the dev version.

**Comment by RazCrimson** [comment]
@quincy5891 

Could you just provide me the traceback, if possible?

**Comment by quincy5891** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/e97233d09a327583b8c7dbe13c2224b64aa3750badda2bce3c47e380fa24b266/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/glances/glances/__main__.py", line 18, in <module>
    glances.main()
  File "/glances/glances/__init__.py", line 180, in main
    start(config=core.get_config(), args=core.get_args())
  File "/glances/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glances/glances/webserver.py", line 31, in __init__
    self.stats.update()
  File "/glances/glances/stats.py", line 216, in update
    self._plugins[p].update()
  File "/glances/glances/plugins/glances_plugin.py", line 1114, in wrapper
    ret = fct(self, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/glances/glances/plugins/glances_plugin.py", line 1131, in wrapper
    ret = fct(*args, **kw)
          ^^^^^^^^^^^^^^^^
  File "/glances/glances/plugins/glances_containers.py", line 158, in update
    stats_docker = self.update_docker() if self.docker_extension else {}
                   ^^^^^^^^^^^^^^^^^^^^
  File "/glances/glances/plugins/glances_containers.py", line 178, in update_docker
    version, containers = self.docker_extension.update(all_tag=self._all_tag())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glances/glances/plugins/containers/glances_docker.py", line 282, in update
    container_stats = [self.generate_stats(container) for container in containers]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glances/glances/plugins/containers/glances_docker.py", line 282, in <listcomp>
    container_stats = [self.generate_stats(container) for container in containers]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glances/glances/plugins/containers/glances_docker.py", line 299, in generate_stats
    'Image': str(container.image.tags),
                 ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/models/containers.py", line 40, in image
    return self.client.images.get(image_id.split(':')[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/models/images.py", line 335, in get
    return self.prepare_model(self.client.api.inspect_image(name))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/e97233d09a327583b8c7dbe13c2224b64aa3750badda2bce3c47e380fa24b266/json: Not Found ("no such image: e97233d09a327583b8c7dbe13c2224b64aa3750badda2bce3c47e380fa24b266: No such image: sha256:e97233d09a327583b8c7dbe13c2224b64aa3750badda2bce3c47e380fa24b266")

**Comment by RazCrimson** [comment]
@quincy5891 
This issue is caused by a regression of the fix made in https://github.com/nicolargo/glances/issues/2233
I've pushed 14d26f27 which applies the fix back again.

Please give the newer dev images another try.

**Comment by quincy5891** [comment]
Works! Thank you!On May 12, 2023, at 3:11 PM, RazCrimson ***@***.***> wrote:﻿
@quincy5891
This issue is caused by a regression of the fix made in #2233
I've pushed 14d26f2 which applies the fix back again.
Please give the newer dev images another try.
