### ISSUE TITLE
Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by IThundxr** [nicolargo/glances#2275]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/lib/python3.10/site-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.10/site-packages/glances/outputs/glances_bottle.py", line 616, in _enable_cors
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/glances/outputs/glances_bottle.py", line 47, in wrapper
    ret = deflate_compress(ret)
  File "/usr/lib/python3.10/site-packages/glances/outputs/glances_bottle.py", line 60, in deflate_compress
    return zobj.compress(b(data)) + zobj.flush()
  File "/usr/lib/python3.10/site-packages/glances/compat.py", line 97, in b
    return s.encode('utf-8', errors=errors)
AttributeError: 'NoneType' object has no attribute 'encode'

Added a password and tried visiting api using tag latest-full

**Comment by RazCrimson** [comment]
@IThundxr 

Please fill in the bug template, as it help debugging the issue a lot more easier. 

It can be found by clicking on the `New Issue` button on the top right and then selecting the `Get Started` button to the right of Bug Report

**Comment by IThundxr** [comment]
Nvm seems api works but tbh idk what I changed

**Comment by IThundxr** [comment]
> Hey @IThundxr, I'm experiencing the same issue. Any idea what changes you tried?

Seems just visiting status doesn't work try 

http://serverip:port/api/3/mem

That should show the memory usage
