### ISSUE TITLE
KeyError with IP Plugin

### ISSUE THREAD

**Issue by RazCrimson** [nicolargo/glances#2301]
Error with IP Plugin

```bash
$ lsb_release -sd
Ubuntu 20.04.5 LTS
$ glances --version
Glances v3.1.3 with psutil v5.5.1
$ glances
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.3', 'console_scripts', 'glances')()
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 112, in start
    mode.serve_forever()
  File "/usr/lib/python3/dist-packages/glances/standalone.py", line 151, in serve_forever
    loop = self.__serve_forever()
  File "/usr/lib/python3/dist-packages/glances/standalone.py", line 138, in __serve_forever
    ret = not self.screen.update(self.stats, duration=adapted_refresh)
  File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 982, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 957, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 581, in display
    self.__display_header(__stat_display)
  File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 646, in __display_header
    self.display_plugin(stat_display["ip"])
KeyError: 'ip'
$ echo $?
1
```

_Originally posted by @sebmpluriad in https://github.com/nicolargo/glances/issues/1528#issuecomment-1474026003_

Tracking in a newer issue as old issue should be fixed and this might be a newer bug

**Comment by nicolargo** [comment]
Already corrected long time ago thanks to commit https://github.com/nicolargo/glances/commit/1d6be6ceabf79425e9b92caff57a655cb252d66b (release in version 3.3.1.1).

User should upgrade or disable the IP plugin.

**Comment by sebma** [comment]
@nicolargo How can I disable the IP plugin ?

Like this in `~/.config/glances/glances.conf` ? : 
```conf
[ip]
disable=True
```

**Comment by RazCrimson** [comment]
@sebma 
Yes, that should disable the IP plugin.

You can also disable it with the command line options like:
```sh
glances --disable-plugin ip`

**Comment by RazCrimson** [comment]
@sebma 
The `IP` is just an abbreviation of `Public IP`, the IP plugin gets your public IP using external services.

The TCP Connections is from the `connections` Plugin.

**Comment by sebma** [comment]
@RazCrimson Thanks for this clarification 👍
