### ISSUE TITLE
Crash on Glances Startup: 'ThreadScanner' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by creeloper27** [nicolargo/glances#2306]
**Describe the bug**
When starting glances on my server (while inside ssh) it immidiately crashes.

**To Reproduce**
1. ssh into a server running Debian GNU/Linux 11 (bullseye) x86_64, Linux 5.10.0-21-amd64 and have glances installed with apt and at the latest version v3.1.0 (3.1.0-1+deb10u1 ) with psutil v5.8.0
2. start ‘glances’
3. the software instantly crashes

**Expected behavior**
glances starts and works normally

**Screenshots and Outputs**
running glances in a remote server through ssh:
`ssh user@server.com`
`# successfully ssh into server`
`glances`
```bash
Traceback (most recent call last):
                                    File "/usr/bin/glances", line 11, in <module>
                                                                                     load_entry_point('Glances==3.1.0', 'console_scripts', 'glances')()
                                                                                                                                                         File "/usr/lib/python3/dist-packages/glances/__init__.py", line 140, in main
                            start(config=config, args=args)
                                                             File "/usr/lib/python3/dist-packages/glances/__init__.py", line 109, in start
                                                                                                                                              mode.serve_forever()
                                                                                                                                                                    File "/usr/lib/python3/dist-packages/glances/standalone.py", line 146, in serve_forever
                                                  loop = self.__serve_forever()
                                                                                 File "/usr/lib/python3/dist-packages/glances/standalone.py", line 116, in __serve_forever
                                                                                                                                                                              self.stats.update()
                                                                                                                                                                                                   File "/usr/lib/python3/dist-packages/glances/stats.py", line 222, in update
                                                                     self._plugins[p].update()
                                                                                                File "/usr/lib/python3/dist-packages/glances/plugins/glances_plugin.py", line 923, in wrapper
                                                                                                                                                                                                 ret = fct(*args, **kw)
            File "/usr/lib/python3/dist-packages/glances/plugins/glances_ports.py", line 84, in update
                                                                                                          thread_is_running = self._thread.isAlive()
                                                                                                                                                    AttributeError: 'ThreadScanner' object has no attribute 'isAlive'
        %
```
I have tried installing the pip version of glances with
`pip install glances`
this installed glances 3.3.0.4
trying to run the pip version with
`~/.local/bin/glances`
works as expected without any problem.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye) x86_64 and Linux 5.10.0-21-amd64
 - Glances apt Version: Glances v3.1.0 with psutil v5.8.0
 - Glances apt logs file: running `glances -V ` doesn’t return a log location, /var/log/glances also doesn’t exist, is it somewhere else?
 - Glances apt test: unavailable as version is too old
 - Glances pip Version: Glances v3.3.0.4 with PsUtil v5.8.0
 - Glances pip logs file:
```
2023-03-23 09:36:46,462 -- INFO -- Start Glances 3.3.0.4
2023-03-23 09:36:46,462 -- INFO -- CPython 3.9.2 (/usr/bin/python3) and psutil 5.8.0 detected
2023-03-23 09:42:37,201 -- INFO -- Start Glances 3.3.0.4
2023-03-23 09:42:37,201 -- INFO -- CPython 3.9.2 (/usr/bin/python3) and psutil 5.8.0 detected
2023-03-23 09:42:37,206 -- INFO -- Read configuration file '/etc/glances/glances.conf'
2023-03-23 09:42:37,214 -- INFO -- Start GlancesStandalone mode
2023-03-23 09:42:37,238 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2023-03-23 09:42:37,294 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2023-03-23 09:42:37,297 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2023-03-23 09:42:37,297 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2023-03-23 09:42:37,304 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2023-03-23 09:42:37,493 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2023-03-23 09:42:38,167 -- INFO -- Issue mode is ON
```
 - Glances pip test: 
 ```
===========================================================================================================================================================================================================
Glances 3.3.0.4 (/home/user/.local/lib/python3.9/site-packages/glances/__init__.py)
Python 3.9.2 (/usr/bin/python3)
PsUtil 5.8.0 (/usr/lib/python3/dist-packages/psutil/__init__.py)
===========================================================================================================================================================================================================
alert         [OK]    0.00002s []
amps          [OK]    0.00024s key=name [{'key': 'name', 'name': 'Dropbox', 'result': None, 'refresh': 3.0, 'timer': 2.8715710639953613, 'count': 0, 'countmin': 1.0, 'countmax': None, 'regex': 
cloud         [OK]    0.00006s {}
connections   [OK]    0.00885s {'LISTEN': 24, 'ESTABLISHED': 1, 'SYN_SENT': 1, 'SYN_RECV': 1, 'initiated': 2, 'terminated': 2, 'nf_conntrack_count': 16.0, 'nf_conntrack_max': 262144.0, 'nf_conn
core          [OK]    0.00057s {'phys': 8, 'log': 16}
cpu           [OK]    0.00025s {'total': 13.0, 'user': 7.1, 'nice': 0.0, 'system': 0.7, 'idle': 91.1, 'iowait': 0.7, 'irq': 0.0, 'softirq': 0.3, 'steal': 0.0, 'guest': 0.0, 'guest_nice': 0.0, '
diskio        [OK]    0.00059s key=disk_name [{'time_since_update': 2.6844794750213623, 'disk_name': 'sda', 'read_count': 0, 'write_count': 0, 'read_bytes': 0, 'write_bytes': 0, 'key': 'disk_na
docker        [OK]    0.01105s []
folders       [OK]    0.00004s []
fs            [OK]    0.00062s key=mnt_point [{'device_name': '/dev/sda3', 'fs_type': 'ext4', 'mnt_point': '/', 'size': 195722883072, 'used': 75722084352, 'free': 109984014336, 'percent': 40.8,
gpu           [OK]    0.00002s []
help          [OK]    0.00001s None
ip            [OK]    0.00038s {'gateway': '192.168.1.1', 'address': '192.168.1.2', 'mask': '255.255.255.0', 'mask_cidr': 24, 'public_address': '12.34.56.78', 'public_info_human': '
irq           [OK]    0.00052s key=irq_line [{'irq_line': 'LOC', 'irq_rate': 119946, 'key': 'irq_line', 'time_since_update': 2.61755633354187}, {'irq_line': 'RES', 'irq_rate': 1625, 'key': 'irq
load          [OK]    0.00004s {'min1': 1.06, 'min5': 1.26, 'min15': 1.32, 'cpucore': 16}
mem           [OK]    0.00013s {'total': 33652088832, 'available': 17528430592, 'percent': 47.9, 'used': 16123658240, 'free': 17528430592, 'active': 2134532096, 'inactive': 19147497472, 'buffer
memswap       [OK]    0.00017s {'total': 11998851072, 'used': 0, 'free': 11998851072, 'percent': 0.0, 'sin': 0, 'sout': 0, 'time_since_update': 2.61856985092163
network       [OK]    0.00040s key=interface_name [{'interface_name': 'lo', 'alias': None, 'time_since_update': 2.0267281532287598, 'cumulative_rx': 30938684, 'rx': 0, 'cumulative_tx': 30938684
now           [OK]    0.00001s 2023-03-23 09:42:40 CET
percpu        [OK]    0.00008s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 57.0, 'user': 0.0, 'system': 0.0, 'idle': 43.0, 'nice': 0.0, 'iowait': 0.0, 'irq': 0.0, 'softirq':
ports         [OK]    0.00001s [{'host': '192.168.1.1', 'port': 0, 'description': 'DefaultGateway', 'refresh': 30, 'timeout': 3, 'status': 0.005901, 'rtt_warning': None, 'indice': 'port_0'
processcount  [OK]    0.05896s {'total': 332, 'running': 1, 'sleeping': 222, 'thread': 931, 'pid_max': 
processlist   [OK]    0.00028s key=pid [{'num_threads': 136, 'memory_percent': 19.959707112186432, 'name': 'java', 'pid': 2775, 'status': 'S', 'cpu_times': pcputimes(user=92282.61, system=4150.
psutilversion [OK]    0.00003s (5, 8, 0)
quicklook     [OK]    0.00031s {'cpu': 13.0, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 57.0, 'user': 0.0, 'system': 0.0, 'idle': 43.0, 'nice': 0.0, 'iowait': 0.0, 'irq': 0.0, '
raid          [OK]    0.00002s {}
sensors       [OK]    0.00001s key=label [{'label': 'SYSTIN', 'unit': 'C', 'value': 32, 'warning': 0, 'critical': None, 'type': 'temperature_core', 'key': 'label'}, {'label': 'PCH_CPU_TEMP', 'u
smart         [NA]
system        [OK]    0.00001s {'os_name': 'Linux', 'hostname': 'aaabbbccc.no', 'platform': '64bit', 'linux_distro': 'Debian GNU/Linux 11', 'os_version': '5.10.0-21-amd64', 'hr_name': 'Debian GNU
uptime        [OK]    0.00009s {'seconds': 148586}
wifi          [OK]    0.00002s []
===========================================================================================================================================================================================================
Total time to update all stats: 0.08717s
===========================================================================================================================================================================================================
You are using Glances version 3.3.0.4, however version 3.3.1.1 is available.
You should consider upgrading using: pip install --upgrade glances
You are using Glances version 3.3.0.4, however version 3.3.1.1 is available.
You should consider upgrading using: pip install --upgrade glances
```

**Additional context**
This started happening only recently, I think this might have started happening after I updated some packages with apt tho I’m not totally sure.
Feel free to ask for any more logs or data that might help debug this issue.

**Comment by RazCrimson** [comment]
I think you are having two versions of glances installed. The one from apt is old, please remove that or don't use it. You are encountering the error from that version.

This issue that you describe was fixed in 2e00997e made 3 years ago.
