### ISSUE TITLE
Index error when displaying programs on MacOS

### ISSUE THREAD

**Issue by nickto** [nicolargo/glances#2360]
**Describe the bug**
When switching to displaying programs instead of threads on MacOS 13.2.1 crashes with `IndexError: tuple index out of range` error. 

**To Reproduce**
1. Start Glances.
2. Press the key 'j'
3. See error

**Expected behavior**
Switching to displaying programs instead of threads.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1  with M1 Apple silicon chip. 
 - Glances Version Glances v3.3.1.1 with PsUtil v5.9.5
 - Glances logs file
 ```
2023-04-27 12:38:09,589 -- INFO -- Start GlancesStandalone mode
2023-04-27 12:38:09,611 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2023-04-27 12:38:09,612 -- WARNING -- Error loading Docker deps Lib. Docker plugin is disabled (No module named 'docker')
2023-04-27 12:38:09,613 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
2023-04-27 12:38:09,613 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2023-04-27 12:38:09,613 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2023-04-27 12:38:09,616 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2023-04-27 12:38:09,616 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2023-04-27 12:38:09,618 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2023-04-27 12:38:09,618 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
 ```
(no error message in the logs)
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)
 ```
===============================================================================
Glances 3.3.1.1 (/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/glances/__init__.py)
Python 3.11.3 (/Users/[REDACTED]/.local/pipx/venvs/glances/bin/python)
PsUtil 5.9.5 (/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/__init__.py)
===============================================================================
alert         [OK]    0.00002s [[1682588962.0, -1, 'WARNING', 'MEM', 
amps          [OK]    0.00008s []
cloud         [OK]    0.00004s {}
connections   [OK]    0.00013s {}
core          [OK]    0.00007s {'phys': 8, 'log': 8}
cpu           [OK]    0.00019s {'total': 32.8, 'user': 17.1, 'nice': 
diskio        [OK]    0.00131s key=disk_name [{'time_since_update': 2
docker        [OK]    0.00006s []
folders       [OK]    0.00004s []
fs            [OK]    0.00115s key=mnt_point [{'device_name': '/dev/d
gpu           [OK]    0.00002s []
help          [OK]    0.00001s None
ip            [OK]    0.00002s {}
irq           [OK]    0.00002s []
load          [OK]    0.00004s {'min1': 1.7587890625, 'min5': 5.61230
mem           [OK]    0.00006s {'total': 17179869184, 'available': 44
memswap       [OK]    0.00007s {'total': 1073741824, 'used': 45416448
network       [OK]    0.00163s key=interface_name [{'interface_name':
now           [OK]    0.00001s 2023-04-27 12:49:24 EEST
percpu        [OK]    0.00004s key=cpu_number [{'key': 'cpu_number', 
ports         [OK]    0.00023s []
processcount  [OK]    0.02563s {'total': 611, 'running': 611, 'sleepi
processlist   [OK]    0.00016s key=pid [{'name': 'python3.10', 'cpu_t
psutilversion [OK]    0.00002s (5, 9, 5)
quicklook     [OK]    0.00009s {'cpu': 32.8, 'percpu': [{'key': 'cpu_
raid          [OK]    0.00001s {}
sensors       [OK]    0.00000s key=label [{'label': 'Battery', 'value
smart         [NA]
system        [OK]    0.00000s {'os_name': 'Darwin', 'hostname': 'bra
uptime        [OK]    0.00002s {'seconds': 9764}
wifi          [OK]    0.00001s []
===============================================================================
Total time to update all stats: 0.03437s
===============================================================================

```

**Additional context**
Full error with which glances fails:
```
Traceback (most recent call last):
File "/Users/[REDACTED]/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/[REDACTED]/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/__main__.py", line 19, in <module>
glances.main()
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
start(config=core.get_config(), args=core.get_args())
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/__init__.py", line 131, in start
mode.serve_forever()
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/standalone.py", line 169, in serve_forever
while self.__serve_once():
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/standalone.py", line 153, in __serve_once
ret = not self.screen.update(self.stats, duration=adapted_refresh)
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/outputs/glances_curses.py", line 1142, in update
self.flush(stats, cs_status=cs_status)
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/outputs/glances_curses.py", line 1124, in flush
self.display(stats, cs_status=cs_status)
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/outputs/glances_curses.py", line 637, in display
__stat_display["processlist"] = stats.get_plugin('processlist').get_stats_display(args=self.args)
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 890, in get_stats_display
ret = {'display': display_curse, 'msgdict': self.msg_curse(args), 'align': align_curse}
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/plugins/glances_processlist.py", line 520, in msg_curse
ret.extend(self.get_process_curses_data(p, i == args.cursor_position, args))
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/plugins/glances_processlist.py", line 367, in get_process_curses_data
ret.append(self._get_process_curses_vms(p, selected, args))
File "/Users/[REDACTED]/.local/lib/python3.10/site-packages/glances/plugins/glances_processlist.py", line 225, in _get_process_curses_vms
msg = self.layout_stat['virt'].format(self.auto_unit(p['memory_info'][1], low_precision=False))
IndexError: tuple index out of range
```

Tried with older Python versions and with Rosetta 2, but to no avail.

**Comment by nicolargo** [comment]
@nickto can you please copy paste the result of the following commands:

```
python
>>> import psutil
>>> p = psutil.Process(0)
>>> p
>>> p.memory_info()
>>> p.memory_info()[1]
>>> exit()
```

Thanks !

**Comment by nickto** [comment]
@nicolargo 

glances installed with pipx, so using the same Python binary as reported in `glances --issue` (although tried installing using `pip install --user` and `brew`, and the issue was still there).

```
/Users/[REDACTED]/.local/pipx/venvs/glances/bin/python
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> p = psutil.Process(0)
>>> p
psutil.Process(pid=0, name='kernel_task', status='running', started='2023-04-28 10:01:30')
>>> p.memory_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_common.py", line 480, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_common.py", line 478, in wrapper
    return fun(self)
           ^^^^^^^^^
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/__init__.py", line 1063, in memory_info
    return self._proc.memory_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_psosx.py", line 446, in memory_info
    rawtuple = self._get_pidtaskinfo()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_psosx.py", line 353, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: (pid=0, name='kernel_task')
>>> p.memory_info()[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_common.py", line 480, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_common.py", line 478, in wrapper
    return fun(self)
           ^^^^^^^^^
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/__init__.py", line 1063, in memory_info
    return self._proc.memory_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_psosx.py", line 446, in memory_info
    rawtuple = self._get_pidtaskinfo()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[REDACTED]/.local/pipx/venvs/glances/lib/python3.11/site-packages/psutil/_psosx.py", line 353, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: (pid=0, name='kernel_task')
>>> exit()
```

Since this looks like some access rights issue, tried running glances with sudo (it still runs the same glances installed with pipx judging by the outputs of `glances --issue` and `sudo glances --issue`), then glances groups by programs **successfully**, i.e. the **issue is not there** anymore. 

If this is intended behavior, feel free to close the issue: it solved the issue for me :) Thank you!

**Comment by nicolargo** [comment]
Ok @nickto but Glances should handle this kind of errors and never crash...

So we will add some control on the stats in order to avoid the crach and log a message to warn the user that some stats can not be displayed.

**Comment by nicolargo** [comment]
Done on the develop branch
