### ISSUE TITLE
WebUI build failed with VueJS >= 3.3.0

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2389]
After merging the PR https://github.com/nicolargo/glances/pull/2388 Glances WebUI failed to build:

```
> build
> webpack --progress --mode=production

[webpack-cli] Failed to load '/home/nicolargo/dev/glances/glances/outputs/static/webpack.config.js' config
[webpack-cli] Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/vue-loader/dist/compiler.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/vue-loader/dist/index.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
make: *** [Makefile:117: webui] Error 2
```

Problem is reproduced with all VueJS version >= 3.3.0. 

Downgraded to VueJS version 3.2.47 solves the issue.

```
package.json:        "vue": "^3.2.47"
```

**Comment by nicolargo** [comment]
@notFloran Can you have a look on this issue ?
