### ISSUE TITLE
Error while generating the documentation (ModuleNotFoundError: No module named 'glances') 

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2391]
Following error occurs when trying to generate the documentation (make docs):

```
...
cd docs && ./build.sh && cd ..
make[1]: Entering directory '/home/nicolargo/dev/glances/docs'
../venv/bin/sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v6.2.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/nicolargo/dev/glances/venv/lib/python3.10/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/nicolargo/dev/glances/docs/conf.py", line 15, in <module>
    from glances import __version__
ModuleNotFoundError: No module named 'glances'

make[1]: *** [Makefile:56: html] Error 2
make[1]: Leaving directory '/home/nicolargo/dev/glances/docs'
make[1]: Entering directory '/home/nicolargo/dev/glances/docs'
../venv/bin/sphinx-build -b man -d _build/doctrees   . _build/man
Running Sphinx v6.2.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/nicolargo/dev/glances/venv/lib/python3.10/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/nicolargo/dev/glances/docs/conf.py", line 15, in <module>
    from glances import __version__
ModuleNotFoundError: No module named 'glances'

make[1]: *** [Makefile:156: man] Error 2
make[1]: Leaving directory '/home/nicolargo/dev/glances/docs'
make: *** [Makefile:101: docs] Error 2
```

**Comment by nicolargo** [comment]
Ok find the bug:

https://github.com/nicolargo/glances/commit/cf76040b566634ee468796d729d42a6fe3253d74#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3

The Glances lib import has been moved before the sys call...

Revert.
