### ISSUE TITLE
3.4.0 crash on startup with minimal deps

### ISSUE THREAD

**Issue by pulberg** [nicolargo/glances#2401]
**Describe the bug**
3.4.0 crashes on startup

**To Reproduce**
1. Start Glances
2. See errors
[glances.log](https://github.com/nicolargo/glances/files/11491280/glances.log)

Adding shell output for verbosity - 

```
Traceback (most recent call last):
File "/opt/homebrew/bin/glances", line 8, in <module> sys.exit(main())
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/__init__.py", line 180, in main start(config=core.get_config(), args=core.get_args())
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/__init__.py", line 131, in start mode.serve_forever()
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/standalone.py", line 171, in serve_forever while self.__serve_once():
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/standalone.py", line 155, in __serve_once ret = not self.screen.update(self.stats, duration=adapted_refresh)
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/outputs/glances_curses.py", line 1151, in update self.flush(stats, cs_status=cs_status)
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/outputs/glances_curses.py", line 1133, in flush
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/outputs/glances_curses.py", line 614, in display __stat_display = self.__get_stat_display(stats, layer=cs_status)
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/outputs/glances_curses.py", line 590, in __get_stat_display ret[p] = stats.get_plugin(p).get_stats_display(args=self.args, max_width=plugin_max_width)
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/plugins/glances_plugin.py", line 888, in get_stats_display ret = {'display': display_curse, 'msgdict': self.msg_curse(args, max_width=max_width), 'align': align_curse}
File "/opt/homebrew/Cellar/glances/3.4.0/libexec/lib/python3.11/site-packages/glances/plugins/glances_connections.py", line 167, in msg_curse '{:0.0f}/{:0.0f}'.format(self.stats['nf_conntrack_count'], self.stats['nf_conntrack_max']),
~~~~~~~~~~ 
KeyError: 'nf_conntrack_count'
```

**Expected behavior**
Glances runs

**Environement (please complete the following information)**
 - Operating System: `macOS 13.3.1 (a), Mac Studio M1 Max`
 - Glances & psutil versions: `glances -V
Glances v3.4.0 with PsUtil v5.9.5
Log file: /Users/pulberg/.local/share/glances/glances.log`
 - How do you install Glances: `brew install glances`
 - Glances test (only available with Glances 3.1.7 or higher): 
[glances--issue.txt](https://github.com/nicolargo/glances/files/11491261/glances--issue.txt)

**Additional context**
Glances v3.3.1.1 was working perfectly, Glances was updated to v3.4.0 by virtue of me running `brew update` like i usually do.

**Comment by defjaf** [comment]
I am getting nearly identical errors (which have the added bonus of requiring a terminal `reset` to get back to a usable state!). I have tried installing with both `brew` and also `pip` with the same behaviour.

**Comment by LukeTheCharl** [comment]
Happens to me too!
Python 3.11.3 mac os 13.3.1.
The version of Galnces 3.3.1.1 works perfectly instead
 I have downgraded.

**Comment by StefanWetterActiware** [comment]
Not only MacOS. I have the same error with Ubuntu, Snap 3.4.0.

```
Traceback (most recent call last):
File "/snap/glances/1492/bin/glances", line 8, in <module> sys.exit(main())
File "/snap/glances/1492/lib/python3.8/site-packages/glances/__init__.py", line 180, in main start(config=core.get_config(), args=core.get_args())
File "/snap/glances/1492/lib/python3.8/site-packages/glances/__init__.py", line 131, in start mode.serve_forever()
File "/snap/glances/1492/lib/python3.8/site-packages/glances/standalone.py", line 171, in serve_forever while self.__serve_once():
File "/snap/glances/1492/lib/python3.8/site-packages/glances/standalone.py", line 155, in __serve_once ret = not self.screen.update(self.stats, duration=adapted_refresh)
File "/snap/glances/1492/lib/python3.8/site-packages/glances/outputs/glances_curses.py", line 1151, in update self.flush(stats, cs_status=cs_status)
File "/snap/glances/1492/lib/python3.8/site-packages/glances/outputs/glances_curses.py", line 1133, in flush self.display(stats, cs_status=cs_status)
File "/snap/glances/1492/lib/python3.8/site-packages/glances/outputs/glances_curses.py", line 614, in display __stat_display = self.__get_stat_display(stats, layer=cs_status)
File "/snap/glances/1492/lib/python3.8/site-packages/glances/outputs/glances_curses.py", line 590, in __get_stat_display ret[p] = stats.get_plugin(p).get_stats_display(args=self.args, max_width=plugin_max_width)
File "/snap/glances/1492/lib/python3.8/site-packages/glances/plugins/glances_plugin.py", line 888, in get_stats_display ret = {'display': display_curse, 'msgdict': self.msg_curse(args, max_width=max_width), 'align': align_curse}
File "/snap/glances/1492/lib/python3.8/site-packages/glances/plugins/glances_connections.py", line 167, in msg_curse '{:0.0f}/{:0.0f}'.format(self.stats['nf_conntrack_count'], self.stats['nf_conntrack_max']),
KeyError: 'nf_conntrack_count'
```

**Comment by nicolargo** [comment]
Hotfix done.

A new 3.4.0.1 will be available soon (build is ongoing).

**Comment by nicolargo** [comment]
New version 3.4.0.1 available. 

Please upgrade and test.

**Comment by LukeTheCharl** [comment]
Now it's OK !!!!!!

**Comment by StefanWetterActiware** [comment]
I confirm. The snap is already updated as well. Thank you very much!
