### ISSUE TITLE
Influxdb2 export not working

### ISSUE THREAD

**Issue by drewzeee** [nicolargo/glances#2407]
**Describe the bug**

As of Monday/Tuesday, `glances --export influxdb2`  returns the following:
`Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/glances/__init__.py", line 180, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/local/lib/python3.9/dist-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python3.9/dist-packages/glances/standalone.py", line 44, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/local/lib/python3.9/dist-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/local/lib/python3.9/dist-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/local/lib/python3.9/dist-packages/glances/stats.py", line 167, in load_exports
    self._exports[export_name] = export_module.Export(args=args, config=self.config)
  File "/usr/local/lib/python3.9/dist-packages/glances/exports/glances_influxdb2.py", line 52, in __init__
    self.interval = int(self.interval)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

I don't have the knowledge base to understand what's goin on here, so I thought to post here. 

**Environement (please complete the following information)**
 - Using Proxmox (debian 11)
 - Glances v3.4.0.1 with PsUtil v5.9.5
 - Installed via pypi

**Additional context**
Strangely enough, `glances --export influxdb3` actually (half-way) works as intended as it starts to feed metrics to my terminal. However it will not export into my influxdb database, even when changing glances.conf to replace "influxdb2" with "influxdb3"

**Comment by nicolargo** [comment]
My bad... should be corrected in the hotfix available in Glances 3.4.0.2 (available now on Pypi).

Can you test it @drewzeee ?

**Comment by drewzeee** [comment]
It works! You da man @nicolargo
