### ISSUE TITLE
--stdout plugin.attr is not compliant with plugins returning list of dicts

### ISSUE THREAD

**Issue by Rogersyangluo** [nicolargo/glances#2446]
In the Linux system, how does the command glances --stdout processlist only take one or several attributes such as pid or name, such as glances --stdout processlist.pid

**Comment by nicolargo** [comment]
For the moment it is not possible:

```
./venv/bin/python -m glances -C ./conf/glances.conf --stdout processlist.username
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/nicolargo/dev/glances/glances/__main__.py", line 18, in <module>
    glances.main()
  File "/home/nicolargo/dev/glances/glances/__init__.py", line 184, in main
    start(config=core.get_config(), args=core.get_args())
  File "/home/nicolargo/dev/glances/glances/__init__.py", line 130, in start
    mode.serve_forever()
  File "/home/nicolargo/dev/glances/glances/standalone.py", line 181, in serve_forever
    while self.__serve_once():
  File "/home/nicolargo/dev/glances/glances/standalone.py", line 160, in __serve_once
    ret = not self.screen.update(self.stats, duration=adapted_refresh)
  File "/home/nicolargo/dev/glances/glances/outputs/glances_stdout.py", line 62, in update
    printandflush("{}.{}: {}".format(plugin, attribute, stat[attribute]))
TypeError: list indices must be integers or slices, not str
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
  File "/home/nicolargo/dev/glances/glances/__init__.py", line 64, in __signal_handler
    end()
  File "/home/nicolargo/dev/glances/glances/__init__.py", line 79, in end
    sys.exit(0)
SystemExit: 0
```

Should have a look on what it is possible to do.

**Comment by nicolargo** [comment]
Corrected in the develop branch.

Will be release with Glances 4.0.
