### ISSUE TITLE
Docker Prometheus issue with IRQ plugin

### ISSUE THREAD

**Issue by aquinary** [nicolargo/glances#2564]
I have the following docker-compose.yml:

```
  glances:
    restart: unless-stopped
    image: nicolargo/glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances-configs/glances.conf:/etc/glances.conf
    pid: host
    ports:
      - 9092:9091
    environment:
      - GLANCES_OPT=--export prometheus
```
In `image` i substitute different images and get different error messages each time.

If `nicolargo/glances` and `:latest`:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 18, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 185, in main
    start(config=core.get_config(), args=core.get_args())
  File "/app/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/glances/standalone.py", line 44, in __init__
    self.stats = GlancesStats(config=config, args=args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/app/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/app/glances/stats.py", line 162, in load_exports
    export_module = __import__(self._exports_all[export_name])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/glances/exports/glances_prometheus.py", line 19, in <module>
    from prometheus_client import start_http_server, Gauge
ModuleNotFoundError: No module named 'prometheus_client'
```
If `nicolargo/glances:dev`:
```
2023-10-02 10:16:21,352 -- INFO -- Start Glances 4.0.0_beta01
2023-10-02 10:16:21,352 -- INFO -- CPython 3.11.5 (/venv/bin/python3) and psutil 5.9.5 detected
2023-10-02 10:16:21,355 -- INFO -- Read configuration file '/etc/glances.conf'
2023-10-02 10:16:21,368 -- INFO -- Start GlancesStandalone mode
2023-10-02 10:16:21,601 -- ERROR -- containers (Podman) plugin - Can't connect to Podman (http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v4.6.0/libpod/_ping (HEAD operation failed))
2023-10-02 10:16:21,672 -- INFO -- Start Prometheus exporter on localhost:9091
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 18, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 183, in main
    start(config=core.get_config(), args=core.get_args())
  File "/app/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/glances/standalone.py", line 106, in __init__
    self.screen = GlancesCursesStandalone(config=config, args=args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/glances/outputs/glances_curses.py", line 142, in __init__
    self.screen = curses.initscr()
                  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/curses/__init__.py", line 29, in initscr
    setupterm(term=_os.environ.get("TERM", "unknown"),
_curses.error: setupterm: could not find terminal
```
If `nicolargo/glances:dev` and `GLANCES_OPT=--quiet --export prometheus`
```
2023-10-02 10:17:13,408 -- INFO -- Start Glances 4.0.0_beta01
2023-10-02 10:17:13,408 -- INFO -- CPython 3.11.5 (/venv/bin/python3) and psutil 5.9.5 detected
2023-10-02 10:17:13,411 -- INFO -- Read configuration file '/etc/glances.conf'
2023-10-02 10:17:13,448 -- INFO -- Start GlancesStandalone mode
2023-10-02 10:17:13,686 -- ERROR -- containers (Podman) plugin - Can't connect to Podman (http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v4.6.0/libpod/_ping (HEAD operation failed))
2023-10-02 10:17:13,772 -- INFO -- Start Prometheus exporter on localhost:9091
2023-10-02 10:17:15,553 -- INFO -- Quiet mode is ON, nothing will be displayed
Exception in thread Thread-23 (update):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/glances/exports/export.py", line 170, in update
    self.export(plugin, export_names, export_values)
  File "/app/glances/exports/prometheus/__init__.py", line 80, in export
    self._metric_dict[metric_name] = Gauge(metric_name, k, labelnames=listkeys(labels))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 365, in __init__
    super().__init__(
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 130, in __init__
    raise ValueError('Invalid metric name: ' + self._name)
ValueError: Invalid metric name: glances_irq_49_ahci[0000:00:1f_2]_irq_rate
Exception in thread Thread-24 (update):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/glances/exports/export.py", line 170, in update
    self.export(plugin, export_names, export_values)
  File "/app/glances/exports/prometheus/__init__.py", line 80, in export
    self._metric_dict[metric_name] = Gauge(metric_name, k, labelnames=listkeys(labels))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 365, in __init__
    super().__init__(
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 130, in __init__
    raise ValueError('Invalid metric name: ' + self._name)
ValueError: Invalid metric name: glances_irq_49_ahci[0000:00:1f_2]_irq_rate
Exception in thread Thread-26 (update):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/glances/exports/export.py", line 170, in update
    self.export(plugin, export_names, export_values)
  File "/app/glances/exports/prometheus/__init__.py", line 80, in export
    self._metric_dict[metric_name] = Gauge(metric_name, k, labelnames=listkeys(labels))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 365, in __init__
    super().__init__(
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 130, in __init__
    raise ValueError('Invalid metric name: ' + self._name)
ValueError: Invalid metric name: glances_irq_49_ahci[0000:00:1f_2]_irq_rate
Exception in thread Thread-27 (update):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/glances/exports/export.py", line 170, in update
    self.export(plugin, export_names, export_values)
  File "/app/glances/exports/prometheus/__init__.py", line 80, in export
    self._metric_dict[metric_name] = Gauge(metric_name, k, labelnames=listkeys(labels))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 365, in __init__
    super().__init__(
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 130, in __init__
    raise ValueError('Invalid metric name: ' + self._name)
ValueError: Invalid metric name: glances_irq_49_ahci[0000:00:1f_2]_irq_rate
```

These are the three main errors i get. I also tried other images (ubuntu, etc.) and the result is exactly the same.

**Comment by pnelsen** [comment]
You would need to use one of the `full` image version to get the `optional-requirements.txt` -> https://hub.docker.com/layers/nicolargo/glances/latest-full/images/sha256-01fcafb39e64230e79f82422813332f62729f71cab476056374fa2caea403666?context=explore

**Comment by pnelsen** [comment]
However, I have noticed that there is a memory leak in the prometheus client when I set this as my config:
```
version: "3.9"
services:
  glances:
    image: nicolargo/glances:latest-full
    ports:
     - 61208-61209:61208-61209
    restart: always
    container_name: glances
    pid: host
    environment:
     - "GLANCES_OPT=-d --export prometheus -q"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ${CONFIG_BASE}/config/glances/glances.conf:/etc/glances.conf
    networks:
     - monitoring_network

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: always
    ports:
     - 9090:9090
    volumes:
     - ${CONFIG_BASE}/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - ${APP_BASE}/prometheus:/prometheus
    networks:
     - monitoring_network
networks:
  monitoring_network:
    driver: bridge
```

I haven't had time to dig into this further, but I suspect the problem is actually in the `prometheus_client` repo:
https://github.com/prometheus/client_python/issues/937

**Comment by aquinary** [comment]
> glances:
>     image: nicolargo/glances:latest-full
>     ports:
>      - 61208-61209:61208-61209
>     restart: always
>     container_name: glances
>     pid: host
>     environment:
>      - "GLANCES_OPT=-d --export prometheus -q"
>     volumes:
>      - /var/run/docker.sock:/var/run/docker.sock:ro
>      - ${CONFIG_BASE}/config/glances/glances.conf:/etc/glances.conf
>     networks:
>      - monitoring_network

I completely copied what you sent. Alas, it didn't work.
I still get the error

```
  File "/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 130, in __init__
    raise ValueError('Invalid metric name: ' + self._name)
ValueError: Invalid metric name: glances_irq_49_ahci[0000:00:1f_2]_irq_rate
```

**Comment by nicolargo** [comment]
Issue reproduced when the 'irq' plugin is enabled (by default the plugin is disabled, it is why it works for @pnelsen ).

@aquinary : as a workaround and waiting for the patch, disable the irq plugin from the command line or the Glances configuration file).

**Comment by nicolargo** [comment]
Patch done in the develop branch.

**Comment by nicolargo** [comment]
@aquinary can you test it when the Docker nicolargo/glances:dev will be available (in one or two hours) ?

**Comment by aquinary** [comment]
@nicolargo yes, now it works. Thanks!!!
