### ISSUE TITLE
psutil library not found. Glances cannot start.

### ISSUE THREAD

**Issue by igorpupkinable** [nicolargo/glances#2605]
**Describe the bug**
I am not 100% sure it is a bug because I cannot debug it.
I have looked through a number of similar tickets but none of the suggested solutions have helped.
```bash
<username>@<router>:~$ python --version
Python 3.11.4
<username>@<router>:~$ pip --version
pip 23.3.1 from /var/services/homes/<username>/.local/lib/python3.11/site-packages/pip (python 3.11)
<username>@<router>:~$ sudo pip --version
pip 23.2.1 from /opt/lib/python3.11/site-packages/pip (python 3.11)

<username>@<router>:~$ pip install --user --upgrade glances
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: glances in /var/services/homes/<username>/.local/lib/python3.11/site-packages (3.4.0.3)
Requirement already satisfied: psutil>=5.6.7 in /var/services/homes/<username>/.local/lib/python3.11/site-packages (from glances) (5.9.6)
Requirement already satisfied: defusedxml in /var/services/homes/<username>/.local/lib/python3.11/site-packages (from glances) (0.8.0rc2)
Requirement already satisfied: packaging in /var/services/homes/<username>/.local/lib/python3.11/site-packages (from glances) (23.2)
Requirement already satisfied: ujson>=5.4.0 in /var/services/homes/<username>/.local/lib/python3.11/site-packages (from glances) (5.6.0)
<username>@router:~$ glances -w
psutil library not found. Glances cannot start.
<username>@router:~$ /opt/bin/python3 -m glances -d
psutil library not found. Glances cannot start.

<username>@<router>:~$ sudo pip install --upgrade glances
Password: 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: glances in /opt/lib/python3.11/site-packages (3.4.0.3)
Requirement already satisfied: psutil>=5.6.7 in /opt/lib/python3.11/site-packages (from glances) (5.9.6)
Requirement already satisfied: defusedxml in /opt/lib/python3.11/site-packages (from glances) (0.7.1)
Requirement already satisfied: packaging in /opt/lib/python3.11/site-packages (from glances) (23.1)
Requirement already satisfied: ujson>=5.4.0 in /opt/lib/python3.11/site-packages (from glances) (5.6.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python3 -m pip install --upgrade pip
<username>@<router>:~$ sudo /opt/bin/python3 -m glances -d
psutil library not found. Glances cannot start.
<username>@<router>:~$ sudo /opt/bin/python3 -m glances -w
psutil library not found. Glances cannot start.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. [Install Entware](https://github-wiki-see.page/m/entware/entware/wiki/Install-on-Synology-NAS)
2. `sudo opkg install python3`
3. `sudo opkg install python3-dev`
4. `pip install --user https://www.piwheels.org/simple/defusedxml/defusedxml-0.8.0rc2-py2.py3-none-any.whl#sha256=84db12bc62e56f86c4b30ac272e34c6f345dff4830ff3cb5905dc5af7d7de6d3`
5. `pip install --user https://www.piwheels.org/simple/psutil/psutil-5.9.6-cp39-abi3-linux_armv7l.whl#sha256=a81f4d0267b0dacfa1fd06929268be99af81a1463a6a0ba02c663b41145d7dda`
6. `pip install --user https://www.piwheels.org/simple/ujson/ujson-5.6.0-cp311-cp311-linux_armv7l.whl#sha256=4a50ed074d494b9e459058ed338b9b9c7c167ffca83fca9fb2d22c591e11ec45`
7. `pip install --user 'glances[all]'`
8. `glances -w`
9. **See error**
10. Repeat steps 4 to 7 with _sudo_
11. `sudo /opt/bin/python3 -m glances -w`
12. **See error**
13. `sudo opkg install python3-psutil`
14. `glances -w`
15. **See error**
16. `sudo /opt/bin/python3 -m glances -w`
17. **See error**

**Expected behavior**
_psutil_ dependency is found. Glances starts successfully.

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): _lbs_release_ binary is not available. `uname -a` is `Linux router 4.4.60 #9346 SMP PREEMPT Fri Nov 4 11:49:28 CST 2022 armv7l GNU/Linux synology_ipq806x_rt2600ac`
 - Glances & psutil versions: `glances -V` throws the same error. `Glances 3.4.0.3; psutil: 5.9.6;`
 - How do you install Glances (Pypi package, script, package manager, source): `pip install --user 'glances[all]'` and `sudo pip install 'glances[all]'`
 - Glances test (only available with Glances 3.1.7 or higher):
 ```
psutil library not found. Glances cannot start.
 ```

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
No configuration file found in any of the locations.

Could anyone suggest how to debug and fix this please?

**Comment by igorpupkinable** [comment]
This is what actually leads to this error.
```bash
$ python
Python 3.11.4 (main, Sep  5 2023, 06:29:01) [GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from psutil import __version__ as psutil_version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/services/homes/<username>/.local/lib/python3.11/site-packages/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/var/services/homes/<username>/.local/lib/python3.11/site-packages/psutil/_pslinux.py", line 25, in <module>
    from . import _psutil_linux as cext
ImportError: /var/services/homes/<username>/.local/lib/python3.11/site-packages/psutil/_psutil_linux.abi3.so: internal error

```

**Comment by igorpupkinable** [comment]
Solved the issue by uninstalling all packages, removing leftovers and starting from scratch.
