### ISSUE TITLE
OpenBSD crash on start without a swap file/partition

### ISSUE THREAD

**Issue by halperyon** [nicolargo/glances#2719]
**Describe the bug**
When starting Glances on OpenBSD without swap set up, glances' quicklook plugin doesn't check for if swap exists, and expecting there to be one it crashes due to psutil.swap_memory() not working, while on Linux it starts just fine without swap.

It starts just fine with the -3 flag disabling quicklook (which has the swap meter alongside other ones)

I believe this to be an issue with psutil on BSD and not glances itself, although a check for swap existing would be good.

**To Reproduce**
1. Make a fresh OpenBSD installation **without** swap.
2. Start Glances with no options. (quicklook enabled)

**Expected behavior**
Glances starts and works.

**Screenshots**
```
$ glances

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/local/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python3.10/site-packages/glances/standalone.py", line 71, in __init__
    self.stats.update()
  File "/usr/local/lib/python3.10/site-packages/glances/stats.py", line 216, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1114, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/local/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1131, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python3.10/site-packages/glances/plugins/glances_quicklook.py", line 58, in update
    stats['swap'] = psutil.swap_memory().percent
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2036, in swap_memory
    return _psplatform.swap_memory()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psbsd.py", line 231, in swap_memory
    total, used, free, sin, sout = cext.swap_mem()
OSError: [Errno 0] Error
```

**Environement (please complete the following information)**
 - Operating System: OpenBSD 7.5
 - Glances & psutil versions: Glances v3.3.0.4 with PsUtil v5.9.8
 - How do you install Glances: Package Manager (pkg_add)
 - Glances test (only available with Glances 3.1.7 or higher):

 ```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/local/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python3.10/site-packages/glances/standalone.py", line 71, in __init__
    self.stats.update()
  File "/usr/local/lib/python3.10/site-packages/glances/stats.py", line 216, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1114, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/local/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1131, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python3.10/site-packages/glances/plugins/glances_memswap.py", line 81, in update
    sm_stats = psutil.swap_memory()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2036, in swap_memory
    return _psplatform.swap_memory()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psbsd.py", line 231, in swap_memory
    total, used, free, sin, sout = cext.swap_mem()
OSError: [Errno 0] Error
 ```

**Additional context**
No swap file or partition set

* the Glances configuration file
Default aside from disabling `memswap`, which doesn't resolve the issue.

---

A quick and dirty fix for this problem is editing the `/usr/local/lib/python3.10/site-packages/glances/plugins/glances_quicklook.py` file and removing any instances of swap.

**Comment by nicolargo** [comment]
Patch merged into develop.

**Comment by daddy32** [comment]
Similar thing happens to me under Windows 11 (current version installed via `pipx`):

```
glances
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\name\.local\bin\glances.exe\__main__.py", line 7, in <module>
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\glances\__init__.py", line 173, in main
    start(config=core.get_config(), args=core.get_args())
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\glances\__init__.py", line 102, in start
    mode = GlancesMode(config=config, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\glances\standalone.py", line 77, in __init__
    self.stats.update()
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\glances\stats.py", line 269, in update
    self.__update_plugin(p)
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\glances\stats.py", line 258, in __update_plugin
    self._plugins[p].update()
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\glances\plugins\plugin\model.py", line 1151, in wrapper
    ret = fct(self, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\glances\plugins\plugin\model.py", line 1168, in wrapper
    ret = fct(*args, **kw)
          ^^^^^^^^^^^^^^^^
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\glances\plugins\memswap\__init__.py", line 80, in update
    sm_stats = psutil.swap_memory()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\psutil\__init__.py", line 1992, in swap_memory
    return _psplatform.swap_memory()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\.local\pipx\venvs\glances\Lib\site-packages\psutil\_pswindows.py", line 262, in swap_memory
    percent = round(percentswap, 1)
                    ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'percentswap' where it is not associated with a value
```
