### ISSUE TITLE
Alpine Docker image build error on ARM

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2735]
Orjson compilation error on ARM/v6

```
#68 567.9   Building wheel for orjson (pyproject.toml): started
#68 ...

#80 [linux/arm/v6 buildfull 1/1] RUN /venv-build/bin/python3.11 -m pip install --target="/venv/lib/python3.11/site-packages"     -r optional-requirements.txt
#80 444.3   Installing backend dependencies: still running...
#80 445.5   Installing backend dependencies: finished with status 'error'
#80 445.8   error: subprocess-exited-with-error
#80 445.8   
#80 445.8   × pip subprocess to install backend dependencies did not run successfully.
#80 445.8   │ exit code: 1
#80 445.8   ╰─> [100 lines of output]
#80 445.8       Collecting cmake>=3.14
#80 445.8         Downloading cmake-3.29.2.tar.gz (30 kB)
#80 445.8         Installing build dependencies: started
#80 445.8         Installing build dependencies: finished with status 'done'
#80 445.8         Getting requirements to build wheel: started
#80 445.8         Getting requirements to build wheel: finished with status 'done'
#80 445.8         Installing backend dependencies: started
#80 445.8         Installing backend dependencies: finished with status 'error'
#80 445.8         error: subprocess-exited-with-error
#80 445.8       
#80 445.8         × pip subprocess to install backend dependencies did not run successfully.
#80 445.8         │ exit code: 2
#80 445.8         ╰─> [77 lines of output]
#80 445.8             Collecting ninja>=1.5
#80 445.8               Downloading ninja-1.11.1.1.tar.gz (132 kB)
#80 445.8                  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.4/132.4 kB 3.1 MB/s eta 0:00:00
#80 445.8               Installing build dependencies: started
#80 445.8               Installing build dependencies: finished with status 'done'
#80 445.8               Getting requirements to build wheel: started
#80 445.8               Getting requirements to build wheel: finished with status 'done'
#80 445.8               Preparing metadata (pyproject.toml): started
#80 445.8               Preparing metadata (pyproject.toml): finished with status 'done'
#80 445.8             Collecting cmake
#80 445.8               Using cached cmake-3.29.2.tar.gz (30 kB)
#80 445.8             ERROR: Exception:
#80 445.8             Traceback (most recent call last):
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
#80 445.8                 status = run_func(*args)
#80 445.8                          ^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
#80 445.8                 return func(self, options, args)
#80 445.8                        ^^^^^^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
#80 445.8                 requirement_set = resolver.resolve(
#80 445.8                                   ^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
#80 445.8                 result = self._result = resolver.resolve(
#80 445.8                                         ^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
#80 445.8                 state = resolution.resolve(requirements, max_rounds=max_rounds)
#80 445.8                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
#80 445.8                 self._add_to_criteria(self.state.criteria, r, parent=None)
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
#80 445.8                 if not criterion.candidates:
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
#80 445.8                 return bool(self._sequence)
#80 445.8                        ^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#80 445.8                 return any(self)
#80 445.8                        ^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#80 445.8                 return (c for c in iterator if id(c) not in self._incompatible_ids)
#80 445.8                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#80 445.8                 candidate = func()
#80 445.8                             ^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
#80 445.8                 base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
#80 445.8                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
#80 445.8                 self._link_candidate_cache[link] = LinkCandidate(
#80 445.8                                                    ^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
#80 445.8                 super().__init__(
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
#80 445.8                 self.dist = self._prepare()
#80 445.8                             ^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
#80 445.8                 dist = self._prepare_distribution()
#80 445.8                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
#80 445.8                 return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#80 445.8                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
#80 445.8                 return self._prepare_linked_requirement(req, parallel_builds)
#80 445.8                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
#80 445.8                 dist = _get_prepared_distribution(
#80 445.8                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 70, in _get_prepared_distribution
#80 445.8                 with build_tracker.track(req, tracker_id):
#80 445.8               File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
#80 445.8                 return next(self.gen)
#80 445.8                        ^^^^^^^^^^^^^^
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/build/build_tracker.py", line 137, in track
#80 445.8                 self.add(req, tracker_id)
#80 445.8               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/build/build_tracker.py", line 103, in add
#80 445.8                 raise LookupError(message)
#80 445.8             LookupError: https://files.pythonhosted.org/packages/80/bf/4f9a9f754507992be28b985d1e9b17f93a2271106b5916a212efe1d65205/cmake-3.29.2.tar.gz (from https://pypi.org/simple/cmake/) (requires-python:>=3.7) is already being built: cmake>=3.14 from https://files.pythonhosted.org/packages/80/bf/4f9a9f754507992be28b985d1e9b17f93a2271106b5916a212efe1d65205/cmake-3.29.2.tar.gz
#80 445.8             [end of output]
#80 445.8       
#80 445.8         note: This error originates from a subprocess, and is likely not a problem with pip.
#80 445.8       error: subprocess-exited-with-error
#80 445.8       
#80 445.8       × pip subprocess to install backend dependencies did not run successfully.
#80 445.8       │ exit code: 2
#80 445.8       ╰─> See above for output.
#80 445.8       
#80 445.8       note: This error originates from a subprocess, and is likely not a problem with pip.
#80 445.8       [end of output]
#80 445.8   
#80 445.8   note: This error originates from a subprocess, and is likely not a problem with pip.
#80 445.8 error: subprocess-exited-with-error
#80 445.8 
#80 445.8 × pip subprocess to install backend dependencies did not run successfully.
#80 445.8 │ exit code: 1
#80 445.8 ╰─> See above for output.
#80 445.8 
#80 445.8 note: This error originates from a subprocess, and is likely not a problem with pip.
#80 ERROR: process "/bin/sh -c /venv-build/bin/python${PYTHON_VERSION} -m pip install --target=\"/venv/lib/python${PYTHON_VERSION}/site-packages\"     -r optional-requirements.txt" did not complete successfully: exit code: 1
```

**Comment by nicolargo** [comment]
Another issue on i386 when ARM/v6 is disable:

```
#86 425.6 Collecting annotated-types>=0.4.0 (from pydantic->-r requirements.txt (line 6))
#86 425.7   Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
#86 ...

#79 [linux/arm/v6 buildfull 1/1] RUN /venv-build/bin/python3.11 -m pip install --target="/venv/lib/python3.11/site-packages"     -r optional-requirements.txt
#79 447.7   Installing backend dependencies: still running...
#79 449.0   Installing backend dependencies: finished with status 'error'
#79 449.2   error: subprocess-exited-with-error
#79 449.2   
#79 449.2   × pip subprocess to install backend dependencies did not run successfully.
#79 449.2   │ exit code: 1
#79 449.2   ╰─> [100 lines of output]
#79 449.2       Collecting cmake>=3.14
#79 449.2         Downloading cmake-3.29.2.tar.gz (30 kB)
#79 449.2         Installing build dependencies: started
#79 449.2         Installing build dependencies: finished with status 'done'
#79 449.2         Getting requirements to build wheel: started
#79 449.2         Getting requirements to build wheel: finished with status 'done'
#79 449.2         Installing backend dependencies: started
#79 449.2         Installing backend dependencies: finished with status 'error'
#79 449.2         error: subprocess-exited-with-error
#79 449.2       
#79 449.2         × pip subprocess to install backend dependencies did not run successfully.
#79 449.2         │ exit code: 2
#79 449.2         ╰─> [77 lines of output]
#79 449.2             Collecting ninja>=1.5
#79 449.2               Downloading ninja-1.11.1.1.tar.gz (132 kB)
#79 449.2                  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.4/132.4 kB 1.9 MB/s eta 0:00:00
#79 449.2               Installing build dependencies: started
#79 449.2               Installing build dependencies: finished with status 'done'
#79 449.2               Getting requirements to build wheel: started
#79 449.2               Getting requirements to build wheel: finished with status 'done'
#79 449.2               Preparing metadata (pyproject.toml): started
#79 449.2               Preparing metadata (pyproject.toml): finished with status 'done'
#79 449.2             Collecting cmake
#79 449.2               Using cached cmake-3.29.2.tar.gz (30 kB)
#79 449.2             ERROR: Exception:
#79 449.2             Traceback (most recent call last):
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
#79 449.2                 status = run_func(*args)
#79 449.2                          ^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
#79 449.2                 return func(self, options, args)
#79 449.2                        ^^^^^^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
#79 449.2                 requirement_set = resolver.resolve(
#79 449.2                                   ^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
#79 449.2                 result = self._result = resolver.resolve(
#79 449.2                                         ^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
#79 449.2                 state = resolution.resolve(requirements, max_rounds=max_rounds)
#79 449.2                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
#79 449.2                 self._add_to_criteria(self.state.criteria, r, parent=None)
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
#79 449.2                 if not criterion.candidates:
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
#79 449.2                 return bool(self._sequence)
#79 449.2                        ^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#79 449.2                 return any(self)
#79 449.2                        ^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#79 449.2                 return (c for c in iterator if id(c) not in self._incompatible_ids)
#79 449.2                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#79 449.2                 candidate = func()
#79 449.2                             ^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
#79 449.2                 base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
#79 449.2                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
#79 449.2                 self._link_candidate_cache[link] = LinkCandidate(
#79 449.2                                                    ^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
#79 449.2                 super().__init__(
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
#79 449.2                 self.dist = self._prepare()
#79 449.2                             ^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
#79 449.2                 dist = self._prepare_distribution()
#79 449.2                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
#79 449.2                 return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#79 449.2                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
#79 449.2                 return self._prepare_linked_requirement(req, parallel_builds)
#79 449.2                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
#79 449.2                 dist = _get_prepared_distribution(
#79 449.2                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 70, in _get_prepared_distribution
#79 449.2                 with build_tracker.track(req, tracker_id):
#79 449.2               File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
#79 449.2                 return next(self.gen)
#79 449.2                        ^^^^^^^^^^^^^^
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/build/build_tracker.py", line 137, in track
#79 449.2                 self.add(req, tracker_id)
#79 449.2               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/build/build_tracker.py", line 103, in add
#79 449.2                 raise LookupError(message)
#79 449.2             LookupError: https://files.pythonhosted.org/packages/80/bf/4f9a9f754507992be28b985d1e9b17f93a2271106b5916a212efe1d65205/cmake-3.29.2.tar.gz (from https://pypi.org/simple/cmake/) (requires-python:>=3.7) is already being built: cmake>=3.14 from https://files.pythonhosted.org/packages/80/bf/4f9a9f754507992be28b985d1e9b17f93a2271106b5916a212efe1d65205/cmake-3.29.2.tar.gz
#79 449.2             [end of output]
#79 449.2       
#79 449.2         note: This error originates from a subprocess, and is likely not a problem with pip.
#79 449.2       error: subprocess-exited-with-error
#79 449.2       
#79 449.2       × pip subprocess to install backend dependencies did not run successfully.
#79 449.2       │ exit code: 2
#79 449.2       ╰─> See above for output.
#79 449.2       
#79 449.2       note: This error originates from a subprocess, and is likely not a problem with pip.
#79 449.2       [end of output]
#79 449.2   
#79 449.2   note: This error originates from a subprocess, and is likely not a problem with pip.
#79 449.3 error: subprocess-exited-with-error
#79 449.3 
#79 449.3 × pip subprocess to install backend dependencies did not run successfully.
#79 449.3 │ exit code: 1
#79 449.3 ╰─> See above for output.
#79 449.3 
#79 449.3 note: This error originates from a subprocess, and is likely not a problem with pip.
#79 ERROR: process "/bin/sh -c /venv-build/bin/python${PYTHON_VERSION} -m pip install --target=\"/venv/lib/python${PYTHON_VERSION}/site-packages\"     -r optional-requirements.txt" did not complete successfully: exit code: 1
```

**Comment by nicolargo** [comment]
Also with ARM/v7:

```
#66 [linux/arm/v7 buildfull 1/1] RUN /venv-build/bin/python3.11 -m pip install --target="/venv/lib/python3.11/site-packages"     -r optional-requirements.txt
#66 364.1   Installing backend dependencies: finished with status 'error'
#66 364.4   error: subprocess-exited-with-error
#66 364.4   
#66 364.4   × pip subprocess to install backend dependencies did not run successfully.
#66 364.4   │ exit code: 1
#66 364.4   ╰─> [100 lines of output]
#66 364.4       Collecting cmake>=3.14
#66 364.4         Downloading cmake-3.29.2.tar.gz (30 kB)
#66 364.4         Installing build dependencies: started
#66 364.4         Installing build dependencies: finished with status 'done'
#66 364.4         Getting requirements to build wheel: started
#66 364.4         Getting requirements to build wheel: finished with status 'done'
#66 364.4         Installing backend dependencies: started
#66 364.4         Installing backend dependencies: finished with status 'error'
#66 364.4         error: subprocess-exited-with-error
#66 364.4       
#66 364.4         × pip subprocess to install backend dependencies did not run successfully.
#66 364.4         │ exit code: 2
#66 364.4         ╰─> [77 lines of output]
#66 364.4             Collecting ninja>=1.5
#66 364.4               Downloading ninja-1.11.1.1.tar.gz (132 kB)
#66 364.4                  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.4/132.4 kB 2.2 MB/s eta 0:00:00
#66 364.4               Installing build dependencies: started
#66 364.4               Installing build dependencies: finished with status 'done'
#66 364.4               Getting requirements to build wheel: started
#66 364.4               Getting requirements to build wheel: finished with status 'done'
#66 364.4               Preparing metadata (pyproject.toml): started
#66 364.4               Preparing metadata (pyproject.toml): finished with status 'done'
#66 364.4             Collecting cmake
#66 364.4               Using cached cmake-3.29.2.tar.gz (30 kB)
#66 364.4             ERROR: Exception:
#66 364.4             Traceback (most recent call last):
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
#66 364.4                 status = run_func(*args)
#66 364.4                          ^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
#66 364.4                 return func(self, options, args)
#66 364.4                        ^^^^^^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
#66 364.4                 requirement_set = resolver.resolve(
#66 364.4                                   ^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
#66 364.4                 result = self._result = resolver.resolve(
#66 364.4                                         ^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
#66 364.4                 state = resolution.resolve(requirements, max_rounds=max_rounds)
#66 364.4                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
#66 364.4                 self._add_to_criteria(self.state.criteria, r, parent=None)
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
#66 364.4                 if not criterion.candidates:
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
#66 364.4                 return bool(self._sequence)
#66 364.4                        ^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#66 364.4                 return any(self)
#66 364.4                        ^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#66 364.4                 return (c for c in iterator if id(c) not in self._incompatible_ids)
#66 364.4                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#66 364.4                 candidate = func()
#66 364.4                             ^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
#66 364.4                 base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
#66 364.4                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
#66 364.4                 self._link_candidate_cache[link] = LinkCandidate(
#66 364.4                                                    ^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
#66 364.4                 super().__init__(
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
#66 364.4                 self.dist = self._prepare()
#66 364.4                             ^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
#66 364.4                 dist = self._prepare_distribution()
#66 364.4                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
#66 364.4                 return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#66 364.4                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
#66 364.4                 return self._prepare_linked_requirement(req, parallel_builds)
#66 364.4                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
#66 364.4                 dist = _get_prepared_distribution(
#66 364.4                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 70, in _get_prepared_distribution
#66 364.4                 with build_tracker.track(req, tracker_id):
#66 364.4               File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
#66 364.4                 return next(self.gen)
#66 364.4                        ^^^^^^^^^^^^^^
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/build/build_tracker.py", line 137, in track
#66 364.4                 self.add(req, tracker_id)
#66 364.4               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/build/build_tracker.py", line 103, in add
#66 364.4                 raise LookupError(message)
#66 364.4             LookupError: https://files.pythonhosted.org/packages/80/bf/4f9a9f754507992be28b985d1e9b17f93a2271106b5916a212efe1d65205/cmake-3.29.2.tar.gz (from https://pypi.org/simple/cmake/) (requires-python:>=3.7) is already being built: cmake>=3.14 from https://files.pythonhosted.org/packages/80/bf/4f9a9f754507992be28b985d1e9b17f93a2271106b5916a212efe1d65205/cmake-3.29.2.tar.gz
#66 364.4             [end of output]
#66 364.4       
#66 364.4         note: This error originates from a subprocess, and is likely not a problem with pip.
#66 364.4       error: subprocess-exited-with-error
#66 364.4       
#66 364.4       × pip subprocess to install backend dependencies did not run successfully.
#66 364.4       │ exit code: 2
#66 364.4       ╰─> See above for output.
#66 364.4       
#66 364.4       note: This error originates from a subprocess, and is likely not a problem with pip.
#66 364.4       [end of output]
#66 364.4   
#66 364.4   note: This error originates from a subprocess, and is likely not a problem with pip.
#66 364.4 error: subprocess-exited-with-error
#66 364.4 
#66 364.4 × pip subprocess to install backend dependencies did not run successfully.
#66 364.4 │ exit code: 1
#66 364.4 ╰─> See above for output.
#66 364.4 
#66 364.4 note: This error originates from a subprocess, and is likely not a problem with pip.
#66 ERROR: process "/bin/sh -c /venv-build/bin/python${PYTHON_VERSION} -m pip install --target=\"/venv/lib/python${PYTHON_VERSION}/site-packages\"     -r optional-requirements.txt" did not complete successfully: exit code: 1
```

**Comment by nicolargo** [comment]
The problem came from cmake-3.29.2.tar.gz.

**Comment by nicolargo** [comment]
Look like the bug is already logged here: https://github.com/scikit-build/cmake-python-distributions/issues/494
