### ISSUE TITLE
In codeSpace (with Python 3.8), an error occurs in ./unittest-restful.py

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2773]
```
./venv/bin/python ./unittest-restful.py
Traceback (most recent call last):
  File "./unittest-restful.py", line 20, in <module>
    from glances.outputs.glances_restful_api import GlancesRestfulApi
  File "/workspaces/glances/glances/outputs/glances_restful_api.py", line 20, in <module>
    from typing import Annotated
ImportError: cannot import name 'Annotated' from 'typing' (/usr/lib/python3.8/typing.py)
make: *** [Makefile:69: test-restful] Error 1
```

**Comment by nicolargo** [comment]
Patch done in develop branch,

Will be released in Glances 4.0.5.
