### ISSUE TITLE
Exception when Glances is ran with limited plugin list

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2822]
Example:

glances --disable-plugin all --enable cp

```
Traceback (most recent call last):
                                    File "<frozen runpy>", line 198, in _run_module_as_main
                                                                                             File "<frozen runpy>", line 88, in _run_code
                                                                                                                                           File "/home/nicolargo/dev/glances/glances/__main__.py", line 17, in <module>
                             glances.main()
                                             File "/home/nicolargo/dev/glances/glances/__init__.py", line 173, in main
                                                                                                                          start(config=core.get_config(), args=core.get_args())
                                                                                                                                                                                 File "/home/nicolargo/dev/glances/glances/__init__.py", line 121, in start
                                                                 mode.serve_forever()
                                                                                       File "/home/nicolargo/dev/glances/glances/standalone.py", line 184, in serve_forever
                                                                                                                                                                               while self.__serve_once():
                     ^^^^^^^^^^^^^^^^^^^
                                          File "/home/nicolargo/dev/glances/glances/standalone.py", line 156, in __serve_once
                                                                                                                                 ret = not self.screen.update(self.stats, duration=adapted_refresh)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                             File "/home/nicolargo/dev/glances/glances/outputs/glances_curses.py", line 1186, in update
                                                                                                                                                                           self.flush(stats, cs_status=cs_status)
                     File "/home/nicolargo/dev/glances/glances/outputs/glances_curses.py", line 1167, in flush
                                                                                                                  self.display(stats, cs_status=cs_status)
                                                                                                                                                            File "/home/nicolargo/dev/glances/glances/outputs/glances_curses.py", line 653, in display
                                                            self.separator_line()
                                                                                   File "/home/nicolargo/dev/glances/glances/outputs/glances_curses.py", line 573, in separator_line
                                                                                                                                                                                        self.term_window.addnstr(
                   _curses.error: addnwstr() returned ERR
```

**Comment by nicolargo** [comment]
Exception should be catched in separator method.

**Comment by nicolargo** [comment]
Corrected in develop branch.
