### ISSUE TITLE
Graph export is broken if there is no graph section in Glances configuration file

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2839]
With Glances 4.0.8 and no [graph] section in glances.conf then:

```
./venv/bin/python -m glances --export graph --export-graph-path /tmp
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nhe/dev/glances/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/home/nhe/dev/glances/glances/__init__.py", line 173, in main
    start(config=core.get_config(), args=core.get_args())
  File "/home/nhe/dev/glances/glances/__init__.py", line 102, in start
    mode = GlancesMode(config=config, args=args)
  File "/home/nhe/dev/glances/glances/standalone.py", line 42, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/home/nhe/dev/glances/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/home/nhe/dev/glances/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/home/nhe/dev/glances/glances/stats.py", line 214, in load_exports
    self._exports[exporter_name] = export_module.Export(args=args, config=self.config)
  File "/home/nhe/dev/glances/glances/exports/glances_graph/__init__.py", line 37, in __init__
    self.generate_every = int(getattr(self, 'generate_every', 0))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Default value should be set for generate_every, path and size.

**Comment by nicolargo** [comment]
Corrected in develop branch.
