### ISSUE TITLE
Glances 4.1.1 on Windows - AttributeError: 'CpuPercent' object has no attribute 'cpu_percent'

### ISSUE THREAD

**Issue by AnthonyBe** [nicolargo/glances#2859]
**Describe the bug**
I updated from Glances 4.0.8 to 4.1.1 and now receive the following errors on launch:

```
Error while initializing the cpu plugin ('CpuPercent' object has no attribute 'cpu_percent')
Error while initializing the percpu plugin ('CpuPercent' object has no attribute 'cpu_percent')
Error while initializing the quicklook plugin ('CpuPercent' object has no attribute 'cpu_percent')
```
In the logfile, primary issue summary:

`AttributeError: 'CpuPercent' object has no attribute 'cpu_percent'`

and then CPU module fails to load.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Glances with the following options: glances -w
2. See error

**Expected behaviour**
CPU module to not error

**Screenshots**

**Environment (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): Windows Server 2016 and python 3.12.3
 - Glances & psutil versions: Glances 4.1.1 and psutil 5.9.8
 - How do you install Glances (Pypi package, script, package manager, source): Pypi
 - Glances test: ` To be completed with result of: glances --issue`

```
C:\WINDOWS\system32>glances --issue
Error while initializing the cpu plugin ('CpuPercent' object has no attribute 'cpu_percent')
Error while initializing the percpu plugin ('CpuPercent' object has no attribute 'cpu_percent')
Error while initializing the quicklook plugin ('CpuPercent' object has no attribute 'cpu_percent')
===============================================================================
Glances [94m4.1.1[0m (C:\Python312\Lib\site-packages\glances\__init__.py)
Python [94m3.12.3[0m (C:\Python312\python.exe)
PsUtil [94m5.9.8[0m (C:\Python312\Lib\site-packages\psutil\__init__.py)
===============================================================================
[94malert         [92m[OK]   [94m 0.00000s
[0m[][0m
[94mamps          [92m[OK]   [94m 0.00000s [93mkey=name [0m
[{'count': 0,
  'countmax': None,
  'countmin': 1.0,
  'key': 'name',
  'name': 'Dropbox',
  'refresh': 3.0,
  'regex': True,
  'result': None,
  'timer': 5.579416751861572}, ...][0m
[94mcloud[0m         [NA][0m[0m
[94mconnections[0m   [NA][0m[0m
[94mcontainers[0m    [NA][0m[0m
[94mcore          [92m[OK]   [94m 0.00000s
[0m{'log': 2, 'phys': 2}[0m
[94mdiskio        [92m[OK]   [94m 0.00000s [93mkey=disk_name [0m
[{'disk_name': 'PhysicalDrive0',
  'key': 'disk_name',
  'read_bytes': 205312,
  'read_bytes_gauge': 96912597504,
  'read_bytes_rate_per_sec': 98299.0,
  'read_count': 10,
  'read_count_gauge': 5274162,
  'read_count_rate_per_sec': 4.0,
  'time_since_update': 2.0886406898498535,
  'write_bytes': 1073152,
  'write_bytes_gauge': 336260792832,
  'write_bytes_rate_per_sec': 513804.0,
  'write_count': 114,
  'write_count_gauge': 29151108,
  'write_count_rate_per_sec': 54.0}, ...][0m
[94mfolders[0m       [NA][0m[0m
[94mfs            [92m[OK]   [94m 0.00000s [93mkey=mnt_point [0m
[{'device_name': 'C:\\',
  'free': 208758390784,
  'fs_type': 'NTFS',
  'key': 'mnt_point',
  'mnt_point': 'C:\\',
  'percent': 62.0,
  'size': 549048020992,
  'used': 340289630208}, ...][0m
[94mgpu[0m           [NA][0m[0m
[94mhelp          [92m[OK]   [94m 0.00000s
[0mNone[0m
[94mip            [92m[OK]   [94m 2.01624s
[0m{'address': '***', 'gateway': '***', 'mask': '***', 'mask_cidr': '***'}[0m
[94mirq[0m           [NA][0m[0m
[94mload          [92m[OK]   [94m 0.00000s
[0m{'cpucore': 2, 'min1': 0.0, 'min15': 0.0, 'min5': 0.0}[0m
[94mmem           [92m[OK]   [94m 0.00000s
[0m{'available': 5061533696, 'free': 5061533696, 'percent': 70.5, 'total': 17143681024, 'used': 12082147328}[0m
[94mmemswap       [92m[OK]   [94m 0.00000s
[0m{'free': 2310197248,
 'percent': 9.4,
 'sin': 0,
 'sout': 0,
 'time_since_update': 4.456623792648315,
 'total': 2550136832,
 'used': 239939584}[0m
[94mnetwork       [92m[OK]   [94m 0.01563s [93mkey=interface_name [0m
[{'alias': None,
  'bytes_all': 0,
  'bytes_all_gauge': 0,
  'bytes_all_rate_per_sec': 0.0,
  'bytes_recv': 0,
  'bytes_recv_gauge': 0,
  'bytes_recv_rate_per_sec': 0.0,
  'bytes_sent': 0,
  'bytes_sent_gauge': 0,
  'bytes_sent_rate_per_sec': 0.0,
  'interface_name': 'Ethernet 2',
  'key': 'interface_name',
  'speed': 0,
  'time_since_update': 4.104231834411621}, ...][0m
[94mnow           [92m[OK]   [94m 0.00000s
[0m{'custom': '2024-07-01 10:44:46 +1000', 'iso': '2024-07-01T10:44:46+10:00'}[0m
[94mports         [92m[OK]   [94m 0.00000s [93mkey=indice [0m
[{'description': 'DefaultGateway',
  'host': '192.168.0.1',
  'indice': 'port_0',
  'key': 'indice',
  'port': 0,
  'refresh': 30,
  'rtt_warning': None,
  'status': 0.113514,
  'timeout': 3}, ...][0m
[94mprocesscount  [92m[OK]   [94m 0.18751s
[0m{'pid_max': 0, 'running': 85, 'sleeping': 0, 'thread': 1079, 'total': 88}[0m
[94mprocesslist   [92m[OK]   [94m 0.00000s
[0m[][0m
[94mpsutilversion [92m[OK]   [94m 0.00000s
[0m'5.9.8'[0m
[94mraid[0m          [NA][0m[0m
[94msensors[0m       [NA][0m[0m
[94msmart[0m         [NA][0m[0m
[94msystem        [92m[OK]   [94m 0.00000s
[0m{'hostname': 'ANTMICROSERVER',
 'hr_name': 'Windows 2016Server SP0 64bit',
 'os_name': 'Windows',
 'os_version': '2016Server SP0',
 'platform': '64bit'}[0m
[94muptime        [92m[OK]   [94m 0.00000s
[0m{'seconds': 342513}[0m
[94mversion       [92m[OK]   [94m 0.00000s
[0m'4.1.1'[0m
[94mwifi[0m          [NA][0m[0m
===============================================================================
Total time to update all stats: [94m2.30490s[0m
===============================================================================
```

**Additional context**
Full log:

```
2024-07-01 10:35:41,930 -- WARNING -- PsUtil can not grab processes gids ('Process' object has no attribute 'gids')
2024-07-01 10:35:41,930 -- INFO -- Start Glances 4.1.1
2024-07-01 10:35:41,930 -- INFO -- CPython 3.12.3 (C:\Python312\python.exe) and psutil 5.9.8 detected
2024-07-01 10:35:41,962 -- INFO -- Read configuration file 'C:\Users\Administrator\AppData\Roaming\glances\glances.conf'
2024-07-01 10:35:49,738 -- INFO -- Start GlancesWebServer mode
2024-07-01 10:35:57,095 -- ERROR -- containers (Docker) plugin - Can't connect to Docker (Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.'))
2024-07-01 10:35:57,220 -- CRITICAL -- Error while initializing the cpu plugin ('CpuPercent' object has no attribute 'cpu_percent')
2024-07-01 10:35:57,397 -- ERROR -- Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\glances\stats.py", line 100, in _load_plugin
    plugin = import_module('glances.plugins.' + plugin_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Python312\Lib\site-packages\glances\plugins\cpu\__init__.py", line 13, in <module>
    from glances.cpu_percent import cpu_percent
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 132, in <module>
    cpu_percent = CpuPercent()
                  ^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 36, in __init__
    self.cpu_percent = self.get_cpu()
                       ^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 89, in get_cpu
    return self.cpu_percent
           ^^^^^^^^^^^^^^^^
AttributeError: 'CpuPercent' object has no attribute 'cpu_percent'

2024-07-01 10:35:58,402 -- CRITICAL -- Error while initializing the percpu plugin ('CpuPercent' object has no attribute 'cpu_percent')
2024-07-01 10:35:58,447 -- ERROR -- Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\glances\stats.py", line 100, in _load_plugin
    plugin = import_module('glances.plugins.' + plugin_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Python312\Lib\site-packages\glances\plugins\percpu\__init__.py", line 11, in <module>
    from glances.cpu_percent import cpu_percent
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 132, in <module>
    cpu_percent = CpuPercent()
                  ^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 36, in __init__
    self.cpu_percent = self.get_cpu()
                       ^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 89, in get_cpu
    return self.cpu_percent
           ^^^^^^^^^^^^^^^^
AttributeError: 'CpuPercent' object has no attribute 'cpu_percent'

2024-07-01 10:35:58,847 -- CRITICAL -- Error while initializing the quicklook plugin ('CpuPercent' object has no attribute 'cpu_percent')
2024-07-01 10:35:58,855 -- ERROR -- Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\glances\stats.py", line 100, in _load_plugin
    plugin = import_module('glances.plugins.' + plugin_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Python312\Lib\site-packages\glances\plugins\quicklook\__init__.py", line 13, in <module>
    from glances.cpu_percent import cpu_percent
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 132, in <module>
    cpu_percent = CpuPercent()
                  ^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 36, in __init__
    self.cpu_percent = self.get_cpu()
                       ^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\glances\cpu_percent.py", line 89, in get_cpu
    return self.cpu_percent
           ^^^^^^^^^^^^^^^^
AttributeError: 'CpuPercent' object has no attribute 'cpu_percent'

2024-07-01 10:36:05,148 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/4
2024-07-01 10:36:05,164 -- INFO -- Get WebUI in C:\Python312\Lib\site-packages\glances\outputs\static/public
2024-07-01 10:36:05,164 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/
```

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
[glances.conf.txt](https://github.com/user-attachments/files/16046858/glances.conf.txt)

* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)
[glances-Administrator.log](https://github.com/user-attachments/files/16046859/glances-Administrator.log)

**Comment by RazCrimson** [comment]
@AnthonyBe Could you just test out the latest develop?

**Comment by AnthonyBe** [comment]
Apologies, first time installing non-prod version of Glances.
I just tried installing latest develop version by following steps in [README ](https://github.com/nicolargo/glances?tab=readme-ov-file#installation)for PyPi install:
`pip install --user -i https://test.pypi.org/simple/ Glances`
however it only offered Glances 4.1.1? I can see 4.2.0 beta on the site but not sure why above is not picking it up?

**Comment by RazCrimson** [comment]
@AnthonyBe @Jayspek 
Can anyone of you try out this?
```pip install -i https://test.pypi.org/simple/ Glances==4.2.0b2```

**Comment by Chuffnugget** [comment]
> @AnthonyBe @Jayspek Can anyone of you try out this? `pip install -i https://test.pypi.org/simple/ Glances==4.2.0b2`

I had exactly the same issue as OP, it's working on 4.2.0b2, thanks!

**Comment by AnthonyBe** [comment]
> @AnthonyBe @Jayspek Can anyone of you try out this? `pip install -i https://test.pypi.org/simple/ Glances==4.2.0b2`

Yep, 4.2.0b2 has resolved the issue for me as well.
