### ISSUE TITLE
raid plugin breaks with inactive raid0 arrays

### ISSUE THREAD

**Issue by jimk-bdrc** [nicolargo/glances#2908]
**Check the bug**
I haven't seen this mentioned in `is:issue is:open terminal

**Describe the bug**
I have two Debian buster (10) instances, both python 3.9.
On one, glances works fine. `$ glances`
On the other,  `glances` emits a curses error, and breaks the screen.

and the terminal subsequently replaces CRLF with LF only. All subsequent output lacks a CR:

```
ls
 5works                 full2015.csv   sini-usb            sini-work-list                  werke
                                                                                                '#arc-image-size.py#'   run30.csv      sini-usb.para.log   tibetan_ok_third_party_p1.csv
                                       %
```

Also, the TERM is set to `screen`

This occurs when I ssh onto the bad debian system from either:
- MacOS iterm 3.5.3 (TERM=xterm-256color)
- Windows shell (TERM=xterm-256color)
**To Reproduce**
1. Start Glances with the following options:none
2. See error

**Expected behavior**
I expect glances to appear in its terminal brilliance

**Screenshots**
```
Traceback (most recent call last):
                                    File "/home/jimk/.local/bin/glances", line 8, in <module>
                                                                                                 sys.exit(main())
                                                                                                                   File "/home/jimk/.local/lib/python3.9/site-packages/glances/__init__.py", line 173, in main
                                                                 start(config=core.get_config(), args=core.get_args())
                                                                                                                        File "/home/jimk/.local/lib/python3.9/site-packages/glances/__init__.py", line 121, in start
                                                                       mode.serve_forever()
                                                                                             File "/home/jimk/.local/lib/python3.9/site-packages/glances/standalone.py", line 184, in serve_forever
                                                      while self.__serve_once():
                                                                                  File "/home/jimk/.local/lib/python3.9/site-packages/glances/standalone.py", line 156, in __serve_once
                                          ret = not self.screen.update(self.stats, duration=adapted_refresh)
                                                                                                              File "/home/jimk/.local/lib/python3.9/site-packages/glances/outputs/glances_curses.py", line 1062, in update
                                                                             self.flush(stats, cs_status=cs_status)
                                                                                                                     File "/home/jimk/.local/lib/python3.9/site-packages/glances/outputs/glances_curses.py", line 1043, in flush
                                                                                   self.display(stats, cs_status=cs_status)
                                                                                                                             File "/home/jimk/.local/lib/python3.9/site-packages/glances/outputs/glances_curses.py", line 512, in display
                                                                                            __stat_display = self.__get_stat_display(stats, layer=cs_status)
             File "/home/jimk/.local/lib/python3.9/site-packages/glances/outputs/glances_curses.py", line 488, in __get_stat_display
                                                                                                                                        ret[p] = stats.get_plugin(p).get_stats_display(args=self.args, max_width=plugin_max_width)
                                                                                   File "/home/jimk/.local/lib/python3.9/site-packages/glances/plugins/plugin/model.py", line 916, in get_stats_display
                                                          ret = {'display': display_curse, 'msgdict': self.msg_curse(args, max_width=max_width), 'align': align_curse}
                       File "/home/jimk/.local/lib/python3.9/site-packages/glances/plugins/raid/__init__.py", line 138, in msg_curse
                                                                                                                                        if self.stats[array]['type'] != 'raid0' and (self.stats[array]['used'] < self.stats[array]['available']):
                                                                                                TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

**Environment (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): `To be completed with result of: lsb_release -a`
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

 - Glances & psutil versions: `To be completed with result of: glances -V`
 ❯ glances -V
Glances version:	4.1.2
Glances API version:	4
PsUtil version:		6.0.0
Log file:		/home/jimk/.local/share/glances/glances.log
**The system where it works has PsUtil 5.9.5** but replacing psutil 6.0.0 with 5.9.5 doesn't affect the output on the bad system.

 - How do you install Glances (Pypi package, script, package manager, source): 
 - `pip install glances`
 - Glances test: ` To be completed with result of: glances --issue`
Normal seeming output

**Additional context**

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
No known log file
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)
See [pastebin](https://pastebin.com/EiULMV17)

**Comment by RazCrimson** [comment]
@jimk-bdrc 

Could you just give me the output of running the below in a python shell?
```
import pymdstat; pymdstat.MdStat().get_stats()
```

**Comment by jimk-bdrc** [comment]
Thanks!

On the system where glances works:

```
❯ python
Python 3.9.1 (default, Dec 22 2022, 17:12:51)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymdstat; pymdstat.MdStat().get_stats()
{'personalities': ['linear', 'multipath', 'raid0', 'raid1', 'raid6', 'raid5', 'raid4', 'raid10'], 'arrays': {}}
```

On the system where glances fails:

```
❯ python
Python 3.9.17 (main, Aug 29 2023, 14:47:57)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymdstat; pymdstat.MdStat().get_stats()
{'personalities': ['linear', 'multipath', 'raid0', 'raid1', 'raid6', 'raid5', 'raid4', 'raid10'], 'arrays': {'md4': {'status': 'inactive', 'type': None, 'components': {'sdb3': '4'}, 'available': None, 'used': None, 'config': None}}}
>>>
```
