### ISSUE TITLE
Glances will not start. same error installed from snap and from debian unstable.

### ISSUE THREAD

**Issue by cribbageSTARSHIP** [nicolargo/glances#2973]
**Check the bug**
Before filling this bug report, please search if a similar issue already exists.
In this case, just add a comment on this existing issue.

This issue seems to be the same as [here](https://github.com/nicolargo/glances/issues/1769). Here is my specific prinout:

**Describe the bug**

Here is my specific prinout:

`/snap/glances/current/bin/glances -w
Traceback (most recent call last):
  File "/snap/glances/current/bin/glances", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/__init__.py", line 173, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/__init__.py", line 102, in start
    mode = GlancesMode(config=config, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/webserver.py", line 29, in __init__
    self.stats.update()
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/stats.py", line 269, in update
    self.__update_plugin(p)
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/stats.py", line 258, in __update_plugin
    self._plugins[p].update()
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/plugins/plugin/model.py", line 1124, in wrapper
    ret = fct(self, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/plugins/plugin/model.py", line 1141, in wrapper
    ret = fct(*args, **kw)
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/plugins/containers/__init__.py", line 229, in update
    version, containers = watcher.update(all_tag=self._all_tag())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/plugins/containers/engines/docker.py", line 280, in update
    container_stats = [self.generate_stats(container) for container in containers]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/plugins/containers/engines/docker.py", line 280, in <listcomp>
    container_stats = [self.generate_stats(container) for container in containers]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/plugins/containers/engines/docker.py", line 346, in generate_stats
    stats['uptime'] = pretty_date(parser.parse(started_at).astimezone(tz.tzlocal()).replace(tzinfo=None))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/globals.py", line 333, in pretty_date
    diff = get_diff_time(time)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Glances-4.2.0b4-py3.11.egg/glances/globals.py", line 282, in get_diff_time
    isinstance(time, int): now - datetime.fromtimestamp(time),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'datetime.datetime' object cannot be interpreted as an integer
`

**To Reproduce**
1. Start Glances with the following options '...'
2. Press the key '....'
3. See error

**Expected behavior**

**Screenshots**

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): `To be completed with result of: lsb_release -a`
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

 - Glances & psutil versions: `To be completed with result of: glances -V`
/snap/glances/current/bin/glances -V
Glances version:	4.2.0_beta04
Glances API version:	4
PsUtil version:		5.9.4
Log file:		/home/prizm/.local/share/glances/glances.log

psutils/stable 1.17.dfsg-4 amd64 

 - How do you install Glances (Pypi package, script, package manager, source): `To be completed`

I had the same error installing glances from source, unstable, and snap.

 - Glances test: ` To be completed with result of: glances --issue`

[glances --issue](https://pastebin.com/XpWurL1E)

**Additional context**

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)

[Glances configuration file](https://pastebin.com/Nh0i7Le9)
[Glances log file](https://pastebin.com/gXwJ8FGj)

**Comment by cribbageSTARSHIP** [comment]
I should add that I've tried installing from source, debian unstable, and now snap

**Comment by nicolargo** [comment]
Reproduced on my side:

```
➜ make run
venv/bin/python -m glances -C conf/glances.conf
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/nicolargo/dev/glances/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/home/nicolargo/dev/glances/glances/__init__.py", line 173, in main
    start(config=core.get_config(), args=core.get_args())
  File "/home/nicolargo/dev/glances/glances/__init__.py", line 102, in start
    mode = GlancesMode(config=config, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolargo/dev/glances/glances/standalone.py", line 77, in __init__
    self.stats.update()
  File "/home/nicolargo/dev/glances/glances/stats.py", line 269, in update
    self.__update_plugin(p)
  File "/home/nicolargo/dev/glances/glances/stats.py", line 258, in __update_plugin
    self._plugins[p].update()
  File "/home/nicolargo/dev/glances/glances/plugins/plugin/model.py", line 1124, in wrapper
    ret = fct(self, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolargo/dev/glances/glances/plugins/plugin/model.py", line 1141, in wrapper
    ret = fct(*args, **kw)
          ^^^^^^^^^^^^^^^^
  File "/home/nicolargo/dev/glances/glances/plugins/containers/__init__.py", line 229, in update
    version, containers = watcher.update(all_tag=self._all_tag())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolargo/dev/glances/glances/plugins/containers/engines/docker.py", line 280, in update
    container_stats = [self.generate_stats(container) for container in containers]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolargo/dev/glances/glances/plugins/containers/engines/docker.py", line 346, in generate_stats
    stats['uptime'] = pretty_date(parser.parse(started_at).astimezone(tz.tzlocal()).replace(tzinfo=None))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolargo/dev/glances/glances/globals.py", line 333, in pretty_date
    diff = get_diff_time(time)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/nicolargo/dev/glances/glances/globals.py", line 282, in get_diff_time
    isinstance(time, int): now - datetime.fromtimestamp(time),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'datetime.datetime' object cannot be interpreted as an integer
^CException ignored in: <module 'threading' from '/usr/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1622, in _shutdown
    lock.acquire()
  File "/home/nicolargo/dev/glances/glances/__init__.py", line 59, in __signal_handler
    end()
  File "/home/nicolargo/dev/glances/glances/__init__.py", line 74, in end
    sys.exit(0)
SystemExit: 0
make: *** [Makefile:262 : run] Erreur 1
```

**Comment by nicolargo** [comment]
I just revert the PR https://github.com/nicolargo/glances/pull/2961
Problem solved on the develop branch.

Thanks for the issue report  @cribbageSTARSHIP
