### ISSUE TITLE
Non blocking error message when Glances starts from a container (alpine-dev image)

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2991]
Perhaps related to the migration from Python 3.11 to Python 3.12 in the container:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/handlers.py", line 193, in shouldRollover
    pos = self.stream.tell()
          ^^^^^^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 159, in main
    logger.info(f'Start Glances {__version__}')
Message: 'Start Glances 4.3.0_dev02'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/handlers.py", line 193, in shouldRollover
    pos = self.stream.tell()
          ^^^^^^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 162, in main
    logger.info(f'{python_impl} {python_ver} ({sys.executable}) and psutil {psutil_version} detected')
Message: 'CPython 3.12.7 (/venv/bin/python3) and psutil 6.1.0 detected'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/handlers.py", line 193, in shouldRollover
    pos = self.stream.tell()
          ^^^^^^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 170, in main
    core = GlancesMain()
  File "/app/glances/main.py", line 99, in __init__
    self.args = self.parse_args()
  File "/app/glances/main.py", line 735, in parse_args
    self.config = Config(args.conf_file)
  File "/app/glances/config.py", line 130, in __init__
    self.read()
  File "/app/glances/config.py", line 175, in read
    logger.info(f"Read configuration file '{config_file}'")
Message: "Read configuration file '/etc/glances/glances.conf'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/handlers.py", line 193, in shouldRollover
    pos = self.stream.tell()
          ^^^^^^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 173, in main
    start(config=core.get_config(), args=core.get_args())
  File "/app/glances/__init__.py", line 101, in start
    logger.info(f"Start {GlancesMode.__name__} mode")
Message: 'Start GlancesStandalone mode'
Arguments: ()
```

**Comment by nicolargo** [comment]
Additional information:

No error with Ubuntu image (CPython 3.12.3):

```
➜ make run-docker-ubuntu-dev 
docker run --rm -e TZ="" -e GLANCES_OPT="" --pid host --network host -v /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro -v /var/run/docker.sock:/var/run/docker.sock:ro -it glances:local-ubuntu-dev
2024-10-26 07:13:18,939 -- INFO -- Start Glances 4.3.0_dev02
2024-10-26 07:13:18,940 -- INFO -- CPython 3.12.3 (/venv/bin/python3) and psutil 6.1.0 detected
2024-10-26 07:13:18,943 -- INFO -- Read configuration file '/etc/glances/glances.conf'
2024-10-26 07:13:19,093 -- INFO -- Start GlancesStandalone mode
```

Error with the Alpine image (CPython 3.12.7):

```
➜ make run-docker-alpine-dev 
docker run --rm -e TZ="" -e GLANCES_OPT="" --pid host --network host -v /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro -v /var/run/docker.sock:/var/run/docker.sock:ro -it glances:local-alpine-dev
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/handlers.py", line 193, in shouldRollover
    pos = self.stream.tell()
          ^^^^^^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 159, in main
    logger.info(f'Start Glances {__version__}')
Message: 'Start Glances 4.3.0_dev02'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/handlers.py", line 193, in shouldRollover
    pos = self.stream.tell()
          ^^^^^^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 162, in main
    logger.info(f'{python_impl} {python_ver} ({sys.executable}) and psutil {psutil_version} detected')
Message: 'CPython 3.12.7 (/venv/bin/python3) and psutil 6.1.0 detected'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/handlers.py", line 193, in shouldRollover
    pos = self.stream.tell()
          ^^^^^^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 170, in main
    core = GlancesMain()
  File "/app/glances/main.py", line 99, in __init__
    self.args = self.parse_args()
  File "/app/glances/main.py", line 735, in parse_args
    self.config = Config(args.conf_file)
  File "/app/glances/config.py", line 130, in __init__
    self.read()
  File "/app/glances/config.py", line 175, in read
    logger.info(f"Read configuration file '{config_file}'")
Message: "Read configuration file '/etc/glances/glances.conf'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/handlers.py", line 193, in shouldRollover
    pos = self.stream.tell()
          ^^^^^^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/glances/__main__.py", line 17, in <module>
    glances.main()
  File "/app/glances/__init__.py", line 173, in main
    start(config=core.get_config(), args=core.get_args())
  File "/app/glances/__init__.py", line 101, in start
    logger.info(f"Start {GlancesMode.__name__} mode")
Message: 'Start GlancesStandalone mode'
Arguments: ()
```

**Comment by nicolargo** [comment]
Patch done on the develop branch.
