### ISSUE TITLE
Glances 4.3.0 | Error while initializing the ports plugin (No implementation for `gateways()` yet)

### ISSUE THREAD

**Issue by AnthonyBe** [nicolargo/glances#3072]
**Describe the bug**
Ref this as starting point - https://github.com/nicolargo/glances/discussions/3064
So after installing via `pip install glances` all was fine.
Then ran `pip install glances[all]` which also installed netifaces2 lib and when I then ran Glances I got error:

```
C:\WINDOWS\system32>glances -w --fs-free-space --enable-process-extended --config %APPDATA%\glances\glances.conf
Error while initializing the ports plugin (No implementation for `gateways()` yet)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python313\Scripts\glances.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "c:\Python313\Lib\site-packages\glances\__init__.py", line 173, in main
    start(config=core.get_config(), args=core.get_args())
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\site-packages\glances\__init__.py", line 102, in start
    mode = GlancesMode(config=config, args=args)
  File "c:\Python313\Lib\site-packages\glances\webserver.py", line 32, in __init__
    self.stats.update()
    ~~~~~~~~~~~~~~~~~^^
  File "c:\Python313\Lib\site-packages\glances\stats.py", line 269, in update
    self.__update_plugin(p)
    ~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\site-packages\glances\stats.py", line 258, in __update_plugin
    self._plugins[p].update()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Python313\Lib\site-packages\glances\plugins\plugin\model.py", line 1124, in wrapper
    ret = fct(self, *args, **kw)
  File "c:\Python313\Lib\site-packages\glances\plugins\plugin\model.py", line 1141, in wrapper
    ret = fct(*args, **kw)
  File "c:\Python313\Lib\site-packages\glances\plugins\ip\__init__.py", line 144, in update
    stats = self.get_stats_for_local_input(stats)
  File "c:\Python313\Lib\site-packages\glances\plugins\ip\__init__.py", line 157, in get_stats_for_local_input
    stop, stats = self.get_private_ip(stats)
                  ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "c:\Python313\Lib\site-packages\glances\plugins\ip\__init__.py", line 91, in get_private_ip
    default_gw = netifaces.gateways()[netifaces.AF_INET][0]
                 ~~~~~~~~~~~~~~~~~~^^
  File "c:\Python313\Lib\site-packages\netifaces\__init__.py", line 232, in gateways
    raise NotImplementedError("No implementation for `gateways()` yet")
NotImplementedError: No implementation for `gateways()` yet
```

I disabled Ports module in my conf file but it still errors.

**Environment**
 - Operating System: Windows Server 2016, python 3.13.1
 - Glances & psutil versions: Glances version 4.3.0.6, psutil 6.1.0

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)

[glances.conf-no Ports.txt](https://github.com/user-attachments/files/18279231/glances.conf-no.Ports.txt)

**Comment by nicolargo** [comment]
Yes, netifaces is deprecated and should be uninstall. instead netifaces2 should be install:

```
pip uninstall netifaces
pip install netifaces2
```
