### ISSUE TITLE
Bugs with SNMP mode.

### ISSUE THREAD

**Issue by t00sh** [nicolargo/glances#362]
Bonjour,
j'ai deux problèmes avec le mode SNMP.

### 1/
Avec la version 1 du protocole, lorsque je lance : 
```
$ LANGUAGE=en_US.utf8  ~/glances-venv/bin/python -m glances --snmp-version 1 --snmp-community public -c 192.168.1.5
```
Glances se termine avec pleins de messages d'erreurs, et en laissant le terminal dans un mauvais état. (obligé de lancer la commande "reset")

Voici les messages d'erreurs : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main                                                                                                                 "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tosh/tmp/glances/glances/__main__.py", line 38, in <module>                                                                                                              glances.main()
  File "/home/tosh/tmp/glances/glances/__init__.py", line 104, in main
    if not client.login():
  File "/home/tosh/tmp/glances/glances/core/glances_client.py", line 129, in login                                                                                                     self.screen = glancesCurses(args=self.args)
  File "/home/tosh/tmp/glances/glances/outputs/glances_curses.py", line 72, in __init__
    curses.cbreak()                                                                                                                                                                _curses.error: cbreak() returned ERR
```

```
Info: Connection to Glances server failed. Trying fallback to SNMP...                                                                                                              Error: Update mem failed: 'dict' object has no attribute 'iterkeys'
Error: Update uptime failed: 'dict' object has no attribute 'iterkeys'
Error: Update cpu failed: 'dict' object has no attribute 'iterkeys'
Error: Update memswap failed: 'dict' object has no attribute 'iterkeys'                                                                                                            Error: Update system failed: 'dict' object has no attribute 'iterkeys'
Error: Update load failed: 'dict' object has no attribute 'iterkeys'
```
À noter que avec snmpwalk, tout marche niquel : 
```
snmpwalk -v 1 -c public 192.168.1.5
```

#### 2/
Le deuxième problème n'est pas vraiment un bug, et concerne la version 3 du protocole SNMP.
En fait, je n'arrive pas à m'authentifier auprès du serveur lorsque j'utilise l'algorithme SHA. Avec MD5, j'ai le même bug que le 1/, je suppose donc que l'authentification auprès du serveur fonctionnne.

Voici comment je procède avec snmpwalk : 
```
snmpwalk -v 3 -u neo-snmp -a SHA -A PASS -x AES -X PASS -l authPriv 192.168.1.5
```

Puis avec Glances : 
```
LANGUAGE=en_US.utf8  ~/glances-venv/bin/python -m glances --snmp-version 3 --snmp-user neo-snmp --snmp-auth PASS -c 192.168.1.5
```

#### Environnement
Agent SNMP : Raspberry PI
```
Linux neo 3.10.27+ #630 PREEMPT Fri Jan 17 19:44:36 GMT 2014 armv6l GNU/Linux
```

Client Glances : ArchLinux 32 bits
```
Linux morpheus 3.14.4-1-ARCH #1 SMP PREEMPT Tue May 13 16:44:54 CEST 2014 i686 GNU/Linux
```

Version de Glances : 
```
Glances v2.0_RC2 with psutil v2.1.1
```

Voilà, si tu as des questions, n'hésite pas. Et peut être que je n'utilise tout simplement pas Glances correctement :) .

Cordialement, 
-TOSH-

**Comment by nicolargo** [comment]
Support of the SNMP protocol v3 to be postpone to a future release.
