### ISSUE TITLE
Cannot start glances 2.0.1 using pip on Debian

### ISSUE THREAD

**Issue by rverchere** [nicolargo/glances#399]
I upgraded the glances application using pip on my Debian oldstable server, and I cannot start glances anymore.

<pre>
$ sudo pip install glances --upgrade
[...]
$ glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.0.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2244, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.6/dist-packages/glances/__init__.py", line 50, in <module>
    from glances.core.glances_globals import gettext_domain, locale_dir
ImportError: No module named core.glances_globals
</pre>

**Comment by rverchere** [comment]
For the record, it was a pip vs debian package issue.

When upgrading Glances using pip on Debian, the old Glances install dir was not deleted, so it led to misconfiguration when starting the new package (PYTHONPATH or PATH or whatelse issue).

So I had to delete manually all /usr/local/lib/python2.7/dist-package/Glances* dir and reinstall Glances to make it work again
