### ISSUE TITLE
psutil.NoSuchProcess: process no longer exists 

### ISSUE THREAD

**Issue by hank** [nicolargo/glances#432]
Using latest develop HEAD:

```
Traceback (most recent call last):  
     File "/usr/local/bin/glances", line 9, in <module>
                                                           load_entry_point('Glances==2.2-BETA', 'console_scripts', 'glances')()  
File "/usr/local/lib/python2.7/dist-packages/Glances-2.2_BETA-py2.7.egg/glances/__init__.py", line 121, in main
               standalone.serve_forever()  
File "/usr/local/lib/python2.7/dist-packages/Glances-2.2_BETA-py2.7.egg/glances/core/glances_standalone.py", line 71, in serve_forever
                                                                  self.stats.update()  
File "/usr/local/lib/python2.7/dist-packages/Glances-2.2_BETA-py2.7.egg/glances/core/glances_stats.py", line 130, in update
                                                                                                   self.__update__(input_stats)  
File "/usr/local/lib/python2.7/dist-packages/Glances-2.2_BETA-py2.7.egg/glances/core/glances_stats.py", line 121, in __update__
                              self._plugins[p].update()  
File "/usr/local/lib/python2.7/dist-packages/Glances-2.2_BETA-py2.7.egg/glances/plugins/glances_processcount.py", line 55, in update
                                                                              glances_processes.update()  
File "/usr/local/lib/python2.7/dist-packages/Glances-2.2_BETA-py2.7.egg/glances/core/glances_processes.py", line 345, in update
       self.processcount[str(proc.status())] = 1  
File "build/bdist.linux-x86_64/egg/psutil/__init__.py", line 555, in status  
File "build/bdist.linux-x86_64/egg/psutil/_pslinux.py", line 707, in wrapper
psutil.NoSuchProcess: process no longer exists (pid=19691, name='Plex')
```

Looks like you still need exception handling around the psutil call in the loop to deal with this.  It happens rarely, but enough that every couple of days it's crashed.

**Comment by bchretien** [comment]
I'm getting this issue again with the last release (2.4.1):

```sh
$ glances --version
Glances v2.4.1 with psutil v2.2.1
$ glances
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/psutil/_pslinux.py", line 645, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/psutil/_pslinux.py", line 1082, in uids
    with open("/proc/%s/status" % self.pid, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/21664/status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.1', 'console_scripts', 'glances')()
  File "/usr/lib/python3.4/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/lib/python3.4/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/lib/python3.4/site-packages/glances/core/glances_standalone.py", line 89, in __serve_forever
    self.stats.update()
  File "/usr/lib/python3.4/site-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/lib/python3.4/site-packages/glances/plugins/glances_processcount.py", line 58, in update
    glances_processes.update()
  File "/usr/lib/python3.4/site-packages/glances/core/glances_processes.py", line 596, in update
    standard_stats=self.max_processes is None)
  File "/usr/lib/python3.4/site-packages/glances/core/glances_processes.py", line 562, in __get_process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "/usr/lib/python3.4/site-packages/glances/core/glances_processes.py", line 379, in __get_mandatory_stats
    'name', 'cpu_times'], ad_value=''))
  File "/usr/lib/python3.4/site-packages/psutil/__init__.py", line 429, in as_dict
    ret = attr()
  File "/usr/lib/python3.4/site-packages/psutil/__init__.py", line 580, in username
    real_uid = self.uids().real
  File "/usr/lib/python3.4/site-packages/psutil/__init__.py", line 617, in uids
    return self._proc.uids()
  File "/usr/lib/python3.4/site-packages/psutil/_pslinux.py", line 654, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=21664)
```

I guess some `try/catch` blocks are missing.
