### ISSUE TITLE
R/W error with the glances.log file

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#474]
Message lliseil:

===

Bonjour

Lancer glances en user échoue si un autre user ou root l'ont déja lancé pendant la session.

J'ai tenté d'ajouter un 'log_file = /pah/to/glances_USER.log' dans $XDG_CONFIG_HOME/glances/glances.conf et relancé mais c'est toujours /tmp/glances.conf qui est utilisé.

Y-a moyen d'éditer le chemin ou le nom du fichier log SVP ?

cyrille

===

**Comment by nicolargo** [comment]
[hennionn@MasterVM tmp]$ python -m glances

Traceback (most recent call last):

  File "/usr/lib64/python2.7/runpy.py", line 151, in _run_module_as_main

    mod_name, loader, code, fname = _get_module_details(mod_name)

  File "/usr/lib64/python2.7/runpy.py", line 109, in _get_module_details

    return _get_module_details(pkg_main_name)

  File "/usr/lib64/python2.7/runpy.py", line 101, in _get_module_details

    loader = get_loader(mod_name)

  File "/usr/lib64/python2.7/pkgutil.py", line 464, in get_loader

    return find_loader(fullname)

  File "/usr/lib64/python2.7/pkgutil.py", line 474, in find_loader

    for importer in iter_importers(fullname):

  File "/usr/lib64/python2.7/pkgutil.py", line 430, in iter_importers

    __import__(pkg)

  File "glances/__init__.py", line 44, in <module>

    from glances.core.glances_logging import logger

  File "glances/core/glances_logging.py", line 86, in <module>

    logger = glances_logger()

  File "glances/core/glances_logging.py", line 77, in glances_logger

    logging.config.dictConfig(LOGGING_CFG)

Reproducted:
 
 File "/usr/lib64/python2.7/logging/config.py", line 803, in dictConfig

    dictConfigClass(config).configure()

  File "/usr/lib64/python2.7/logging/config.py", line 585, in configure

    '%r: %s' % (name, e))

ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/tmp/glances.log'

**Comment by nicolargo** [comment]
Workaround:

    chmod 777 /tmp/glances.log

**Comment by nicolargo** [comment]
Corrected in the DEVELOP branch (commit: e674cfb)
