### ISSUE TITLE
test de la branche develop linux 3.14.14 gentoo x86_64 python 3.3.5 

### ISSUE THREAD

**Issue by phaleon2** [nicolargo/glances#497]
Test de la branch develop dans un virtualenv : python 3.3.5 
Glances v2.3_RC1 with psutil v2.2.0 
Linux  3.14.14-gentoo #  x86_64 GenuineIntel GNU/Linux
LANGUAGE=en_US.utf8  python -m glances -d -C conf/glances.conf marche nickel ;) 
LANGUAGE=en_US.utf8  python -m glances -d -C conf/glances-test.conf  donne des erreurs : 
Traceback (most recent call last):
  File "/usr/lib64/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "./glances/__main__.py", line 38, in <module>
    glances.main()
  File "./glances/__init__.py", line 119, in main
    args=core.get_args())
  File "./glances/core/glances_standalone.py", line 62, in __init__
    self.stats.update()
  File "./glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "./glances/plugins/glances_plugin.py", line 632, in wrapper
    ret = fct(*args, **kw)
  File "/data2/projects/glances-dev/glances-develop/glances/plugins/glances_fs.py", line 172, in update
    self.update_views()
  File "/data2/projects/glances-dev/glances-develop/glances/plugins/glances_fs.py", line 184, in update_views
    self.views[i[self.get_key()]]['used']['decoration'] = self.get_alert(i['used'], max=i['size'], header=i['mnt_point'])
  File "./glances/plugins/glances_plugin.py", line 418, in get_alert
    item for item in self.stats if item[self.get_key()] == header).next()
AttributeError: 'generator' object has no attribute 'next'

**Comment by nicolargo** [comment]
Corrected in the latest commit: 3817b84
Thk for the report.

**Comment by phaleon2** [comment]
will try to test on freebsd also...
