### ISSUE TITLE
Failed to start in Win7

### ISSUE THREAD

**Issue by heroWang** [nicolargo/glances#502]
```
Traceback (most recent call last):
  File "d:\python2.7\Scripts\glances-script.py", line 9, in <module>
    load_entry_point('Glances==2.2.1', 'console_scripts', 'glances')()
  File "d:\python2.7\lib\site-packages\glances\__init__.py", line 122, in main
    standalone.serve_forever()
  File "d:\python2.7\lib\site-packages\glances\core\glances_standalone.py", line 83, in serve_forever
    self.screen.update(self.stats)
  File "d:\python2.7\lib\site-packages\glances\outputs\glances_curses.py", line776, in update
    self.flush(stats, cs_status=cs_status)
  File "d:\python2.7\lib\site-packages\glances\outputs\glances_curses.py", line754, in flush
    self.display(stats, cs_status=cs_status)
  File "d:\python2.7\lib\site-packages\glances\outputs\glances_curses.py", line422, in display
    args=self.args, max_width=plugin_max_width)
  File "d:\python2.7\lib\site-packages\glances\plugins\glances_plugin.py", line400, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "d:\python2.7\lib\site-packages\glances\plugins\glances_network.py", line 265, in msg_curse
    msg = '{0:{width}}'.format(ifname, width=ifname_max_width)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```
error occured when i  enter the  simple command  `glances`. seems like that when ifname is a string '本地连接',the format action throw an error. python version is 2.7
i think i have found the solution.

**Comment by nicolargo** [comment]
What solution do you propose ?

**Comment by heroWang** [comment]
it is a common unicode problem in python .I found the solution here <http://www.ianbicking.org/illusive-setdefaultencoding.html>.

in my case I add a file named sitecustomize.py with content
``` python
import sys
sys.setdefaultencoding('utf-8')
```
to PYTHON_HOME/Lib/site-packages/.
