### ISSUE TITLE
Server mode issue when no network interface is available

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#528]
Run Glances server on a machine without networdk interface:

```
$ python -m glances -s 
Announce the Glances server on the LAN (using None IP address) 
Traceback (most recent call last): 
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main 
    "__main__", fname, loader, pkg_name) 
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code 
    exec code in run_globals 
  File "/home/nicolargo/Dropbox/dev/glances/glances/__main__.py", line 38, in <module> 
    glances.main() 
  File "glances/__init__.py", line 174, in main 
    args=args) 
  File "glances/core/glances_server.py", line 225, in __init__ 
    self.autodiscover_client = GlancesAutoDiscoverClient(socket.gethostname(), args) 
  File "glances/core/glances_autodiscover.py", line 212, in __init__ 
    address=socket.inet_aton(zeroconf_bind_address), port=args.port, 
TypeError: must be string, not None 
```

**Comment by nicolargo** [comment]
Corrected in the dev branch
