### ISSUE TITLE
Unexpected Crash / Exit...

### ISSUE THREAD

**Issue by aphorise** [nicolargo/glances#533]
On Debian 7.8 with Python 2.7.3 - installed via web install script

However when trying to run result sin : 
```
# sudo glances
Traceback (most recent call last):
	File "/usr/local/bin/glances", line 9, in <module>
		load_entry_point('Glances==2.3', 'console_scripts', 'glances')()
			File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 122, in main
					standalone.serve_forever()
			File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 74, in serve_forever
					self.screen.update(self.stats)
			File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 795, in update
					self.flush(stats, cs_status=cs_status)
			File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 773, in flush
					self.display(stats, cs_status=cs_status)
			File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 525, in display
					self.display_plugin(stats_network)
			File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 746, in display_plugin
					offset = len(m['msg'].decode("utf-8"))
			File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
				 return codecs.utf_8_decode(input, errors, True)
		UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte
```

Any suggestions?

**Comment by nicolargo** [comment]
Just add a "replace" option in the UTF-8 decode function.
Should solve the issue in the next version.
