### ISSUE TITLE
Error after 2.4 upgrade = AttributeError: 'module' object has no attribute 'gateways'

### ISSUE THREAD

**Issue by davidkulak** [nicolargo/glances#603]
After 2.4 upgrade glances doesn't start anymore : 

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 122, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 646, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_ip.py", line 67, in update
    default_gw = netifaces.gateways()['default'][netifaces.AF_INET]
AttributeError: 'module' object has no attribute 'gateways'

**Comment by davidkulak** [comment]
Ok with a complete reinstall.
