### ISSUE TITLE
AttributeError: 'module' object has no attribute 'gateways'

### ISSUE THREAD

**Issue by ticktockhouse** [nicolargo/glances#604]
Hello,

Server:
Description:	Debian GNU/Linux 7.6 (wheezy)

I'm getting this error after following the PyPi install instructions. I searched, but couldn't see an error with "gateways" anywhere...

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 122, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 646, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_ip.py", line 67, in update
    default_gw = netifaces.gateways()['default'][netifaces.AF_INET]
AttributeError: 'module' object has no attribute 'gateways'

Thanks

**Comment by Yeoh95** [comment]
Hello, i have the same problem on RHEL6.6 :

Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/glances/__init__.py", line 42, in <module>
    from glances.core.glances_logging import logger
  File "/usr/lib/python2.6/site-packages/glances/core/glances_logging.py", line 28, in <module>
    from logging.config import dictConfig
ImportError: cannot import name dictConfig

**Comment by asergi** [comment]
Duplicate #603.
