### ISSUE TITLE
Crash when "top extended stats" is enabled on osx

### ISSUE THREAD

**Issue by notFloran** [nicolargo/glances#612]
On osx, when I try to enable "top extended stats", glances crash and show : 

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.1', 'console_scripts', 'glances')()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Glances-2.4.1-py2.7.egg/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Glances-2.4.1-py2.7.egg/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Glances-2.4.1-py2.7.egg/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Glances-2.4.1-py2.7.egg/glances/outputs/glances_curses.py", line 863, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Glances-2.4.1-py2.7.egg/glances/outputs/glances_curses.py", line 829, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Glances-2.4.1-py2.7.egg/glances/outputs/glances_curses.py", line 466, in display
    if self.args.enable_process_extended and not self.args.process_tree:
AttributeError: 'Namespace' object has no attribute 'process_tree'
```

Maybe related to #542 ?

**Comment by asergi** [comment]
https://github.com/nicolargo/glances/commit/64132c2045aeef1aaa8df164a311af20f0ff1d3f
