### ISSUE TITLE
psutil.NoSuchProcess: process no longer exists (again)

### ISSUE THREAD

**Issue by Ustilago** [nicolargo/glances#613]
Hi,
I'm having for some days this error again (see #421), with Glances 2.5beta with PSutil 2.1.1 :
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/src/glances/glances/__main__.py", line 38, in <module>
    glances.main()
  File "glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "glances/core/glances_standalone.py", line 89, in __serve_forever
    self.stats.update()
  File "glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/local/src/glances/glances/plugins/glances_processcount.py", line 58, in update
    glances_processes.update()
  File "glances/core/glances_processes.py", line 596, in update
    standard_stats=self.max_processes is None)
  File "glances/core/glances_processes.py", line 562, in __get_process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "glances/core/glances_processes.py", line 379, in __get_mandatory_stats
    'name', 'cpu_times'], ad_value=''))
  File "/usr/local/src/glances-dev/local/lib/python2.7/site-packages/psutil/__init__.py", line 414, in as_dict
    ret = attr()
  File "/usr/local/src/glances-dev/local/lib/python2.7/site-packages/psutil/__init__.py", line 902, in memory_percent
    rss = self._proc.memory_info()[0]
  File "/usr/local/src/glances-dev/local/lib/python2.7/site-packages/psutil/_pslinux.py", line 704, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=18518)
```
I'm using Debian Sid, glances is launched in a screen session in a rxvt terminal in a virtualenv :
```
(glances-dev)$ python --version
Python 2.7.8
(glances-dev)$ uname -a
Linux I10005 4.0.0-3.slh.1-aptosid-amd64 #1 SMP PREEMPT aptosid 4.0-10 (2015-05-15) x86_64 GNU/Linux
```
Crashes are random, sometimes at work, sometimes at home (it's a laptop), I can't find an action leading to the crash.
Regards,
Sébastien

**Comment by asergi** [comment]
@nicolargo fixed a similar issue yesterday (https://github.com/nicolargo/glances/commit/4f79ead1b46292186fda68fba3aee128108246e8). Could you test it again?

**Comment by nicolargo** [comment]
Same issue than https://github.com/nicolargo/glances/issues/432
Patch (4f79ead) should solve the issue.

Can you test, cannot reproduce on my system.

**Comment by nicolargo** [comment]
Assume solved...

**Comment by sm0ketst** [comment]
Hi all,

Same issue here, do not know if it is useful or not but I'm noticing the following for Debian Jessie 8.2:

- I'm running: 
glances --version
Glances v2.1.1 with psutil v2.1.1

python --version
Python 2.7.9

- I'm checking the proposed patch:
https://github.com/nicolargo/glances/commit/4f79ead1b46292186fda68fba3aee128108246e8

But the current "/usr/lib/python3/dist-packages/glances/core/glances_processes.py" contains the following code instead the proposed patch:

[...]
            # Process CPU, MEM percent and name
            procstat.update(proc.as_dict(attrs=['cpu_percent', 'memory_percent', 'name'], ad_value=''))

            # Process command line (cached with internal cache)
            try:
                self.cmdline_cache[procstat['pid']]
            except KeyError:
                # Patch for issue #391
                try:
                    self.cmdline_cache[procstat['pid']] = ' '.join(proc.cmdline())
                except (AttributeError, UnicodeDecodeError, psutil.AccessDenied, psutil.NoSuchProcess):
                    self.cmdline_cache[procstat['pid']] = ""
            procstat['cmdline'] = self.cmdline_cache[procstat['pid']]

[...]

Should I post to Debian folks?

TIA

JJ

**Comment by nicolargo** [comment]
Hi @sm0ketst , this bug is corrected in the version 2.4.2 or higher.
The Debian package is out dated (you can report the bug to the Debian packager...).

Best way to processed is to uninstall the Debian package and install the latest stable version using the auto install script:  https://github.com/nicolargo/glancesautoinstall

**Comment by sm0ketst** [comment]
I'll do, thanks Nico.

**Comment by piotrp88** [comment]
I left glances running for about 16 hours (I can't determine exactly when the crash occured) and the software crashed with this message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 1390, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 1950, in connections
    ret = _connections.retrieve(kind, self.pid)
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 920, in retrieve
    inodes = self.get_proc_inodes(pid)
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 742, in get_proc_inodes
    for fd in os.listdir("%s/%s/fd" % (self._procfs_path, pid)):
FileNotFoundError: [Errno 2] No such file or directory: '/proc/9903/fd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python3.5/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python3.5/dist-packages/glances/__init__.py", line 103, in start
    mode.serve_forever()
  File "/usr/local/lib/python3.5/dist-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/lib/python3.5/sched.py", line 147, in run
    action(*argument, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/glances/standalone.py", line 100, in __serve_forever
    self.stats.update()
  File "/usr/local/lib/python3.5/dist-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.5/dist-packages/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "/usr/local/lib/python3.5/dist-packages/glances/processes.py", line 521, in update
    extended_stats=first)
  File "/usr/local/lib/python3.5/dist-packages/glances/processes.py", line 394, in __get_process_stats
    procstat = self.__get_extended_stats(proc, procstat)
  File "/usr/local/lib/python3.5/dist-packages/glances/processes.py", line 371, in __get_extended_stats
    procstat['tcp'] = len(proc.connections(kind="tcp"))
  File "/usr/local/lib/python3.5/dist-packages/psutil/__init__.py", line 1158, in connections
    return self._proc.connections(kind)
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 1401, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=9903, name='postgres')
```

This is the command I used to run glances:

```
glances -t 1 --export-graph --path-graph /var/www/glances/ --disable-hddtemp --disable-sensors --disable-cloud --disable-wifi
```

It's the first time I see this message but it's also the first time I let glances running so much long 
and with the `--export-graph` option.

All the software on this machine is updated at the latest version available.
I'm running `Glances v2.11.1 with psutil v5.4.3` on `Ubuntu 16.04.4 LTS 4.4.0-116-generic`.
