### ISSUE TITLE
OS X 10.10.3 crash.

### ISSUE THREAD

**Issue by Phrohdoh** [nicolargo/glances#622]
```sh
16:37 $ glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 854, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 832, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 479, in display
    'processlist').get_stats_display(args=self.args)
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 543, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/site-packages/glances/plugins/glances_processlist.py", line 424, in msg_curse
    ret.extend(self.get_process_curses_data(p, first, args))
  File "/usr/local/lib/python2.7/site-packages/glances/plugins/glances_processlist.py", line 242, in get_process_curses_data
    delta = timedelta(seconds=sum(p['cpu_times']))
TypeError: 'NoneType' object is not iterable
x(1) ~ 
```

Glances v2.4.2 with psutil v3.0.1
Python 2.7.9+

I was running tmux with 2 panes, one for glances and the other was me building radare2 from source.

**Comment by nicolargo** [comment]
Do you have the same issue running Glances with root right ?

    $ sudo glances

?

**Comment by d2a-raudenaerde** [comment]
I have the a similar problem (ubuntu 14.04 LTS)
raudenaerde@roba-ubuntu:~/$ sudo glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 122, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 646, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_ip.py", line 67, in update
    default_gw = netifaces.gateways()['default'][netifaces.AF_INET]
AttributeError: 'module' object has no attribute 'gateways'

**Comment by Phrohdoh** [comment]
@nicolargo Sorry I completely forgot to respond. Yes I get the same error.

**Comment by nicolargo** [comment]
Thk @Phrohdoh . I do not understand why the p['cpu_times'] is equal to None (cause of the 'TypeError: 'NoneType' object is not iterable' error message).

I will add a try/catch.

**Comment by nicolargo** [comment]
Try/except added.

**Comment by hank** [comment]
Ah I see - I search for "cpu" in the title, and didn't find this.  I should really start using the develop branch...

**Comment by nicolargo** [comment]
Not a problem ;)

**Comment by nicolargo** [comment]
@hank The version 2.5 is in RC...
