### ISSUE TITLE
Infrequently crashing due to assert

### ISSUE THREAD

**Issue by tbu-** [nicolargo/glances#623]
The backtrace shown is:
```
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/lib/python3.4/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/lib/python3.4/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/lib/python3.4/site-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/lib/python3.4/site-packages/glances/outputs/glances_curses.py", line 854, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib/python3.4/site-packages/glances/outputs/glances_curses.py", line 832, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib/python3.4/site-packages/glances/outputs/glances_curses.py", line 538, in display
    'quicklook').get_stats_display(max_width=quicklook_width, args=self.args)
  File "/usr/lib/python3.4/site-packages/glances/plugins/glances_plugin.py", line 539, in get_stats_display
    'msgdict': self.msg_curse(args, max_width=max_width),
  File "/usr/lib/python3.4/site-packages/glances/plugins/glances_quicklook.py", line 97, in msg_curse
    bar.percent = self.stats[key]
  File "/usr/lib/python3.4/site-packages/glances/outputs/glances_bars.py", line 72, in percent
    assert value >= 0
```

I have
```
$ glances --version
Glances v2.4.2 with psutil v2.2.1
```
on Arch Linux.

**Comment by nicolargo** [comment]
Corrected in DEVELOP branch.
Thk for the report.
