### ISSUE TITLE
Bug when I try run glances

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#625]
Hello. I'm install program by command:

pip install Glances and by small "g" too and from github and each time when

try to lonch it have crush:

```
#glances
	Traceback (most recent call last):
  File "./glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 122, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 646, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_ip.py", line 67, in update
    default_gw = netifaces.gateways()['default'][netifaces.AF_INET]
  AttributeError: 'module' object has no attribute 'gateways'
```

System information:
Operating System Type :  GNU/Linux
OS Name : Zorin OS
OS Version : 9
Architecture :  x86_64
Kernel Release :  3.13.0-53-generic

**Comment by mike-tr-adamson** [comment]
I ran into this on my mint (ubuntu) install. The distro package python-netifaces was installed and this is currently at v0.8 so didn't have the gateways method. Uninstalling this package and installing the pypi package fixed the problem, i.e sudo pip install netifaces.

**Comment by ogerasymenko** [comment]
pip install --upgrade netifaces this help. with netifaces v. 0.10.4 glances works fine.

**Comment by nicolargo** [comment]
+1 for @ogerasymenko
