### ISSUE TITLE
When python 2.6 installation glances 2.4.2 library is not part of the associated installation

### ISSUE THREAD

**Issue by jos666** [nicolargo/glances#627]
**python 2.6  install  glances 2.4.2**

## ERROR1
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/glances/__init__.py", line 42, in <module>
    from glances.core.glances_logging import logger
  File "/usr/lib/python2.6/site-packages/glances/core/glances_logging.py", line 28, in <module>
    from logging.config import dictConfig
ImportError: cannot import name dictConfig

need install library is   logutils    **pip install logutils**

## ERROR2
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/glances/__init__.py", line 43, in <module>
    from glances.core.glances_main import GlancesMain
  File "/usr/lib/python2.6/site-packages/glances/core/glances_main.py", line 23, in <module>
    import argparse
need install library is   logutils    **pip install argparse**

**Please authors logutils and argparse added to requirements.txt inside**

**Comment by asergi** [comment]
Closed #627 via https://github.com/nicolargo/glances/commit/c9df26a2270989241a80f9ba89a56da8f73d1041.

**Comment by stephdl** [comment]
Hi
I Have the same issue when I start glances

Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/glances/__init__.py", line 42, in <module>
    from glances.core.glances_logging import logger
  File "/usr/lib/python2.6/site-packages/glances/core/glances_logging.py", line 28, in <module>
    from logging.config import dictConfig
ImportError: cannot import name dictConfig

please what can I do

**Comment by stephdl** [comment]
I manually installed logutils by pip install and then it works now, but I don't understand why the dependence was not installed automatically

**Comment by hardevine** [comment]
@stephdl  thanks saved my day :+1:
