### ISSUE TITLE
Error with IP plugin

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#651]
Source: https://github.com/nicolargo/glances/issues/622#issuecomment-131746366

I have the a problem (ubuntu 14.04 LTS):

```
raudenaerde@roba-ubuntu:~/$ sudo glances
Traceback (most recent call last):
File "/usr/local/bin/glances", line 9, in
load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
File "/usr/local/lib/python2.7/dist-packages/glances/init.py", line 122, in main
args=core.get_args())
File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 68, in init
self.stats.update()
File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_stats.py", line 156, in update
self._plugins[p].update()
File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 646, in wrapper
ret = fct(args, *kw)
File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_ip.py", line 67, in update
default_gw = netifaces.gateways()['default'][netifaces.AF_INET]
AttributeError: 'module' object has no attribute 'gateways'
```

**Comment by azgaviperr** [comment]
I got the exact same troubles using glances from a pip install on Fedora22 / Viperr7

Traceback (most recent call last):
  File "/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 122, in main
    args=core.get_args())
  File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/lib/python2.7/site-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 646, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_ip.py", line 67, in update
    default_gw = netifaces.gateways()['default'][netifaces.AF_INET]
AttributeError: 'module' object has no attribute 'gateways'

**Comment by nicolargo** [comment]
Catched in the latest commit.
