### ISSUE TITLE
Filter processes crashs with a bad regular expression pattern

### ISSUE THREAD

**Issue by notFloran** [nicolargo/glances#665]
With a bad regular expression pattern like ```*glances*```, Glances crashs : 
```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 89, in __serve_forever
    self.stats.update()
  File "/usr/local/lib/python2.7/site-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/site-packages/glances/plugins/glances_processcount.py", line 58, in update
    glances_processes.update()
  File "/usr/local/lib/python2.7/site-packages/glances/core/glances_processes.py", line 602, in update
    if s is None or (self.is_filtered(s['cmdline']) and self.is_filtered(s['name'])):
  File "/usr/local/lib/python2.7/site-packages/glances/core/glances_processes.py", line 346, in is_filtered
    return self.process_filter_re.match(value) is None
AttributeError: 'NoneType' object has no attribute 'match'
```

**Comment by nicolargo** [comment]
Corrected in latest commit.

Thanks for the report @notFloran
