### ISSUE TITLE
p['cpu_times'] is None

### ISSUE THREAD

**Issue by hank** [nicolargo/glances#685]
Crashing repeatedly in freebsd after some hours:
```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.4.2', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/outputs/glances_curses.py", line 854, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/outputs/glances_curses.py", line 832, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/outputs/glances_curses.py", line 479, in display
    'processlist').get_stats_display(args=self.args)
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/plugins/glances_plugin.py", line 543, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/plugins/glances_processlist.py", line 424, in msg_curse
    ret.extend(self.get_process_curses_data(p, first, args))
  File "/usr/local/lib/python2.7/site-packages/Glances-2.4.2-py2.7.egg/glances/plugins/glances_processlist.py", line 242, in get_process_curses_data
    delta = timedelta(seconds=sum(p['cpu_times']))
TypeError: 'NoneType' object is not iterable
```

**Comment by nicolargo** [comment]
REJECTED: duplicated https://github.com/nicolargo/glances/issues/622
