### ISSUE TITLE
Unable to unlock password protected servers in browser mode

### ISSUE THREAD

**Issue by asergi** [nicolargo/glances#694]
Steps to reproduce (using Glances 2.5):
- server: glances -s --password
- client: glances --browser
- select the password protected server
- enter the password
```
Traceback (most recent call last):
  File "/home/alessio/venvs/py27-glances/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/home/alessio/venvs/py27-glances/lib/python2.7/site-packages/glances/__init__.py", line 154, in main
    client.serve_forever()
  File "/home/alessio/venvs/py27-glances/lib/python2.7/site-packages/glances/core/glances_client_browser.py", line 246, in serve_forever
    return self.__serve_forever()
  File "/home/alessio/venvs/py27-glances/lib/python2.7/site-packages/glances/core/glances_client_browser.py", line 194, in __serve_forever
    self.set_in_selected('password', self.password.sha256_hash(clear_password))
AttributeError: 'GlancesPassword' object has no attribute 'sha256_hash'
```

**Comment by asergi** [comment]
`glances_passwordlist` has no `sha256_hash` method and also has the same class name of `glances_password`.

Only Glances 2.5 is affected by this bug, not 2.4 series.

**Comment by asergi** [comment]
I came up with this patch which solves the above crash:
```diff
diff --git a/glances/core/glances_client_browser.py b/glances/core/glances_client_browser.py                                                                                                                                                                                     
index b0a8713..0de724f 100644                                                    
--- a/glances/core/glances_client_browser.py
+++ b/glances/core/glances_client_browser.py
@@ -32,8 +32,8 @@ except ImportError:                                            
 from glances.core.glances_autodiscover import GlancesAutoDiscoverServer         
 from glances.core.glances_client import GlancesClient, GlancesClientTransport   
 from glances.core.glances_logging import logger                                 
+from glances.core.glances_passwordlist import GlancesPasswordList as GlancesPassword
 from glances.core.glances_staticlist import GlancesStaticServer                 
-from glances.core.glances_passwordlist import GlancesPassword
from glances.outputs.glances_curses import GlancesCursesBrowser                 
                                                                                 
                                                                                 
diff --git a/glances/core/glances_passwordlist.py b/glances/core/glances_passwordlist.py
index bd29d1a..1fa9f1a 100644                                                    
--- a/glances/core/glances_passwordlist.py
+++ b/glances/core/glances_passwordlist.py
@@ -21,15 +21,18 @@                                                              
                                                                                 
 # Import Glances libs                                                           
 from glances.core.glances_logging import logger                                 
+from glances.core.glances_password import GlancesPassword
                                                                                 
                                                                                 
-class GlancesPassword(object):
+class GlancesPasswordList(GlancesPassword):
                                                                                 
     """Manage the Glances passwords list for the client|browser/server."""      
                                                                                 
     _section = "passwords"                                                      
     
     def __init__(self, config=None, args=None):                                 
+        super(GlancesPassword, self).__init__()

         # password_dict is a dict (JSON compliant)                              
         # {'host': 'password', ... }                                            
         # Load the configuration file
```

**Comment by nicolargo** [comment]
Looks nice for me.

Can you push it on the develop branch ?
I will release a 2.5.1 patch.

**Comment by asergi** [comment]
https://github.com/nicolargo/glances/commit/25b6b5c797b348318bf3f1bf110944c4f37d5e2d
