### ISSUE TITLE
Infrequently crashing because of the same assert

### ISSUE THREAD

**Issue by tbu-** [nicolargo/glances#709]
```
$ glances
Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/lib/python3.5/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/lib/python3.5/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/lib/python3.5/site-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/lib/python3.5/site-packages/glances/outputs/glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib/python3.5/site-packages/glances/outputs/glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib/python3.5/site-packages/glances/outputs/glances_curses.py", line 578, in display
    'quicklook').get_stats_display(max_width=quicklook_width, args=self.args)
  File "/usr/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 547, in get_stats_display
    'msgdict': self.msg_curse(args, max_width=max_width),
  File "/usr/lib/python3.5/site-packages/glances/plugins/glances_quicklook.py", line 133, in msg_curse
    bar.percent = self.stats[key]
  File "/usr/lib/python3.5/site-packages/glances/outputs/glances_bars.py", line 73, in percent
    raise AssertionError('The percent must be between 0 and 100.')
```

See also #623 .
The fix has apparantly been reverted: https://github.com/nicolargo/glances/commit/168969bdf4c973089e3c59cb5efbc892285154fb.

**Comment by nicolargo** [comment]
@asergi Can you have a look on this issue ?

**Comment by asergi** [comment]
For the record: the reverted commit has nothing to do with this. That comes from PR 683.

**Comment by tbu-** [comment]
As far as I can tell, the commit that was reverted fixed the problem. #683 just changed `assert` to raising an explicit `AssertionError`, which does the same thing.

**Comment by asergi** [comment]
https://github.com/nicolargo/glances/commit/25816ceae7799eafda2b23dd8cc872f309e876a0

**Comment by tbu-** [comment]
Thanks!
