### ISSUE TITLE
KeyError: 'cpucore' when exporting data to InfluxDB

### ISSUE THREAD

**Issue by mattpoel** [nicolargo/glances#729]
Hi,

I'm trying to capture the performance data of a windows machine and write it to InfluxDB. Glances is capturing the data fine for a few refreshes, but throws the following exception afterwards:

```
Traceback (most recent call last):
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\Scripts\glances.exe\__main__.py", line 9, in <module>
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\glances\__init__.py", line 125, in main
    standalone.serve_forever()
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\glances\core\glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\glances\core\glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\glances\outputs\glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\glances\outputs\glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\glances\outputs\glances_curses.py", line 458, in display
    stats_load = stats.get_plugin('load').get_stats_display(args=self.args)
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\glances\plugins\glances_plugin.py", line 551, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "C:\PERF\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\glances\plugins\glances_load.py", line 148, in msg_curse
    if self.stats['cpucore'] > 0:
KeyError: 'cpucore'
```

Glances command is executed with the following options:
```
glances --export-influxdb -C glances_db.cfg -t 5 -1
```
Configuration file looks like:
```
[influxdb]
host=influxdb_ip
port=8086
user=glances
password=user_password
db=GLANCES
# prefix=testpre
tags=machine:myWindowsMachine
```

Should not be an InfluxDB issue per se as some measurements are written to the DB:
```
> select * from processcount
name: processcount
------------------
time			machine		        running	sleeping	thread	total
1448491390635029773	myWindowsMachine	65	0		964	65
1448491395838791827	myWindowsMachine	65	0		963	65
1448491401053786107	myWindowsMachine	65	0		962	65
1448491406274844110	myWindowsMachine	65	0		959	65
```

Exception only occurs if data is exported to InfluxDB. Running glances with -t 5 and -1 works without any issue.

Thank your for your help in advance!

Best regards,
Matt

**Comment by mattpoel** [comment]
Link to the debug logfile: http://pastebin.com/AFCd61mu

**Comment by nicolargo** [comment]
Hi @mattpoel thanks for the report.

Some additional information:
* What is your Glances / PsUtil version ?
* Does Glances work without error when you use it without the InfluxDB export ?
* Can you start Glances with the -d (DEBUG tag): glances --export-influxdb -C glances_db.cfg -t 5 -1 -d and http://pastebin.com/ the output of the debug file (%APPDATA%\Local\temp\glances.log)

**Comment by mattpoel** [comment]
Hi @nicolargo ,

>What is your Glances / PsUtil version ?

Glances 2.5.1 / PSutil 3.2.2

>Does Glances work without error when you use it without the InfluxDB export ?

Yes, starting glances with `glances -t 5 -1` works with any issue.

>Can you retry without the tags=machine:myWindowsMachine configuration case (just to be sure)

No, unfortunately still the same problem. The tags are written correctly to InfluxDB until the cpucore-KeyError occurs.

Best regards,
Matt

**Comment by mattpoel** [comment]
Did some further testing. I think the error is related to running `--export-influxdb` in combination with the curses output. If I run glances with the `-q` option it does not raise an exception (although other errors are raised in the log file for writing the collected data to influxdb - I will open a separate issue for these errors).

**Comment by nicolargo** [comment]
Not reproduced on Linux OS. The bug is only on Windows.

**Comment by nicolargo** [comment]
@mattpoel Should be corrected in the latest commit. Can you test the develop branch ?
=> https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version

**Comment by nicolargo** [comment]
@mattpoel Any news ?

If no, i will close this issue.
