### ISSUE TITLE
Default configuration file raises an uncatched exception

### ISSUE THREAD

**Issue by mohierf** [nicolargo/glances#730]
I just copied the `/usr/local/share/doc/glances/glances.conf` to `/etc/glances/glances.conf` and tried to start glances ...

```
 glances -c /etc/glances/glances.conf

No Glances server found. Trying fallback to SNMP...
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 149, in main
    if not client.login():
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_client.py", line 152, in login
    if not self.stats.check_snmp():
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_stats.py", line 364, in check_snmp
    ret = clientsnmp.get_by_oid("1.3.6.1.2.1.1.5.0") != {}
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_snmp.py", line 89, in get_by_oid
    cmdgen.UdpTransportTarget((self.host, self.port)),
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/hlapi/transport.py", line 10, in __init__
    self.transportAddr = self._resolveAddr(transportAddr)
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/hlapi/asyncore/transport.py", line 51, in _resolveAddr
    raise error.PySnmpError('Bad IPv4/UDP transport address %s: %s' % ('@'.join([ str(x) for x in transportAddr ]), sys.exc_info()[1]))
NameError: global name 'error' is not defined
```

**Comment by nicolargo** [comment]
It is -C not -c ;)

**Comment by mohierf** [comment]
Sorry ... I sould have learnt reading :-)

**Comment by nicolargo** [comment]
No problem, i have already done this mistake myself ;)
