### ISSUE TITLE
glances with influxdb logging crashes after some time

### ISSUE THREAD

**Issue by LucChoubert** [nicolargo/glances#749]
Hello nicolargo,

First, I would like to thank you for this very good software.
I am trying to use connected with influxdb (glances --export-influxdb) and after a while, glances stops with following traceback:

  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 462, in display
    args=self.args, max_width=plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 551, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_network.py", line 254, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers, not str

I use:
glances -V
Glances v2.5.1 with psutil v3.3.0

InfluxDb version 0.9.5.1

Config file:
[influxdb]
host=192.168.1.10
port=8086
user=root
password=root
db=MonitoringDb
tags=host:ubuntu2

I get many data in influxdb and crash happens after several hours.
I do not have same issue when used only in curses mode

Thank your for your help in advance!

Best regards,

Luc

PS: One more question: glances -s --export-influxdb does not work. What is the best practice to use glances in background with feed of the data to influxdb ?

**Comment by nicolargo** [comment]
Hi @LucChoubert , thanks for the report.

I will have a look on it.

For your PS question, you can use the quiet mode:

    glances -q --export-influxdb

**Comment by nicolargo** [comment]
Can you start Glances in debug mode (-d), when it crach, can you send us the last relevant line of the log file (/tmp/glances.log).

Thanks in advance.

**Comment by ruudboon** [comment]
@nicolargo will
``` glances -q --export-influxdb ```
Push the data every 3 seconds by default?

**Comment by nicolargo** [comment]
Yes it does. You can change the refresh time with the -r option.

**Comment by ruudboon** [comment]
Hmm Looks like it's only pushing once. Will dive into and open an other issue otherwise.

**Comment by LucChoubert** [comment]
I tried glances -d --export-influxdb for almost 24h with no crash.
Then I tried again glances  --export-influxdb and it crashed few minutes after.

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 462, in display
    args=self.args, max_width=plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 551, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_network.py", line 254, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers, not str

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 462, in display
    args=self.args, max_width=plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 551, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_network.py", line 254, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers, not str


Last logs are the following:

2015-12-11 19:02:57,218 -- ERROR -- Cannot export diskio stats to InfluxDB (400: write failed: field type conflict: input field "sda9.time_since_update" on measurement "diskio" is type float64, already exists as type integer
)
2015-12-11 19:02:57,223 -- ERROR -- Cannot export docker stats to InfluxDB (400: unable to parse 'docker,host=ubuntu2 ': invalid field format
)
2015-12-11 19:02:57,234 -- ERROR -- Cannot export ip stats to InfluxDB (400: unable to parse 'ip,host=ubuntu2 ': invalid field format
)
2015-12-11 19:02:57,262 -- ERROR -- Cannot export ip stats to InfluxDB (400: unable to parse 'ip,host=ubuntu2 ': invalid field format
)
2015-12-11 19:02:57,327 -- ERROR -- Cannot export network stats to InfluxDB (400: write failed: field type conflict: input field "eth0.time_since_update" on measurement "network" is type float64, already exists as type integer
)
2015-12-11 19:02:57,532 -- ERROR -- Cannot export docker stats to InfluxDB (400: unable to parse 'docker,host=ubuntu2 ': invalid field format
)
2015-12-11 19:02:57,577 -- ERROR -- Cannot export docker stats to InfluxDB (400: unable to parse 'docker,host=ubuntu2 ': invalid field format
)
2015-12-11 19:02:57,725 -- ERROR -- Cannot export diskio stats to InfluxDB (400: write failed: field type conflict: input field "sda5.time_since_update" on measurement "diskio" is type float64, already exists as type integer
)
2015-12-11 19:02:57,756 -- ERROR -- Cannot export docker stats to InfluxDB (400: unable to parse 'docker,host=ubuntu2 ': invalid field format
)
2015-12-11 19:02:57,939 -- ERROR -- Cannot export diskio stats to InfluxDB (400: write failed: field type conflict: input field "sda10.time_since_update" on measurement "diskio" is type float64, already exists as type integer
)
2015-12-11 19:02:58,048 -- ERROR -- Cannot export docker stats to InfluxDB (400: unable to parse 'docker,host=ubuntu2 ': invalid field format
)
2015-12-11 19:02:58,404 -- ERROR -- Cannot export docker stats to InfluxDB (400: unable to parse 'docker,host=ubuntu2 ': invalid field format
)
2015-12-11 19:02:58,541 -- ERROR -- Cannot export network stats to InfluxDB (400: write failed: field type conflict: input field "eth0.time_since_update" on measurement "network" is type float64, already exists as type integer
)
2015-12-11 19:02:58,655 -- ERROR -- Cannot export diskio stats to InfluxDB (400: write failed: field type conflict: input field "sr0.time_since_update" on measurement "diskio" is type float64, already exists as type integer
)
2015-12-11 19:02:58,854 -- ERROR -- Cannot export docker stats to InfluxDB (400: unable to parse 'docker,host=ubuntu2 ': invalid field format
)



Hope it helps

Luc

**Comment by nicolargo** [comment]
Should be corrected: read https://github.com/nicolargo/glances/issues/750#issuecomment-164167498

**Comment by LucChoubert** [comment]
Thanks.

I tested over the week end with option -q (glances --export-influxdb -q ) and had no crash at all.
Thanks for this for best in class support.

Luc

**Comment by nicolargo** [comment]
Ok !
Thanks for the issue report.

**Comment by carlba** [comment]
I get exactly this error with both the stable(2.7.1) and development (2.8) branches of glances. It happens with both the Elasticsearch and InfluxDB exports.


# Stacktrace
```bash
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    load_entry_point('Glances===2.8-DEVELOP', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/__init__.py", line 225, in main
    start_standalone(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/__init__.py", line 108, in start_standalone
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/standalone.py", line 104, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/outputs/glances_curses.py", line 960, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/outputs/glances_curses.py", line 938, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/outputs/glances_curses.py", line 523, in display
    __stat_display = self.__get_stat_display(stats, plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/outputs/glances_curses.py", line 478, in __get_stat_display
    args=self.args, max_width=plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/plugins/glances_plugin.py", line 701, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/plugins/glances_network.py", line 301, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers, not str
```

[glances-root.log.zip](https://github.com/nicolargo/glances/files/705865/glances-root.log.zip)

**Comment by nicolargo** [comment]
@carlba I do not think that the problem came from the export module. The error is in the network plugin. Can you please then us back the results of the following commands:

On a first terminal, enter:

    # glances  -w

On a second one:

   # http://0.0.0.0:61208/api/2/network

Thanks !

**Comment by carlba** [comment]
[results.json.zip](https://github.com/nicolargo/glances/files/706247/results.json.zip)
