### ISSUE TITLE
Glances compatibility with Python 3.5.1

### ISSUE THREAD

**Issue by HLFH** [nicolargo/glances#757]
Hi,

I'm on ArchLinux with Python 3.5.1 and Glances Develop. And Glances does not seem to work.
Do you confirm it also?
Do you plan to make Glances compatible with Python 3.5.1?

Thanks,
HLFH

**Comment by nicolargo** [comment]
Please follow the guideline to report issue => https://github.com/nicolargo/glances/blob/master/CONTRIBUTING.md#bug-reports

We need:
* Glances version
* PsUtil version
* Operating system version
* Error message
* Log file (with Glances -d to switch on the debug mode)

Thanks

**Comment by asergi** [comment]
I use Glances with Python 3.5.

No output, no log, no useful info.
There's no issue here.

**Comment by HLFH** [comment]
@asergi I'll answer in a few hours to get this issue more useful. Thanks.

**Comment by HLFH** [comment]
- Glances version: develop branch
- Python version: 3.5.1
- psutil version: 3.3.0
- OS version : ArchLinux (rolling release)
- Error message:

```bash
[root@arch-server ~]# ~/glances-venv/bin/pip install psutil
Collecting psutil
  Using cached psutil-3.3.0.tar.gz
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil
  Complete output from command /root/glances-venv/bin/python3 -c "import setuptools;__file__='/tmp/pip-build-0cqcuz53/psutil/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp_l9n4ss2pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.5/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.5/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-3.5/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.5/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.5/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-3.5/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-3.5/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-3.5/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-3.5/psutil
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/psutil
  gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -DPSUTIL_VERSION=330 -I/usr/include/python3.5m -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-3.5/psutil/_psutil_linux.o
  gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-3.5/psutil/_psutil_linux.o -L/usr/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/psutil/_psutil_linux.cpython-35m-x86_64-linux-gnu.so
  building 'psutil._psutil_posix' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/usr/include/python3.5m -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-3.5/psutil/_psutil_posix.o
  psutil/_psutil_posix.c: Dans la fonction ‘psutil_convert_ipaddr’:
  psutil/_psutil_posix.c:141:23: attention : comparaison entre des expressions entières signée et non signée [-Wsign-compare]
           for (n = 0; n < len; ++n) {
                         ^
  gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-3.5/psutil/_psutil_posix.o -L/usr/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/psutil/_psutil_posix.cpython-35m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_psutil_posix.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_psutil_linux.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/__init__.py -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_compat.py -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_common.py -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_psosx.py -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_pssunos.py -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_psbsd.py -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_psposix.py -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_pslinux.py -> build/bdist.linux-x86_64/wheel/psutil
  copying build/lib.linux-x86_64-3.5/psutil/_pswindows.py -> build/bdist.linux-x86_64/wheel/psutil
  running install_egg_info
  running egg_info
  writing dependency_links to psutil.egg-info/dependency_links.txt
  writing psutil.egg-info/PKG-INFO
  writing top-level names to psutil.egg-info/top_level.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'psutil.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*' found under directory 'docs/_build'
  warning: manifest_maker: MANIFEST.in, line 18: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
  
  writing manifest file 'psutil.egg-info/SOURCES.txt'
  Copying psutil.egg-info to build/bdist.linux-x86_64/wheel/psutil-3.3.0-py3.5.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-0cqcuz53/psutil/setup.py", line 268, in <module>
      main()
    File "/tmp/pip-build-0cqcuz53/psutil/setup.py", line 265, in main
      setup(**setup_args)
    File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for psutil
Failed to build psutil
Installing collected packages: psutil
  Running setup.py install for psutil
Successfully installed psutil-3.3.0
[root@arch-server ~]# ~/glances-venv/bin/pip install wheel
Requirement already satisfied (use --upgrade to upgrade): wheel in ./glances-venv/lib/python3.5/site-packages
[root@arch-server ~]# ~/glances-venv/bin/pip install psutil
Requirement already satisfied (use --upgrade to upgrade): psutil in ./glances-venv/lib/python3.5/site-packages
[root@arch-server ~]# ~/glances-venv/bin/pip install zeroconf
Collecting zeroconf
  Using cached zeroconf-0.17.4-py2.py3-none-any.whl
Collecting enum-compat (from zeroconf)
  Using cached enum-compat-0.0.2.tar.gz
Collecting netifaces (from zeroconf)
  Using cached netifaces-0.10.4.tar.gz
Collecting six (from zeroconf)
  Using cached six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: enum-compat, netifaces
  Running setup.py bdist_wheel for enum-compat
  Complete output from command /root/glances-venv/bin/python3 -c "import setuptools;__file__='/tmp/pip-build-oxtxj9v3/enum-compat/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp2mmv5z_ppip-wheel-:
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_egg_info
  running egg_info
  writing dependency_links to enum_compat.egg-info/dependency_links.txt
  writing enum_compat.egg-info/PKG-INFO
  writing top-level names to enum_compat.egg-info/top_level.txt
  deleting enum_compat.egg-info/requires.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'enum_compat.egg-info/SOURCES.txt'
  writing manifest file 'enum_compat.egg-info/SOURCES.txt'
  Copying enum_compat.egg-info to build/bdist.linux-x86_64/wheel/enum_compat-0.0.2.data/purelib/enum_compat-0.0.2-py3.5.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-oxtxj9v3/enum-compat/setup.py", line 45, in <module>
      install_requires=[] if has_enum else ['enum34'],
    File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for enum-compat
  Running setup.py bdist_wheel for netifaces
  Complete output from command /root/glances-venv/bin/python3 -c "import setuptools;__file__='/tmp/pip-build-oxtxj9v3/netifaces/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpk3c2kz41pip-wheel-:
  running bdist_wheel
  running build
  running build_ext
  checking for getifaddrs...found.
  checking for getnameinfo...found.
  checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h neteconet/ec.h netipx/ipx.h netpacket/packet.h linux/irda.h linux/atm.h linux/llc.h linux/tipc.h linux/dn.h.
  checking whether struct sockaddr has a length field...no.
  checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un ash ec ll atmpvc atmsvc dn irda llc.
  checking for routing socket support...no.
  checking for sysctl(CTL_NET...) support...no.
  checking for netlink support...yes.
  will use netlink to read routing table
  building 'netifaces' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -DNETIFACES_VERSION=0.10.4 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IRDA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_DN_H=1 -DHAVE_SOCKADDR_AT=1 -DHAVE_SOCKADDR_AX25=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_IPX=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_ASH=1 -DHAVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_ATMSVC=1 -DHAVE_SOCKADDR_DN=1 -DHAVE_SOCKADDR_IRDA=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1 -I/usr/include/python3.5m -c netifaces.c -o build/temp.linux-x86_64-3.5/netifaces.o
  netifaces.c: Dans la fonction ‘string_from_sockaddr’:
  netifaces.c:390:16: attention : comparaison entre des expressions entières signée et non signée [-Wsign-compare]
       if (buflen < 3 * len)
                  ^
  netifaces.c: Dans la fonction ‘gateways’:
  netifaces.c:1587:33: attention : comparaison entre des expressions entières signée et non signée [-Wsign-compare]
           if (pmsg->hdr.nlmsg_seq != seq || pmsg->hdr.nlmsg_pid != sanl.nl_pid)
                                   ^
  creating build/lib.linux-x86_64-3.5
  gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-3.5/netifaces.o -L/usr/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/netifaces.cpython-35m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  copying build/lib.linux-x86_64-3.5/netifaces.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
  running install_egg_info
  running egg_info
  writing top-level names to netifaces.egg-info/top_level.txt
  writing netifaces.egg-info/PKG-INFO
  writing dependency_links to netifaces.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'netifaces.egg-info/SOURCES.txt'
  writing manifest file 'netifaces.egg-info/SOURCES.txt'
  Copying netifaces.egg-info to build/bdist.linux-x86_64/wheel/netifaces-0.10.4-py3.5.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-oxtxj9v3/netifaces/setup.py", line 533, in <module>
      ext_modules=[iface_mod])
    File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/root/glances-venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for netifaces
Failed to build enum-compat netifaces
Installing collected packages: enum-compat, netifaces, six, zeroconf
  Running setup.py install for enum-compat
  Running setup.py install for netifaces
Successfully installed enum-compat-0.0.2 netifaces-0.10.4 six-1.10.0 zeroconf-0.17.4
[root@arch-server ~]# ~/glances-venv/bin/pip install netifaces
Requirement already satisfied (use --upgrade to upgrade): netifaces in ./glances-venv/lib/python3.5/site-packages
[root@arch-server ~]# ~/glances-venv/bin/pip install bottle
Collecting bottle
  Using cached bottle-0.12.9.tar.gz
Building wheels for collected packages: bottle
  Running setup.py bdist_wheel for bottle
  Stored in directory: /root/.cache/pip/wheels/0f/bd/f7/21e856551fa937e3c8a9d9592fd74a50714af336b8ee4f42c7
Successfully built bottle
Installing collected packages: bottle
Successfully installed bottle-0.12.9
[root@arch-server ~]# ~/glances-venv/bin/pip install influxdb
Collecting influxdb
  Using cached influxdb-2.10.0-py2.py3-none-any.whl
Collecting pytz (from influxdb)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in ./glances-venv/lib/python3.5/site-packages (from influxdb)
Collecting requests>=1.0.3 (from influxdb)
  Using cached requests-2.9.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.0.0 (from influxdb)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Installing collected packages: pytz, requests, python-dateutil, influxdb
Successfully installed influxdb-2.10.0 python-dateutil-2.4.2 pytz-2015.7 requests-2.9.0
[root@arch-server ~]# ~/glances-venv/bin/pip install influxdb^C
[root@arch-server ~]# ~/glances-venv/bin/pip install potsdb
Collecting potsdb
Installing collected packages: potsdb
Successfully installed potsdb-1.0.2
[root@arch-server ~]# ~/glances-venv/bin/pip install statsd
Collecting statsd
  Using cached statsd-3.2.1-py2.py3-none-any.whl
Installing collected packages: statsd
Successfully installed statsd-3.2.1
[root@arch-server ~]# ~/glances-venv/bin/pip install pika
Collecting pika
  Using cached pika-0.10.0-py2.py3-none-any.whl
Installing collected packages: pika
Successfully installed pika-0.10.0
[root@arch-server ~]# ~/glances-venv/bin/pip install pystache
Collecting pystache
Installing collected packages: pystache
Successfully installed pystache-0.5.4
[root@arch-server ~]# ~/glances-venv/bin/pip install docker-py
Collecting docker-py
  Using cached docker-py-1.6.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.2 in ./glances-venv/lib/python3.5/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in ./glances-venv/lib/python3.5/site-packages (from docker-py)
Collecting websocket-client>=0.32.0 (from docker-py)
  Using cached websocket_client-0.34.0.tar.gz
Building wheels for collected packages: docker-py, websocket-client
  Running setup.py bdist_wheel for docker-py
  Stored in directory: /root/.cache/pip/wheels/e6/d9/a1/fe57c3e479387975813b221e7f01dcaa0f73e9149744472c71
  Running setup.py bdist_wheel for websocket-client
  Stored in directory: /root/.cache/pip/wheels/c2/af/03/d3899019a2100d8b39625e578e8680f444096278d16b7dc4a4
Successfully built docker-py websocket-client
Installing collected packages: websocket-client, docker-py
Successfully installed docker-py-1.6.0 websocket-client-0.34.0
[root@arch-server ~]# ~/glances-venv/bin/pip install py-cpuinfo
Collecting py-cpuinfo
Installing collected packages: py-cpuinfo
Successfully installed py-cpuinfo-0.1.6
[root@arch-server ~]# ~/glances-venv/bin/pip install https://bitbucket.org/gleb_zhulik/py3sensors/get/tip.tar.gz
Collecting https://bitbucket.org/gleb_zhulik/py3sensors/get/tip.tar.gz
  Downloading https://bitbucket.org/gleb_zhulik/py3sensors/get/tip.tar.gz
Installing collected packages: PySensors
  Running setup.py install for PySensors
Successfully installed PySensors-0.0.2
```

- Log file: it's just during the installation, I'm wondering why I'm getting these kind of messages in red: 

- Failed building wheel for psutil
- Failed to build psutil 
 - Failed building wheel for enum-compat
 - Failed building wheel for netifaces
 - Failed to build enum-compat netifaces

Why does it happen? I'm don't it's a big issue because I can run Glances in this environment in console mode (not in webserver mode because of https://github.com/nicolargo/glances/issues/687)

Thanks in advance,
HLFH

**Comment by asergi** [comment]
Not a Glances issue.

It just fails to build wheel for psutil, enum-compat and netifaces.
Please report those bugs to their bug tracker.

**Comment by HLFH** [comment]
@asergi Done.
