### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#758]
With the 2.6 DEVELOP branch, after a while, Glances generate the following error:

```
python -m glances --export-influxdb
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nicolargo/Dropbox/dev/glances/glances/__main__.py", line 38, in <module>
    glances.main()
  File "glances/__init__.py", line 124, in main
    standalone.serve_forever()
  File "glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "glances/standalone.py", line 88, in __serve_forever
    self.stats.update()
  File "glances/stats.py", line 165, in update
    self._plugins[p].update()
  File "glances/plugins/glances_plugin.py", line 650, in wrapper
    ret = fct(*args, **kw)
  File "/home/nicolargo/Dropbox/dev/glances/glances/plugins/glances_load.py", line 109, in update
    self.update_views()
  File "/home/nicolargo/Dropbox/dev/glances/glances/plugins/glances_load.py", line 116, in update_views
    super(Plugin, self).update_views()
  File "glances/plugins/glances_plugin.py", line 300, in update_views
    for key in iterkeys(self.get_raw()):
RuntimeError: dictionary changed size during iteration
```

**Comment by nicolargo** [comment]
Patch to be tested (OK in Python 2 / TBD in Python 3)

**Comment by asergi** [comment]
@nicolargo: can you try this patch instead? https://gist.github.com/asergi/1197f15b8b3e08a7142a

**Comment by nicolargo** [comment]
@asergi Tested and approved. You can merge it to the develop branch.
