### ISSUE TITLE
Cannot start Glances 2.5.1 in server mode -s : always socket.error: [Errno 1]

### ISSUE THREAD

**Issue by bzazzera** [nicolargo/glances#762]
Hi all,

I cannot start Glances 2.5.1 in server mode -s I got always: `./glances -s`
```
Announce the Glances server on the LAN (using 192.168.194.103 IP address)
Traceback (most recent call last):
  File "./glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 169, in main
    args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_server.py", line 225, in __init__
    self.autodiscover_client = GlancesAutoDiscoverClient(socket.gethostname(), args)
  File "/usr/local/lib/python2.7/dist-packages/glances/core/glances_autodiscover.py", line 213, in __init__
    self.zeroconf.register_service(self.info)
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1415, in register_service
    self.check_service(info)
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1531, in check_service
    self.send(out)
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1651, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
socket.error: [Errno 1] Opération non permise
```
Many thanks in advance.

Bruno.

**Comment by nicolargo** [comment]
Try to uninstall zerconf:

    $ sudo pip uninstall zeroconf

Start Glances server again.

**Comment by bzazzera** [comment]
OK thank you it's working now by uninstalling zeroconf.

Merci beaucoup.
Bruno.
