### ISSUE TITLE
RAID support broken on python3

### ISSUE THREAD

**Issue by jlec** [nicolargo/glances#793]
```python
$ (0) glances
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/lib64/python3.4/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/lib64/python3.4/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/lib64/python3.4/site-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/lib64/python3.4/site-packages/glances/outputs/glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib64/python3.4/site-packages/glances/outputs/glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib64/python3.4/site-packages/glances/outputs/glances_curses.py", line 472, in display
    args=self.args)
  File "/usr/lib64/python3.4/site-packages/glances/plugins/glances_plugin.py", line 551, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/lib64/python3.4/site-packages/glances/plugins/glances_raid.py", line 98, in msg_curse
    arrays.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```
This happens with

* python-3.4.3
* glances-2.5.1
* pymdstat-0.4.2

**Comment by nicolargo** [comment]
@jlec : Is it working fine with Python 2 ?

**Comment by jlec** [comment]
@nicolargo yes it is.  Simple python 3 incompatibility

**Comment by asergi** [comment]
@jlec should be fixed in the develop branch. Can you please test? Thanks.

**Comment by jlec** [comment]
aa86c0b alone, doesn't fix the problem.

```python
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/usr/lib64/python3.4/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/lib64/python3.4/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/lib64/python3.4/site-packages/glances/core/glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/lib64/python3.4/site-packages/glances/outputs/glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib64/python3.4/site-packages/glances/outputs/glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib64/python3.4/site-packages/glances/outputs/glances_curses.py", line 472, in display
    args=self.args)
  File "/usr/lib64/python3.4/site-packages/glances/plugins/glances_plugin.py", line 551, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/lib64/python3.4/site-packages/glances/plugins/glances_raid.py", line 97, in msg_curse
    arrays = sorted(iterkeys(self.stats))
NameError: name 'iterkeys' is not defined
```

**Comment by asergi** [comment]
@jlec `develop` branch: `git clone -b develop https://github.com/nicolargo/glances.git`.
There is no `iterkeys` in master.

**Comment by jlec** [comment]
@asergi works here.

**Comment by asergi** [comment]
@jlec here's the patch for Glances 2.5.1 (master):
```diff
diff --git a/glances/plugins/glances_raid.py b/glances/plugins/glances_raid.py
index 3a88004..4e98f9b 100644
--- a/glances/plugins/glances_raid.py
+++ b/glances/plugins/glances_raid.py
@@ -94,8 +94,7 @@ class Plugin(GlancesPlugin):
         msg = '{0:>6}'.format('Avail')
         ret.append(self.curse_add_line(msg))
         # Data
-        arrays = self.stats.keys()
-        arrays.sort()
+        arrays = sorted(self.stats.keys())
         for array in arrays:
             # New line
             ret.append(self.curse_new_line())
@@ -114,8 +113,7 @@ class Plugin(GlancesPlugin):
                 ret.append(self.curse_new_line())
                 msg = '└─ Status {0}'.format(self.stats[array]['status'])
                 ret.append(self.curse_add_line(msg, status))
-                components = self.stats[array]['components'].keys()
-                components.sort()
+                components = sorted(self.stats[array]['components'].keys())
                 for i, component in enumerate(components):
                     if i == len(components) - 1:
                         tree_char = '└─'
```

**Comment by asergi** [comment]
@jlec +1. Thanks.
