### ISSUE TITLE
Sorting processes by I/O rate (io_counters) fails

### ISSUE THREAD

**Issue by sillage** [nicolargo/glances#795]
Using Glances v2.5.1 with psutil v4.0.0 on MacOS X 10.11.3, sorting processes by I/O rate (io_counters) fails:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/glances/core/glances_processes.py", line 666, in update
    reverse=self.sort_reverse)
  File "/usr/local/lib/python3.5/site-packages/glances/core/glances_processes.py", line 665, in <lambda>
    key=lambda x: x[1][self.sort_key],
KeyError: 'io_counters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/glances/__init__.py", line 125, in main
    standalone.serve_forever()
  File "/usr/local/lib/python3.5/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python3.5/site-packages/glances/core/glances_standalone.py", line 89, in __serve_forever
    self.stats.update()
  File "/usr/local/lib/python3.5/site-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.5/site-packages/glances/plugins/glances_processcount.py", line 58, in update
    glances_processes.update()
  File "/usr/local/lib/python3.5/site-packages/glances/core/glances_processes.py", line 669, in update
    logger.error("%s" % str(processdict.items()[0]))
TypeError: 'dict_items' object does not support indexing
```

**Comment by asergi** [comment]
There is no process `io_counters` on OS X. You shouldn't be able to do that.

**Comment by asergi** [comment]
After some investigation, the "real" bug is actually the second exception.

@sillage should be fixed in the develop branch. Can you please test? Thanks.

**Comment by nclsHart** [comment]
Tested and working fine on MacOS X 10.11.3 and Glances v2.6beta with psutil v4.0.0.

**Comment by asergi** [comment]
Thanks @nclsHart.
