### ISSUE TITLE
Filter processes crash

### ISSUE THREAD

**Issue by nclsHart** [nicolargo/glances#809]
Press ENTER, enter a filter...

Glances crach

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/silence/dev/glances/glances/__main__.py", line 38, in <module>
    glances.main()
  File "glances/__init__.py", line 126, in main
    standalone.serve_forever()
  File "glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "glances/standalone.py", line 88, in __serve_forever
    self.stats.update()
  File "glances/stats.py", line 165, in update
    self._plugins[p].update()
  File "/home/silence/dev/glances/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "glances/processes.py", line 603, in update
    if s is None or (self.is_filtered(s['cmdline']) and self.is_filtered(s['name'])):
  File "glances/processes.py", line 344, in is_filtered
    return self.process_filter_re.match(value) is None
TypeError: expected string or buffer
```

Glances v2.6beta with psutil v4.0.0
OS : Ubuntu 15.10

**Comment by nicolargo** [comment]
@asergi it is a regression, works with COMMIT d6e1067e9f0dbf66f0e0ccb650fa53999d0ab786

Can you have a look on it ?

Nicolas
