### ISSUE TITLE
Some Chrome processes are displayed as name "Enabled" 

### ISSUE THREAD

**Issue by nclsHart** [nicolargo/glances#826]
The processes appearing as "Enabled" in the following capture are in fact instances of chrome. 

![chrome](https://cloud.githubusercontent.com/assets/833625/14067370/1f9d0b7a-f464-11e5-9572-2563e1e6523f.png)

Full Google Chrome process: 

```
/opt/google/chrome/chrome --type=renderer --enable-features=LinuxObsoleteSystemIsEndOfTheLine<LinuxObsoleteSystemIsEndOfTheLine --lang=fr --force-fieldtrials=AppBannerTriggering/Aggressive/AutofillProfileOrderByFrecency/Enabled/CaptivePortalInterstitial/Enabled/*ChildAccountDetection/Disabled/*ChromeSuggestions/Default/*ClientSideDetectionModel/Model0/*CrossDevicePromo/Control/*DataReductionProxyConfigService/Enabled/*ExtensionActionRedesign/Enabled/*ExtensionDeveloperModeWarning/Default/*GFE/Default/InstanceID/Enabled/*LinuxObsoleteSystemIsEndOfTheLine/EndOfLine/MaterialDesignDownloads/Enabled/*OmniboxBundledExperimentV1/Unused_2/*PasswordBranding/Disabled/*PasswordGeneration/Disabled/*QUIC/EnabledAckDecimation/ReportCertificateErrors/ShowAndPossiblySend/SHA1IdentityUIWarning/Enabled/SHA1ToolbarUIJanuary2016/Warning/SHA1ToolbarUIJanuary2017/Error/*SafeBrowsingIncidentReportingService/Default/SafeBrowsingUnverifiedDownloads/DisableByParameterMostSbTypes2/*SafeBrowsingUpdateFrequency/Default/*SpdyEnableDependencies/Default/*UMA-Population-Restrict/normal/*UMA-Uniformity-Trial-1-Percent/group_84/*UMA-Uniformity-Trial-10-Percent/default/*UMA-Uniformity-Trial-100-Percent/group_01/*UMA-Uniformity-Trial-20-Percent/default/*UMA-Uniformity-Trial-5-Percent/group_13/*UMA-Uniformity-Trial-50-Percent/default/*UseDelayAgnosticAEC/DefaultEnabled/WebRTC-LocalIPPermissionCheck/Enabled
```

Glances version: 2.7_BETA
PSutil version: 4.0.0
OS: Ubuntu 15.10

**Comment by nicolargo** [comment]
@asergi Perhaps another issue connected to https://github.com/nicolargo/glances/issues/546 ?

**Comment by asergi** [comment]
It's the same psutil bug mentioned by desbma in #\546.
Anyway, here's the patch: https://gist.github.com/asergi/7a30cbb7f24fd146af21cd33b094c1db

Please test.

**Comment by nicolargo** [comment]
Hi @asergi : Patch tested. Can you merge it to the develop branch ?

**Comment by asergi** [comment]
d9bdce6

**Comment by asergi** [comment]
@nicolargo 2.6.2? We could just cherry pick the bugfix commits.

**Comment by nicolargo** [comment]
Yes @asergi, we can merge it to the DEVELOP branch and to a specific branch derived from MASTER to create the 2.6.2 version.

**Comment by nclsHart** [comment]
@asergi I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/silence/dev/glances/glances/__main__.py", line 38, in <module>
    glances.main()
  File "glances/__init__.py", line 133, in main
    standalone.serve_forever()
  File "glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "glances/standalone.py", line 92, in __serve_forever
    self.screen.update(self.stats)
  File "glances/outputs/glances_curses.py", line 975, in update
    self.flush(stats, cs_status=cs_status)
  File "glances/outputs/glances_curses.py", line 953, in flush
    self.display(stats, cs_status=cs_status)
  File "glances/outputs/glances_curses.py", line 558, in display
    'processlist').get_stats_display(args=self.args)
  File "glances/plugins/glances_plugin.py", line 559, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/home/silence/dev/glances/glances/plugins/glances_processlist.py", line 426, in msg_curse
    ret.extend(self.get_process_curses_data(p, first, args))
  File "/home/silence/dev/glances/glances/plugins/glances_processlist.py", line 311, in get_process_curses_data
    path, cmd, arguments = split_cmdline(cmdline)
  File "/home/silence/dev/glances/glances/plugins/glances_processlist.py", line 52, in split_cmdline
    exe, arguments = cmdline[0].split(' ', maxsplit=1)
TypeError: split() takes no keyword arguments
```

**Comment by asergi** [comment]
Fixed, thanks.
