### ISSUE TITLE
Exception after running glances for several hours

### ISSUE THREAD

**Issue by ngergo** [nicolargo/glances#840]
#### Circumstances
- `glances` without options with the default config
- running glances in tmux
- after some hours of run the following error will occur:

```
Traceback (most recent call last):/python2.7/site-packages/bernhard/__init__.py", line 54, in read_exactly
  File "/home/argus/venv/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.6', 'console_scripts', 'glances')()
  File "/home/argus/venv/local/lib/python2.7/site-packages/Glances-2.6-py2.7.egg/glances/__init__.py", line 133, in main
    standalone.serve_forever()
  File "/home/argus/venv/local/lib/python2.7/site-packages/Glances-2.6-py2.7.egg/glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "/home/argus/venv/local/lib/python2.7/site-packages/Glances-2.6-py2.7.egg/glances/standalone.py", line 92, in __serve_forever
    self.screen.update(self.stats)
  File "/home/argus/venv/local/lib/python2.7/site-packages/Glances-2.6-py2.7.egg/glances/outputs/glances_curses.py", line 975, in update
    self.flush(stats, cs_status=cs_status)
  File "/home/argus/venv/local/lib/python2.7/site-packages/Glances-2.6-py2.7.egg/glances/outputs/glances_curses.py", line 953, in flush
    self.display(stats, cs_status=cs_status)
  File "/home/argus/venv/local/lib/python2.7/site-packages/Glances-2.6-py2.7.egg/glances/outputs/glances_curses.py", line 524, in display
    args=self.args, max_width=plugin_max_width)
  File "/home/argus/venv/local/lib/python2.7/site-packages/Glances-2.6-py2.7.egg/glances/plugins/glances_plugin.py", line 555, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/home/argus/venv/lib/python2.7/site-packages/Glances-2.6-py2.7.egg/glances/plugins/glances_fs.py", line 229, in msg_curse
    for i in sorted(self.stats, key=comparsion_key):
TypeError: string indices must be integers, not str
```

I'm working on finding the root-cause for the issue. I'll post it here if I find.
#### Possible solution

Use  `isinstance(x, dict)` for all the items to check if it is a proper `comparsion_key` **or** avoid adding a non-dict instance to the list.
#### Versions
- Glances: `Glances v2.7_BETA`
- PSutil: `psutil v4.1.0`
- OS info:

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```
#### Logs

No related logs available in `glances.log`.

**Comment by nicolargo** [comment]
Hi @gregory094 ,

the line 

    for i in sorted(self.stats, key=comparsion_key):

did not exist in Glances 2.7 Beta.

It has been replaced by : 

    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):

Are you sure that you test it on the good Glances version ?

Nicolas

**Comment by gregory094** [comment]
Hi @nicolargo,

Sorry I've just modified the code after the first error to separate the possible part of the code that throws the exception. `operator.itemgetter(self.get_key())` will result this exception. So the error is valid.

The `itemgetter` awaits a `dict` but gets an `str` somewhere... That's why it throws the error mentioned above.

**Comment by nicolargo** [comment]
@gregory094 

Nope, itemgetter can get a 'str':

    In [10]: stats
    Out[10]: [{'d': 'c', 'k': 'b'}, {'d': 'b', 'k': 'a'}, {'d': 'a', 'k': 'c'}]
    In [11]: sorted(stats, key=operator.itemgetter('k'))
    Out[11]: [{'d': 'b', 'k': 'a'}, {'d': 'c', 'k': 'b'}, {'d': 'a', 'k': 'c'}]

Do not understand why a exception is raised ?

**Comment by gregory094** [comment]
@nicolargo 

Sorry... I've misinterpreted it's not the `itemgetter` that throws the error but the `sorted` function. Somehow it awaits a `dict` to lookup the key but gets an `str` as far as I can understand. Please correct me if it's not the situation.

**Comment by nicolargo** [comment]
Are you sure that you use the latest develop branch ? In your first comment, Glances 2.6 seems to be used (/home/argus/venv/lib/python2.7/site-packages/Glances-2.6-py2.7.egg).

**Comment by ngergo** [comment]
Hm... I do. `Glances v2.7_BETA` is the version string printed by glances.

**Comment by nicolargo** [comment]
Do you reproduce with the latest HEAD version (develop branch) ?

**Comment by ngergo** [comment]
Yes. After some hours I have the same issue. I'll try to investigate the problem further and give a short description here... maybe a fix.

**Comment by nicolargo** [comment]
Ok thanks @ngergo !

**Comment by nicolargo** [comment]
Any head up ? Can you try on the stable Glances 2.7 version ?
