### ISSUE TITLE
Glances stopped working when using VPN with no internet access.

### ISSUE THREAD

**Issue by lnxg33k** [nicolargo/glances#842]
#### Description

Working behind a VPN with no internet access 'no internet splitting is allowed through the VPN connection'

Network Interface:
```utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1400
	inet 172.30.65.18 --> 172.30.65.18 netmask 0xffffffff```
#### Versions

* Glances v2.6.1 with psutil v4.1.0
* Operating System  OSX 10.11.4

#### Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.6.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 133, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/site-packages/glances/standalone.py", line 92, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 975, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 953, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 518, in display
    stats_ip = stats.get_plugin('ip').get_stats_display(args=self.args)
  File "/usr/local/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 555, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/site-packages/glances/plugins/glances_ip.py", line 116, in msg_curse
    msg = '{0:}/{1}'.format(self.stats['address'], self.stats['mask_cidr'])
KeyError: 'mask_cidr'```

**Comment by nicolargo** [comment]
Should be corrected in the latest HEAD version (DEVELOP branch).

Thanks for the report !

**Comment by asergi** [comment]
If I'm not wrong, is a `netifaces` issue. It would be nice to know why it fails.
Perhaphs, we could use psutil's `net_if_addrs()` as fallback to get the same info (don't know if it's doable, gateway info is missing). Also, this way we could provide the IP plugin to *BSD as well (netifaces is broken for now).
