### ISSUE TITLE
Wrong formatting for tree columns

### ISSUE THREAD

**Issue by mmozeiko** [nicolargo/glances#849]
When I run `glances --tree` the tree menu is messed up. It looks like `W/s` and `Command` columns are swapped for some of child processes. If I run glances command multiple times, this always happens for same processes.

![screenshot](http://i.imgur.com/RMhiKwE.png)

* Glances: 2.6.1
* PSutil: 4.1.0
* Operating System: ArchLinux

**Comment by nicolargo** [comment]
@desbma Can you have a look on this issue ?

**Comment by desbma** [comment]
I did reproduce and fix is available in #851.

**Comment by nicolargo** [comment]
@mmozeiko : Can you test the DEVELOP branch and check that the bug is corrected ?

**Comment by mmozeiko** [comment]
I get IndexError exception:

```
$ ./glances --tree
Traceback (most recent call last):
  File "./glances", line 9, in <module>
    load_entry_point('Glances==2.6.1', 'console_scripts', 'glances')()
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/__init__.py", line 133, in main
    standalone.serve_forever()
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/standalone.py", line 92, in __serve_forever
    self.screen.update(self.stats)
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/outputs/glances_curses.py", line 975, in update
    self.flush(stats, cs_status=cs_status)
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/outputs/glances_curses.py", line 953, in flush
    self.display(stats, cs_status=cs_status)
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/outputs/glances_curses.py", line 558, in display
    'processlist').get_stats_display(args=self.args)
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/plugins/glances_plugin.py", line 559, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/plugins/glances_processlist.py", line 427, in msg_curse
    max_node_count=glances_processes.max_processes))
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/plugins/glances_processlist.py", line 132, in get_process_tree_curses_data
    max_node_count=children_max_node_count)
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/plugins/glances_processlist.py", line 139, in get_process_tree_curses_data
    child_data = self.add_tree_decoration(child_data, child is node.children[-1], first_level)
  File "/home/mmozeiko/venv/lib/python3.5/site-packages/Glances-2.6.1-py3.5.egg/glances/plugins/glances_processlist.py", line 169, in add_tree_decoration
    child_data[pos[0]]["msg"] = prefix
IndexError: list index out of range
```

**Comment by desbma** [comment]
That last error should be fixed by #852.

**Comment by mmozeiko** [comment]
Yes, develop branch + b410a0c commit in #852 fixes the problem. Now I get pretty tree view!

![screenshot](http://i.imgur.com/DE6yG1h.png)

**Comment by nicolargo** [comment]
Ok, merged in the DEVELOP branch.

Thanks all !
