### ISSUE TITLE
Random crach occurs with the sensor plugin

### ISSUE THREAD

**Issue by sungmok** [nicolargo/glances#861]
#### Description

If execute follow command then the crash occur at random.
$ glances -C ~/glances.conf --export-influxdb

#### Versions

* Glances (glances -V): 2.6.1
* PSutil (glances -V):4.1.0
* Operating System (lsb_release -a):

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

#### Logs

$ glances -C ~/glances.conf --export-influxdb

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.6.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 133, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 92, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 975, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 953, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 530, in display
    'sensors').get_stats_display(args=self.args)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 555, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_sensors.py", line 186, in msg_curse
    if i['value'] != b'ERR':
TypeError: string indices must be integers, not str

**Comment by nicolargo** [comment]
Hi @sungmok can you start Glances in debug mode (just add -d to your command line) and [paste/bin](http://pastebin.com/) the /tmp/glances.log file.

Thnaks in advance.

**Comment by nicolargo** [comment]
@sungmok Can you check if Glances 2.7 correct this issue ?
