### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by oppianmatt** [nicolargo/glances#864]
#### Description

Looks like a race condition with docker containers. Sometimes it will throw this exception with stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.6.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 133, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 88, in __serve_forever
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 658, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_docker.py", line 226, in update
    container['memory'] = self.get_docker_memory(container['Id'], self.thread_list[container['Id']].stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_docker.py", line 297, in get_docker_memory
    ret['rss'] = all_stats['memory_stats']['stats']['rss']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

#### Versions

* Glances (glances -V): Glances v2.6.1 with psutil v4.1.0
* PSutil (glances -V): Glances v2.6.1 with psutil v4.1.0
* Operating System (lsb_release -a):

```
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
```

**Comment by nicolargo** [comment]
The Docker API has change between the version 1.0 and 1.1. Glances 2.6.1 is not compatible with Docker 1.1. Please use the latest DEVELOP branch (2.7 beta) or disable the Docker plugin using --disable-docker.

Thanks for the issue report.

**Comment by oppianmatt** [comment]
using the latest from pip, and using glances especially to monitor docker because glances is awesome at it.

But if anyone else sees this and wants to know a workaround, use the docker glances as described.

**Comment by nicolargo** [comment]
REJECTED: cause duplicated =>https://github.com/nicolargo/glances/issues/848

**Comment by nicolargo** [comment]
Note: i just release a official patch (Glances 2.6.2) for this issue. Please upgrade your Glances software using Pipy.
