### ISSUE TITLE
Crash at startup on macOs

### ISSUE THREAD

**Issue by notFloran** [nicolargo/glances#879]
#### Description

Glances crash at startup on macOs.

#### Versions

* Glances: develop
* PSutil : psutil v3.2.2
* Operating System : macOs 10.11.5

#### Logs

```bash
$ LANGUAGE=en_US.utf8 ~/glances-venv/bin/python -m glances
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/f.brutel/dev/glances/glances/__main__.py", line 29, in <module>
    glances.main()
  File "glances/__init__.py", line 127, in main
    args=core.get_args())
  File "glances/standalone.py", line 68, in __init__
    self.stats.update()
  File "glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/Users/f.brutel/dev/glances/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "glances/processes.py", line 408, in update
    OSX and s['name'] == 'kernel_task'):
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by nicolargo** [comment]
Strange, it means that s is None but s should contains the process stats:

            s = self.__get_process_stats(proc,
                                         mandatory_stats=True,
                                         standard_stats=self.max_processes is None)

I just add a check (s is None) in the latest HEAD version (develop branch), can you test it ?

**Comment by notFloran** [comment]
@nicolargo That fix the bug, thanks !
