### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by geekrohit** [nicolargo/glances#884]
Getting this error when trying to run glances, or even with ALL the disable parameters. Any pointers ?

Version : 
glances --version
Glances v2.6.2 with psutil v4.3.0

lsb_release -a : 
<pre>
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
</pre>

<pre>
glances
/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py:364: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 2] No such file or directory: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.6.2', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 130, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 67, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 658, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_network.py", line 90, in update
    netstatus = psutil.net_if_stats()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1961, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 791, in net_if_stats
    isup, duplex, speed, mtu = cext.net_if_stats(name)
OSError: [Errno 25] Inappropriate ioctl for device
</pre>

**Comment by nicolargo** [comment]
Looks like a PSUtil issue, can you update it using:

    pip install --upgrade psutil

Use sudo if needed...

**Comment by nicolargo** [comment]
REJECTED: can not reproduce + no news...
