### ISSUE TITLE
Glances crash when exporting to InfluxDB

### ISSUE THREAD

**Issue by Coriou** [nicolargo/glances#931]
I seem to have a problem when I'm trying to run Glances to export data to InfluxDB. There seems to be a few issues very similar to mine, however all closed and apparently fixed. 

Am I missing something here ?

**EDIT :** Problem happens even if I use the `--disable-docker` flag.

#### Description

I'm getting this error shortly after running `glances --export-influxdb -C /etc/glances/glances.conf` :

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 130, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 111, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 96, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 1018, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 996, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 541, in display
    args=self.args, max_width=plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 631, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_network.py", line 281, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers, not str
```

#### Versions

* Glances (glances -V): 2.7.1
* PSutil (glances -V): 4.3.1
* Operating System (lsb_release -a): Debian GNU/Linux 8.5 (jessie)
* Influx (influx -version) : 1.0.0

#### Config

My `glances.conf` file (influx server running fine, database exists, valid credentials) :

> [influxdb]
> host=localhost
> port=8086
> user=root
> password=root
> db=glances

#### Log

`ERROR -- Cannot export docker stats to InfluxDB (400: {"error":"unable to parse 'docker,server=stats ': invalid field format"}`

Complete : http://pastebin.com/QMz4WDyx

**Comment by nicolargo** [comment]
Hi @Coriou .

I can not reproduce the bug on my system (more or less the same configuration).

My conf file:

```
[influxdb]
# Configuration for the --export-influxdb option
# https://influxdb.com/
host=localhost
port=8086
user=root
password=root
db=glances
prefix=localhost
#tags=foo:bar,spam:eggs
```

My command line:

```
$ glances --export-influxdb -C ./glances.conf
```

and the log file (/tmp/glances.log):

```
2016-09-27 21:35:14,017 -- INFO -- Start Glances 2.7.1
2016-09-27 21:35:14,017 -- INFO -- CPython 2.7.12 and PSutil 4.3.1 detected
2016-09-27 21:35:14,021 -- INFO -- Read configuration file './glances.conf'
2016-09-27 21:35:14,022 -- INFO -- Start standalone mode
2016-09-27 21:35:14,325 -- INFO -- Stats will be exported to InfluxDB server: http://localhost:8086
2016-09-27 21:39:11,082 -- INFO -- Stop Glances
```

The result:

![selection_257](https://cloud.githubusercontent.com/assets/776747/18888987/151c27e4-84fb-11e6-9351-7c8b3e47f826.png)

Is your Docker plugin displayed correctly in the user interface ?
Can we have a screenshot ?

**Comment by Coriou** [comment]
Hello !

Thanks for trying to reproduce my issue. I thought it would work though (I mean that I thought you'd be able to reproduce easily). Are you also using Influx 1.0 ? Other than that my config is quite standard.

Anyway, I've been trying again this morning without any luck. Same thing happens.

Here's my InfluxDB (empty, of course) :

![influxDB Web Admin](https://i.imgur.com/oh0CYLs.png) 

And this is my Glances UI (started simply with `glances`, no params). It runs fine :

![Glances](https://i.imgur.com/e99mLMv.png) 

I have installed all the optional dependencies for Glances, using pip as mentioned in the docs (I only replaced `cassandra` with `cassandra-driver`, but I don't use it anyway) :

`pip install bottle requests batinfo https://bitbucket.org/gleb_zhulik/py3sensors/get/tip.tar.gz zeroconf netifaces pymdstat influxdb elasticsearch potsdb statsd pystache docker-py pysnmp pika py-cpuinfo bernhard cassandra-driver scandir`

Here's my `pip freeze` : http://pastebin.com/k0gMJDtj

**Comment by Coriou** [comment]
^ closed by accident..

**Comment by nicolargo** [comment]
Yes i have InfluxDB version 1.0.0 runniing inside a container (Docker). 

Have you try to delete and recreate your glances database ?

**Comment by Coriou** [comment]
Hey !

Yes, I have recreated my glances database.

I have attached the [glances.log](https://github.com/nicolargo/glances/files/503077/glances.log.zip) file to this post, here's [a Pastebin too](http://pastebin.com/wa6kAzU2).

Thanks !

**Comment by tuwid** [comment]
Hi,
i'm having this issue too :

```
Traceback (most recent call last):ng or critical alert detected
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 130, in main
    standalone.serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 111, in serve_forever
    return self.__serve_forever()
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 96, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 1018, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 996, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib/python2.7/site-packages/glances/outputs/glances_curses.py", line 541, in display
    args=self.args, max_width=plugin_max_width)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 631, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_network.py", line 281, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers, not str

```

I do have the data on flux but this will crash after a while ( 20 seconds or more )

**Comment by nicolargo** [comment]
@tuwid : i just commit a workaround on the DEVELOP branch. The --disable-docker tag should work ok now. Can you try this ?

**Comment by thomasbl** [comment]
Heya,

I had had the same issue with same error/debug messages and almost same config for influxdb. After playing around a bit I found out that it still works if you use python3 instead of python2. Here is what I was doing:

`
$ virtualenv --python=python3 venv_py3
$ venv_py3/bin/pip install glances influxdb
$ venv_py3/bin/glances --debug -t 5 --export-influxdb --config `pwd`/glances.conf
`

cheers,
Thomas

**Comment by tuwid** [comment]
@nicolargo I tried the --disable-docker tag but it didnt work. I'll try to switch to the dev branch and retry

**Comment by nicolargo** [comment]
@tuwid For the moment, it should only work on the DEVELOP branch.

Keep us inform.

**Comment by nicolargo** [comment]
@tuwid Any head up ?

**Comment by Coriou** [comment]
Sorry for late reply !

I have installed latest develop release (v2.7.1_1) and I still have the same error :

```
$:~# glances -t 5 --export-influxdb
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 130, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 111, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 96, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 1018, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 996, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 541, in display
    args=self.args, max_width=plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 631, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_network.py", line 281, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers, not str
```

My log file (using `glances -t 5 --export-influxdb -d`) : 

```
2016-11-02 04:33:42,963 -- DEBUG -- InfluxDB error during stat convertion /.mnt_point=/ (could not convert string to float: /)
2016-11-02 04:33:42,964 -- DEBUG -- InfluxDB error during stat convertion /.fs_type=ext4 (could not convert string to float: ext4)
2016-11-02 04:33:42,964 -- DEBUG -- InfluxDB error during stat convertion /.key=mnt_point (could not convert string to float: mnt_point)
2016-11-02 04:33:42,964 -- DEBUG -- InfluxDB error during stat convertion /.device_name=/dev/vda1 (could not convert string to float: /dev/vda1)
2016-11-02 04:33:42,968 -- DEBUG -- Export mem stats to InfluxDB
2016-11-02 04:33:42,976 -- DEBUG -- Export sensors stats to InfluxDB
2016-11-02 04:33:42,976 -- DEBUG -- InfluxDB error during stat convertion Battery.key=label (could not convert string to float: label)
2016-11-02 04:33:42,976 -- DEBUG -- InfluxDB error during stat convertion Battery.type=battery (could not convert string to float: battery)
2016-11-02 04:33:42,976 -- DEBUG -- InfluxDB error during stat convertion Battery.unit=% (could not convert string to float: %)
2016-11-02 04:33:42,976 -- DEBUG -- InfluxDB error during stat convertion Battery.value= (could not convert string to float: )
2016-11-02 04:33:42,976 -- DEBUG -- InfluxDB error during stat convertion Battery.label=Battery (could not convert string to float: Battery)
2016-11-02 04:33:42,979 -- DEBUG -- Export cpu stats to InfluxDB
2016-11-02 04:33:42,984 -- DEBUG -- Export processcount stats to InfluxDB
2016-11-02 04:33:42,992 -- DEBUG -- Export docker stats to InfluxDB
2016-11-02 04:33:42,995 -- ERROR -- Cannot export docker stats to InfluxDB (400: {"error":"unable to parse 'docker ': invalid field format"}
)
2016-11-02 04:33:43,028 -- DEBUG -- Plugin amps update return []
2016-11-02 04:33:43,028 -- DEBUG -- Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2016-11-02 04:33:43,028 -- DEBUG -- No config file found
2016-11-02 04:33:43,030 -- DEBUG -- Can't connect to the Docker server (('Connection aborted.', error(2, 'No such file or directory')))
2016-11-02 04:33:43,030 -- DEBUG -- Plugin docker update return {}
2016-11-02 04:33:43,030 -- DEBUG -- ports plugin - Create thread for scan list []
2016-11-02 04:33:43,030 -- DEBUG -- Plugin ports update return []
2016-11-02 04:33:43,031 -- DEBUG -- Finalise export interface influxdb
2016-11-02 04:33:43,031 -- DEBUG -- Stop the load plugin
2016-11-02 04:33:43,031 -- DEBUG -- Stop the help plugin
2016-11-02 04:33:43,031 -- DEBUG -- Stop the ip plugin
2016-11-02 04:33:43,031 -- DEBUG -- Stop the memswap plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the batpercent plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the processlist plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the uptime plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the network plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the percpu plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the irq plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the system plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the diskio plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the folders plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the core plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the fs plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the raid plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the mem plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the alert plugin
2016-11-02 04:33:43,032 -- DEBUG -- Stop the psutilversion plugin
2016-11-02 04:33:43,033 -- DEBUG -- Stop the hddtemp plugin
2016-11-02 04:33:43,033 -- DEBUG -- Stop the sensors plugin
2016-11-02 04:33:43,033 -- DEBUG -- Stop the now plugin
2016-11-02 04:33:43,033 -- DEBUG -- Stop the quicklook plugin
2016-11-02 04:33:43,033 -- DEBUG -- Stop the cpu plugin
2016-11-02 04:33:43,033 -- DEBUG -- Stop the processcount plugin
2016-11-02 04:33:43,033 -- DEBUG -- Stop the amps plugin
2016-11-02 04:33:43,033 -- DEBUG -- Stop the docker plugin
2016-11-02 04:33:43,033 -- DEBUG -- ports plugin - Close thread for scan list []
2016-11-02 04:33:43,033 -- DEBUG -- Stop the ports plugin
2016-11-02 04:33:43,033 -- DEBUG -- Check Glances version (installed: 2.7.1 / latest: 2.7.1)
```

**Comment by SvenBrunk** [comment]
I would like to mention that I have the very same issue currently with the rabbitmq export. It seems to be a problem on a higher level. Could you post a reference to the commit on develop that is supposed to fix this?

**Comment by nicolargo** [comment]
The issue 2.7.1 is not the development branch.
The current development branch is 2.8_DEVELOP and can be installed with the following procedure: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version

**Comment by SvenBrunk** [comment]
I was more after a small patch for this, but I will try the development branch, thanks

**Comment by SvenBrunk** [comment]
AHA! Now I can at least see the root cause of the problem:

/home/vagrant/glances-venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/vagrant/glances-venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "glances/exports/glances_export.py", line 167, in update
    export_names, export_values = self.__build_export(all_stats[i])
  File "glances/exports/glances_export.py", line 203, in __build_export
    item_names, item_values = self.__build_export(item)
  File "glances/exports/glances_export.py", line 181, in __build_export
    pre_key = '{}.'.format(stats[stats['key']])
KeyError: u'python'

**Comment by SvenBrunk** [comment]
@nicolargo could you please check if that KeyError is still due to the same refactoring please? It seems to me that the data structure just changed or something like that. Everything but the pure curses interface seems not to work properly anymore

**Comment by nicolargo** [comment]
Hi @SvenBrunk , can you double check your Glances version.

It should display:

    glances -V
    Glances v2.8_DEVELOP with psutil v5.0.0

**Comment by SvenBrunk** [comment]
@nicolargo yes, it does. See the tickets I referenced. You already found that the base error is in ip module. It does no longer occur if I also add --disable-ip
Using glances develop only changed one error to another. 
It would of course be better if glances would fail with a bit more helpful error message if there is such a bug in a plugin :)
