### ISSUE TITLE
Default AMP crashes when `command` given

### ISSUE THREAD

**Issue by mbirth** [nicolargo/glances#933]
#### Description

As soon as I define a `command=` line (empty or with an actual command) in a `[amp_xxx]` section, the entry is missing from the task list and on startup, glances throws this error (one for each AMP section with a `command` line):

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/usr/local/lib/python3.5/dist-packages/glances/amps/glances_default.py", line 70, in update
    self.set_result(to_ascii(msg.rstrip()))
  File "/usr/local/lib/python3.5/dist-packages/glances/compat.py", line 35, in to_ascii
    return unicodedata.normalize('NFKD', s).encode('ASCII', 'ignore')
TypeError: normalize() argument 2 must be str, not bytes
```

#### Versions

```
$ glances -V
Glances v2.7.1 with psutil v4.3.1
```

and

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

$ uname -a
Linux raspi 4.4.0-1023-raspi2 #29-Ubuntu SMP Tue Sep 6 16:12:44 UTC 2016 armv7l armv7l armv7l GNU/Linux

$ python3 -V
Python 3.5.2
```

**Comment by nicolargo** [comment]
Please can you provide your glances.conf file as an example?

**Comment by mbirth** [comment]
http://pastebin.com/MBVbL2Wk

**Comment by nicolargo** [comment]
Problem reproduced but only with the Python 3.5 interpreter.

I do not understand your log. The crash shows that you uses Python 3:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
```

But the glances -V shows:

```
Glances v2.7.1 with psutil v4.3.1
```

As a work around, use Python 2.7 instead of Python 3.x...

**Comment by nicolargo** [comment]
Corrected in the latest DEVELOP branch (HEAD).

Workarround for the current Glances version (2.7.1): use Python 2.7.
