### ISSUE TITLE
latest DockerHub Version and latest pip Version doesn't match

### ISSUE THREAD

**Issue by RocKordier** [nicolargo/glances#944]
Hey @nicolargo 

in my environment i have some servers with docker installed and some without.
So i 've tried to setup a client-server glances infrastructure.

The connection to a glance server (latest docker hub image)  in a pip environment (Glances v2.7.1 with psutil v4.4.2) fails with this error:
```
$ glances --export-influxdb -C glances.conf -c xxx.xxx.xxx.xxx
Traceback (most recent call last):
 File "/usr/local/bin/glances", line 9, in <module>
   load_entry_point('Glances==2.7', 'console_scripts', 'glances')()
 File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 154, in main
   if not client.login():
 File "/usr/local/lib/python2.7/dist-packages/glances/client.py", line 156, in login
   if not self._login_glances():
 File "/usr/local/lib/python2.7/dist-packages/glances/client.py", line 124, in _login_glances
   self.stats.set_plugins(json.loads(self.client.getAllPlugins()))
 File "/usr/local/lib/python2.7/dist-packages/glances/stats_client.py", line 48, in set_plugins
   plugin = __import__(header + item)
ImportError: No module named glances_wifi
```

The problem is that you have no tags on docker hub which corresponds with a stable glance release. You only build the latest tag from your develop-branch. Could you please push stable releases to docker hub also?

Thx, Eric

**Comment by nicolargo** [comment]
Hi @RocKordier ,

the Glances Docker container available in the purpose is to simplify the test of the DEVELOP branch.

**Comment by nicolargo** [comment]
Done !

I just add a 'stable' tag based on the master branch.
