### ISSUE TITLE
Deprecated platform.linux_distribution() in Python 3.5

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#945]
#### Description

Warning message returned by CircleCI (https://circleci.com/gh/nicolargo/glances/417):

/home/ubuntu/glances/glances/plugins/glances_system.py:115: PendingDeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5 and will be removed in Python 3.7
  linux_distro = platform.linux_distribution()

One solution: Use the distro Pypi lib => https://pypi.python.org/pypi/distro

```
In [1]: import distro

In [2]: distro.linux_distribution()
Out[2]: (u'Ubuntu', u'16.04', u'Xenial Xerus')
```

**Comment by nicolargo** [comment]
Done in the latest commit.

Please test.

**Comment by asergi** [comment]
@nicolargo 
Hi, can we revert this change, please? There really is no need to make `distro` mandatory for Python < 3.7. There really is no need to depend on that library even on Python >= 3.7, imo.

I already addressed the issue in af67cfc. We just need to make use of that function by default on Python >= 3.5.

**Comment by nicolargo** [comment]
No problem @asergi . Can you make a pull request ?

**Comment by asergi** [comment]
I can't test at the moment... develop is borked :)
```
Traceback (most recent call last):
  File "/home/alessio/venvs/py35-glances/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/home/alessio/venvs/py35-glances/src/glances/glances/__init__.py", line 130, in main
    args=core.get_args())
  File "/home/alessio/venvs/py35-glances/src/glances/glances/standalone.py", line 68, in __init__
    self.stats.update()
  File "/home/alessio/venvs/py35-glances/src/glances/glances/stats.py", line 160, in update
    self._plugins[p].update()
  File "/home/alessio/venvs/py35-glances/src/glances/glances/plugins/glances_plugin.py", line 805, in wrapper
    ret = fct(self, *args, **kw)
  File "/home/alessio/venvs/py35-glances/src/glances/glances/plugins/glances_plugin.py", line 814, in wrapper
    ret = fct(*args, **kw)
  File "/home/alessio/venvs/py35-glances/src/glances/glances/plugins/glances_docker.py", line 157, in update
    self.docker_client = self.connect()
  File "/home/alessio/venvs/py35-glances/src/glances/glances/plugins/glances_docker.py", line 101, in connect
    ret = docker.Client(base_url='unix://var/run/docker.sock')
AttributeError: module 'docker' has no attribute 'Client'
```

**Comment by nicolargo** [comment]
@asergi Can not reproduce on my Python 3.5 virtenv. What is your Docker and Docker-py version ?

**Comment by asergi** [comment]
None. Just a fresh venv with glances + psutil and nothing more.

**Comment by nicolargo** [comment]
@asergi the last commit (0d634d0) on the DEVELOP branch should resolv this issue....

**Comment by asergi** [comment]
```diff
diff --git a/glances/plugins/glances_system.py b/glances/plugins/glances_system.py
index 58c6031..1ade27b 100644                                                    
--- a/glances/plugins/glances_system.py                                          
+++ b/glances/plugins/glances_system.py                                          
@@ -113,11 +113,15 @@ class Plugin(GlancesPlugin):                               
             self.stats['hostname'] = platform.node()                            
             self.stats['platform'] = platform.architecture()[0]                 
             if self.stats['os_name'] == "Linux":                                
-                linux_distro = platform.linux_distribution()                    
-                if linux_distro[0] == '':                                       
+                try:                                                            
+                    linux_distro = platform.linux_distribution()                
+                except AttributeError:                                          
                     self.stats['linux_distro'] = _linux_os_release()            
                 else:                                                           
-                    self.stats['linux_distro'] = ' '.join(linux_distro[:2])     
+                    if linux_distro[0] == '':                                   
+                        self.stats['linux_distro'] = _linux_os_release()        
+                    else:                                                       
+                        self.stats['linux_distro'] = ' '.join(linux_distro[:2]) 
                 self.stats['os_version'] = platform.release()                   
             elif self.stats['os_name'].endswith('BSD'):                         
                 self.stats['os_version'] = platform.release()
```
We can avoid using `platform.linux_distribution()` on Python 3.5-3.6 too, but I think the above solution is better since we don't need to add check for them. Anyway, DeprecationWarning is ignored by default in Python 2.7+. To see them you need to change the warnings filter on purpose (like CircleCI).

**Comment by TJPoorman** [comment]
With the new v4 requiring python3.8+ would it be worth swapping this over to the distro package to remove the deprecated feature of platform?
