### ISSUE TITLE
IRQ module IOErro

### ISSUE THREAD

**Issue by hastinbe** [nicolargo/glances#954]
#### Description

Contrary to expectations, the --disable-irq option doesn't disable the IRQ module and seems to only prohibit its output.  In my case this Linux system doesn't have a /proc/interrupts because of OpenVZ, so the IRQ module throws an IOError.  But I think the bigger question is why are disabled plugin modules being loaded at all?

#### Versions

* Glances (glances -V): v2.7.1
* PSutil (glances -V): v4.4.2
* Operating System (lsb_release -a): Ubuntu 12.04.5 LTS

#### Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 127, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 734, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_irq.py", line 66, in update
    with open('/proc/interrupts') as irq_proc:
IOError: [Errno 2] No such file or directory: '/proc/interrupts'
```

**Comment by hastinbe** [comment]
Closing. I searched this issue but not on the develop branch. https://github.com/nicolargo/glances/commit/540e840bbb07762275c3ac3a8987cc10651f6c06

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/948
