### ISSUE TITLE
Influxdb via SSL

### ISSUE THREAD

**Issue by egyptianbman** [nicolargo/glances#973]
#### Description

Is there any way to send influxdb data via SSL? Adding an option for `ssl` might be the most direct route to achieve this.

#### Versions

* Glances (glances -V): develop branch, latest running in docker
* PSutil (glances -V): develop branch, latest running in docker
* Operating System (lsb_release -a): Fedora, running on docker

#### Logs

```
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
app_1  |     "__main__", fname, loader, pkg_name)
app_1  |   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
app_1  |     exec code in run_globals
app_1  |   File "/glances/glances/__main__.py", line 29, in <module>
app_1  |     glances.main()
app_1  |   File "glances/__init__.py", line 229, in main
app_1  |     start_standalone(config=config, args=args)
app_1  |   File "glances/__init__.py", line 109, in start_standalone
app_1  |     standalone = GlancesStandalone(config=config, args=args)
app_1  |   File "glances/standalone.py", line 42, in __init__
app_1  |     self.stats = GlancesStats(config=config, args=args)
app_1  |   File "glances/stats.py", line 43, in __init__
app_1  |     self.load_modules(self.args)
app_1  |   File "glances/stats.py", line 83, in load_modules
app_1  |     self.load_exports(args=args)
app_1  |   File "glances/stats.py", line 131, in load_exports
app_1  |     self._exports[export_name] = export_module.Export(args=args, config=self.config)
app_1  |   File "/glances/glances/exports/glances_influxdb.py", line 59, in __init__
app_1  |     self.client = self.init()
app_1  |   File "/glances/glances/exports/glances_influxdb.py", line 115, in init
app_1  |     get_all_db = [i['name'] for i in db.get_list_database()]
app_1  |   File "/usr/local/lib/python2.7/dist-packages/influxdb/influxdb08/client.py", line 538, in get_list_database
app_1  |     expected_response_code=200
app_1  |   File "/usr/local/lib/python2.7/dist-packages/influxdb/influxdb08/client.py", line 255, in request
app_1  |     raise InfluxDBClientError(response.content, response.status_code)
app_1  | influxdb.influxdb08.client.InfluxDBClientError: 400: <html>
app_1  | <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
app_1  | <body bgcolor="white">
app_1  | <center><h1>400 Bad Request</h1></center>
app_1  | <center>The plain HTTP request was sent to HTTPS port</center>
app_1  | <hr><center>nginx/1.11.3</center>
app_1  | </body>
app_1  | </html>
```

**Comment by nicolargo** [comment]
In the InfluxDB API, the constructor has two options:

* ssl (bool) – use https instead of http to connect to InfluxDB, defaults to False
* verify_ssl (bool) – verify SSL certificates for HTTPS requests, defaults to False

Note for developer: To be tested.

**Comment by egyptianbman** [comment]
I'm trying to fix this locally and am finding that even if you pass `verify_ssl=False`, it still throws a warning if the ssl certificate isn't "valid". To get around this, I'm calling it via `python -W ignore -m glances....`.
