### ISSUE TITLE
Glances stops after a few minutes when using --export-statsd

### ISSUE THREAD

**Issue by ucoria-itexico** [nicolargo/glances#985]
#### Description

Set glances config file to:
```
[statsd]
host=localhost
port=8125
prefix=glances
```
Run:
`sudo glances --export-statsd`

Everything works fine, Interface in terminal appears to be working fine, but after a few minutes it stops and displays:

```Traceback (most recent call last):ng or critical alert detected
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 130, in main
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 111, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 96, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 1018, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 996, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 545, in display
    stats_ip = stats.get_plugin('ip').get_stats_display(args=self.args)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 631, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_ip.py", line 136, in msg_curse
    msg = '{}'.format(self.stats['address'])
KeyError: 'address
```

~~While trying to extract logs using `sudo glances -d --export-statsd` couldn't replicate~~
Edit: Got the logs

#### Versions

* Glances: Glances v2.7.1
* PSutil: psutil v5.0.0
* Operating System:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04

#### Logs

http://pastebin.com/AiXswyhu

```
2016-12-20 09:43:37,724 -- WARNING -- PyStache lib not installed (action script with mustache will not work)
2016-12-20 09:44:08,268 -- INFO -- Start Glances 2.7.1
2016-12-20 09:44:08,269 -- INFO -- CPython 2.7.12 and PSutil 5.0.0 detected
2016-12-20 09:44:08,273 -- INFO -- Start standalone mode
2016-12-20 09:44:08,280 -- WARNING -- PyStache lib not installed (action script with mustache will not work)
2016-12-20 09:44:12,985 -- INFO -- Start Glances 2.7.1
2016-12-20 09:44:12,985 -- INFO -- CPython 2.7.12 and PSutil 5.0.0 detected
2016-12-20 09:44:12,990 -- INFO -- Read configuration file '/home/test-engineer/.config/glances/glances.conf'
2016-12-20 09:44:12,990 -- INFO -- Start standalone mode
2016-12-20 09:44:12,997 -- WARNING -- PyStache lib not installed (action script with mustache will not work)
```

**Comment by nicolargo** [comment]
The error is not in the export method but in the generation of the display for the IP plugin. Have you the same issue when you do not use the --export-statsd option ?

You can also test those two workarounds:
1. Disable the ip plugin using the --disable-ip option
2. Run Glances in quiet mode (nothing is displayed but the export is done) using the --quiet option

**Comment by ucoria-itexico** [comment]
Testing workarounds, will let you know results.

**Comment by ucoria-itexico** [comment]
`--quiet` still stops, gatherling logs and trying with `--disable-ip` after that.

**Comment by nicolargo** [comment]
So ?

**Comment by tidusjar** [comment]
Had the same problem, but exporting it to InfluxDB.


Running it with `--disable-ip` it works fine.

Full command: `--export-influxdb --config glances.conf --disable-load --disable-ip`

**Comment by SvenBrunk** [comment]
yep... all related --disable-ip also helps me with #931 #997 and my current problem with --export-rabbitmq

**Comment by nicolargo** [comment]
@ucoria-itexico Any head up with the --disable-ip test ?

**Comment by ucoria-itexico** [comment]
--disable-ip doesn't has been working fine too for me

**Comment by nicolargo** [comment]
Do not understand why the plugin crashs on your system. The stat dictionary should alway have the 'address' key...

I am going to add a check inside the msg_curses but it's a only a patch to hide the source error...

**Comment by SvenBrunk** [comment]
Hm. Strangely when I start without --disable-ip, but use the webserver, it works today. So the plugin seems to return proper data (also get data from it via JSON API)
I would say the real root cause is still unknown.

**Comment by nicolargo** [comment]
Let the issue open...

**Comment by nicolargo** [comment]
Should be reopen if the problem came back...

**Comment by roessland** [comment]
I had the same problem using --export-prometheus, and fixed it using --disable-ip.

**Comment by ajj** [comment]
Same problem using --export-influxdb, fixed using --disable-ip.

* Glances 2.11.1
* psutil v5.3.1
* OS
  * Debian 8 32 bit on arm (raspberry pi)
  * Kernel 4.9.35
