### ISSUE TITLE
AttributeError: 'module' object has no attribute 'connection'

### ISSUE THREAD

**Issue by ky0ncheng** [nicolargo/glances#991]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances (glances -V):
Glances v2.7.1 with psutil v5.0.1
* PSutil (glances -V):
Glances v2.7.1 with psutil v5.0.1
* Operating System (lsb_release -a):
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

#### Logs

➜  ~ glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 127, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 42, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 76, in load_modules
    self.load_plugins(args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 94, in load_plugins
    plugin = __import__(os.path.basename(item)[:-3])
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_docker.py", line 35, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 11, in <module>
    from . import api
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 2, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 19, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .ssladapter import ssladapter
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/__init__.py", line 1, in <module>
    from .ssladapter import SSLAdapter # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/ssladapter.py", line 22, in <module>
    urllib3.connection.match_hostname = match_hostname
AttributeError: 'module' object has no attribute 'connection'

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Hi @ky0ncheng 

the problem seems to come from the Docker lib. Please can you show me your Docker and Docker lib version:

    # pip list | grep docker
    ...
    # docker info
    ...

Thanks

PS: as a workarround please use the --disable-docker option in the glances command line

**Comment by ky0ncheng** [comment]
# pip list | grep docker
docker-py (1.10.6)
docker-pycreds (0.2.1)

------

# glances -w
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 195, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/webserver.py", line 34, in __init__
    self.stats = GlancesStats(config, args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 43, in __init__
    self.load_modules(self.args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 76, in load_modules
    self.load_plugins(args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 94, in load_plugins
    plugin = __import__(os.path.basename(item)[:-3])
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_docker.py", line 35, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 11, in <module>
    from . import api
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 2, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 19, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .ssladapter import ssladapter
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/__init__.py", line 1, in <module>
    from .ssladapter import SSLAdapter # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/ssladapter.py", line 22, in <module>
    urllib3.connection.match_hostname = match_hostname
AttributeError: 'module' object has no attribute 'connection'

**Comment by nicolargo** [comment]
@ky0ncheng Ok but we also need your Docker version:

    # docker info

Thanks

**Comment by vorobievalex** [comment]
Could it be a dup of #1054

**Comment by mreinhardt** [comment]
For anyone not wanting to hunt down the rabbit trail, this was fixed for me with:

```
pip install --user 'docker-py==1.7.2'
```

**Comment by Hubbitus** [comment]
As far I known `docker-py` in obsoleted and replaced by `docker` module. Even [official project](https://github.com/docker/docker-py) said I should do:

    pip install docker

You may refer also [ansible similar bug](https://github.com/ansible/ansible/issues/37200).

So could you please update dependency and refresh API usage in `Glances`?

**Comment by nonbinary** [comment]
I tried the above solutions on a CentOS 7 machine, and it does not help. pip allready has docker as installed, and --disable-docker does not make any difference. Glances still tries to load the docker extension, and cannot.
